Repository operator-framework/operator-sdk, pull requests merged in 2018-10, with the labels that each got.

#548 test/e2e/memcached_test.go: fix e2e testing on local machines
  test/e2e/memcached_test.go
Labels: size/XS

#556 *: add add_controller_test and addtoscheme_test
  pkg/scaffold/add_controller_test.go
  pkg/scaffold/addtoscheme_test.go
  pkg/scaffold/test_constant.go
Labels: size/M

#551 *: update user-guide and memcached-operator example
  Gopkg.lock
  README.md
  doc/project_layout.md
  doc/user-guide.md
  example/memcached-operator/handler.go.tmpl
  example/memcached-operator/memcached_controller.go.tmpl
Labels: size/XL

#562 pkg/refactor: add controller_kind_test.go and controller_test.go
  pkg/scaffold/controller_kind_test.go
  pkg/scaffold/controller_test.go
Labels: size/L

#561 commands/{build,cmdutil},pkg/generator: remove build.sh
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/cmdutil/util.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/generator/templates.go
Labels: size/L

#565 commands/operator-sdk,pkg/generator: Fix project root function and rbac updates for Ansible Operator
  commands/operator-sdk/cmd/cmdutil/util.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/generator/templates.go
Labels: needs-ok-to-test, size/M

#557 pkg/test: create new frameworkClient
  Gopkg.lock
  doc/test-framework/writing-e2e-tests.md
  pkg/test/client.go
  pkg/test/context.go
  pkg/test/framework.go
  pkg/test/main_entry.go
  pkg/test/resource_creator.go
  test/e2e/incluster-test-code/memcached_test.go.tmpl
  test/test-framework/memcached_test.go
Labels: size/L

#566 pkg/ansible: cherry pick from master into refactor branch
  Gopkg.lock
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/source.go
  pkg/ansible/controller/types.go
  pkg/ansible/events/log_events.go
  pkg/ansible/paramconv/paramconv.go
  pkg/ansible/proxy/kubeconfig/kubeconfig.go
  pkg/ansible/proxy/kubectl.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/runner/eventapi/eventapi.go
  pkg/ansible/runner/eventapi/types.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  pkg/ansible/runner/runner.go
Labels: size/XXL

#572 *: remove unused projectPath from DocInput
  commands/operator-sdk/cmd/add/api.go
  pkg/scaffold/doc.go
Labels: size/XS

#573 test/e2e/memcached_test.go: use local memcached example handler
  test/e2e/memcached_test.go
Labels: size/S

#575 pkg/scaffold: add cr_test.go doc_test.go dockerfile_test.go
  pkg/scaffold/cr_test.go
  pkg/scaffold/doc_test.go
  pkg/scaffold/dockerfile_test.go
Labels: size/M

#576 pkg/scaffold: add crd_test.go gitignore_test.go gopkgtoml_test.go
  pkg/scaffold/crd_test.go
  pkg/scaffold/gitignore_test.go
  pkg/scaffold/gopkgtoml_test.go
Labels: size/L

#577 pkg/scaffold: add operator_test.go register_test.go role_test.go
  pkg/scaffold/operator_test.go
  pkg/scaffold/register_test.go
  pkg/scaffold/role_test.go
Labels: size/L

#571 commands/new; Allow Ansible Operator to be created outside GOPATH
  commands/operator-sdk/cmd/new.go
Labels: ansible-operator, needs-ok-to-test, size/S

#543 pkg/ansible: Add Phase to CR status field for Ansible Operator
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/types.go
Labels: ansible-operator, size/M

#578 pkg/scaffold: add rolebinding_test.go types_test.go version_test.go
  pkg/scaffold/rolebinding_test.go
  pkg/scaffold/types_test.go
  pkg/scaffold/version_test.go
Labels: size/L

#580 pkg/test/main_entry.go: fix global resource cleanup
  pkg/test/main_entry.go
Labels: size/XS

#559 docs: Add a user guide for using an Ansible Operator
  doc/ansible/project_layout.md
  doc/ansible/user-guide.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
Labels: ansible-operator, needs-ok-to-test, size/L

#564 Add metrics example to the generated operator
  example/memcached-operator/handler.go.tmpl
  pkg/generator/generator_test.go
  pkg/generator/templates.go
Labels: size/M

#569 commands/up/local; pkg/ansible; Add support for `up local` to Ansible Operator
  Gopkg.lock
  Gopkg.toml
  commands/operator-sdk/cmd/cmdutil/util.go
  commands/operator-sdk/cmd/up/local.go
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/source.go
  pkg/ansible/operator/operator.go
Labels: ansible-operator, needs-ok-to-test, size/L

#587 test/e2e/memcached_test.go: check error for all ioutil.ReadFile
  test/e2e/memcached_test.go
Labels: size/S

#582 Adds integration tests for ansible operator
  .travis.yml
  Gopkg.lock
  hack/ci/setup-minikube.sh
  hack/ci/setup-openshift.sh
  test/ansible-memcached/defaults.yml
  test/ansible-memcached/memfin/tasks/main.yml
  test/ansible-memcached/tasks.yml
  test/ansible-memcached/watches-finalizer.yaml
  test/ansible-operator/Dockerfile
  test/ansible-operator/README.md
  test/ansible-operator/bin/entrypoint
  test/ansible-operator/bin/user_setup
  test/ansible-operator/cmd/ansible-operator/main.go
  test/test-ansible.sh
  test/test-go.sh
Labels: size/L

#581 Refactor file generation using abstractions
  Gopkg.lock
  Gopkg.toml
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/cmdutil/util.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/new.go
  commands/operator-sdk/cmd/test/local.go
  pkg/ansible/events/log_events.go
  pkg/scaffold/add_controller.go
  pkg/scaffold/add_controller_test.go
  pkg/scaffold/addtoscheme.go
  pkg/scaffold/addtoscheme_test.go
  pkg/scaffold/apis.go
  pkg/scaffold/apis_test.go
  pkg/scaffold/boilerplate.go
  pkg/scaffold/build.go
  pkg/scaffold/build_dockerfile.go
  pkg/scaffold/build_dockerfile_test.go
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/constants.go
  pkg/scaffold/controller.go
  pkg/scaffold/controller_kind.go
  pkg/scaffold/controller_kind_test.go
  pkg/scaffold/controller_test.go
  pkg/scaffold/cr.go
  pkg/scaffold/cr_test.go
  pkg/scaffold/crd.go
  pkg/scaffold/crd_test.go
  pkg/scaffold/doc.go
  pkg/scaffold/doc_test.go
  pkg/scaffold/gitignore.go
  pkg/scaffold/gitignore_test.go
  pkg/scaffold/go_test_script.go
  pkg/scaffold/go_test_script_test.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/input/input.go
  pkg/scaffold/operator.go
  pkg/scaffold/operator_test.go
  pkg/scaffold/register.go
  pkg/scaffold/register_test.go
  pkg/scaffold/role.go
  pkg/scaffold/role_test.go
  pkg/scaffold/rolebinding.go
  pkg/scaffold/rolebinding_test.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/test_framework_dockerfile.go
  pkg/scaffold/test_framework_dockerfile_test.go
  pkg/scaffold/test_pod.go
  pkg/scaffold/test_pod_test.go
  pkg/scaffold/test_setup.go
  pkg/scaffold/types.go
  pkg/scaffold/types_test.go
  pkg/scaffold/version.go
  pkg/scaffold/version_test.go
  pkg/util/file_util.go
  test/e2e/memcached_test.go
Labels: design, refactoring, size/XXL

#593 add OPERATOR_NAME env var
  doc/user-guide.md
Labels: needs-ok-to-test, size/XS

#594 pkg/{scaffold,util}: fix execute mode and container user
  pkg/scaffold/build_dockerfile.go
  pkg/scaffold/build_dockerfile_test.go
  pkg/util/file_util.go
Labels: size/XS

#595 commands,pkg/scaffold: remove unused boilerplate codegen
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/boilerplate.go
  pkg/scaffold/constants.go
Labels: size/M

#530 Added leader election.
  pkg/leader/doc.go
  pkg/leader/leader.go
Labels: enhancement, size/L

#531 Version and release documentation
  .gitignore
  Makefile
  doc/release-versioning.md
  pkg/generator/templates.go
  release.sh
Labels: docs, documentation, needs discussion, size/L

#603 pkg/generator: remove generator
  commands/operator-sdk/cmd/cmdutil/util.go
  commands/operator-sdk/cmd/generate.go
  commands/operator-sdk/cmd/generate/olm_catalog.go
  pkg/generator/gen_config.go
  pkg/generator/gen_config_test.go
  pkg/generator/gen_deps.go
  pkg/generator/gen_deps_test.go
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/generator/templates.go
  pkg/generator/test_constants.go
  pkg/generator/util.go
  pkg/generator/util_test.go
Labels: size/XXL

#601 hack/ci/setup-openshift.sh: update to oc 3.11.0
  hack/ci/setup-openshift.sh
Labels: size/XS

#605 pkg/{k8sclient,sdk}: remove old sdk functions
  Gopkg.lock
  pkg/k8sclient/client.go
  pkg/sdk/action.go
  pkg/sdk/api.go
  pkg/sdk/handler.go
  pkg/sdk/informer-sync.go
  pkg/sdk/informer.go
  pkg/sdk/metrics.go
  pkg/sdk/query-opt.go
  pkg/sdk/query.go
  pkg/sdk/types.go
  pkg/sdk/watch-opt.go
Labels: size/XL

#604 cherry pick: Version and release documentation (#531)
  .gitignore
  Makefile
  doc/release-versioning.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  release.sh
Labels: size/L

#610 release.sh: compare file versions against new version
  release.sh
Labels: size/XS

#621 .travis.yml: remove minikube tests
  .travis.yml
Labels: size/S

#624 *: release v0.0.7
  CHANGELOG.md
  pkg/generator/templates.go
  version/version.go
Labels: size/S

#625 Makefile: build signature target performs correct comparison
  Makefile
Labels: size/XS

#628 test/e2e/memcached_test.go: regexp branch substitution
  test/e2e/memcached_test.go
Labels: size/XS

#591 Add Issue and PR templates to the project
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/L

#632 .github: Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-question.md
Labels: size/XS

#634 moves controller creation and startup out of ansible's main.go
  commands/operator-sdk/cmd/up/local.go
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/proxy.go
  test/ansible-operator/cmd/ansible-operator/main.go
Labels: ansible-operator, refactoring, size/M

#626 Cleanup grammar in short description
  commands/operator-sdk/cmd/root.go
Labels: needs-ok-to-test, size/XS

#629 *: add back service account
  README.md
  commands/operator-sdk/cmd/new.go
  commands/operator-sdk/cmd/test/local.go
  doc/ansible/user-guide.md
  doc/dev/testing/end-to-end.md
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  doc/user-guide.md
  pkg/scaffold/ansible/operator.go
  pkg/scaffold/constants.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/operator.go
  pkg/scaffold/operator_test.go
  pkg/scaffold/rolebinding.go
  pkg/scaffold/rolebinding_test.go
  pkg/scaffold/service_account.go
  pkg/scaffold/service_account_test.go
  test/e2e/memcached_test.go
  test/test-ansible.sh
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/deploy/operator.yaml
  test/test-framework/deploy/role_binding.yaml
  test/test-framework/deploy/sa.yaml
  test/test-framework/deploy/service_account.yaml
Labels: size/L

#630 test/e2e: make running e2e tests locally easier
  .travis.yml
  test/e2e/memcached_test.go
Labels: size/M

#631 Makefile,hack/tests: separate tests to make testing simpler and quicker
  .travis.yml
  Makefile
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-go.sh
  hack/tests/sanity-check.sh
  hack/tests/test-subcommand.sh
  hack/tests/unit.sh
  test/.gitignore
Labels: size/L

#636 pkg/scaffold/*_test.go: make diff nicer
  pkg/scaffold/add_controller_test.go
  pkg/scaffold/addtoscheme_test.go
  pkg/scaffold/apis_test.go
  pkg/scaffold/build_dockerfile_test.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/controller_kind_test.go
  pkg/scaffold/controller_test.go
  pkg/scaffold/cr_test.go
  pkg/scaffold/crd_test.go
  pkg/scaffold/doc_test.go
  pkg/scaffold/gitignore_test.go
  pkg/scaffold/go_test_script_test.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/operator_test.go
  pkg/scaffold/register_test.go
  pkg/scaffold/role_test.go
  pkg/scaffold/rolebinding_test.go
  pkg/scaffold/test_framework_dockerfile_test.go
  pkg/scaffold/test_pod_test.go
  pkg/scaffold/types_test.go
  pkg/scaffold/util.go
  pkg/scaffold/version_test.go
  pkg/util/k8sutil/k8sutil_test.go
Labels: size/L

#645 test/test-framework/memcached_test.go: bump timeout
  test/test-framework/memcached_test.go
Labels: size/XS

#642 commands/operator-sdk: consolidate operator types into cmdutil package
  commands/operator-sdk/cmd/cmdutil/util.go
  commands/operator-sdk/cmd/new.go
Labels: size/M

#647 cmd: initial resource validation
  commands/operator-sdk/cmd/generate/k8s.go
  pkg/scaffold/resource.go
Labels: enhancement, size/M

#635 doc/user: document refactor to controller-runtime
  doc/user-guide.md
  doc/user/client.md
  pkg/scaffold/controller_kind.go
  pkg/scaffold/controller_kind_test.go
Labels: documentation, needs discussion, refactoring, size/L

#646 commands/.../cmdutil: deduplicate updateRoleForResource and support ClusterRole
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/crd.go
  commands/operator-sdk/cmd/cmdutil/util.go
  commands/operator-sdk/cmd/new.go
Labels: size/L

#590 Add helper function for generating ServiceMonitor objects
  Gopkg.lock
  pkg/scaffold/role.go
  pkg/scaffold/role_test.go
  pkg/sdk/metrics.go
  pkg/sdk/service-monitor.go
Labels: size/L

#617 pkg/leader: allow setting the pod name explicitly.
  pkg/leader/doc.go
  pkg/leader/leader.go
  pkg/scaffold/operator.go
  pkg/scaffold/operator_test.go
Labels: size/M

#656 version: set to v0.0.7-git
  version/version.go
Labels: size/XS

#657 Makefile: convert release signing target to full bash
  Makefile
Labels: size/S

#600 docs/ansible/dev; Add developer documentation for Ansible Operator
  doc/ansible/dev/developer_guide.md
Labels: ansible-operator, docs, documentation, needs-ok-to-test, size/L

#650 Document snake_case conversion by ansible operator
  doc/ansible/user-guide.md
Labels: ansible-operator, needs-ok-to-test, size/XS

#641 pkg/ansible,*: Adding ability to specify re-queue period per GVK via watches file.
  commands/operator-sdk/cmd/up/local.go
  pkg/ansible/operator/operator.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/runner/testdata/duplicate_gvk.yaml
  pkg/ansible/runner/testdata/invalid.yaml
  pkg/ansible/runner/testdata/invalid_duration.yaml
  pkg/ansible/runner/testdata/invalid_finalizer_playbook_path.yaml
  pkg/ansible/runner/testdata/invalid_finalizer_role_path.yaml
  pkg/ansible/runner/testdata/invalid_playbook_path.yaml
  pkg/ansible/runner/testdata/invalid_role_path.yaml
  pkg/ansible/runner/testdata/valid.yaml
  test/ansible-operator/cmd/ansible-operator/main.go
Labels: ansible-operator, size/L

#653 doc: add migration guide
  doc/migration/v0.1.0-migration-guide.md
  doc/user-guide.md
Labels: size/L

#660 doc/test-framework: add service account flag to cluster test cmd
  doc/test-framework/writing-e2e-tests.md
Labels: size/XS

#649 Util dir refactor
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/add/crd.go
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/cmdutil/util.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/new.go
  commands/operator-sdk/cmd/test/cluster.go
  commands/operator-sdk/cmd/test/local.go
  commands/operator-sdk/cmd/up/local.go
  internal/util/fileutil/file_util.go
  internal/util/projutil/project_util.go
  pkg/k8sutil/constants.go
  pkg/k8sutil/k8sutil.go
  pkg/k8sutil/k8sutil_test.go
  pkg/scaffold/add_controller.go
  pkg/scaffold/addtoscheme.go
  pkg/scaffold/ansible/dockerfile.go
  pkg/scaffold/ansible/operator.go
  pkg/scaffold/ansible/playbook.go
  pkg/scaffold/ansible/watches.go
  pkg/scaffold/apis.go
  pkg/scaffold/build_dockerfile.go
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/constants.go
  pkg/scaffold/controller.go
  pkg/scaffold/controller_kind.go
  pkg/scaffold/cr.go
  pkg/scaffold/crd.go
  pkg/scaffold/doc.go
  pkg/scaffold/gitignore.go
  pkg/scaffold/go_test_script.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/operator.go
  pkg/scaffold/register.go
  pkg/scaffold/role.go
  pkg/scaffold/rolebinding.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/service_account.go
  pkg/scaffold/test_framework_dockerfile.go
  pkg/scaffold/test_pod.go
  pkg/scaffold/types.go
  pkg/scaffold/version.go
  pkg/sdk/metrics.go
  pkg/tls/error.go
  pkg/tls/primitives.go
  pkg/tls/tls.go
  pkg/util/k8sutil/k8sutil.go
  test/ansible-operator/cmd/ansible-operator/main.go
  test/e2e/memcached_test.go
  test/e2e/tls_util_test.go
Labels: needs discussion, refactoring, size/XXL

#661 doc: clean up README and user-guide
  README.md
  doc/user-guide.md
Labels: size/M

#668 Fixed ansible_user_guide link
  README.md
Labels: needs-ok-to-test, size/XS

#677 pkg/ansible: fail early if we are unable to find role or playbook
  .gitignore
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/runner/testdata/playbook.yml
  pkg/ansible/runner/testdata/roles/role/tasks.yaml
  pkg/ansible/runner/testdata/valid.yaml.tmpl
Labels: ansible-operator, bug, size/M

#674 doc/sdk-cli-reference: update for [api,controller], cleanup for [new, generate]
  doc/sdk-cli-reference.md
Labels: size/L

#681 CHANGELOG.md: update for v0.1.0
  CHANGELOG.md
Labels: size/S

#682 pkg/scaffold,version: release to v0.1.0
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#680 .travisl.yml: skip CI on change to docs or untestable project files
  .travis.yml
Labels: size/XS

#683 pkg/scaffold,version: bump to v0.1.0-git
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S
