Repository operator-framework/operator-sdk, pull requests merged in 2018-11, with the labels that each got.

#676 allow operator-sdk to run with composed GOPATH
  hack/lib/test_lib.sh
  internal/util/projutil/project_util.go
Labels: needs-ok-to-test, size/S

#679 pkg/scaffold: remove TODO for metrics port
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
Labels: size/XS

#684 Release versioning
  doc/release-versioning.md
  release.sh
Labels: size/M

#639 pkg/ansible - update status to include failure message on the status.
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/status/types.go
  pkg/ansible/controller/status/utils.go
  pkg/ansible/controller/status/utils_test.go
  pkg/ansible/controller/types.go
  pkg/ansible/events/log_events.go
  pkg/ansible/runner/eventapi/types.go
Labels: ansible-operator, size/XL

#688 doc/migration: skip git for new project
  doc/migration/v0.1.0-migration-guide.md
Labels: size/XS

#690 pkg/scaffold: fix hardcoded crd version
  pkg/scaffold/crd.go
Labels: needs-ok-to-test, size/XS

#667 Adding ansible operator workflow to the README
  README.md
Labels: size/XS

#695 Cherry pick commits for v0.1.1 release
  doc/release-versioning.md
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/crd.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  release.sh
  version/version.go
Labels: size/M

#588 Release signing process
  Makefile
  doc/release-versioning.md
Labels: documentation, enhancement, needs discussion, size/S

#698 test/e2e/memcached_test.go: comment out gopkg version during tests
  test/e2e/memcached_test.go
Labels: size/XS

#693 doc/migration: Tweak client examples, add unstructured
  doc/migration/v0.1.0-migration-guide.md
Labels: docs, documentation, needs-ok-to-test, size/S

#704 PR Template: fix comment tag
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs-ok-to-test, size/XS

#692 commands/.../build.go: set exec command output to stdout, stderr
  commands/operator-sdk/cmd/build.go
Labels: size/M

#696 pkg/scaffold,version,changelog: bump to v0.1.1
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#702 cmd/test: do not append empty manifests
  commands/operator-sdk/cmd/test/local.go
Labels: needs-ok-to-test, size/S

#697 pkg/scaffold/build_dockerfile: update base image
  pkg/scaffold/build_dockerfile.go
  pkg/scaffold/build_dockerfile_test.go
Labels: size/XS

#708 Use marker for markdown link verification
  .github/ISSUE_TEMPLATE/feature-request.md
  .travis.yml
  doc/proposals/leader-for-life.md
  doc/proposals/tls-utilities.md
  hack/ci/marker
Labels: size/S

#705 pkg/k8sutil,cmd/up/local: Fixing kubeconfig environment variable.
  commands/operator-sdk/cmd/up/local.go
  pkg/k8sutil/constants.go
Labels: size/XS

#713 Improves output available for troubleshooting ansible
  pkg/ansible/controller/reconcile.go
  pkg/ansible/events/log_events.go
  pkg/ansible/runner/eventapi/eventapi.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  pkg/ansible/runner/runner.go
Labels: ansible-operator, size/M

#672 Exit if not a Go project
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/generate/k8s.go
  internal/util/projutil/project_util.go
Labels: bug, size/S

#703 doc/test-framework: improve example code
  doc/test-framework/writing-e2e-tests.md
Labels: needs-ok-to-test, size/XS

#716 better Resource field pattern matching
  pkg/scaffold/resource.go
Labels: size/XS

#699 Fix sed issue on OSX
  README.md
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  doc/user-guide.md
Labels: needs-ok-to-test, size/S

#721 Revert "decompose GOPATH and set it according to the current working dir."
  commands/operator-sdk/main.go
  internal/util/projutil/project_util.go
Labels: size/M

#722 tests/e2e-ansible: ansible tests should not run in Golang environment
  hack/tests/e2e-ansible.sh
  test/ansible-operator/Dockerfile
Labels: ansible-operator, bug, size/S

#723 commands/operator-sdk/cmd: set composed GOPATH for Go projects (fix #712)
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/new.go
  internal/util/projutil/project_util.go
  test/e2e/memcached_test.go
Labels: enhancement, size/M

#717 commands/.../test,internal/util: use clientcmd's kubeconfig getter
  Gopkg.lock
  commands/operator-sdk/cmd/test/cluster.go
  commands/operator-sdk/cmd/test/local.go
  internal/util/k8sutil/k8sutil.go
  pkg/test/framework.go
Labels: size/M

#728 *: better docs and error reporting for project type issue
  doc/migration/v0.1.0-migration-guide.md
  internal/util/projutil/project_util.go
Labels: docs, size/XS

#738 pkg/scaffold/internal/testutil/test_util.go: scaffold unit test utilities
  pkg/scaffold/add_controller_test.go
  pkg/scaffold/addtoscheme_test.go
  pkg/scaffold/apis_test.go
  pkg/scaffold/build_dockerfile_test.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/controller_kind_test.go
  pkg/scaffold/controller_test.go
  pkg/scaffold/cr_test.go
  pkg/scaffold/crd_test.go
  pkg/scaffold/doc_test.go
  pkg/scaffold/gitignore_test.go
  pkg/scaffold/go_test_script_test.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/internal/testutil/test_util.go
  pkg/scaffold/operator_test.go
  pkg/scaffold/register_test.go
  pkg/scaffold/role_test.go
  pkg/scaffold/rolebinding_test.go
  pkg/scaffold/service_account_test.go
  pkg/scaffold/test_framework_dockerfile_test.go
  pkg/scaffold/test_pod_test.go
  pkg/scaffold/types_test.go
  pkg/scaffold/version_test.go
Labels: refactoring, size/M

#707 SDK log injection and uniform logging in operator-sdk binary
  Gopkg.lock
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/add/crd.go
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/new.go
  commands/operator-sdk/cmd/test/cluster.go
  commands/operator-sdk/cmd/test/local.go
  commands/operator-sdk/cmd/up/local.go
  commands/operator-sdk/main.go
  doc/dev/logging.md
  example/memcached-operator/memcached_controller.go.tmpl
  hack/check_error_case.sh
  internal/util/fileutil/file_util.go
  internal/util/projutil/project_util.go
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/status/types.go
  pkg/ansible/events/log_events.go
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/kubectl.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/runner/eventapi/eventapi.go
  pkg/ansible/runner/eventapi/types.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  pkg/ansible/runner/runner.go
  pkg/leader/leader.go
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/controller_kind.go
  pkg/scaffold/controller_kind_test.go
  pkg/scaffold/role.go
  pkg/scaffold/scaffold.go
  pkg/scaffold/test_setup.go
  pkg/sdk/internal/metrics/metrics.go
  pkg/sdk/metrics.go
  pkg/test/context.go
  pkg/test/main_entry.go
  test/ansible-operator/cmd/ansible-operator/main.go
  test/e2e/framework/framework.go
  test/e2e/framework/main_entry.go
Labels: design, enhancement, refactoring, size/XL

#749 pkg/scaffold: Fix logging bug in controller
  pkg/scaffold/controller_kind.go
  pkg/scaffold/controller_kind_test.go
Labels: size/XS

#750 pkg/scaffold: fixing typo in controller log
  pkg/scaffold/controller_kind.go
  pkg/scaffold/controller_kind_test.go
Labels: size/XS

#740 doc/dev/developer_guide.md: update dev guide
  doc/dev/developer_guide.md
Labels: docs, size/M

#752 pkg/scaffold: fixing main printVersion
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
Labels: size/S

#755 doc/user/logging.md: moved
  doc/user/logging.md
Labels: docs, size/XS

#761 Update 3rd Party Resources User-Guide Info
  doc/user-guide.md
Labels: needs-ok-to-test, size/XS

#711 pkg/ansible: Adding unit tests for the ansible operator reconcile loop
  Gopkg.lock
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
  pkg/ansible/controller/status/types.go
  pkg/ansible/runner/fake/runner.go
  pkg/ansible/runner/runner.go
Labels: ansible-operator, refactoring, size/XL

#766 Adds travis support for push builds
  .travis.yml
  test/e2e/memcached_test.go
Labels: size/S, testing

#764 Remove existing metrics
  Gopkg.lock
  pkg/metrics/metrics.go
  pkg/metrics/service-monitor.go
  pkg/sdk/internal/metrics/metrics.go
Labels: size/M

#775 .travis.yml: Only run markdown checker on doc dir
  .travis.yml
Labels: size/XS

#774 hack/ci: Remove unused setup-minikube script
  hack/ci/setup-minikube.sh
Labels: size/S

#772 'operator-sdk print-deps' command
  Gopkg.lock
  commands/operator-sdk/cmd/print_deps.go
  commands/operator-sdk/cmd/root.go
  doc/sdk-cli-reference.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
Labels: enhancement, size/L

#777 CHANGELOG.md: update CHANGELOG
  CHANGELOG.md
Labels: size/S

#778 CHANGELOG.md: add print-deps line
  CHANGELOG.md
Labels: docs, size/XS

#779 doc/sdk-cli-reference.md: add print-deps example
  doc/sdk-cli-reference.md
Labels: size/S

#768 commands/.../test/local,pkg/test: add image flag to test local
  CHANGELOG.md
  Gopkg.lock
  commands/operator-sdk/cmd/test/local.go
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  hack/tests/test-subcommand.sh
  pkg/test/resource_creator.go
Labels: size/M, test-framework

#757 doc/user/unit-testing.md: explain fake client and unit test example
  doc/user/unit-testing.md
Labels: docs, size/L, testing

#780 CHANGELOG.md: adds ansible operator changes
  CHANGELOG.md
Labels: documentation, size/XS

#744 pkg/ansible: introduce managedStatus flag
  CHANGELOG.md
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
  pkg/ansible/operator/operator.go
  pkg/ansible/runner/fake/runner.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/runner/testdata/invalid_status.yaml
  pkg/ansible/runner/testdata/valid.yaml.tmpl
Labels: ansible-operator, needs-ok-to-test, size/L

#771 doc/user/event-filtering.md: event filtering with Predicates
  doc/user/event-filtering.md
Labels: docs, size/L

#770 commands/.../test/local,pkg/test: add `no-setup` flag
  CHANGELOG.md
  commands/operator-sdk/cmd/test/local.go
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  hack/lib/test_lib.sh
  hack/tests/e2e-ansible.sh
  hack/tests/test-subcommand.sh
  pkg/test/framework.go
Labels: size/L, test-framework

#516 Design doc csv generation
  doc/design/milestone-0.2.0/csv-generation.md
  doc/sdk-cli-reference.md
Labels: design, needs discussion, size/L

#781 commands/.../test,pkg/test: add --up-local flag to test local
  CHANGELOG.md
  Gopkg.lock
  commands/operator-sdk/cmd/test/local.go
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  hack/tests/test-subcommand.sh
  pkg/scaffold/test_pod_test.go
  pkg/test/e2eutil/wait_util.go
  pkg/test/framework.go
  pkg/test/main_entry.go
  pkg/test/resource_creator.go
  test/e2e/incluster-test-code/memcached_test.go.tmpl
  test/test-framework/cmd/manager/main.go
  test/test-framework/pkg/controller/add_memcached.go
  test/test-framework/pkg/controller/controller.go
  test/test-framework/pkg/controller/memcached/memcached_controller.go
  test/test-framework/test/e2e/main_test.go
  test/test-framework/test/e2e/memcached_test.go
Labels: size/XL, test-framework

#788 test/ansible-operator/Dockerfile: fix e2e ownerref issue
  hack/tests/e2e-ansible.sh
  test/ansible-operator/Dockerfile
Labels: size/S

#791 pkg/scaffold,version,changelog: bump to v0.2.0
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#792 Revert "pkg/scaffold,version,changelog: bump to v0.2.0"
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#793 Revert "Adds travis support for push builds"
  .travis.yml
  test/e2e/memcached_test.go
Labels: size/S

#795 test/e2e/memcached_test.go: comment out gopkg version during tests
  test/e2e/memcached_test.go
Labels: size/XS

#796 Fix kubeconfig pointer override
  hack/tests/test-subcommand.sh
  pkg/test/main_entry.go
Labels: size/XS

#794 pkg/scaffold,version,changelog: bump to v0.2.0 (again)
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#799 pkg/scaffold,version,changelog: bump to v0.2.0 (again) (again)
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#800 pkg/scaffold,version,changelog: bump to v0.2.0+git
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S
