Repository operator-framework/operator-sdk, pull requests merged in 2018-09, with the labels that each got.

#504 add api: add new type, generate crd and example cr
  commands/operator-sdk/cmd/add/api.go
  pkg/scaffold/cr.go
  pkg/scaffold/crd.go
  pkg/scaffold/resource.go
Labels: size/L

#505 *: add codegen for deploy/role_bind.yaml
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/rolebinding.go
Labels: size/M

#511 *: add codegen for deploy/operator.yaml
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/operator.go
Labels: size/M

#512 *: add codegen for scripts/codegen/Boilerplate.go.txt and fix typos
  commands/operator-sdk/cmd/new.go
Labels: size/S

#507 MAINTAINERS: update MAINTAINERS file
  MAINTAINERS
Labels: size/S

#513 *: add codegen for version/version.go
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/version.go
Labels: size/M

#509 doc/user-guide: Adding add to scheme documentation
  doc/user-guide.md
Labels: size/M

#515 add missing mkdir
  README.md
Labels: size/XS

#454 Create SA for the operator
  README.md
  commands/operator-sdk/cmd/test.go
  doc/user-guide.md
  pkg/generator/generator.go
  pkg/generator/generator_test.go
  pkg/generator/templates.go
  test/e2e/memcached_test.go
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/deploy/operator.yaml
  test/test-framework/deploy/rbac.yaml
  test/test-framework/deploy/sa.yaml
Labels: size/M

#514 *: add controller command and templates
  commands/operator-sdk/cmd/add.go
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/add_controller.go
  pkg/scaffold/controller_kind.go
Labels: size/L

#525 test/e2e/memcached_test.go: fix dep issues in travis
  test/e2e/memcached_test.go
Labels: size/S

#522 Gopkg.*,pkg/generator/templates.go: update to kubernetes 1.11.2
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  pkg/generator/templates.go
  pkg/k8sclient/client.go
  pkg/test/framework.go
  test/e2e/framework/framework.go
Labels: needs-ok-to-test, size/L

#529 test/e2e/memcached_test.go: fix travis on master
  test/e2e/memcached_test.go
Labels: size/M

#527 *: add codegen for .gitignore
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/gitignore.go
Labels: size/L

#532 *: add codegen for Gopkg.toml
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/gopkgtoml.go
Labels: size/M

#533 commands: update up local command to run cmd/manager/main.go
  commands/operator-sdk/cmd/up/local.go
Labels: size/S

#539 pkg/scaffold: use Role/Binding instead of ClusterRole/Binding
  pkg/scaffold/role.go
  pkg/scaffold/rolebinding.go
Labels: size/S

#526 Update Docs With Incluster Testing Support
  commands/operator-sdk/cmd/test/cluster.go
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
Labels: size/L

#473 pkg/ansible: Adding ansible operator controller and events package
  Gopkg.lock
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/source.go
  pkg/ansible/controller/types.go
  pkg/ansible/events/log_events.go
Labels: ansible-operator, size/XL

#544 cmd/add: append role of new apiGroup and Resource to role.yaml
  commands/operator-sdk/cmd/add/api.go
Labels: size/M

#542 *: update README and fix templates and commands
  README.md
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/new.go
  pkg/scaffold/cmd.go
  pkg/scaffold/controller_kind.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/operator.go
Labels: size/L

#546 commands,pkg/test: support single namespace mode for local test
  .travis.yml
  commands/operator-sdk/cmd/test/local.go
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  hack/ci/setup-openshift.sh
  pkg/test/framework.go
  pkg/test/main_entry.go
  pkg/test/resource_creator.go
Labels: size/M
