Repository operator-framework/operator-sdk, pull requests merged in 2018-12, with the labels that each got.

#790 Minor travis improvments
  .travis.yml
Labels: size/XS

#802 Fix validation check for when API version is missed
  pkg/scaffold/resource.go
Labels: needs-ok-to-test, size/XS

#760 pkg/ansible/proxy; Integrate caching to AO proxy
  Gopkg.lock
  commands/operator-sdk/cmd/up/local.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/proxy/proxy_test.go
  pkg/ansible/proxy/requestfactory/requestinfo.go
  test/ansible-operator/cmd/ansible-operator/main.go
Labels: ansible-operator, needs-ok-to-test, size/XL

#813 test/ansible-operator/Dockerfile: lock idna to 2.7
  test/ansible-operator/Dockerfile
Labels: size/XS

#810 test/e2e,pkg/test: merge internal and external test frameworks
  Makefile
  doc/dev/testing/end-to-end.md
  hack/tests/e2e-go.sh
  internal/util/projutil/project_util.go
  pkg/test/framework.go
  pkg/test/resource_creator.go
  test/e2e/e2eutil/check_util.go
  test/e2e/framework/context.go
  test/e2e/framework/framework.go
  test/e2e/framework/main_entry.go
  test/e2e/framework/resource_creator.go
  test/e2e/main_test.go
  test/e2e/memcached_test.go
  test/e2e/testdata/empty.yaml
  test/e2e/tls_util_test.go
Labels: size/XL

#815 pkg/scaffold/resource.go: robust validators and avoid panics
  pkg/scaffold/resource.go
Labels: size/S

#753 doc/proposals: Add operator specific metrics proposal
  doc/proposals/metering-operator-metrics.md
Labels: size/M

#812 pkg/ansible/runner: logs the stdout and stderr from ansible-runner if…
  pkg/ansible/runner/runner.go
Labels: ansible-operator, size/XS

#819 fixes several ansible test failures and flaws
  hack/tests/e2e-ansible.sh
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
  pkg/ansible/events/log_events.go
  pkg/ansible/proxy/proxy.go
  test/ansible-memcached/memfin/tasks/main.yml
  test/ansible-operator/cmd/ansible-operator/main.go
Labels: ansible-operator, size/M

#825 changelog: add cluster-scope flag to changelog
  CHANGELOG.md
Labels: size/XS

#828 Pin controller-runtime to v0.1.4
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
Labels: size/XS

#807 bump k8s dependencies to 1.12.3
  Gopkg.lock
  Gopkg.toml
  pkg/helm/release/manager.go
  pkg/helm/release/manager_factory.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
Labels: size/L, versioning

#824 pkg/ansible/proxy: change a cache miss log from error to info
  pkg/ansible/proxy/proxy.go
Labels: size/XS

#831 Backport Pin controller-runtime to v0.1.4 #828 to v0.2.x
  pkg/ansible/runner/runner.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  test/ansible-operator/Dockerfile
Labels: size/S

#834 version,pkg/scaffold,changelog: bump to v0.2.1+git
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#787 pkg/ansible/controller,pkg/helm/controller; Enable status subresource by default
  CHANGELOG.md
  doc/ansible/dev/developer_guide.md
  doc/user-guide.md
  doc/user/client.md
  example/memcached-operator/memcached_controller.go.tmpl
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/status/types.go
  pkg/helm/controller/reconcile.go
  pkg/scaffold/crd.go
  pkg/scaffold/crd_test.go
  test/test-framework/pkg/controller/memcached/memcached_controller.go
Labels: ansible-operator, needs-ok-to-test, size/L

#830 fixed #827
  Makefile
Labels: size/XS

#817 Set KUBECONFIG and K8S_AUTH_KUBECONFIG environment variables for ansible-runner
  pkg/ansible/runner/runner.go
Labels: size/XS

#839 release 0.3.0
  CHANGELOG.md
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  version/version.go
Labels: size/S

#842 changelog: move the subresource note to correct section
  CHANGELOG.md
Labels: size/XS

#840 .github/ISSUE_TEMPLATE/bug-report.md: add Helm
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/XS

#847 changelog: fix typo in link
  CHANGELOG.md
Labels: size/XS

#843 changelog: move the subresource note to correct section
  CHANGELOG.md
Labels: size/XS

#848 Update maintainers
  MAINTAINERS
Labels: size/XS

#853 doc/dev/testing: Update documentation
  doc/dev/testing/end-to-end.md
  doc/dev/testing/travis-build.md
Labels: size/S

#814 pkg/helm: use status conditions, update status for failures
  Gopkg.lock
  hack/tests/e2e-helm.sh
  pkg/ansible/controller/controller.go
  pkg/helm/controller/controller.go
  pkg/helm/controller/reconcile.go
  pkg/helm/engine/ownerref.go
  pkg/helm/internal/types/types.go
  pkg/helm/internal/types/types_test.go
  pkg/helm/release/manager.go
  pkg/predicate/predicate.go
Labels: helm-operator, size/L

#821 ServiceMonitors
  Gopkg.lock
  pkg/k8sutil/k8sutil.go
  pkg/metrics/service-monitor.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
Labels: size/L

#849 Yaml scanner
  Gopkg.lock
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/test/local.go
  internal/util/projutil/project_util.go
  internal/util/yamlutil/manifest.go
  internal/util/yamlutil/scan.go
  pkg/test/resource_creator.go
  test/e2e/memcached_test.go
Labels: enhancement, size/L

#754 pkg/ansible,cmd/up/local: Add ansible operator flags to your CLI
  Gopkg.lock
  commands/operator-sdk/cmd/up/local.go
  hack/tests/e2e-ansible.sh
  pkg/ansible/flags/flag.go
  pkg/ansible/operator/operator.go
  test/ansible-operator/bin/entrypoint
  test/ansible-operator/cmd/ansible-operator/main.go
Labels: ansible-operator, enhancement, refactoring, size/M

#851 doc/proposals: Add proposal README and template
  doc/proposals/README.md
  doc/proposals/TEMPLATE.md
Labels: size/M

#854 doc/dev,.travis.yml,makefile: update testing docs
  .travis.yml
  Makefile
  doc/dev/developer_guide.md
  doc/dev/testing/end-to-end.md
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
  hack/ci/setup-openshift.sh
Labels: size/L

#844 Break up and add steps to release documentation
  doc/dev/release.md
  doc/release-versioning.md
  doc/versioning.md
  release.sh
Labels: docs, size/L

#751 Add proposal for Ansible Operator e2e test integration
  doc/proposals/ansible-operator-testing.md
Labels: ansible-operator, size/M, testing

#850 CustomRenderer interface for non-templated scaffolds
  pkg/scaffold/customrender.go
  pkg/scaffold/scaffold.go
Labels: enhancement, size/M

#832 Build, tag, and push operator base images during CI
  .travis.yml
  Makefile
  hack/ci/check-doc-only-update.sh
  hack/image/build-ansible-image.sh
  hack/image/build-helm-image.sh
  hack/image/push-image-tags.sh
  hack/lib/common.sh
  hack/lib/test_lib.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  pkg/scaffold/ansible/dockerfile.go
  pkg/scaffold/helm/dockerfile.go
  test/ansible-operator/cmd/ansible-operator/main.go
  test/helm-operator/cmd/helm-operator/main.go
Labels: size/L

#862 CHANGELOG.md: Adding info about new locations for base images
  CHANGELOG.md
Labels: size/XS

#863 README.md: Adding link to SDK CLI Reference doc
  README.md
Labels: size/XS

#820 generate k8s: call binary directly instead of vendored version
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/generate/k8s.go
  internal/util/projutil/project_util.go
Labels: enhancement, size/L

#859 pkg/scaffold/*: allow Inputs to specify template functions
  pkg/scaffold/input/input.go
  pkg/scaffold/scaffold.go
Labels: enhancement, size/S

#866 Fix gcp authentication for the test framework
  commands/operator-sdk/cmd/test/cluster.go
  pkg/test/framework.go
Labels: size/XS

#864 test/e2e/memcached_test.go: make tests work on forks
  .travis.yml
  test/e2e/memcached_test.go
Labels: size/S

#867 commands/../new.go: Output the operator filepath
  commands/operator-sdk/cmd/new.go
Labels: size/XS

#871 Symlink internal dir in e2e
  internal/util/projutil/project_util.go
  test/e2e/memcached_test.go
Labels: bug, size/S

#836 k8sutil: ExposeMetricsPort works for ClusterScoped
  pkg/k8sutil/constants.go
  pkg/k8sutil/k8sutil.go
  pkg/leader/leader.go
Labels: size/M

#878 Update query-api.md
  doc/design/milestone-0.0.2/query-api.md
Labels: size/XS
