Repository operator-framework/operator-sdk, pull requests merged in 2019-12, with the labels that each got.

#2280 install golangci-lint via curl as recommended by its docs
  hack/common.sh
Labels: size/XS, testing

#2185 add steps to migrate the projects to use the sdk version 0.12
  doc/migration/version-upgrade-guide.md
Labels: approved, kind/bug, kind/documentation, size/M

#2238 feat(linter): add misspell and check and fix issues
  hack/generate/gen-cli-doc.go
  hack/go-linter.sh
  internal/scaffold/ansible/input.go
  internal/scaffold/olm-catalog/csv_test.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scorecard/plugins/plugin_runner.go
  pkg/ansible/watches/watches.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1alpha2/types.go
Labels: approved, do-not-merge/hold, kind/cleanup, lgtm, size/M

#2260 fix scripts to run in mac os x and or linux
  doc/dev/testing/travis-build.md
  hack/generate/gen-test-framework.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
Labels: kind/bug, lgtm, size/M, testing

#2228 feat(linter): add structcheck and fix issues
  hack/go-linter.sh
  pkg/handler/enqueue_annotation.go
  pkg/test/framework.go
Labels: approved, kind/cleanup, size/XS

#2188 add mapping to roles/Foo/tasks/main.yml
  doc/ansible/dev/developer_guide.md
Labels: ansible-operator, approved, kind/documentation, lgtm, ok-to-test, size/S

#2283 improve the ansible tests and its logs
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
  hack/common.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
Labels: ansible-operator, approved, kind/bug, kind/flake, lgtm, size/L, testing

#2229 feat(linter) : add varcheck and deadcode and then, fix issues
  cmd/operator-sdk/up/local.go
  hack/go-linter.sh
  internal/scaffold/olm-catalog/csv.go
  internal/scorecard/interfaces.go
  internal/scorecard/plugins/labels.go
  internal/scorecard/plugins/plugin_runner.go
  pkg/helm/internal/types/types_test.go
  pkg/metrics/metrics.go
Labels: approved, kind/cleanup, lgtm, size/M

#2231 feat(linter) : add interfacer check and solve issues
  hack/go-linter.sh
  internal/scorecard/plugins/plugin_runner.go
  pkg/helm/controller/reconcile.go
Labels: approved, kind/cleanup, size/XS

#2175 fix(issue 671): Generated Role.yaml and RoleBinding.yaml don't work w…
  CHANGELOG.md
  internal/scaffold/role.go
  internal/scaffold/role_test.go
Labels: approved, kind/bug, size/M

#1162 internal/scaffold/olm-catalog: populate CSV customresourcedefinitions from Go type annotations
  doc/user/olm-catalog/csv-annotations.md
  go.mod
  go.sum
  internal/annotations/prefix.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scaffold/olm-catalog/descriptor/descriptor.go
  internal/scaffold/olm-catalog/descriptor/descriptor_test.go
  internal/scaffold/olm-catalog/descriptor/parse.go
  internal/scaffold/olm-catalog/descriptor/parse_test.go
  internal/scaffold/olm-catalog/descriptor/search.go
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  test/test-framework/go.sum
  test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go
Labels: approved, kind/feature, olm-catalog, size/XXL

#2287 Helm: allow relative paths for helm charts in watches.yaml file
  CHANGELOG.md
  doc/helm/dev/developer_guide.md
  doc/helm/user-guide.md
  internal/scaffold/helm/entrypoint.go
  internal/scaffold/helm/watches.go
Labels: approved, helm-operator, kind/feature, lgtm, size/M

#1902 internal/olm: make CLI output text more consistent; check resource errors
  internal/olm/client.go
  internal/olm/client/client.go
  internal/olm/client/status.go
Labels: approved, lgtm, olm-catalog, size/L

#2274 scorecard: Fix basic tests run when 'olm-deployed: true'
  CHANGELOG.md
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/resource_handler.go
Labels: approved, lgtm, ok-to-test, size/XS

#2207 fix(linter) : Add unparam checks and fix issues
  cmd/operator-sdk/test/local.go
  hack/go-linter.sh
  internal/scaffold/helm/chart.go
  internal/scaffold/olm-catalog/package_manifest.go
Labels: approved, kind/cleanup, lgtm, refactoring, size/S

#2276 Deprecate 'generate openapi', add 'generate crds'
  CHANGELOG.md
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/crds.go
  cmd/operator-sdk/generate/openapi.go
  cmd/operator-sdk/internal/genutil/crds.go
  cmd/operator-sdk/internal/genutil/openapi.go
  doc/cli/operator-sdk_add_api.md
  doc/cli/operator-sdk_generate.md
  doc/cli/operator-sdk_generate_crds.md
  doc/cli/operator-sdk_generate_openapi.md
  doc/operator-scope.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  doc/user/migrating-existing-apis.md
  hack/generate/gen-test-framework.sh
  hack/tests/scaffolding/scaffold-memcached.go
  internal/scaffold/types.go
  internal/scaffold/types_test.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1alpha2/types.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
Labels: lgtm, size/L

#2254 Add dev linter makefile target
  .travis.yml
  Makefile
  hack/go-linter.sh
  hack/tests/check-lint.sh
Labels: approved, kind/feature, size/M, testing

#2250 internal/scaffold/olm-catalog: refactor CSV updaters
  internal/scaffold/olm-catalog/csv.go
  internal/scaffold/olm-catalog/csv_test.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scaffold/olm-catalog/descriptor/descriptor.go
  internal/scaffold/olm-catalog/descriptor/descriptor_test.go
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, olm-catalog, size/XL

#2281 doc: add note to described the possibility to use MultiNamespacedCach…
  doc/user-guide.md
Labels: kind/documentation, size/S

#2240 Fix linter golint
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/add/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/scorecard/cmd.go
  hack/tests/check-lint.sh
  internal/flags/watch/flags.go
  internal/scaffold/add_controller_test.go
  internal/scaffold/addtoscheme_test.go
  internal/scaffold/ansible/constants.go
  internal/scaffold/controller_kind_test.go
  internal/scaffold/cr_test.go
  internal/scaffold/crd_test.go
  internal/scaffold/doc_test.go
  internal/scaffold/helm/chart_test.go
  internal/scaffold/olm-catalog/csv.go
  internal/scaffold/register_test.go
  internal/scaffold/test_setup.go
  internal/scaffold/types_test.go
  internal/scorecard/scorecard.go
  pkg/ansible/paramconv/paramconv.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  pkg/apis/scorecard/formatting.go
  pkg/k8sutil/k8sutil.go
  pkg/leader/leader.go
  pkg/test/context.go
Labels: approved, kind/cleanup, size/L

#2297 cmd/.../gen-csv.go: set operatorName from config after CLI if empty
  CHANGELOG.md
  cmd/operator-sdk/olmcatalog/gen-csv.go
Labels: kind/bug, lgtm, olm-catalog, size/S

#2298 internal/scaffold/olm-catalog/csv*.go: set install strategy if empty
  CHANGELOG.md
  internal/scaffold/olm-catalog/csv_updaters.go
Labels: kind/bug, olm-catalog, size/S

#2293 CHANGELOG.md: add gen-csv Go API code annotations PR #1162
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#2301 Added `displayName` as required field.
  doc/user/olm-catalog/generating-a-csv.md
Labels: kind/documentation, lgtm, olm-catalog, size/XS

#2296 Helm: always use GOOS=linux for operator base image
  Makefile
  hack/image/build-helm-image.sh
Labels: approved, lgtm, size/XS

#2268 use go's built-in runtime arch
  CHANGELOG.md
  cmd/operator-sdk/build/cmd.go
Labels: approved, size/XS

#2246 Changed log.info to tidy up using fmt.sprintf
  CHANGELOG.md
  pkg/ansible/watches/watches.go
Labels: kind/bug, size/M

#2305 update ref links
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  doc/user/unit-testing.md
Labels: lgtm, size/S

#2311 *: release v0.13.0
  CHANGELOG.md
  doc/dev/release.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2314 *: bump to v0.13.0+git
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2317 doc: improve README to try operator-sdk
  README.md
Labels: lgtm, size/S

#2309 Deprecated SDK impl of DynamicRESTMapper and replace its usage for controller-runtime impl
  CHANGELOG.md
  internal/olm/client/client.go
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
  pkg/ansible/run.go
  pkg/restmapper/dynamicrestmapper.go
Labels: approved, lgtm, size/M

#2316 hack/generate/gen-test-framework.sh: fix for release branches
  hack/generate/gen-test-framework.sh
Labels: lgtm, size/XS

#2315 *: bump to v0.13.0+git
  CHANGELOG.md
  hack/generate/gen-test-framework.sh
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#1047 pkg/{ansible,helm}/controller: cached default manager client
  CHANGELOG.md
  hack/tests/e2e-ansible.sh
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
  pkg/ansible/run.go
  pkg/helm/run.go
Labels: ansible-operator, helm-operator, kind/bug, size/L

#2312 cmd/operator-sdk/build: fix handling of spaces within quotes
  CHANGELOG.md
  cmd/operator-sdk/build/cmd.go
  go.mod
  go.sum
  hack/tests/subcommand.sh
  test/test-framework/go.sum
Labels: lgtm, size/S

#2080 Upgrade helm-operator to Helm v3
  CHANGELOG.md
  cmd/operator-sdk/new/cmd.go
  doc/helm/dev/developer_guide.md
  doc/helm/project_layout.md
  doc/helm/user-guide.md
  go.mod
  go.sum
  internal/olm/client/client.go
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/chart.go
  internal/scaffold/helm/chart_test.go
  internal/scaffold/helm/go_mod.go
  internal/scaffold/helm/role.go
  internal/scaffold/helm/role_test.go
  internal/scaffold/helm/testdata/testcharts/test-chart-1.2.0.tgz
  internal/scaffold/helm/testdata/testcharts/test-chart-1.2.3.tgz
  internal/scaffold/helm/testdata/testcharts/test-chart/.helmignore
  internal/scaffold/helm/testdata/testcharts/test-chart/Chart.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/NOTES.txt
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/_helpers.tpl
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/deployment.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/ingress.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/service.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/serviceaccount.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/tests/test-connection.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/values.yaml
  pkg/helm/client/client.go
  pkg/helm/controller/controller.go
  pkg/helm/controller/reconcile.go
  pkg/helm/engine/doc.go
  pkg/helm/engine/ownerref.go
  pkg/helm/engine/ownerref_test.go
  pkg/helm/release/manager.go
  pkg/helm/release/manager_factory.go
  pkg/helm/watches/watches.go
  pkg/helm/watches/watches_test.go
  test/test-framework/go.mod
  test/test-framework/go.sum
Labels: area/dependency, size/XXL

#2326 add scorecard bundle validation feature
  CHANGELOG.md
  cmd/operator-sdk/scorecard/cmd.go
  doc/cli/operator-sdk_scorecard.md
  doc/test-framework/scorecard.md
  go.mod
  go.sum
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/helpers/helpers.go
  internal/scorecard/helpers/test_definitions.go
  internal/scorecard/plugins/config.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/scorecard.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1alpha2/formatter.go
  pkg/apis/scorecard/v1alpha2/types.go
  pkg/apis/scorecard/v1v2conversions.go
  test/test-framework/.osdk-scorecard-bundle.yaml
  test/test-framework/go.sum
Labels: lgtm, size/XL

#2322 cmd/operator-sdk/olmcatalog: gen-csv must run in project root
  CHANGELOG.md
  cmd/operator-sdk/olmcatalog/gen-csv.go
Labels: olm-catalog, size/XS

#2323 CHANGELOG.md: add leader election bugfix (#2210)
  CHANGELOG.md
Labels: kind/documentation, lgtm, size/XS

#2310 Remove k8s_status module, install from galaxy
  CHANGELOG.md
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  cmd/operator-sdk/migrate/cmd.go
  doc/ansible/dev/developer_guide.md
  hack/image/ansible/scaffold-ansible-image.go
  internal/scaffold/ansible/dockerfilehybrid.go
  internal/scaffold/ansible/k8s_status.go
  internal/scaffold/ansible/roles_meta_main.go
  test/ansible-memcached/tasks.yml
Labels: size/XL

#2321 feat:Improve log format of Ansible-based Operators
  CHANGELOG.md
  pkg/ansible/events/log_events.go
Labels: approved, lgtm, size/S

#2331 scorecard - add shortnames labels to each test
  CHANGELOG.md
  doc/test-framework/scorecard.md
  internal/scorecard/plugins/basic_tests.go
  internal/scorecard/plugins/labels.go
  internal/scorecard/plugins/labels_test.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
Labels: size/L

#2341 update the link in master
  doc/proposals/sdk-integration-with-olm.md
Labels: lgtm, size/XS

#2343 doc/proposals/openshift-4.4/tech-debt.md: add proposal
  doc/proposals/tech-debt.md
Labels: lgtm, size/L

#2330 CHANGELOG.md: add leader election bugfix (#2210)
  CHANGELOG.md
Labels: lgtm, size/XS

#2338 combine commons.sh scripts and update dependent tests
  hack/common.sh
  hack/lib/common.sh
  hack/tests/check-lint.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/subcommand-scorecard.sh
Labels: lgtm, size/M

#2328 internal/generate: interfaces and types for generators
  internal/generate/gen/generator.go
  internal/generate/gen/rules.go
Labels: kind/feature, size/L

#2348 doc/proposals/openshift-4.4: add k8s-1.17 proposal, move tech debt proposal
  doc/proposals/openshift-4.4/kubernetes-1.17.md
  doc/proposals/openshift-4.4/tech-debt.md
Labels: lgtm, size/L

#2344 doc/proposals/openshift-4.4/ansible-operator-devex.md: Add proposal for Ansible Operator 4.4 features
  doc/proposals/openshift-4.4/ansible-operator-devex.md
Labels: lgtm, size/L

#2350 Add 4.4 proposal for Kubebuilder integration for Go operators
  doc/proposals/openshift-4.4/kubebuilder-integration.md
Labels: kind/documentation, size/L
