Repository operator-framework/operator-sdk, pull requests merged in 2019-02, with the labels that each got.

#1042 Makefile: trim gopath from panic logs
  Makefile
  commands/operator-sdk/cmd/build.go
  hack/image/build-scorecard-proxy-image.sh
Labels: bug, size/S

#1045 pkg/leader: Switch to controller-runtime config pkg
  pkg/leader/leader.go
Labels: size/XS

#1022 ansible/controller,helm/controller: reconcile controller to use cache
  pkg/ansible/controller/controller.go
  pkg/helm/controller/controller.go
Labels: ansible-operator, bug, helm-operator, size/S

#1048 pkg/ansible/controller: reconciler needs to get the resource
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
Labels: size/S

#1050 commands/.../generate: add defaulter-gen support
  commands/operator-sdk/cmd/generate/k8s.go
Labels: size/S

#1043 Makefile: trim gopath from panic logs (#1042)
  Makefile
  commands/operator-sdk/cmd/build.go
  hack/image/build-scorecard-proxy-image.sh
Labels: size/S

#1046 commands/../new.go: Clarify flags use cases
  commands/operator-sdk/cmd/new.go
Labels: size/XS

#916 pkg/helm: new watch file option to support watching dependent resources
  pkg/helm/controller/reconcile.go
  pkg/helm/release/manager_factory.go
  pkg/helm/release/new.go
  pkg/helm/run.go
  pkg/helm/watches/watches.go
Labels: size/L

#1031 pkg/ansible; Add support to watch cluster-scoped resources (#924)
  doc/ansible/dev/advanced_options.md
  images/scorecard-proxy/cmd/proxy/main.go
  pkg/ansible/controller/controller.go
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/controllermap/controllermap.go
  pkg/ansible/proxy/kubeconfig/kubeconfig.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/proxy/proxy_test.go
  pkg/ansible/run.go
  pkg/ansible/runner/fake/runner.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/runner/testdata/valid.yaml.tmpl
Labels: ansible-operator, bug, size/L, v0.4.x

#1026 doc/test-framework/scorecard: add config file section
  doc/test-framework/scorecard.md
Labels: docs, scorecard, size/S

#979 commands/.../scorecard,Gopkg.lock: add crdsHaveValidation func
  commands/operator-sdk/cmd/scorecard.go
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  doc/test-framework/scorecard.md
  hack/tests/scorecard-subcommand.sh
  test/test-framework/deploy/namespace-init.yaml
Labels: enhancement, scorecard, size/L

#1058 scorecard CI: use non-default scorecard config
  commands/operator-sdk/cmd/scorecard/scorecard.go
  hack/tests/scorecard-subcommand.sh
  test/test-framework/.test-osdk-scorecard.yaml
Labels: scorecard, size/S, testing

#1039 pkg/ansible/proxy: adding ability for dependent watches to be recovered
  pkg/ansible/proxy/proxy.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, bug, size/L

#1066 pkg/ansible: Update the running condition when reconcile happens
  pkg/ansible/controller/reconcile.go
Labels: ansible-operator, bug, size/M, v0.4.x

#1068 .travis.yml: cache $HOME/.cache/go-build
  .travis.yml
Labels: size/XS, testing

#1056 pkg/scaffold/crd*.go: support crd.Versions
  pkg/scaffold/crd.go
  pkg/scaffold/crd_test.go
Labels: enhancement, size/M

#1067 pkg/ansible/proxy: adding ability for dependent watches to be recovered
  pkg/ansible/proxy/proxy.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, bug, size/L, v0.4.x

#1023 pkg/ansible/runner: Add ability to specify ANSIBLE_INVENTORY env variable
  hack/tests/e2e-ansible-molecule.sh
  pkg/ansible/runner/internal/inputdir/inputdir.go
  test/ansible-inventory/ansible.cfg
  test/ansible-inventory/build/Dockerfile
  test/ansible-inventory/deploy/crds/inventory_v1alpha1_inventory_cr.yaml
  test/ansible-inventory/deploy/crds/inventory_v1alpha1_inventory_crd.yaml
  test/ansible-inventory/deploy/operator.yaml
  test/ansible-inventory/deploy/role.yaml
  test/ansible-inventory/deploy/role_binding.yaml
  test/ansible-inventory/deploy/service_account.yaml
  test/ansible-inventory/inventory/group_vars/test.yml
  test/ansible-inventory/inventory/hosts
  test/ansible-inventory/molecule/test-local/asserts.yml
  test/ansible-inventory/molecule/test-local/molecule.yml
  test/ansible-inventory/molecule/test-local/playbook.yml
  test/ansible-inventory/molecule/test-local/prepare.yml
  test/ansible-inventory/playbooks/playbook.yml
  test/ansible-inventory/plugins/filter/test.py
  test/ansible-inventory/roles/inventory/tasks/main.yml
  test/ansible-inventory/watches.yaml
Labels: ansible-operator, bug, size/XL

#1070 *: release v0.4.1
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#1073 pkg,version,CHANGELOG: bump to v0.4.1+git
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#1060 package/scaffold/olm-catalog: fix CRD description updater
  pkg/scaffold/crd_test.go
  pkg/scaffold/olm-catalog/csv_updaters.go
  pkg/scaffold/scaffold.go
Labels: bug, olm-catalog, size/M

#1075 hack/ci/check-doc-only-update: don't set -x
  hack/ci/check-doc-only-update.sh
Labels: size/XS, testing

#1072 Fix few typos
  CHANGELOG.md
  doc/proposals/ansible-operator.md
  doc/proposals/helm-operator.md
Labels: size/XS

#1079 MAINTAINERS: add @theishshah
  MAINTAINERS
Labels: size/XS

#1078 Release v0.5.0
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#1080 Post Release Clean-Up
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1071 commands/.../scorecard: move getCRDs to k8sutil
  commands/operator-sdk/cmd/generate/openapi.go
  commands/operator-sdk/cmd/olm-catalog/gen-csv.go
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  internal/util/k8sutil/crd.go
Labels: enhancement, refactoring, size/L

#1084 Correct path in example
  doc/ansible/user-guide.md
Labels: needs-ok-to-test, size/XS

#1089 pkg/test/main_entry.go: build local binary instead of `go run`
  CHANGELOG.md
  pkg/test/main_entry.go
Labels: bug, size/S, test-framework

#1081 doc/dev/release: make some minor corrections
  doc/dev/release.md
Labels: docs, size/XS

#1083 pkg/scaffold: use afero.Fs instead of os package directly
  internal/util/fileutil/file_util.go
  pkg/scaffold/ansible/k8s_status.go
  pkg/scaffold/crd.go
  pkg/scaffold/customrender.go
  pkg/scaffold/olm-catalog/concat_crd.go
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/scaffold.go
Labels: enhancement, size/M

#1059 yamlutil: add directory parameters to manifest generators
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  commands/operator-sdk/cmd/test/local.go
  internal/util/yamlutil/manifest.go
  test/e2e/memcached_test.go
Labels: refactoring, scorecard, size/M

#1076 pkg/scaffold: Adjust log msg create -> created
  doc/helm/dev/developer_guide.md
  doc/sdk-cli-reference.md
  pkg/scaffold/helm/chart.go
  pkg/scaffold/scaffold.go
Labels: size/M

#998 Remove hyphen from controller generated code
  pkg/scaffold/addtoscheme.go
  pkg/scaffold/controller_kind.go
  pkg/scaffold/doc.go
  pkg/scaffold/register.go
  pkg/scaffold/resource.go
  pkg/scaffold/types.go
Labels: size/S

#1027 commands/.../scorecard: improve crd resources check
  commands/operator-sdk/cmd/scorecard/basic_tests.go
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  hack/tests/scorecard-subcommand.sh
  test/test-framework/.test-osdk-scorecard.yaml
  test/test-framework/deploy/memcachedoperator.0.0.2.csv.yaml
Labels: enhancement, scorecard, size/L

#1108 doc/dev/release.md: remove flaky hyperlink
  doc/dev/release.md
Labels: docs, size/XS, testing

#1104 Update diagrams for the latest Operator Maturity Model in png and svg format
  doc/images/Operator-Maturity-Model-transparent-bg.png
  doc/images/Operator-Maturity-Model.png
  doc/images/Operator-Maturity-Model.svg
Labels: size/M

#1052 doc/user-guide: show how to enable both leader election options
  doc/user-guide.md
Labels: docs, size/M

#1109 commands/.../test,pkg/test: fix test local --up-local
  commands/operator-sdk/cmd/test/local.go
  pkg/test/main_entry.go
Labels: bug, size/S, test-framework

#1096 New Operator maturity model
  doc/design/milestone-0.2.0/csv-generation.md
  doc/images/Operator-Maturity-Detailed.png
  doc/images/operator-maturity-model-transparent-bg.png
  doc/images/operator-maturity-model.png
  doc/images/operator-maturity-model.svg
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator.csv.yaml
Labels: docs, needs-ok-to-test, size/XS

#1111 commands/.../test/local: move an error check to correct location
  commands/operator-sdk/cmd/test/local.go
Labels: size/XS, test-framework

#1110 commands/.../test,pkg/test: fix test local --up-local (#1109)
  CHANGELOG.md
  commands/operator-sdk/cmd/test/local.go
Labels: bug, size/S, test-framework, v0.4.x

#1037 pkg/metrics: Add Deployment ownerReference to metrics Service object
  commands/operator-sdk/cmd/test/cluster.go
  pkg/k8sutil/constants.go
  pkg/k8sutil/k8sutil.go
  pkg/leader/leader.go
  pkg/metrics/metrics.go
Labels: size/L

#1016 CSV versioning
  commands/operator-sdk/cmd/olm-catalog/gen-csv.go
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
  hack/tests/scorecard-subcommand.sh
  pkg/scaffold/olm-catalog/concat_crd.go
  pkg/scaffold/olm-catalog/concat_crd_test.go
  pkg/scaffold/olm-catalog/config.go
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/olm-catalog/csv_test.go
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  test/test-framework/.test-osdk-scorecard.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
Labels: enhancement, needs discussion, olm-catalog, size/L

#1119 doc/*: fix broken links
  doc/dev/developer_guide.md
  doc/dev/release.md
  doc/versioning.md
Labels: size/XS

#1125 documentation: Add Ansible Operator Flow document
  doc/ansible/ao-flow.png
  doc/ansible/information-flow-ansible-operator.md
Labels: ansible-operator, needs-ok-to-test, size/M

#1121 misspell: Fix misspelled words
  doc/ansible/dev/developer_guide.md
  doc/proposals/ansible-operator.md
  pkg/ansible/controller/reconcile.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  pkg/k8sutil/constants.go
  pkg/k8sutil/k8sutil_test.go
  pkg/metrics/metrics.go
  pkg/ready/ready.go
  pkg/scaffold/ansible/molecule_test_cluster_playbook.go
  pkg/scaffold/ansible/molecule_test_local_playbook.go
  test/ansible-inventory/molecule/test-local/playbook.yml
  test/ansible-memcached/asserts.yml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
Labels: needs-ok-to-test, size/M

#1126 doc/helm/*: fix helm docs links
  doc/helm/dev/developer_guide.md
  doc/helm/project_layout.md
  doc/helm/user-guide.md
Labels: size/S

#1114 pkg/scaffold/helm/operator.go: Remove metrics port
  pkg/scaffold/helm/operator.go
Labels: size/XS

#1113 Add docs for finalizers
  doc/ansible/dev/advanced_options.md
  doc/ansible/dev/finalizers.md
  doc/user-guide.md
Labels: ansible-operator, size/L

#1131 Molecule override cmd
  pkg/scaffold/ansible/molecule_default_molecule.go
  pkg/scaffold/ansible/molecule_test_local_molecule.go
  test/ansible-inventory/molecule/test-local/molecule.yml
  test/ansible-memcached/molecule.yml
Labels: size/XS

#1133 pkg/scaffold/olm-catalog: add InstallModes to CSV's
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
Labels: olm-catalog, size/S

#1135 pkg/helm/run.go: fix logging when WATCH_NAMESPACE=""
  pkg/helm/run.go
Labels: size/XS

#1136 Code cleanup for removing unused container port:60000
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  pkg/scaffold/olm-catalog/testdata/deploy/operator.yaml
  test/ansible-inventory/deploy/operator.yaml
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  test/test-framework/deploy/operator.yaml
Labels: needs-ok-to-test, size/S

#1139 Use RHEL UBI for go, helm, and scorecard base images
  CHANGELOG.md
  doc/sdk-cli-reference.md
  images/scorecard-proxy/Dockerfile
  pkg/scaffold/build_dockerfile.go
  pkg/scaffold/build_dockerfile_test.go
  pkg/scaffold/helm/dockerfilehybrid.go
Labels: size/S

#1095 test/test-framework/deploy: make memcached CSV OLM-ready
  hack/tests/scorecard-subcommand.sh
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
Labels: olm-catalog, size/L

#1140 CHANGELOG: CSV versioning
  CHANGELOG.md
Labels: docs, size/XS

#1141 hack,pkg/ansible/proxy: move ansible proxy test to e2e
  hack/tests/e2e-ansible.sh
  hack/tests/unit.sh
  pkg/ansible/proxy/proxy_test.go
Labels: ansible-operator, size/S, testing

#1118 pkg/scaffold/olm-catalog: remove required CRDDescription updater
  pkg/scaffold/olm-catalog/csv_updaters.go
  pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha1_app_crd.yaml
  pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha2_app_crd.yaml
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
Labels: olm-catalog, size/M

#1145 hack/ci/marker: recompile marker with CentOS 7
  hack/ci/marker
Labels: size/XS, testing

#1142 Use registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:7.6 for UBI
  CHANGELOG.md
  doc/sdk-cli-reference.md
  images/scorecard-proxy/Dockerfile
  pkg/scaffold/build_dockerfile.go
  pkg/scaffold/build_dockerfile_test.go
  pkg/scaffold/helm/dockerfilehybrid.go
Labels: size/S

#1146 OWNERS: add file
  OWNERS
Labels: size/S

#1044 commands/.../scorecard: optionally use only a CSV manifest when deployed with OLM
  CHANGELOG.md
  commands/operator-sdk/cmd/scorecard.go
  commands/operator-sdk/cmd/scorecard/basic_tests.go
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  doc/sdk-cli-reference.md
  pkg/scaffold/ansible/k8s_status.go
Labels: enhancement, olm-catalog, scorecard, size/L

#1009 test/e2e,pkg/test/e2eutil: re-enable and fix leader election e2e test
  pkg/test/e2eutil/wait_util.go
  test/e2e/incluster-test-code/memcached_test.go.tmpl
  test/e2e/memcached_test.go
Labels: size/M

#1138 pkg/ansible: Adding ability to have a flag that turns off the owner ref.
  doc/ansible/dev/advanced_options.md
  images/scorecard-proxy/cmd/proxy/main.go
  pkg/ansible/flags/flag.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/run.go
Labels: ansible-operator, size/M
