Repository operator-framework/operator-sdk, pull requests merged in 2019-10, with the labels that each got.

#1940 doc/dev/release.md: add statement ppcle64 support
  CHANGELOG.md
  doc/dev/release.md
Labels: lgtm, size/XS

#1971 travis: use kind instead of openshift
  .travis.yml
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
  hack/ci/setup-k8s.sh
  hack/ci/setup-openshift.sh
  hack/image/build-ansible-image.sh
  hack/image/build-helm-image.sh
  hack/image/build-scorecard-proxy-image.sh
  hack/lib/image_lib.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-go.sh
  hack/tests/e2e-helm.sh
  hack/tests/scaffolding/scaffold-memcached.go
  test/test-framework/test/e2e/memcached_test.go
Labels: lgtm, size/L

#1970 ci: run tests being run in prow CI in travis CI for non-master…
  .gitignore
  .travis.yml
  Makefile
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible-e2e.Dockerfile
  ci/dockerfiles/builder.Dockerfile
  ci/dockerfiles/go-e2e.Dockerfile
  ci/dockerfiles/helm-e2e-hybrid.Dockerfile
  ci/dockerfiles/helm-e2e.Dockerfile
  ci/dockerfiles/scorecard-proxy.Dockerfile
  ci/prow.Makefile
  ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-ansible-scaffold.sh
  ci/tests/scaffolding/e2e-go-scaffold.sh
  ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-helm-scaffold.sh
  ci/tests/scaffolding/scorecard-proxy-scaffold.sh
  ci/tests/subcommand-scorecard.sh
  ci/tests/subcommand.sh
  doc/dev/developer_guide.md
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
  hack/tests/subcommand-olm-install.sh
  hack/tests/subcommand-scorecard.sh
  hack/tests/subcommand.sh
Labels: size/L, testing

#1998 doc: show how to expose custom metrics
  doc/user/metrics/README.md
Labels: kind/documentation, ok-to-test, size/XS

#1960 Fix minor typo in faq.md
  doc/faq.md
Labels: approved, lgtm, ok-to-test, size/XS

#1990 Ansible ubi upgrade
  CHANGELOG.md
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/tests/e2e-ansible.sh
  doc/sdk-cli-reference.md
  internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/M

#2004 ansible images using just ubi8
  CHANGELOG.md
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  internal/pkg/scaffold/ansible/ao_logs.go
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/M

#1943 Breaking change: bumping kube-state-metrics to v1.7.2
  CHANGELOG.md
  go.mod
  go.sum
  pkg/kube-metrics/metrics.go
  pkg/kube-metrics/server.go
  pkg/kube-metrics/store.go
Labels: size/M

#1945 hack/tests: remove tty setup in e2e usage of kubectl run
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
Labels: size/S

#2015 *: fix gen-csv to copy CRD manifests with any name
  CHANGELOG.md
  cmd/operator-sdk/olmcatalog/gen-csv.go
  internal/util/k8sutil/k8sutil.go
Labels: kind/bug, lgtm, release-blocker, size/S

#1916 initial draft of operator-testing-tool proposal for openshift-4.3
  doc/proposals/openshift-4.3/operator-testing-tool.md
Labels: size/L

#1899 go.mod,go.sum,internal/pkg/scaffold: use git.apache.org mirror
  go.mod
  go.sum
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/helm/go_mod.go
Labels: area/dependency, size/M

#2017 internal/pkg/scaffold/olm-catalog/csv_updaters.go: fix applying owned CRDs
  CHANGELOG.md
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
Labels: lgtm, release-blocker, size/XS

#1928 doc(Issue:1905):Improve doc titles in order to better be returned in the searches
  doc/ansible/dev/advanced_options.md
  doc/ansible/dev/apb_migration_guide.md
  doc/ansible/dev/dependent_watches.md
  doc/ansible/dev/finalizers.md
  doc/ansible/dev/testing_guide.md
  doc/ansible/information-flow-ansible-operator.md
  doc/ansible/project_layout.md
  doc/dev/release.md
  doc/dev/reporting_bugs.md
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
  doc/faq.md
  doc/helm/dev/developer_guide.md
  doc/helm/project_layout.md
  doc/migration/v0.1.0-migration-guide.md
  doc/migration/version-upgrade-guide.md
  doc/operator-scope.md
  doc/project_layout.md
  doc/proposals/README.md
  doc/proposals/TEMPLATE.md
  doc/proposals/ansible-operator-status.md
  doc/proposals/ansible-operator-testing.md
  doc/proposals/ansible-operator.md
  doc/proposals/cli-ux-phase1.md
  doc/proposals/helm-operator.md
  doc/proposals/improved-scorecard-config.md
  doc/proposals/leader-for-life.md
  doc/proposals/metering-operator-metrics.md
  doc/proposals/scorecard-plugin-system.md
  doc/proposals/sdk-code-annotations.md
  doc/proposals/tls-utilities.md
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
  doc/user/client.md
  doc/user/event-filtering.md
  doc/user/logging.md
  doc/user/metrics/README.md
  doc/user/metrics/service-monitor.md
  doc/user/olm-catalog/generating-a-csv.md
  doc/user/unit-testing.md
  doc/versioning.md
Labels: size/L

#2022 CHANGELOG: remove extra bugfix section
  CHANGELOG.md
Labels: lgtm, size/XS

#2026 Update writing-e2e-tests doc
  doc/test-framework/writing-e2e-tests.md
Labels: lgtm, size/XS

#1929 same standard for all proposals
  doc/proposals/TEMPLATE.md
  doc/proposals/ansible-operator-status.md
  doc/proposals/ansible-operator-testing.md
  doc/proposals/ansible-operator.md
  doc/proposals/cli-ux-phase1.md
  doc/proposals/helm-operator.md
  doc/proposals/improved-scorecard-config.md
  doc/proposals/leader-for-life.md
  doc/proposals/metering-operator-metrics.md
  doc/proposals/scorecard-plugin-system.md
  doc/proposals/sdk-code-annotations.md
  doc/proposals/tls-utilities.md
Labels: size/L

#2028 fix link doc olm (#1888)
  CHANGELOG.md
  doc/design/milestone-0.2.0/csv-generation.md
  doc/proposals/cli-ux-phase1.md
  doc/proposals/sdk-code-annotations.md
  doc/test-framework/scorecard.md
  doc/user/csv-annotations.md
Labels: backport, release-blocker, size/M

#2021 cherry-pick csv-gen bugfixes for #2015 #2017
  CHANGELOG.md
  cmd/operator-sdk/olmcatalog/gen-csv.go
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/util/k8sutil/k8sutil.go
Labels: backport, kind/bug, size/S

#2027 Fixes #2023: jmespath required to run default molecule tests in Travis CI environment.
  CHANGELOG.md
  internal/pkg/scaffold/ansible/travis.go
Labels: lgtm, ok-to-test, size/XS

#1966 Allow some commands to generate k8s, without requiring build files.
  CHANGELOG.md
  cmd/operator-sdk/main.go
  cmd/operator-sdk/printdeps/cmd.go
  internal/util/projutil/project_util.go
Labels: size/M

#2031 pkg/ansible/controller/reconcile.go: fix invalid logger.Info usage
  CHANGELOG.md
  pkg/ansible/controller/reconcile.go
Labels: approved, kind/bug, lgtm, release-blocker, size/XS

#2035 Cherry pick PR #2031 to v0.10.x
  CHANGELOG.md
  pkg/ansible/controller/reconcile.go
Labels: backport, kind/bug, size/XS

#2038 *: release v0.10.1
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#2041 *: release bump to v0.10.1+git
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#2039 Revert "Allow some commands to generate k8s, without requiring build …
  CHANGELOG.md
  cmd/operator-sdk/main.go
  cmd/operator-sdk/printdeps/cmd.go
  internal/util/projutil/project_util.go
Labels: lgtm, size/M

#2034 *: release v0.11.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#2043 Revert "*: release v0.11.0"
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#2044 *: allow add crd to run for ansible/helm projects outside $GOPATH
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
  cmd/operator-sdk/add/crd.go
  hack/image/build-ansible-image.sh
  hack/image/build-helm-image.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
Labels: size/M

#2047 *: release v0.11.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#2052 *: bump to v0.11.0+git for master
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1997 doc/migration/version-upgrade-guide.md: v0.10 and v0.11 upgrade guides
  doc/migration/version-upgrade-guide.md
  doc/user/unit-testing.md
Labels: approved, do-not-merge/hold, kind/documentation, lgtm, size/L

#2045 ci/tests: add timeout to ansible e2e
  ci/tests/e2e-ansible.sh
Labels: lgtm, size/XS

#2064 cmd: fix typo
  cmd/operator-sdk/new/cmd.go
  doc/sdk-cli-reference.md
Labels: lgtm, ok-to-test, size/XS

#1957 fix t.Fataf using in goroutine
  internal/pkg/scaffold/helm/chart_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1953 scaffold: printVersion includes operator's Version
  CHANGELOG.md
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
Labels: approved, ok-to-test, size/XS

#2070 Add Operator capability level image in the README
  README.md
Labels: size/XS

#2074 Fix ansible-e2e CRD deletion timeouts
  ci/tests/e2e-ansible.sh
Labels: approved, lgtm, size/XS

#2068 Documents Unsupported ansible modules Q/A
  doc/faq.md
Labels: lgtm, ok-to-test, size/S

#2079 Add labels to scorecard tests
  internal/pkg/scorecard/helpers/helpers.go
  internal/pkg/scorecard/helpers/test_definitions.go
  internal/pkg/scorecard/plugins/basic_tests.go
  internal/pkg/scorecard/plugins/labels.go
  internal/pkg/scorecard/plugins/olm_tests.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1v2conversions.go
Labels: scorecard, size/M

#1991 Allow using subset of endpoints when creating a ServiceMonitor
  hack/tests/sanity-check.sh
  pkg/metrics/service-monitor.go
Labels: lgtm, metrics, ok-to-test, size/S

#2067 refactor(ansible): store relevant data on watch
  pkg/ansible/run.go
  pkg/ansible/run_test.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/runner/testdata/playbook.yml
  pkg/ansible/runner/testdata/roles/role/tasks.yaml
  pkg/ansible/watches/testdata/valid.yaml.tmpl
  pkg/ansible/watches/watches.go
  pkg/ansible/watches/watches_test.go
Labels: lgtm, size/XL

#2006 .gitignore: clean up, regexp on top-level artifact dirs
  .gitignore
Labels: approved, lgtm, size/S

#1976 bugfix: error in Do will never return to outer scope
  CHANGELOG.md
  internal/olm/manager.go
Labels: approved, lgtm, ok-to-test, size/S

#1903 docs: make directories clear, escape less than
  doc/ansible/project_layout.md
Labels: approved, lgtm, size/XS

#2051 doc: Explain how to set maxWorkers
  doc/ansible/dev/advanced_options.md
Labels: approved, lgtm, size/M

#2018 operator test tool proposal - add updates from comments
  doc/proposals/openshift-4.3/operator-testing-tool.md
Labels: approved, kind/documentation, size/M

#1936 doc(operator and crds scope) : Improvements with the purpose to make the understanding easier
  doc/operator-scope.md
Labels: approved, lgtm, size/M

#2019 Makefile: Use hyphen instead of slash
  .travis.yml
  Makefile
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/dockerfiles/helm-e2e-hybrid.Dockerfile
  ci/dockerfiles/helm.Dockerfile
  ci/prow.Makefile
  doc/dev/developer_guide.md
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
Labels: size/L

#2087 feat(ansible): make ansible verbosity configurable
  CHANGELOG.md
  doc/ansible/dev/advanced_options.md
  pkg/ansible/flags/flag.go
  pkg/ansible/run.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/watches/testdata/valid.yaml.tmpl
  pkg/ansible/watches/watches.go
  pkg/ansible/watches/watches_test.go
Labels: ansible-operator, lgtm, size/L

#1949 Go 1.13 and removing support for --dep-manager=dep
  .travis.yml
  CHANGELOG.md
  README.md
  ci/dockerfiles/builder.Dockerfile
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/main.go
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/printdeps/cmd.go
  cmd/operator-sdk/test/local.go
  cmd/operator-sdk/up/local.go
  doc/ansible/user-guide.md
  doc/dev/release.md
  doc/helm/user-guide.md
  doc/project_layout.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  doc/user/install-operator-sdk.md
  go.mod
  go.sum
  hack/ci/setup-build-dependencies.sh
  hack/tests/sanity-check.sh
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/ansible/gopkgtoml.go
  internal/scaffold/go_mod.go
  internal/scaffold/gopkgtoml.go
  internal/scaffold/helm/go_mod.go
  internal/scaffold/helm/gopkgtoml.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
  pkg/test/main_entry.go
  release.sh
Labels: size/XL

#2090 fix role for the metric services
  CHANGELOG.md
  internal/scaffold/role.go
  internal/scaffold/role_test.go
Labels: approved, lgtm, size/XS

#2098 hack/tests/sanity-check.sh: fail on changed go.mod and go.sum
  hack/tests/sanity-check.sh
Labels: lgtm, size/XS

#2104 fix Dockerfile ansible test image
  internal/scaffold/ansible/build_test_framework_dockerfile.go
Labels: ansible-operator, size/XS

#2083 Bump to controller-runtime 0.3.0 and Kubernetes 1.15
  CHANGELOG.md
  doc/dev/release.md
  go.mod
  go.sum
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/crd.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
Labels: lgtm, size/XL

#2093 fix(ansible): invalid maxArtifacts annotation
  CHANGELOG.md
  pkg/ansible/runner/runner.go
Labels: ansible-operator, approved, kind/bug, lgtm, size/XS

#1913 doc/proposals/sdk-integration-with-olm.md: SDK/OLM integration…
  doc/proposals/sdk-integration-with-olm.md
Labels: size/L

#2116 internal/util/operator-registry: fix default channel check
  CHANGELOG.md
  internal/util/operator-registry/package_manifest.go
  internal/util/operator-registry/package_manifest_test.go
Labels: olm-catalog, size/L

#1816 doc/test-framework/scorecard.md: document --olm-deployed prereq…
  doc/test-framework/scorecard.md
Labels: approved, kind/documentation, scorecard, size/L

#1955 doc/proposals: proposal for upstreaming features into controller-runtime
  doc/proposals/upstream-osdk-features-into-controller-runtime.md
Labels: size/L

#2053 *: bump to v0.11.0+git for v0.11.x
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: approved, backport, size/M

#2109 *: updating k8s version references, follow-up from #2083
  CHANGELOG.md
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
  ci/tests/subcommand.sh
  hack/ci/setup-k8s.sh
  internal/scaffold/ansible/molecule_default_molecule.go
  internal/scaffold/ansible/molecule_test_local_molecule.go
  test/ansible-inventory/molecule/test-local/molecule.yml
  test/ansible-memcached/molecule.yml
  test/e2e/_incluster-test-code/memcached_test.go
Labels: lgtm, size/S

#2096 add selector flag to the scorecard subcommand
  CHANGELOG.md
  cmd/operator-sdk/scorecard/cmd.go
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/config.go
  internal/scorecard/helpers/test_definitions.go
  internal/scorecard/plugins/basic_tests.go
  internal/scorecard/plugins/config.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/scorecard.go
Labels: lgtm, scorecard, size/L

#2119 *: release v0.12.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2120 hack/tests/e2e-ansible*: fix travis ansible e2e tests
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
Labels: size/S

#2124 *: bump to v0.12.0+git for master
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2126 *: remove broken and unnecessary Go env for master
  Makefile
  README.md
  ci/dockerfiles/builder.Dockerfile
  ci/prow.Makefile
  ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  hack/tests/scaffolding/scaffold-memcached.go
Labels: lgtm, size/S

#2135 *: remove broken and unnecessary Go env for v0.12.x
  Makefile
  README.md
  ci/dockerfiles/builder.Dockerfile
  ci/prow.Makefile
  ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  hack/tests/scaffolding/scaffold-memcached.go
Labels: lgtm, size/S

#2024 Ansible operator: Adding support for event filtering via predicates
  CHANGELOG.md
  pkg/ansible/proxy/proxy.go
  pkg/helm/controller/controller.go
  pkg/internal/predicates/predicates.go
Labels: ansible-operator, lgtm, ok-to-test, size/L

#2107 fix ansible minimal version in the roles
  CHANGELOG.md
  internal/scaffold/ansible/roles_meta_main.go
Labels: ansible-operator, kind/bug, lgtm, size/XS

#2136 *: bump to v0.12.0+git for v0.12.x
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2134 doc/user-guide.md: add CRD validation annotation notes
  doc/user-guide.md
Labels: kind/documentation, size/M
