Repository operator-framework/operator-sdk, pull requests merged in 2019-06, with the labels that each got.

#1510 Update install guide with 0.8.1 version
  doc/user/install-operator-sdk.md
Labels: ok-to-test, size/XS

#1422 Add run local in debug
  CHANGELOG.md
  README.md
  cmd/operator-sdk/up/local.go
  doc/sdk-cli-reference.md
Labels: ok-to-test, size/S

#1470 cmd/operator-sdk: codify openapi and deepcopy generators
  Gopkg.lock
  Gopkg.toml
  cmd/operator-sdk/internal/genutil/genutil.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/tools.go
  internal/util/projutil/exec.go
  vendor/k8s.io/code-generator/LICENSE
  vendor/k8s.io/code-generator/cmd/deepcopy-gen/args/args.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/doc.go
  vendor/k8s.io/gengo/examples/set-gen/sets/empty.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/args/args.go
  vendor/k8s.io/kube-openapi/pkg/generators/api_linter.go
  vendor/k8s.io/kube-openapi/pkg/generators/extension.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/doc.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/names_match.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/empty.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/string.go
Labels: area/dependency, priority/important-soon, size/XXL

#1509 Add --local-operator-flags for testing with --up-local
  cmd/operator-sdk/test/local.go
  doc/sdk-cli-reference.md
  pkg/test/main_entry.go
Labels: size/M

#1482 pkg/helm/run.go,pkg/internal/scaffold: helm operator metrics
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/role.go
  internal/pkg/scaffold/helm/role_test.go
  internal/pkg/scaffold/role.go
  internal/pkg/scaffold/role_test.go
  pkg/helm/run.go
Labels: size/L

#1396 internal/pkg/scaffold/olm-catalog: use olm.targetNamespaces annotation in WATCH_NAMESPACE
  CHANGELOG.md
  internal/pkg/scaffold/olm-catalog/csv_test.go
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
Labels: kind/bug, olm-catalog, size/L

#1420 Added changes in README.md
  doc/user/install-operator-sdk.md
Labels: ok-to-test, size/XS

#1483 pkg/scaffold/helm/chart_test.go: add chart scaffolding tests
  internal/pkg/scaffold/helm/chart_test.go
Labels: lgtm, size/L

#1535 cmd/operator-sdk/build: expand env in go build
  CHANGELOG.md
  cmd/operator-sdk/build/cmd.go
  internal/util/projutil/exec.go
Labels: kind/bug, size/XS

#1519 *: remove vendor requirements
  CHANGELOG.md
  README.md
  cmd/operator-sdk/new/cmd.go
  doc/project_layout.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  internal/util/projutil/exec.go
  test/e2e/memcached_test.go
Labels: size/L

#1525 cmd/operator-sdk/internal/genutil: relax version dir check in `parseGroupVersions()`
  CHANGELOG.md
  cmd/operator-sdk/internal/genutil/genutil.go
Labels: size/S

#1515 pkg/helm/release/manager.go: improve error handling with failed releases
  pkg/helm/controller/reconcile.go
  pkg/helm/release/manager.go
Labels: lgtm, size/M

#1547 internal/pkg/scaffold/helm/chart_test.go: add license header
  internal/pkg/scaffold/helm/chart_test.go
Labels: size/S

#1450 test/e2e: allow release PRs to pass CI
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  test/e2e/main_test.go
  test/e2e/memcached_test.go
Labels: size/L, testing

#1548 hack/lib/test_lib.sh: `listFiles` is GOPATH-agnostic
  hack/lib/test_lib.sh
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/util/projutil/project_util.go
Labels: size/S

#1463 pkg/ansible: pass along requests for virtual resources to cluster
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/inject_owner.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/runner/eventapi/eventapi.go
  test/ansible-memcached/asserts.yml
  test/ansible-memcached/tasks.yml
Labels: lgtm, size/L

#1506 internal/annotations/prefix.go: define annotation separators, join and split functions
  internal/annotations/prefix.go
  internal/annotations/prefix_test.go
Labels: size/L

#1544 Fix multiline boilerplates
  internal/pkg/scaffold/boilerplate_go_txt_test.go
  internal/pkg/scaffold/scaffold.go
Labels: lgtm, size/M

#1277 pkg/kube-metrics: Add initial operator specific metrics
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  pkg/k8sutil/k8sutil.go
  pkg/kube-metrics/collector.go
  pkg/kube-metrics/metrics.go
  pkg/kube-metrics/server.go
  pkg/kube-metrics/uclient.go
  test/e2e/memcached_test.go
  vendor/k8s.io/kube-state-metrics/LICENSE
  vendor/k8s.io/kube-state-metrics/pkg/collector/collector.go
  vendor/k8s.io/kube-state-metrics/pkg/metric/family.go
  vendor/k8s.io/kube-state-metrics/pkg/metric/generator.go
  vendor/k8s.io/kube-state-metrics/pkg/metric/metric.go
  vendor/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go
Labels: size/XXL

#1507 internal/util/projutil: generalize project util functions for GOPATH and non-GOPATH scenarios
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
Labels: lgtm, size/M

#1557 cmd/operator-sdk/new/cmd.go: only validate new go projects
  cmd/operator-sdk/new/cmd.go
  doc/sdk-cli-reference.md
Labels: lgtm, size/S

#1555 Fix minor typo
  doc/design/milestone-0.0.2/query-api.md
Labels: ok-to-test, size/XS

#1520 faq + explanation fo resourceVersion too old
  README.md
  doc/faq.md
Labels: lgtm, size/M

#1440 doc(unit-testing): Improvements, add example/explanation over how to use third-party resources and common issues
  doc/user/unit-testing.md
Labels: lgtm, ok-to-test, size/L

#1401 internal/pkg/scaffold: add group.go scaffold to prevent deepcopy parse errors
  CHANGELOG.md
  cmd/operator-sdk/add/api.go
  internal/pkg/scaffold/group.go
Labels: size/M

#1528 pkg/*,internal/pkg/flags: move flags packages to internal/flags
  cmd/operator-sdk/main.go
  internal/flags/flags.go
  internal/flags/watch/flags.go
  pkg/ansible/flags/flag.go
  pkg/helm/flags/flag.go
Labels: size/S

#1563 ansible-operator: Add extra var containing watched resource spec
  CHANGELOG.md
  doc/ansible/dev/developer_guide.md
  pkg/ansible/runner/runner.go
Labels: lgtm, size/S

#1524 doc/user-guide.md: improve finalizer example
  doc/user-guide.md
Labels: lgtm, size/L

#1532 doc/user/logging.md: update to include a runnable standalone example
  doc/user/logging.md
Labels: size/L

#1562 pkg/metrics/service-monitor.go: Populate all ports
  pkg/metrics/service-monitor.go
Labels: lgtm, size/S

#1572 hack/ci/setup-build-dependencies.sh: add setup script in SDK repo
  .travis.yml
  hack/ci/setup-build-dependencies.sh
Labels: lgtm, size/S, testing

#1475 *: remove GOPATH requirement from the SDK and operator projects
  CHANGELOG.md
  README.md
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/add/controller.go
  cmd/operator-sdk/add/crd.go
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  cmd/operator-sdk/main.go
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/olmcatalog/gen-csv.go
  cmd/operator-sdk/up/local.go
  doc/dev/testing/running-the-tests.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  hack/image/build-ansible-image.sh
  hack/image/build-helm-image.sh
  hack/image/build-scorecard-proxy-image.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/internal/deps/print_go_mod.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
  test/e2e/memcached_test.go
Labels: size/L

#1565 internal/pkg/scorecard: access `CRManifestOpt` correctly with `--olm-deployed`
  CHANGELOG.md
  internal/pkg/scorecard/scorecard.go
Labels: kind/bug, scorecard, size/M

#1521 doc/user/metrics/README.md: Add Custom Resource docs
  doc/user/metrics/README.md
Labels: do-not-merge/hold, lgtm, size/S

#1583 internal/pkg/scaffold/ansible: bump molecule retries to wait 60s
  internal/pkg/scaffold/ansible/molecule_test_cluster_playbook.go
  internal/pkg/scaffold/ansible/molecule_test_local_playbook.go
Labels: lgtm, size/XS

#1522 doc/user/metrics/README.md: Link to details about metrics
  doc/user/metrics/README.md
Labels: size/XS

#1592 doc/*: Change underscore links for marker tool to work
  doc/ansible/user-guide.md
  doc/dev/developer_guide.md
  doc/helm/user-guide.md
Labels: lgtm, size/L

#1585 test/test-framework,test/e2e: retry conflict updates
  Gopkg.lock
  test/e2e/memcached_test.go
  test/test-framework/test/e2e/memcached_test.go
Labels: lgtm, size/L

#1582 scripts: add --go-ldflags argument to operator-sdk build command
  CHANGELOG.md
  cmd/operator-sdk/build/cmd.go
  doc/sdk-cli-reference.md
Labels: ok-to-test, size/S

#1549 doc/test-framework/scorecard.md: document using the scorecard with a CSV
  doc/test-framework/scorecard.md
Labels: kind/documentation, olm-catalog, scorecard, size/S

#1589 doc/operator-scope: add example manifests
  doc/operator-scope.md
Labels: lgtm, size/M

#1558 doc/proposals/improved-scorecard-config.md: make proposal
  doc/proposals/improved-scorecard-config.md
Labels: scorecard, size/L

#1581 documentation: add note operator-sdk version
  README.md
Labels: lgtm, ok-to-test, size/XS

#1560 pkg/metrics: Allow multi port metrics Service creation
  CHANGELOG.md
  doc/user/metrics/README.md
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
  pkg/ansible/run.go
  pkg/helm/run.go
  pkg/metrics/metrics.go
  test/e2e/memcached_test.go
Labels: size/L

#1596 doc/*: Fix links
  doc/migration/v0.1.0-migration-guide.md
  doc/proposals/ansible-operator-status.md
  doc/proposals/metering-operator-metrics.md
Labels: lgtm, size/XS

#1498 Ansible E2E in Openshift API-CI
  .gitignore
  Makefile
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible-e2e.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/dockerfiles/builder.Dockerfile
  ci/tests/e2e-ansible-scaffold-hybrid.sh
  ci/tests/e2e-ansible-scaffold.sh
  ci/tests/e2e-ansible.sh
Labels: size/L

#1472 cmd,internal: move internal plugins to separate package
  cmd/operator-sdk/scorecard/cmd.go
  internal/pkg/scaffold/internal/testutil/test_util.go
  internal/pkg/scorecard/helpers/helpers.go
  internal/pkg/scorecard/helpers/test_definitions.go
  internal/pkg/scorecard/interfaces.go
  internal/pkg/scorecard/plugins/basic_tests.go
  internal/pkg/scorecard/plugins/config.go
  internal/pkg/scorecard/plugins/olm_tests.go
  internal/pkg/scorecard/plugins/plugin_runner.go
  internal/pkg/scorecard/plugins/resource_handler.go
  internal/pkg/scorecard/scorecard.go
Labels: refactoring, scorecard, size/XXL

#1598 test/test-framework,test/e2e: get latest resource during RetryOnConflict
  test/e2e/memcached_test.go
  test/test-framework/test/e2e/memcached_test.go
Labels: lgtm, size/S

#1574 e2e: better method of adding SDK repo replace directive to operator's go.mod
  hack/lib/test_lib.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  test/e2e/memcached_test.go
Labels: size/L

#1604 doc: remove obsolete references to --cluster-scoped flag
  doc/ansible/user-guide.md
  doc/helm/user-guide.md
  doc/user-guide.md
Labels: lgtm, size/S

#1575 doc/faq.md: Add metrics Service creation error question
  doc/faq.md
Labels: lgtm, size/S

#1580 internal/../crd.go: Add check to prevent index panic
  internal/pkg/scaffold/crd.go
Labels: lgtm, size/S

#1605 support multi-arch for "operator-sdk build"
  cmd/operator-sdk/build/cmd.go
Labels: ok-to-test, size/XS

#1594 pkg/helm/run.go: Enable custom resource metrics
  hack/tests/e2e-helm.sh
  pkg/helm/run.go
Labels: size/S

#1556 doc/dev/testing/running-the-tests.md: add Go e2e test flag section
  doc/dev/testing/running-the-tests.md
Labels: kind/documentation, size/XS

#1571 Add --operator-name flag to olm-catalog gen-csv
  cmd/operator-sdk/olmcatalog/gen-csv.go
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/pkg/scaffold/olm-catalog/csv_test.go
Labels: size/M

#1613 Correct unit-test.md call to reconcile client
  doc/user/unit-testing.md
Labels: lgtm, ok-to-test, size/XS

#1588 cmd/operator-sdk/new: make git init opt-in with --git-init flag
  CHANGELOG.md
  cmd/operator-sdk/new/cmd.go
  doc/sdk-cli-reference.md
Labels: size/M

#1364 cmd/operator-sdk/olmcatalog: scaffold package.yaml for a set of…
  CHANGELOG.md
  Gopkg.lock
  cmd/operator-sdk/olmcatalog/gen-csv.go
  doc/sdk-cli-reference.md
  internal/pkg/scaffold/constants.go
  internal/pkg/scaffold/olm-catalog/config.go
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/pkg/scaffold/olm-catalog/package_manifest.go
  internal/pkg/scaffold/olm-catalog/package_manifest_test.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/app-operator.package.yaml
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/types.go
Labels: kind/feature, olm-catalog, size/L

#1616 .travis.yml: don't run travis on release branches
  .travis.yml
Labels: size/XS, testing

#1586 hack/tests,test/e2e: separate testing and scaffolding of E2E te…
  Gopkg.lock
  hack/tests/e2e-go.sh
  hack/tests/scaffolding/e2e-go-scaffold.sh
  hack/tests/scaffolding/scaffold-memcached.go
  test/e2e/_incluster-test-code/main_test.go
  test/e2e/_incluster-test-code/memcached_test.go
  test/e2e/incluster-test-code/memcached_test.go.tmpl
  test/e2e/main_test.go
  test/e2e/memcached_test.go
  vendor/github.com/prometheus/prometheus/LICENSE
  vendor/github.com/prometheus/prometheus/NOTICE
  vendor/github.com/prometheus/prometheus/util/promlint/promlint.go
Labels: refactoring, size/XXL, testing
