Repository operator-framework/operator-sdk, pull requests merged in 2019-03, with the labels that each got.

#1150 Makefile: add SOURCES to build
  Makefile
Labels: size/XS

#1159 doc/*: fix broken links (#1119)
  doc/dev/developer_guide.md
  doc/dev/release.md
  doc/versioning.md
Labels: size/XS, v0.4.x

#1156 OWNERS,*/OWNERS: add fabianvf and jmrodri to OWNERS for ansible
  OWNERS
  doc/ansible/OWNERS
  pkg/ansible/OWNERS
  pkg/scaffold/ansible/OWNERS
  test/ansible-inventory/OWNERS
  test/ansible-memcached/OWNERS
Labels: size/M

#1158 Molecule override cmd (#1131)
  pkg/scaffold/ansible/molecule_default_molecule.go
  pkg/scaffold/ansible/molecule_test_local_molecule.go
  test/ansible-memcached/molecule.yml
Labels: size/XS

#1147 MAINTAINERS: update maintainers
  MAINTAINERS
Labels: docs, size/XS

#1154 test/e2e/memcached_test.go: poll for leader lock configmap
  test/e2e/memcached_test.go
Labels: size/S

#1117 *: remove 'creationTimestamp' metadata in manifests
  commands/operator-sdk/cmd/olm-catalog/gen-csv.go
  internal/util/k8sutil/object.go
  pkg/scaffold/crd.go
  pkg/scaffold/crd_test.go
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/olm-catalog/csv_test.go
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  pkg/scaffold/olm-catalog/testdata/deploy/role.yaml
  test/ansible-inventory/deploy/role.yaml
  test/test-framework/deploy/crds/cache_v1alpha1_memcached_crd.yaml
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/deploy/role.yaml
Labels: enhancement, olm-catalog, size/L

#1160 docs: Use project proper names and fix typos.
  doc/ansible/dev/developer_guide.md
  doc/ansible/project_layout.md
  doc/ansible/user-guide.md
  doc/design/milestone-0.0.2/query-api.md
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
  doc/helm/dev/developer_guide.md
  doc/helm/user-guide.md
  doc/proposals/ansible-operator.md
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  doc/user-guide.md
Labels: size/M

#1057 [pkg/ansible/runner] link latest artifacts directory to 'latest' ident
  pkg/ansible/runner/runner.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, size/M

#1112 doc/ansible/dev/*: add documentation for dependent watches option
  doc/ansible/dev/advanced_options.md
  doc/ansible/dev/dependent_watches.md
Labels: ansible-operator, needs-ok-to-test, size/M

#1144 pkg/ansible: support multiple workers
  pkg/ansible/controller/controller.go
  pkg/ansible/flags/flag.go
  pkg/ansible/operator/operator.go
  pkg/ansible/operator/operator_test.go
Labels: ansible-operator, enhancement, size/L

#1157 pkg,test: Add deployments/finalizers to roles
  pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  pkg/scaffold/olm-catalog/testdata/deploy/role.yaml
  pkg/scaffold/role.go
  pkg/scaffold/role_test.go
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  test/test-framework/deploy/role.yaml
Labels: size/M

#1166 README.md: update kubernetes prereq to 1.11.3+
  README.md
  doc/dev/testing/running-the-tests.md
  doc/user-guide.md
Labels: size/S

#1167 pkg/test: unexport cleanupNoT
  CHANGELOG.md
  pkg/test/context.go
  pkg/test/main_entry.go
Labels: size/XS, style, test-framework

#1173 .travis.yml,Makefile: disable travis tests that run in prow
  .travis.yml
  Makefile
Labels: size/S, testing

#719 doc/user: Add metrics and service-monitor docs
  doc/user-guide.md
  doc/user/metrics/README.md
  doc/user/metrics/service-monitor.md
Labels: size/L

#922 Add Ansible Operator testing guide
  doc/ansible/dev/testing_guide.md
Labels: ansible-operator, docs, lgtm, size/L

#994 commands/.../scorecard: modularize tests and implement weights
  commands/operator-sdk/cmd/scorecard/basic_tests.go
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  commands/operator-sdk/cmd/scorecard/test_definitions.go
  hack/tests/scorecard-subcommand.sh
Labels: size/XL

#1097 test/e2e/memcached_test.go: Add metrics test
  Gopkg.lock
  test/e2e/memcached_test.go
  vendor/github.com/prometheus/prometheus/LICENSE
  vendor/github.com/prometheus/prometheus/NOTICE
  vendor/github.com/prometheus/prometheus/util/promlint/promlint.go
Labels: size/XL

#1183 commands/.../scorecard: set annotation example test max points to 1
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  hack/tests/scorecard-subcommand.sh
Labels: bug, scorecard, size/XS

#1153 Bugfix/update owner ref behavior 4.0
  Gopkg.lock
  hack/tests/e2e-ansible-molecule.sh
  pkg/ansible/proxy/proxy.go
  pkg/handler/enqueue_annotation.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, lgtm, size/L, v0.4.x

#1187 Fix a minor typo
  doc/helm/user-guide.md
Labels: ok-to-test, size/XS

#1180 Adding max workers to the string of the message instead of a logr field
  pkg/ansible/operator/operator.go
Labels: ansible-operator, bug, lgtm, size/XS

#1195 pkg/test: remove dependence on ctx.t
  pkg/test/context.go
  pkg/test/main_entry.go
Labels: size/S, test-framework

#1194 .github: don't ask for Gopkg.lock
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: size/XS

#1151 Makefile: change make test to run just unit tests
  Makefile
  doc/dev/developer_guide.md
  doc/dev/testing/travis-build.md
  hack/tests/unit.sh
Labels: size/S

#1192 pkg/ansible: Updating reconciler to make errors more obvious
  pkg/ansible/controller/reconcile.go
  pkg/ansible/runner/eventapi/types.go
Labels: ansible-operator, bug, lgtm, size/M

#1193 Add log aggregator sidecar for Ansible Operator
  commands/operator-sdk/cmd/migrate.go
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  hack/image/ansible/scaffold-ansible-image.go
  hack/tests/e2e-ansible.sh
  pkg/scaffold/ansible/ao_logs.go
  pkg/scaffold/ansible/deploy_operator.go
  pkg/scaffold/ansible/dockerfilehybrid.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, enhancement, size/L

#1211 doc/helm: Fix minor typos in helm/user-guide.md
  doc/helm/user-guide.md
Labels: ok-to-test, size/XS

#1190 updated description when using cluster-scoped flag
  doc/user-guide.md
Labels: ok-to-test, size/XS

#1209 updated description when using cluster-scoped flag (ansible & helm)
  doc/ansible/user-guide.md
  doc/helm/user-guide.md
Labels: ok-to-test, size/XS

#1210 log: allow different log levels
  doc/user/logging.md
  pkg/log/zap/flags.go
  pkg/log/zap/flags_test.go
  pkg/log/zap/logger.go
  pkg/log/zap/logger_test.go
Labels: ansible-operator, enhancement, size/L

#1214 v0.6.0 release version
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#1215 Post release versioning
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1176 doc/user/metrics/README.md: Add garbage collection
  doc/user/metrics/README.md
Labels: lgtm, size/S

#1220 docs: Make first ref to quay.io link to https://quay.io
  doc/ansible/user-guide.md
  doc/helm/user-guide.md
  doc/user-guide.md
Labels: size/XS

#1102 pkg/helm: migrate to secret storage backend in namespace of CR
  CHANGELOG.md
  Gopkg.lock
  pkg/helm/controller/reconcile.go
  pkg/helm/release/manager.go
  pkg/helm/release/manager_factory.go
  pkg/helm/run.go
Labels: size/L

#1171 Version command
  CHANGELOG.md
  commands/operator-sdk/cmd/root.go
  commands/operator-sdk/cmd/version.go
Labels: ok-to-test, size/M

#1235 Gopkg.toml,pkg/scaffold/helm/gopkgtoml.go: bump to helm 2.13.1
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  pkg/scaffold/helm/gopkgtoml.go
  vendor/k8s.io/helm/pkg/chartutil/save.go
Labels: size/S

#1224 docs: add instructions to install via Homebrew
  README.md
  doc/ansible/user-guide.md
  doc/helm/user-guide.md
  doc/user-guide.md
Labels: ok-to-test, size/M

#1248 *: remove github.com/census-instrumentation/opencensus-proto pin
  Gopkg.toml
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
Labels: size/S

#1250 pkg/scaffold,version: bump to track v0.6.x branch
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M, versioning

#1239 commands/.../generate/*: set generator header file if not supplied
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/generate/internal/genutil.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/generate/openapi.go
Labels: bug, size/M

#1253 Remove invalid GPL license from test file
  test/ansible-inventory/plugins/filter/test.py
Labels: lgtm, size/S

#1252 doc/dev/release.md: add new branch release
  doc/dev/release.md
Labels: docs, size/M, versioning

#1251 pkg/scaffold,version: bump to track v0.5.x branch
  CHANGELOG.md
  doc/dev/developer_guide.md
  doc/dev/release.md
  doc/versioning.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/ansible/molecule_default_molecule.go
  pkg/scaffold/ansible/molecule_test_local_molecule.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  test/ansible-inventory/molecule/test-local/molecule.yml
  test/ansible-memcached/molecule.yml
  version/version.go
Labels: size/M, versioning

#1247 fix(helm dockerfile): reduce extraneous layers
  pkg/scaffold/ansible/build_dockerfile.go
  pkg/scaffold/ansible/dockerfilehybrid.go
  pkg/scaffold/helm/dockerfile.go
  pkg/scaffold/helm/dockerfilehybrid.go
Labels: ansible-operator, helm-operator, ok-to-test, size/S

#1258 internal/util/yamlutil: fix empty yaml bug
  internal/util/yamlutil/scan.go
Labels: bug, lgtm, size/XS

#1049 Proposal: User Defined Tests for the Operator Scorecard
  doc/proposals/scorecard-plugin-system.md
Labels: enhancement, scorecard, size/L
