Repository operator-framework/operator-sdk, pull requests merged in 2019-08, with the labels that each got.

#1756 ansible molecule e2e: pin pyasn1{-modules} version, better ready check, fix e2e user setup
  hack/tests/e2e-ansible-molecule.sh
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
  internal/pkg/scaffold/ansible/molecule_default_prepare.go
  test/ansible-inventory/molecule/test-local/prepare.yml
Labels: size/S

#1754 doc/operator-scope.md: Helm operator supports only namespace-scoped CRDs
  doc/operator-scope.md
Labels: size/XS

#1757 cmd/operator-sdk/internal/genutil/openapi.go: set ignore_autogenerated build tag in generated openapi code
  cmd/operator-sdk/internal/genutil/openapi.go
Labels: kind/bug, lgtm, size/S

#1755 internal/olm/client{,.go}: refactor Client to its own package
  internal/olm/client.go
  internal/olm/client/client.go
  internal/olm/client/status.go
Labels: olm-catalog, refactoring, size/XL

#1769 OWNERS: Remove lilic
  OWNERS
Labels: size/XS

#1529 add support for iso8601 timestamps
  CHANGELOG.md
  doc/user/logging.md
  pkg/log/zap/flags.go
  pkg/log/zap/flags_test.go
  pkg/log/zap/logger.go
  pkg/log/zap/logger_test.go
Labels: lgtm, ok-to-test, size/L

#1765 (refactor controller-runtime v0.2.0) CHANGELOG.md: move breaking changes around and permalink Client/List
  CHANGELOG.md
Labels: kind/documentation, lgtm, size/M

#1689 internal/pkg/scaffold/olm-catalog: preserve certain fields, better CR/CRD updates
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/util/k8sutil/k8sutil.go
Labels: lgtm, olm-catalog, size/L

#1745 doc/user-guide.md: operator-sdk new requires --repo if outside of $GOPATH/src
  doc/user-guide.md
Labels: kind/documentation, lgtm, size/S

#1762 Add APB migration guide
  doc/ansible/dev/apb_migration_guide.md
Labels: lgtm, size/L

#1776 feat(msg error over ) : Improve error msg GO111MODULE=on
  cmd/operator-sdk/main.go
  cmd/operator-sdk/new/cmd.go
Labels: ok-to-test, size/XS

#1761 pkg/ready: Make set/unset idempotent
  CHANGELOG.md
  pkg/ready/ready.go
  pkg/ready/ready_test.go
Labels: lgtm, size/S

#1790 internal/pkg/scaffold: update go.mod scaffolds and fix prometheus module resolution
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
Labels: lgtm, size/L

#1789 internal/pkg/scorecard/plugins: return an error if no CRs exist in alm-examples w/o cr-manifest set
  CHANGELOG.md
  internal/pkg/scorecard/plugins/plugin_runner.go
Labels: kind/bug, lgtm, scorecard, size/XS

#1801 (c-r v0.2.0) internal/pkg/scaffold: update go.mod scaffolds
  go.sum
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
Labels: area/dependency, size/L

#1800 *: release v0.10.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  release.sh
  version/version.go
Labels: size/M

#1805 *: bump to v0.10.0+git for v0.10.x
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M

#1803 *: bump to v0.10.0+git for master
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M

#1798 cmd/operator-sdk/new,doc/sdk-cli-reference.md: add repo example
  cmd/operator-sdk/new/cmd.go
  doc/sdk-cli-reference.md
Labels: lgtm, size/XS

#1660 Bug fix:'operator-sdk add crd' doesn't work after add kubebuilder tags
  CHANGELOG.md
  cmd/operator-sdk/add/crd.go
Labels: kind/bug, ok-to-test, size/XS

#1782 *: refactor CRD/API getters
  cmd/operator-sdk/internal/genutil/genutil.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/util/k8sutil/crd.go
  internal/util/yamlutil/manifest.go
Labels: refactoring, size/L

#1783 doc/user-guide: add docs for advanced controller configurations
  doc/user-guide.md
Labels: lgtm, size/S

#1784 (c-r v0.2.0) *: update CRD manifest file names to <full group>_<resource>_crd.yaml
  CHANGELOG.md
  README.md
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/add/crd.go
  cmd/operator-sdk/generate/openapi.go
  cmd/operator-sdk/scorecard/cmd.go
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  doc/helm/dev/developer_guide.md
  doc/helm/user-guide.md
  doc/operator-scope.md
  doc/proposals/helm-operator.md
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  doc/user-guide.md
  doc/user/olm-catalog/generating-a-csv.md
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  hack/tests/test-subcommand.sh
  internal/pkg/scaffold/ansible/molecule_test_local_prepare.go
  internal/pkg/scaffold/crd.go
  internal/pkg/scaffold/olm-catalog/config_test.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/crds/app.example.com_appservices2_crd.yaml
  internal/pkg/scaffold/olm-catalog/testdata/deploy/crds/app.example.com_appservices_crd.yaml
  internal/pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha1_app_crd.yaml
  internal/pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha1_appservice_cr.yaml
  internal/pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha2_app_crd.yaml
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/csv-config.yaml
  internal/pkg/scaffold/resource.go
  test/ansible-inventory/deploy/crds/inventory.apps.fabianism.us_inventorys_crd.yaml
  test/ansible-inventory/molecule/test-local/prepare.yml
  test/test-framework/deploy/crds/cache.example.com_memcachedrs_crd.yaml
  test/test-framework/deploy/crds/cache.example.com_memcacheds_crd.yaml
Labels: size/L

#1811 (c-r v0.2.0) *: CR name format change
  README.md
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
  ci/tests/scorecard-subcommand.sh
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/add/crd.go
  cmd/operator-sdk/generate/openapi.go
  doc/ansible/user-guide.md
  doc/helm/dev/developer_guide.md
  doc/helm/user-guide.md
  doc/migration/v0.1.0-migration-guide.md
  doc/proposals/helm-operator.md
  doc/proposals/improved-scorecard-config.md
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
  doc/user-guide.md
  doc/user/olm-catalog/generating-a-csv.md
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  hack/tests/scorecard-subcommand.sh
  internal/pkg/scaffold/ansible/molecule_test_cluster_playbook.go
  internal/pkg/scaffold/ansible/molecule_test_local_playbook.go
  internal/pkg/scaffold/cr.go
  internal/pkg/scaffold/olm-catalog/config_test.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/crds/app.example.com_v1alpha1_appservice_cr.yaml
  test/ansible-inventory/deploy/crds/inventory.apps.fabianism.us_v1alpha1_inventory_cr.yaml
  test/ansible-inventory/molecule/test-local/playbook.yml
  test/ansible-memcached/asserts.yml
  test/test-framework/.test-osdk-scorecard.yaml
  test/test-framework/deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml
  test/test-framework/deploy/crds/cache.example.com_v1alpha1_memcachedrs_cr.yaml
Labels: size/L

#1793 feat(olm-catalog) : Generated alm-examples in a pretty format
  CHANGELOG.md
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
Labels: lgtm, ok-to-test, size/M

#1814 CHANGELOG.md: add important addition to v0.9.0 that was missed
  CHANGELOG.md
Labels: docs, lgtm, size/XS

#1817 pkg/helm: only inject ownerrefs into namespace-scoped resources
  CHANGELOG.md
  pkg/helm/engine/ownerref.go
  pkg/helm/engine/ownerref_test.go
  pkg/helm/release/manager_factory.go
Labels: lgtm, size/L

#1746 cmd/.../genutil: fix typo in comment
  cmd/operator-sdk/internal/genutil/genutil.go
Labels: lgtm, ok-to-test, size/XS

#1818 pkg/helm: deprecate UID-based release name, use CR name instead
  CHANGELOG.md
  pkg/helm/release/manager.go
  pkg/helm/release/manager_factory.go
Labels: size/M

#1819 *: print-deps prints file of user's choice or by top-level file; remove --as-file
  CHANGELOG.md
  cmd/operator-sdk/main.go
  cmd/operator-sdk/printdeps/cmd.go
  doc/sdk-cli-reference.md
  go.mod
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  internal/pkg/scaffold/internal/deps/print_dep.go
  internal/pkg/scaffold/internal/deps/print_go_mod.go
Labels: kind/feature, size/L

#1634 internal/olm: get installed version from cluster instead of required CLI argument
  CHANGELOG.md
  cmd/operator-sdk/alpha/olm/install.go
  cmd/operator-sdk/alpha/olm/status.go
  cmd/operator-sdk/alpha/olm/uninstall.go
  doc/sdk-cli-reference.md
  go.mod
  go.sum
  hack/tests/alpha-olm-subcommands.sh
  internal/olm/client.go
  internal/olm/manager.go
Labels: size/L

#1825 ansible Dockerfiles: ensure clean yum cache before installing packages
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/S

#1693 internal/pkg/scaffold/olm-catalog: do not add duplicate channels, use operator-name
  CHANGELOG.md
  cmd/operator-sdk/olmcatalog/gen-csv.go
  internal/pkg/scaffold/olm-catalog/package_manifest.go
  internal/pkg/scaffold/olm-catalog/package_manifest_test.go
Labels: kind/bug, olm-catalog, size/M

#1696 internal/pkg/scaffold/olm-catalog: better CSV version update method
  internal/pkg/scaffold/olm-catalog/csv.go
Labels: size/M

#1829 Default ansible fact gathering to explicit
  internal/pkg/scaffold/ansible/deploy_operator.go
Labels: lgtm, size/XS

#1820 k8s_status module: fix append issue, when condition was on 0 index
  internal/pkg/scaffold/ansible/k8s_status.go
Labels: lgtm, ok-to-test, size/XS

#1838 Issue 1714: max-workers reset to 1.
  pkg/ansible/run.go
  pkg/ansible/run_test.go
Labels: lgtm, size/XS

#1723 ansible: add custom resource metrics
  CHANGELOG.md
  ci/tests/e2e-ansible.sh
  hack/tests/e2e-ansible.sh
  pkg/ansible/run.go
Labels: size/M

#1866 docs: Fix the example indentation
  doc/operator-scope.md
Labels: lgtm, ok-to-test, size/XS

#1642 bump controller-tools to v0.2.0
  CHANGELOG.md
  doc/operator-scope.md
  go.mod
  go.sum
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/crd.go
  internal/pkg/scaffold/crd_test.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/tools.go
  internal/pkg/scaffold/types.go
  internal/pkg/scaffold/types_test.go
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
Labels: lgtm, refactoring, size/L

#1833 doc/migration: add version upgrade guide
  doc/migration/version-upgrade-guide.md
Labels: kind/documentation, lgtm, size/L
