Repository operator-framework/operator-sdk, pull requests merged in 2019-05, with the labels that each got.

#1228 commands/.../scorecard: add support for JSON output
  CHANGELOG.md
  cmd/operator-sdk/scorecard/cmd.go
  hack/tests/scorecard-subcommand.sh
  internal/pkg/scorecard/helpers.go
  internal/pkg/scorecard/olm_tests.go
  internal/pkg/scorecard/resource_handler.go
  internal/pkg/scorecard/scorecard.go
  internal/pkg/scorecard/test_definitions.go
  pkg/apis/scorecard/v1alpha1/boilerplate.txt
  pkg/apis/scorecard/v1alpha1/doc.go
  pkg/apis/scorecard/v1alpha1/register.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1alpha1/zz_generated.deepcopy.go
  test/test-framework/.test-osdk-scorecard.yaml
Labels: scorecard, size/XL

#1278 internal/pkg/scaffold/crd.go: overwrite CRD manifests for Go operators
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  internal/pkg/scaffold/crd.go
  internal/pkg/scaffold/crd_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/internal/testutil/test_util.go
  internal/pkg/scaffold/olm-catalog/csv_test.go
  internal/pkg/scaffold/test_setup.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/util/util.go
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/types.go
Labels: kind/bug, size/L

#1352 Useful debug help
  doc/ansible/user-guide.md
Labels: ok-to-test, size/S

#1373 internal/pkg/scorecard/olm_tests.go: improve CRDsHaveResourcesTest
  internal/pkg/scorecard/olm_tests.go
Labels: size/S

#1370 Backport: pkg/helm/controller/reconcile.go: fix conditions logic (#1321)
  CHANGELOG.md
  pkg/helm/controller/reconcile.go
Labels: size/XS

#1376 internal,images,doc: update base image to ubi7/ubi-minimal:latest
  CHANGELOG.md
  doc/sdk-cli-reference.md
  images/scorecard-proxy/Dockerfile
  internal/pkg/scaffold/build_dockerfile.go
  internal/pkg/scaffold/build_dockerfile_test.go
  internal/pkg/scaffold/helm/dockerfilehybrid.go
Labels: lgtm, size/S

#1375 cmd/.../scorecard: increase init-timeout default to 60s
  cmd/operator-sdk/scorecard/cmd.go
Labels: lgtm, scorecard, size/XS

#1236 commands/.../scorecard: add multi-cr support
  cmd/operator-sdk/scorecard/cmd.go
  hack/tests/scorecard-subcommand.sh
  hack/tests/test-subcommand.sh
  internal/pkg/scorecard/helpers.go
  internal/pkg/scorecard/olm_tests.go
  internal/pkg/scorecard/scorecard.go
  internal/pkg/scorecard/test_definitions.go
  test/e2e/memcached_test.go
  test/test-framework/.test-osdk-scorecard.yaml
  test/test-framework/deploy/crds/cache_v1alpha1_memcachedrs_cr.yaml
  test/test-framework/deploy/crds/cache_v1alpha1_memcachedrs_crd.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  test/test-framework/deploy/operator.yaml
  test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/zz_generated.deepcopy.go
  test/test-framework/pkg/controller/add_memcachedrs.go
  test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go
Labels: kind/feature, scorecard, size/XL

#1361 Add global `--verbose` flag to `operator-sdk` command
  CHANGELOG.md
  cmd/operator-sdk/internal/genutil/genutil.go
  cmd/operator-sdk/main.go
  cmd/operator-sdk/scorecard/cmd.go
  doc/sdk-cli-reference.md
  internal/pkg/flags/flags.go
  internal/pkg/scorecard/scorecard.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
Labels: ok-to-test, size/M

#1374 internal/pkg/scaffold: use `Resource.GoImportGroup` in CRD/CR file names
  internal/pkg/scaffold/cr.go
  internal/pkg/scaffold/crd.go
Labels: kind/bug, size/XS

#1377 fix a typo in doc
  doc/ansible/user-guide.md
Labels: ok-to-test, size/XS

#1387 Doc: add notes in the section ‘Register with the Manager's scheme’
  doc/user-guide.md
Labels: lgtm, ok-to-test, size/S

#1382 remove trailing whitespaces
  doc/ansible/dev/testing_guide.md
  doc/ansible/project_layout.md
  doc/design/long-term/testing-operators.md
  doc/design/milestone-0.0.2/action-api.md
  doc/design/milestone-0.0.2/query-api.md
  doc/dev/reporting_bugs.md
  doc/helm/user-guide.md
  doc/proposals/TEMPLATE.md
  doc/proposals/ansible-operator-testing.md
  doc/proposals/ansible-operator.md
  doc/proposals/tls-utilities.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  doc/user/client.md
  doc/user/metrics/README.md
  doc/user/metrics/service-monitor.md
  doc/user/olm-catalog/generating-a-csv.md
Labels: lgtm, size/L

#1381 Document the Ansible Operator conditions
  doc/ansible/dev/developer_guide.md
Labels: size/M

#1378 internal/pkg/scorecard: improve crd resources check
  CHANGELOG.md
  doc/test-framework/scorecard.md
  hack/tests/scorecard-subcommand.sh
  internal/pkg/scorecard/olm_tests.go
Labels: scorecard, size/S

#1320 Update operator-capability-level diagram and file name
  doc/images/operator-capability-level-transparent-bg.png
  doc/images/operator-capability-level.png
  doc/images/operator-capability-level.svg
  doc/images/operator-maturity-model-transparent-bg.png
  doc/images/operator-maturity-model.png
  doc/images/operator-maturity-model.svg
  doc/user/olm-catalog/generating-a-csv.md
Labels: lgtm, size/M

#1347 internal/pkg/scaffold/olm-catalog/config.go: omit owned CRD's from CSV if no default CRD's dir
  CHANGELOG.md
  internal/pkg/scaffold/olm-catalog/config.go
Labels: kind/bug, olm-catalog, size/S

#1275 cmd/operator-sdk: scaffold a boilerplate file for new and migrated projects
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/generate/k8s.go
  cmd/operator-sdk/generate/openapi.go
  cmd/operator-sdk/internal/genutil/genutil.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  internal/pkg/scaffold/boilerplate_go_txt.go
  internal/pkg/scaffold/boilerplate_go_txt_test.go
  internal/pkg/scaffold/scaffold.go
Labels: kind/feature, size/L

#1001 go mod support for new operators
  .travis.yml
  CHANGELOG.md
  Gopkg.lock
  README.md
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/printdeps/cmd.go
  cmd/operator-sdk/test/local.go
  cmd/operator-sdk/up/local.go
  doc/ansible/user-guide.md
  doc/dev/developer_guide.md
  doc/dev/release.md
  doc/dev/testing/travis-build.md
  doc/helm/user-guide.md
  doc/project_layout.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/internal/deps/print_go_mod.go
  internal/pkg/scaffold/tools.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
  pkg/test/main_entry.go
  release.sh
  test/e2e/memcached_test.go
  vendor/github.com/docker/docker/hack/generate-authors.sh
  vendor/k8s.io/helm/pkg/chartutil/testdata/frobnitz_backslash/LICENSE
Labels: size/XXL

#1407 *types.go: set kubebuilder subresource status annotation in go source
  internal/pkg/scaffold/crd_test.go
  internal/pkg/scaffold/types.go
  internal/pkg/scaffold/types_test.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
Labels: size/XS

#1406 test/e2e: use local path of SDK in go.mod for non-Travis CI environment
  test/e2e/memcached_test.go
Labels: kind/bug, lgtm, size/L, test-framework

#1410 test/e2e/memcached_test.go: refactor and support forks for go.mod replace
  test/e2e/memcached_test.go
Labels: size/L

#1412 internal/pkg/scaffold/*,hack/tests/: use osdk master when not on tagged commit
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/helm/go_mod.go
Labels: size/M

#1416 internal/pkg/scaffold/ansible/go_mod.go: pin to prometheus-operator v0.29.0
  internal/pkg/scaffold/ansible/go_mod.go
Labels: lgtm, size/XS

#1395 *: Point users to the latest release instead of
  README.md
  doc/ansible/user-guide.md
  doc/dev/release.md
  doc/helm/user-guide.md
  doc/user-guide.md
  doc/user/install-operator-sdk.md
  release.sh
Labels: size/L

#1415 test/e2e/memcached_test.go: improve test isolation, cleanup temp files
  test/e2e/memcached_test.go
Labels: size/M

#1429 add comment to generated controller code to explain interface check
  example/memcached-operator/memcached_controller.go.tmpl
  internal/pkg/scaffold/controller_kind.go
  internal/pkg/scaffold/controller_kind_test.go
  pkg/helm/controller/reconcile.go
  test/test-framework/pkg/controller/memcached/memcached_controller.go
  test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go
Labels: lgtm, ok-to-test, size/XS

#1419 cmd: allow CGO_ENABLED=1
  cmd/operator-sdk/build/cmd.go
Labels: ok-to-test, size/XS

#1403 Correct csv-config.yaml supported fields documentation
  doc/design/milestone-0.2.0/csv-generation.md
  doc/user/olm-catalog/generating-a-csv.md
Labels: ok-to-test, size/XS

#1402 doc(finalizer) : Add an example based on Memcached Getting Started one
  doc/user-guide.md
Labels: ok-to-test, size/M

#1414 cmd,pkg/test,test/e2e: remove `test cluster` subcommand
  CHANGELOG.md
  cmd/operator-sdk/build/build_test.go
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/test/cluster.go
  cmd/operator-sdk/test/cmd.go
  doc/dev/testing/travis-build.md
  doc/sdk-cli-reference.md
  doc/test-framework/writing-e2e-tests.md
  internal/pkg/scaffold/go_test_script.go
  internal/pkg/scaffold/go_test_script_test.go
  internal/pkg/scaffold/test_framework_dockerfile.go
  internal/pkg/scaffold/test_framework_dockerfile_test.go
  internal/pkg/scaffold/test_pod.go
  internal/pkg/scaffold/test_pod_test.go
  pkg/test/framework.go
  pkg/test/main_entry.go
  test/e2e/memcached_test.go
Labels: lgtm, size/XL, test-framework

#1408 Added a note to the user guide on running the docker client without sudo
  README.md
  doc/user-guide.md
Labels: lgtm, ok-to-test, size/S

#1379 internal/pkg/scorecard: implement plugin system
  cmd/operator-sdk/scorecard/cmd.go
  hack/tests/scorecard-subcommand.sh
  internal/pkg/scorecard/helpers.go
  internal/pkg/scorecard/scorecard.go
  internal/pkg/scorecard/test_definitions.go
  test/test-framework/scorecard/assets/output.json
  test/test-framework/scorecard/bin/print-json.sh
Labels: kind/feature, scorecard, size/L

#1432 internal/util/projutil/project_util.go: fix repo lookup when CWD is $GOPATH/src
  internal/util/projutil/project_util.go
Labels: lgtm, size/XS

#1438 .travis.yaml: Add $GOPATH/pkg/mod to travis cache
  .travis.yml
Labels: lgtm, size/XS

#1354 doc/proposals/cli-ux-phase1.md: adding first CLI UX proposal
  doc/proposals/cli-ux-phase1.md
Labels: size/L

#1413 pkg/ansible/proxy: refactor proxy to remove public exposed functions
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/inject_owner.go
  pkg/ansible/proxy/proxy.go
Labels: lgtm, size/XL

#1439 docs: update curl to follow redirects
  doc/user/install-operator-sdk.md
Labels: lgtm, ok-to-test, size/XS

#1344 cmd/operator-sdk/add/controller.go: support built-in k8s API controllers
  CHANGELOG.md
  cmd/operator-sdk/add/controller.go
  doc/sdk-cli-reference.md
  internal/pkg/scaffold/controller_kind.go
  internal/pkg/scaffold/controller_kind_test.go
Labels: size/L

#1431 Makefile,version,cmd/operator-sdk/version: add git compile-time variables
  Makefile
  cmd/operator-sdk/version/cmd.go
  release.sh
  version/version.go
Labels: size/M

#1434 Remove cluster-scoped flag
  CHANGELOG.md
  cmd/operator-sdk/new/cmd.go
  doc/ansible/user-guide.md
  doc/helm/user-guide.md
  doc/operator-scope.md
  doc/sdk-cli-reference.md
  doc/user-guide.md
  internal/pkg/scaffold/ansible/deploy_operator.go
  internal/pkg/scaffold/helm/operator.go
  internal/pkg/scaffold/helm/role.go
  internal/pkg/scaffold/operator.go
  internal/pkg/scaffold/operator_test.go
Labels: size/L

#1443 CHANGELOG.md: add scorecard changes
  CHANGELOG.md
Labels: docs, size/XS

#1444 cmd/operator-sdk/main.go: remove --version flag
  CHANGELOG.md
  cmd/operator-sdk/main.go
Labels: lgtm, size/XS

#1445 *: release v0.8.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S, versioning

#1447 *: bump to v0.8.0+git
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M, versioning

#1449 *: release v0.7.1
  CHANGELOG.md
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/S, versioning

#1448 *: bump v0.8.x branch to v0.8.0+git
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M, versioning

#1452 *: bump to v0.7.1+git
  CHANGELOG.md
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M, versioning

#1442 Specify --keyserver to gpg(1) call if needed
  doc/user/install-operator-sdk.md
Labels: ok-to-test, size/XS

#1456 internal/pkg/scaffold/helm/role.go: add custom rules for namespaced scope
  internal/pkg/scaffold/helm/role.go
Labels: kind/bug, size/XS

#1461 Helm: RBAC generation fixes
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/helm/role.go
Labels: kind/bug, size/S

#1466 (backport to v0.8.x) internal/pkg/scaffold/helm/role.go: add custom rules for namespaced scope
  internal/pkg/scaffold/helm/role.go
Labels: backport, kind/bug, size/XS

#1467 (backport to v0.8.x) Helm: RBAC generation fixes
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  internal/pkg/scaffold/helm/role.go
Labels: backport, kind/bug, size/S

#1469 *: release v0.8.1
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1474 *: bump to v0.8.1+git
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1477 internal/{pkg,util}: add missing license headers
  internal/pkg/scaffold/internal/testutil/test_util.go
  internal/util/k8sutil/crd.go
  internal/util/k8sutil/object.go
Labels: size/M

#1481 internal/pkg/scaffold/helm/role_test: add test for role scaffold
  cmd/operator-sdk/new/cmd.go
  internal/pkg/scaffold/helm/role.go
  internal/pkg/scaffold/helm/role_test.go
Labels: size/L

#1454 doc/user/install-operator-sdk.md: Small fixes
  doc/user/install-operator-sdk.md
Labels: size/XS

#1462 Remove TypeMeta declaration from the implementation of the objects
  CHANGELOG.md
  doc/test-framework/writing-e2e-tests.md
  doc/user/client.md
  example/memcached-operator/memcached_controller.go.tmpl
  internal/pkg/scorecard/helpers.go
  pkg/leader/leader.go
  pkg/metrics/metrics.go
  pkg/metrics/service-monitor.go
  pkg/test/framework.go
  test/e2e/incluster-test-code/memcached_test.go.tmpl
  test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go
  test/test-framework/test/e2e/memcached_test.go
Labels: ok-to-test, size/M

#1488 cmd/operator-sdk/build/cmd.go: support podman
  CHANGELOG.md
  README.md
  cmd/operator-sdk/build/cmd.go
  doc/sdk-cli-reference.md
Labels: size/S

#1492 internal/pkg/scaffold/types.go: remove broken kubebuilder book link
  internal/pkg/scaffold/types.go
  internal/pkg/scaffold/types_test.go
Labels: ok-to-test, size/XS

#1487 *: use "/" for Go package paths and filepath.Separator for on-disk paths
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/up/local.go
  internal/pkg/scaffold/test_setup.go
  internal/util/projutil/project_util.go
  test/e2e/memcached_test.go
Labels: size/S

#1433 doc/test-framework/scorecard: update scorecard documentation
  CHANGELOG.md
  cmd/operator-sdk/scorecard/cmd.go
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
  internal/pkg/scorecard/scorecard.go
  pkg/apis/scorecard/v1alpha1/types.go
Labels: scorecard, size/L

#1324 doc/proposals/sdk-code-annotations.md: code annotations for specific commands
  doc/proposals/sdk-code-annotations.md
  doc/user/csv-annotations.md
Labels: kind/documentation, needs discussion, size/L
