Repository operator-framework/operator-sdk, pull requests merged in 2019-04, with the labels that each got.

#1257 CHANGELOG.md: new --header-file flag for 'add api' and 'generate k8s'
  CHANGELOG.md
  doc/sdk-cli-reference.md
Labels: docs, size/XS

#1266 cmd/.../scorecard: change namespaced-manifest flag
  CHANGELOG.md
  cmd/operator-sdk/scorecard/scorecard.go
Labels: lgtm, scorecard, size/XS

#1269 Makefile: Run unit tests in internal dir
  Makefile
  internal/pkg/scaffold/crd_test.go
Labels: lgtm, size/XS

#1274 CHANGELOG.md: add a missing bug fix to changelog
  CHANGELOG.md
Labels: docs, size/XS

#1273 Backport: internal/util/yamlutil: fix empty yaml bug (#1258)
  CHANGELOG.md
  internal/util/yamlutil/scan.go
Labels: backport, bug, lgtm, size/XS

#1148 pkg/ansible - Bugfix/update owner ref behavior
  Gopkg.lock
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/controllermap/controllermap.go
  pkg/ansible/proxy/proxy.go
  pkg/handler/enqueue_annotation.go
Labels: ansible-operator, bug, size/L, v0.4.x

#1271 cmd/.../genutil: verbose codegen by default
  CHANGELOG.md
  cmd/operator-sdk/internal/genutil/genutil.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  test/e2e/memcached_test.go
Labels: bug, size/M

#1279 Backport: commands/.../generate: verbose codegen by default (#1271)
  CHANGELOG.md
  commands/operator-sdk/cmd/generate/internal/genutil.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/generate/openapi.go
  test/e2e/memcached_test.go
Labels: backport, size/M

#1242 doc/user/olm-catalog: CSV user documentation
  doc/design/milestone-0.2.0/csv-generation.md
  doc/user/olm-catalog/generating-a-csv.md
Labels: docs, olm-catalog, size/L

#1284 test/e2e: bump Go e2e timeout
  test/e2e/memcached_test.go
Labels: lgtm, size/XS, testing

#1116 gen-csv: generate 'alm-examples' annotations from CR's
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
Labels: enhancement, olm-catalog, size/L

#1285 CHANGELOG.md: add CSV alm-examples update
  CHANGELOG.md
Labels: size/XS

#1280 internal/pkg/scaffold/gopkgtoml*: Update prometheus-operator
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
Labels: lgtm, size/XS

#1294 CHANGELOG,version,scaffold: release v0.7.0
  CHANGELOG.md
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/S, versioning

#1295 CHANGELOG,version,scaffold: post-release version bump
  CHANGELOG.md
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M, versioning

#1296 CHANGELOG,version,scaffold: post-release v0.7.x
  CHANGELOG.md
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M, versioning

#1272 cmd/.../scorecard: move scorecard libraries out of cmd
  cmd/operator-sdk/scorecard/cmd.go
  cmd/operator-sdk/scorecard/test_definitions.go
  internal/pkg/scorecard/basic_tests.go
  internal/pkg/scorecard/helpers.go
  internal/pkg/scorecard/olm_tests.go
  internal/pkg/scorecard/resource_handler.go
  internal/pkg/scorecard/scorecard.go
  internal/pkg/scorecard/test_definitions.go
Labels: refactoring, scorecard, size/XL

#1283 internal/pkg/scaffold/olm-catalog: better error messages
  internal/pkg/scaffold/olm-catalog/csv.go
Labels: olm-catalog, size/XS

#1297 internal/util/projutil: standardize operator type checks
  Gopkg.lock
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/test/cluster.go
  cmd/operator-sdk/test/local.go
  cmd/operator-sdk/up/local.go
  internal/util/projutil/project_util.go
Labels: lgtm, size/L, style

#1188 pkg/scaffold/role,pkg/operator-sdk/new.go: generate role rules from helm chart
  CHANGELOG.md
  Gopkg.lock
  cmd/operator-sdk/new/cmd.go
  doc/helm/user-guide.md
  internal/pkg/scaffold/helm/chart.go
  internal/pkg/scaffold/helm/role.go
  internal/pkg/scaffold/role.go
  internal/pkg/scaffold/role_test.go
  vendor/k8s.io/helm/pkg/renderutil/deps.go
  vendor/k8s.io/helm/pkg/renderutil/doc.go
  vendor/k8s.io/helm/pkg/renderutil/render.go
Labels: helm-operator, size/XL

#1314 update sed commands for image name and pull policy
  doc/ansible/user-guide.md
Labels: ansible-operator, size/S

#1322 pkg/log/zap: Adding ability to get client-go and trace level logs
  CHANGELOG.md
  Gopkg.lock
  doc/user/logging.md
  pkg/log/zap/flags.go
Labels: size/S

#1288 revert defaulter-gen
  CHANGELOG.md
  cmd/operator-sdk/internal/genutil/k8s.go
  doc/sdk-cli-reference.md
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
Labels: size/S

#1313 internal/pkg/scaffold/resource.go: relax group format check
  CHANGELOG.md
  internal/pkg/scaffold/resource.go
Labels: size/XS

#1311 cmd/build: Add buildah support
  CHANGELOG.md
  cmd/operator-sdk/build/cmd.go
  doc/sdk-cli-reference.md
Labels: ok-to-test, size/M

#1327 pkg/ansible/proxy/kubectl.go: support windows build
  Gopkg.lock
  pkg/ansible/proxy/kubectl.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/pod_port.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/service_port.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/umask.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/umask_windows.go
  vendor/k8s.io/kubernetes/pkg/kubectl/util/util.go
Labels: lgtm, size/L

#1321 pkg/helm/controller/reconcile.go: fix conditions logic
  CHANGELOG.md
  pkg/helm/controller/reconcile.go
Labels: lgtm, size/S

#1329 pkg/restmapper,scaffold/cmd.go: override default restmapper
  CHANGELOG.md
  Gopkg.lock
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
  pkg/restmapper/dynamicrestmapper.go
Labels: lgtm, size/L

#1348 fix ansible e2e
  internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: ansible-operator, kind/bug, lgtm, size/S

#1309 pkg/helm,hack/tests: slim down release information in Helm CR status
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  pkg/helm/controller/reconcile.go
  pkg/helm/internal/types/types.go
  pkg/helm/internal/types/types_test.go
  pkg/helm/release/manager.go
Labels: helm-operator, kind/feature, size/M

#1310 internal/util/projutil: add Go{Build,Test{() functions to run go build/test
  Gopkg.lock
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/test/local.go
  cmd/operator-sdk/up/local.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
  pkg/test/main_entry.go
  test/e2e/memcached_test.go
  vendor/github.com/mitchellh/go-homedir/LICENSE
  vendor/github.com/mitchellh/go-homedir/homedir.go
Labels: kind/feature, size/L

#1353 pkg/k8sutil/k8sutil.go: Set kind and APIVersion
  pkg/k8sutil/k8sutil.go
Labels: lgtm, size/S

#1351 V0.7.x backport: pin ansible version (#1348)
  CHANGELOG.md
  internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: ansible-operator, backport, size/S

#1326 doc/dev/release.md: Add brew formula upgrade guide
  doc/dev/release.md
Labels: lgtm, size/S

#1312 cmd/operator-sdk/{migrate,new}: add dependency management logic
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/printdeps/cmd.go
  doc/sdk-cli-reference.md
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/constants.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  internal/pkg/scaffold/internal/deps/print_dep.go
  internal/pkg/scaffold/version.go
  internal/util/projutil/project_util.go
  pkg/test/main_entry.go
Labels: refactoring, size/L

#1263 metrics: expose ansible operator metrics
  Gopkg.lock
  hack/tests/e2e-ansible-molecule.sh
  pkg/ansible/controller/reconcile.go
  pkg/ansible/metrics/metrics.go
  pkg/ansible/run.go
  pkg/ansible/runner/runner.go
Labels: lgtm, size/L

#1356 backport: pkg/k8sutil/k8sutil.go: Set kind and APIVersion
  pkg/k8sutil/k8sutil.go
Labels: size/S

#1357 cmd/operator-sdk/up/local.go: sdk up local build by package than only the main file
  cmd/operator-sdk/up/local.go
Labels: ok-to-test, size/XS
