Repository operator-framework/operator-sdk, pull requests merged in 2019-11, with the labels that each got.

#2133 Docs Hosting with Hugo proposal
  doc/proposals/README.md
  doc/proposals/hugo-doc-build.md
Labels: size/L

#2144 doc/ansible/project_layout.md: fix Ansible Galaxy link
  doc/ansible/project_layout.md
Labels: kind/documentation, size/XS

#2111 add openAPI validation in migration doc
  doc/migration/version-upgrade-guide.md
Labels: approved, lgtm, size/S

#2141 Fix typo
  doc/migration/version-upgrade-guide.md
Labels: ok-to-test, size/XS

#2146 hack/ci/marker: update marker
  CHANGELOG.md
  Makefile
  doc/sdk-cli-reference.md
  hack/ci/marker
Labels: kind/documentation, testing

#2130 Fix type of node in the test-framework data according to API rule validations
  internal/scaffold/crd_test.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
Labels: lgtm, size/XS

#2137 scorecard - Add list flag
  CHANGELOG.md
  cmd/operator-sdk/scorecard/cmd.go
  doc/test-framework/scorecard.md
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/interfaces.go
  internal/scorecard/plugins/config.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/scorecard.go
  internal/scorecard/scorecard_output.go
  pkg/apis/scorecard/v1alpha2/formatter.go
  pkg/apis/scorecard/v1alpha2/types.go
Labels: lgtm, scorecard, size/L

#2113 Add check for API rule validation and fix type for Memcached test data
  doc/user-guide.md
  hack/tests/scaffolding/scaffold-memcached.go
Labels: lgtm, size/S

#2150 ansible: Update docs to use CR instead of CRD where appropriate
  doc/ansible/dev/developer_guide.md
  doc/ansible/dev/retroactively-owned-resources.md
Labels: ok-to-test, size/S

#1781 pkg/k8sutil/crd*.go: add kubernetes-style version sorter
  internal/scaffold/crd.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  internal/util/k8sutil/crd.go
  internal/util/k8sutil/crd_test.go
Labels: approved, kind/feature, lgtm, size/L

#2037 Refactor e2e framework to remove globals
  cmd/operator-sdk/test/local.go
  internal/util/projutil/exec.go
  pkg/test/context.go
  pkg/test/framework.go
  pkg/test/main_entry.go
  pkg/test/resource_creator.go
Labels: kind/cleanup, lgtm, size/L, test-framework

#2153 Remove TypeMeta initializations
  internal/scorecard/helpers/helpers.go
  pkg/apis/scorecard/v1v2conversions.go
  test/test-framework/pkg/controller/memcached/memcached_controller.go
Labels: lgtm, size/S

#2159 Add back TypeMeta which is mandatory for scorecard object because it is used to distinguish the versions (v1alpha1 and v1alpha2)
  internal/scorecard/helpers/helpers.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1alpha2/types.go
  pkg/apis/scorecard/v1v2conversions.go
Labels: size/M

#2147 ansible: Support vars in watches
  CHANGELOG.md
  doc/ansible/user-guide.md
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/watches/testdata/valid.yaml.tmpl
  pkg/ansible/watches/watches.go
  pkg/ansible/watches/watches_test.go
Labels: lgtm, ok-to-test, size/M

#2160 Update uclient.go
  pkg/kube-metrics/uclient.go
Labels: ok-to-test, size/XS

#2169 hack/doc,doc/cli: disable and remove autogen tag
  doc/cli/operator-sdk.md
  doc/cli/operator-sdk_add.md
  doc/cli/operator-sdk_add_api.md
  doc/cli/operator-sdk_add_controller.md
  doc/cli/operator-sdk_add_crd.md
  doc/cli/operator-sdk_alpha.md
  doc/cli/operator-sdk_alpha_olm.md
  doc/cli/operator-sdk_alpha_olm_install.md
  doc/cli/operator-sdk_alpha_olm_status.md
  doc/cli/operator-sdk_alpha_olm_uninstall.md
  doc/cli/operator-sdk_build.md
  doc/cli/operator-sdk_completion.md
  doc/cli/operator-sdk_completion_bash.md
  doc/cli/operator-sdk_completion_zsh.md
  doc/cli/operator-sdk_generate.md
  doc/cli/operator-sdk_generate_k8s.md
  doc/cli/operator-sdk_generate_openapi.md
  doc/cli/operator-sdk_migrate.md
  doc/cli/operator-sdk_new.md
  doc/cli/operator-sdk_olm-catalog.md
  doc/cli/operator-sdk_olm-catalog_gen-csv.md
  doc/cli/operator-sdk_print-deps.md
  doc/cli/operator-sdk_run.md
  doc/cli/operator-sdk_run_ansible.md
  doc/cli/operator-sdk_run_helm.md
  doc/cli/operator-sdk_scorecard.md
  doc/cli/operator-sdk_test.md
  doc/cli/operator-sdk_test_local.md
  doc/cli/operator-sdk_up.md
  doc/cli/operator-sdk_up_local.md
  doc/cli/operator-sdk_version.md
  hack/doc/gen-cli-doc.go
Labels: size/M

#2171 scorecard proposal - add new scope and associated stories
  doc/proposals/openshift-4.3/operator-testing-tool.md
Labels: kind/documentation, scorecard, size/M

#2165 scorecard - add return code logic
  CHANGELOG.md
  doc/test-framework/scorecard.md
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/scorecard.go
  internal/scorecard/scorecard_output.go
Labels: scorecard, size/M

#2129 Update e2e test data for test-framework
  go.mod
  test/test-framework/deploy/crds/cache.example.com_memcachedrs_crd.yaml
  test/test-framework/deploy/crds/cache.example.com_memcacheds_crd.yaml
  test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/zz_generated.deepcopy.go
  test/test-framework/pkg/apis/cache/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/L, test-framework

#2148 ansible: Clarify doc on owner reference injection
  doc/ansible/dev/advanced_options.md
  doc/ansible/information-flow-ansible-operator.md
Labels: ansible-operator, kind/documentation, ok-to-test, size/S

#2181 update helm user guide to correct cr and crd file names
  doc/helm/user-guide.md
Labels: kind/documentation, size/S

#2191 fix broken links in the helm guide
  doc/helm/dev/developer_guide.md
  doc/helm/project_layout.md
  doc/helm/user-guide.md
Labels: size/XS

#2131 Add test/check sanity to check if test-framework mock data is updated
  Makefile
  go.mod
  hack/check-error-log-msg-format.sh
  hack/check-license.sh
  hack/doc/gen_cli_doc.sh
  hack/generate/gen-cli-doc.go
  hack/generate/gen-cli-doc.sh
  hack/generate/gen-test-framework.sh
  hack/tests/sanity-check.sh
  test/test-framework/pkg/apis/cache/v1alpha1/zz_generated.openapi.go
Labels: approved, kind/feature, lgtm, size/L, test-framework

#2192 Consolidate CI work to Single Provider
  .travis.yml
Labels: lgtm, size/M

#2180 update kube verison in requirements
  README.md
Labels: lgtm, size/XS

#2205 feat: add linter check
  .travis.yml
  Makefile
  hack/common.sh
  hack/go-linter.sh
Labels: lgtm, size/M

#2211 doc: fix link to memcached cr
  doc/ansible/dev/retroactively-owned-resources.md
Labels: size/XS

#2202 test/test-framework: add go.mod, go.sum and build/Dockerfile
  doc/dev/release.md
  hack/generate/gen-test-framework.sh
  internal/scaffold/crd.go
  internal/scaffold/crd_test.go
  test/test-framework/build/Dockerfile
  test/test-framework/go.mod
  test/test-framework/go.sum
Labels: size/XL, test-framework

#2210 leader election bugfix: Delete evicted leader pods
  pkg/leader/leader.go
Labels: lgtm, size/M

#2236 feat(linter) : add goconst check and fix issues
  hack/go-linter.sh
  internal/scaffold/olm-catalog/csv_test.go
  internal/scorecard/plugins/olm_tests.go
Labels: approved, kind/cleanup, lgtm, size/M

#2145 *: bump to kubernetes 1.16
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  hack/generate/gen-test-framework.sh
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/crd.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  pkg/ansible/proxy/kubectl.go
  test/test-framework/go.mod
  test/test-framework/go.sum
Labels: area/dependency, kind/feature, size/XXL

#2206 Organize makefile
  Makefile
Labels: approved, lgtm, refactoring, size/L

#2252 fix(ansible) : install jmespath in the contaner"
  CHANGELOG.md
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  internal/scaffold/ansible/dockerfilehybrid.go
  test/ansible-memcached/secret/tasks/main.yml
Labels: ansible-operator, approved, kind/bug, lgtm, size/S

#2208 Add coveralls
  .travis.yml
  Makefile
  README.md
Labels: approved, kind/feature, lgtm, size/S, testing

#2102 feat(ansible): Configure verbosity via annotation
  CHANGELOG.md
  doc/ansible/dev/advanced_options.md
  doc/ansible/user-guide.md
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
Labels: ansible-operator, approved, kind/feature, lgtm, ok-to-test, size/M

#2255 hack/ci/setup-k8s.sh: update kindest/node to v1.6.3, kind to latest
  hack/ci/setup-k8s.sh
  hack/lib/image_lib.sh
Labels: approved, lgtm, size/S, testing

#2258 remove the badge
  README.md
Labels: size/XS

#2230 feat(linter) : add ineffassign check and fix issues
  hack/go-linter.sh
  internal/scaffold/role.go
  pkg/ansible/proxy/proxy_test.go
  pkg/metrics/metrics.go
Labels: kind/cleanup, lgtm, size/M

#2261 Fix typo
  doc/operator-scope.md
Labels: lgtm, size/XS

#2241 feat(linter): add maligned and fix issues
  hack/go-linter.sh
  internal/scorecard/plugins/config.go
  pkg/ansible/controller/reconcile_test.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/watches/watches_test.go
  pkg/log/zap/flags_test.go
  pkg/log/zap/logger_test.go
  pkg/test/framework.go
Labels: approved, lgtm, size/L

#2248 pkg/test/e2eutil: wait for a deployment to have >= n replicas
  CHANGELOG.md
  pkg/test/e2eutil/wait_util.go
Labels: approved, lgtm, size/XS

#2234 feat(linter) : add check for goimports and to do fixes
  hack/go-linter.sh
  internal/scorecard/scorecard_output.go
  pkg/ansible/controller/status/types.go
  pkg/ansible/controller/status/utils.go
  pkg/ansible/controller/status/utils_test.go
  pkg/apis/scorecard/v1alpha2/formatter.go
  pkg/helm/run.go
  pkg/tls/primitives.go
  pkg/tls/tls.go
  test/e2e/tls_util_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#2203 Use k8s_info module instead of deprecated k8s_facts in molecule scaffold (#2168)
  CHANGELOG.md
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  doc/ansible/dev/retroactively-owned-resources.md
  internal/scaffold/ansible/dockerfilehybrid.go
  internal/scaffold/ansible/molecule_default_asserts.go
  internal/scaffold/ansible/molecule_test_cluster_playbook.go
  internal/scaffold/ansible/molecule_test_local_playbook.go
  test/ansible-inventory/molecule/test-local/playbook.yml
  test/ansible-memcached/asserts.yml
Labels: size/S

#2263 Makefile,.travis.yml: simplify unit test and code coverage make target
  .travis.yml
  Makefile
Labels: approved, lgtm, size/S

#2233 feat(linter): add errcheck check an fix issues
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  cmd/operator-sdk/scorecard/cmd.go
  hack/go-linter.sh
  internal/olm/client.go
  internal/olm/client/client.go
  internal/scaffold/crd_test.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/proxy/kubectl.go
  pkg/ansible/proxy/proxy.go
  pkg/kube-metrics/server.go
  test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go
Labels: approved, kind/cleanup, size/M

#2270 feat(linter): add dupl to linter and fix issues
  hack/go-linter.sh
  internal/scaffold/role.go
  internal/scorecard/plugins/olm_tests.go
Labels: approved, kind/cleanup, lgtm, size/L

#2278 hack/generate/gen-cli-doc.go: recreate doc/cli directory on every run
  hack/generate/gen-cli-doc.go
Labels: lgtm, size/S

#2275 internal/scaffold/crd.go: use structural schema for non-go operator CRDs
  CHANGELOG.md
  internal/scaffold/crd.go
  internal/scaffold/crd_test.go
Labels: lgtm, size/M
