Repository operator-framework/operator-sdk, pull requests merged in 2019-01, with the labels that each got.

#857 pkg/ansible; Add watching of dependent resources
  commands/operator-sdk/cmd/up/local.go
  pkg/ansible/controller/controller.go
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/proxy/proxy_test.go
  pkg/ansible/runner/fake/runner.go
  pkg/ansible/runner/runner.go
  test/ansible-operator/cmd/ansible-operator/main.go
Labels: ansible-operator, size/L

#881 e2e don't error if already gone
  pkg/test/client.go
Labels: size/XS

#888 pkg/ansible; Append current environment vars to runner
  pkg/ansible/runner/runner.go
Labels: ansible-operator, bug, size/XS

#887 adds `migrate` and `run ansible` commands
  commands/operator-sdk/cmd/migrate.go
  commands/operator-sdk/cmd/root.go
  commands/operator-sdk/cmd/run.go
  commands/operator-sdk/cmd/run/ansible.go
  commands/operator-sdk/cmd/up/local.go
  doc/dev/testing/travis-build.md
  hack/image/build-ansible-image.sh
  hack/image/scaffold-ansible-image.go
  hack/tests/e2e-ansible.sh
  pkg/ansible/run.go
  pkg/scaffold/ansible/dockerfilehybrid.go
  pkg/scaffold/ansible/entrypoint.go
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/ansible/main.go
  pkg/scaffold/ansible/usersetup.go
  release.sh
  test/ansible-operator/Dockerfile
  test/ansible-operator/README.md
  test/ansible-operator/bin/entrypoint
  test/ansible-operator/bin/user_setup
Labels: ansible-operator, enhancement, size/XL

#884 pkg/helm/release/manager.go: only apply patch if resources change
  Gopkg.lock
  pkg/helm/release/manager.go
Labels: size/M

#896 hack/image/build-ansible-image.sh,Makefile,.travis.yml: fix ansible deploy stage
  .travis.yml
  Makefile
  hack/image/build-ansible-image.sh
Labels: size/XS

#891 pkg/ansible; Fix implementation of watching dependent resources
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/runner/runner.go
Labels: ansible-operator, bug, size/M

#898 doc/sdk-cli-reference.md: clean up cli ref doc
  doc/sdk-cli-reference.md
Labels: size/L

#895 cmd: adds all possible types for --type arg in "new" sub-command
  commands/operator-sdk/cmd/new.go
Labels: size/XS

#894 pkg/schaffold: Add missing errors handeling in main.go
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
Labels: size/S

#899 CHANGELOG.md,doc/; adds basic documentation of the `migrate` and `run ansible` commands
  CHANGELOG.md
  commands/operator-sdk/cmd/run.go
  commands/operator-sdk/cmd/run/ansible.go
  doc/sdk-cli-reference.md
Labels: ansible-operator, docs, documentation, size/M

#906 commands/.../test/local.go: use manifest gen helpers
  commands/operator-sdk/cmd/test/local.go
Labels: size/M

#885 pkg/helm: add option to watch dependent resources
  commands/operator-sdk/cmd/up/local.go
  hack/tests/e2e-helm.sh
  pkg/helm/controller/controller.go
  pkg/helm/controller/reconcile.go
  test/helm-operator/cmd/helm-operator/main.go
Labels: size/L

#905 pkg/ansible/proxy; Add namespace check to cache
  pkg/ansible/proxy/proxy.go
  pkg/ansible/proxy/proxy_test.go
  pkg/ansible/run.go
Labels: ansible-operator, bug, size/M

#902 Add different prune options to Gopkg.toml
  Gopkg.lock
  Gopkg.toml
Labels: size/L

#913 Fix regexp in sanity check for log message case
  hack/check_error_log_msg_format.sh
  pkg/k8sutil/k8sutil_test.go
  pkg/ready/ready_test.go
Labels: size/S

#925 pkg/helm/run.go: explicitly set metav1.NamespaceAll to watch all namespaces
  pkg/helm/run.go
Labels: size/XS

#914 pkg/ansible/proxy: Allow cache to handle list requests
  CHANGELOG.md
  pkg/ansible/proxy/proxy.go
Labels: ansible-operator, bug, size/M

#889 ansible/runner: Adding ability to rotate artifacts via runner
  doc/ansible/dev/advanced_options.md
  pkg/ansible/runner/runner.go
Labels: ansible-operator, enhancement, size/M

#921 pkg/scaffold/(ansible|helm)/gopkgtoml.go: fix dep ensure errors
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/helm/gopkgtoml.go
Labels: size/M

#929 pkg/ansible/proxy; Do not inject owner references on subresource requests
  pkg/ansible/proxy/proxy.go
Labels: ansible-operator, bug, size/S

#758 commands/.../scorecard.go: add initial scorecard command
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  commands/operator-sdk/cmd/root.go
  commands/operator-sdk/cmd/scorecard.go
  commands/operator-sdk/cmd/scorecard/basic_tests.go
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  commands/operator-sdk/cmd/scorecard/resource_handler.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  hack/image/build-scorecard-proxy-image.sh
  hack/tests/scorecard-subcommand.sh
  images/scorecard-proxy/Dockerfile
  images/scorecard-proxy/cmd/proxy/main.go
  internal/util/fileutil/file_util.go
  pkg/ansible/proxy/proxy.go
  test/test-framework/deploy/memcachedoperator.0.0.2.csv.yaml
Labels: size/XXL, testing

#932 pkg/scaffold: fixing deadlock caused by readiness probe
  CHANGELOG.md
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/operator.go
  pkg/scaffold/operator_test.go
  test/e2e/memcached_test.go
Labels: size/M

#945 pkg/scaffold/ansible; Use yml as playbook extension
  pkg/scaffold/ansible/playbook.go
Labels: size/XS

#912 hack/ci,*: check all returned errors
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/add/crd.go
  commands/operator-sdk/cmd/test/cluster.go
  commands/operator-sdk/cmd/test/local.go
  internal/util/yamlutil/manifest.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
  pkg/ansible/controller/status/types.go
  pkg/ansible/proxy/kubeconfig/kubeconfig.go
  pkg/ansible/proxy/kubectl.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/proxy/proxy_test.go
  pkg/ansible/runner/eventapi/eventapi.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  pkg/helm/internal/types/types.go
  pkg/test/framework.go
  pkg/test/resource_creator.go
  test/e2e/memcached_test.go
  test/test-framework/cmd/manager/main.go
  test/test-framework/pkg/controller/memcached/memcached_controller.go
Labels: size/L

#904 pkg/ansible,pkg/scaffold/ansible; enables leader election for ansible operators
  CHANGELOG.md
  commands/operator-sdk/cmd/test/cluster.go
  pkg/ansible/run.go
  pkg/scaffold/ansible/build_test_framework_ansible_test_script.go
  pkg/scaffold/ansible/deploy_operator.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, enhancement, size/M

#951 doc: update maturity model images
  doc/images/Operator-Maturity-Detailed.png
  doc/images/Operator-Maturity-Model.png
Labels: size/XS

#948 Make migrate command look for playbook.yml instead of .yaml
  commands/operator-sdk/cmd/migrate.go
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  doc/sdk-cli-reference.md
  hack/tests/e2e-ansible-molecule.sh
  pkg/scaffold/ansible/dockerfilehybrid.go
Labels: ansible-operator, bug, size/M

#953 Use same validation with k8s's for API resource group
  Gopkg.lock
  pkg/scaffold/resource.go
Labels: size/XS

#956 doc/sdk-cli-reference: update cli ref
  doc/sdk-cli-reference.md
Labels: size/S

#952 .travis.yml,Makefile: add automatic scorecard image deployment
  .travis.yml
  Makefile
  commands/operator-sdk/cmd/scorecard.go
Labels: size/S

#957 *: release v0.4.0
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/S

#959 *: bump to v0.4.0+git
  CHANGELOG.md
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#965 hack/test,test: Use the :dev image as the base for testing Ansible Operator
  hack/tests/e2e-ansible-molecule.sh
  test/ansible-memcached/prepare-test-image.yml
Labels: ansible-operator, size/S

#964 doc/helm/user-guide.md: update required kubernetes versions
  doc/helm/user-guide.md
Labels: size/XS

#946 pkg/scaffold/ansible; Add k8s_status module
  commands/operator-sdk/cmd/migrate.go
  hack/image/ansible/scaffold-ansible-image.go
  pkg/scaffold/ansible/dockerfilehybrid.go
  pkg/scaffold/ansible/k8s_status.go
  pkg/scaffold/ansible/molecule_test_local_playbook.go
  test/ansible-memcached/asserts.yml
  test/ansible-memcached/tasks.yml
Labels: ansible-operator, bug, size/L

#972 pkg/scaffold/ansible; Add k8s_status module
  commands/operator-sdk/cmd/migrate.go
  hack/image/ansible/scaffold-ansible-image.go
  hack/tests/e2e-ansible-molecule.sh
  pkg/scaffold/ansible/dockerfilehybrid.go
  pkg/scaffold/ansible/k8s_status.go
  pkg/scaffold/ansible/molecule_test_local_playbook.go
  test/ansible-memcached/asserts.yml
  test/ansible-memcached/prepare-test-image.yml
  test/ansible-memcached/tasks.yml
Labels: ansible-operator, bug, size/L

#858 Update README.md
  README.md
Labels: docs, size/S

#963 pkg/ansible/controller; Remove IsVersionRegistered check
  hack/tests/e2e-ansible.sh
  pkg/ansible/controller/controller.go
  test/ansible-memcached/watches-foo-kind.yaml
Labels: ansible-operator, bug, size/S

#989 Fix typo in user guide
  doc/user-guide.md
Labels: size/XS

#985 test/ansible, pkg/scaffold; Update Ansible Operator CI to prevent failures
  pkg/scaffold/ansible/molecule_test_cluster_playbook.go
  pkg/scaffold/ansible/molecule_test_local_playbook.go
  test/ansible-memcached/asserts.yml
Labels: ansible-operator, size/L, testing

#973 pkg/ansible/controller; Remove IsAlreadyRegistered() check in controller
  hack/tests/e2e-ansible.sh
  pkg/ansible/controller/controller.go
  test/ansible-memcached/watches-foo-kind.yaml
Labels: ansible-operator, size/S

#901 Return errors from CLI functions instead of log.Fatal
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/controller.go
  commands/operator-sdk/cmd/add/crd.go
  commands/operator-sdk/cmd/build.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/migrate.go
  commands/operator-sdk/cmd/new.go
  commands/operator-sdk/cmd/print_deps.go
  commands/operator-sdk/cmd/run.go
  commands/operator-sdk/cmd/run/ansible.go
  commands/operator-sdk/cmd/run/helm.go
  commands/operator-sdk/cmd/test/cluster.go
  commands/operator-sdk/cmd/test/local.go
  commands/operator-sdk/cmd/up/local.go
  commands/operator-sdk/main.go
  internal/util/projutil/project_util.go
  pkg/ansible/run.go
  pkg/helm/run.go
  pkg/scaffold/ansible/main.go
  pkg/scaffold/helm/main.go
Labels: size/XL, style

#983 commands/.../up/local: fix kubeconfig and namespace handling
  CHANGELOG.md
  commands/operator-sdk/cmd/up/local.go
Labels: size/M

#942 doc: add scorecard documentation
  CHANGELOG.md
  doc/dev/testing/travis-build.md
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
Labels: docs, scorecard, size/L

#786 Expose controller-runtime metrics
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  commands/operator-sdk/cmd/build_test.go
  pkg/k8sutil/constants.go
  pkg/k8sutil/k8sutil.go
  pkg/metrics/metrics.go
  pkg/scaffold/ansible/deploy_operator.go
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/operator.go
  pkg/scaffold/operator_test.go
Labels: size/L

#919 hack/ci: Add check for valid commit range
  hack/ci/check-doc-only-update.sh
Labels: size/S

#996 commands/.../up/local: fix kubeconfig and namespace handling (#983)
  CHANGELOG.md
  commands/operator-sdk/cmd/up/local.go
Labels: size/M

#1002 CHANGELOG.md: add CSV feature
  CHANGELOG.md
Labels: size/XS

#1011 README.md: remove alpha label
  README.md
Labels: size/S

#1013 doc/user/client.md: fix typo
  doc/user/client.md
Labels: size/XS

#1000 pkg/helm,pkg/scaffold/helm: add leader election
  CHANGELOG.md
  pkg/helm/run.go
  pkg/scaffold/helm/operator.go
Labels: size/S

#1014 OLM version update
  Gopkg.lock
  Gopkg.toml
  commands/operator-sdk/cmd/scorecard/olm_tests.go
  commands/operator-sdk/cmd/scorecard/scorecard.go
  pkg/scaffold/olm-catalog/csv.go
  pkg/scaffold/olm-catalog/csv_test.go
  pkg/scaffold/olm-catalog/csv_updaters.go
Labels: size/L

#1007 Do not let operator-sdk add crd overwrite exsiting file
  pkg/scaffold/cr.go
  pkg/scaffold/crd.go
Labels: size/XS

#1005 Add clear error message when kubeconfig is missing for `operator-sdk scorecard`
  commands/operator-sdk/cmd/scorecard/scorecard.go
Labels: size/XS

#1010 commands/operator-sdk/cmd/up/local.go: build and run binary directly
  commands/operator-sdk/cmd/up/local.go
Labels: size/M

#1015 add crd: only skip overwriting CRD's/CR's when explicitly adding them
  commands/operator-sdk/cmd/add/crd.go
  pkg/scaffold/cr.go
  pkg/scaffold/crd.go
Labels: size/S

#991 pkg/ansible/controller; Check if GVK is already registered
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/e2e-ansible.sh
  pkg/ansible/controller/controller.go
  test/ansible-memcached/asserts.yml
  test/ansible-memcached/secret/tasks/main.yml
  test/ansible-memcached/tasks.yml
  test/ansible-memcached/watches-v1-kind.yaml
Labels: ansible-operator, bug, size/M

#1017 test/test-framework/deploy/operator.yaml: update image
  test/test-framework/deploy/crds/cache_v1alpha1_memcached_crd.yaml
  test/test-framework/deploy/operator.yaml
Labels: size/M, test-framework

#924 pkg/ansible; Add support to watch cluster-scoped resources
  doc/ansible/dev/advanced_options.md
  images/scorecard-proxy/cmd/proxy/main.go
  pkg/ansible/controller/controller.go
  pkg/ansible/operator/operator.go
  pkg/ansible/proxy/controllermap/controllermap.go
  pkg/ansible/proxy/kubeconfig/kubeconfig.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/proxy/proxy_test.go
  pkg/ansible/run.go
  pkg/ansible/runner/fake/runner.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/runner/testdata/valid.yaml.tmpl
Labels: ansible-operator, enhancement, size/L

#967 pkg/scaffold/,commands/operator-sdk/cmd/new.go: use chart values in CR spec
  CHANGELOG.md
  commands/operator-sdk/cmd/new.go
  hack/tests/e2e-helm.sh
  pkg/scaffold/cr.go
  pkg/scaffold/cr_test.go
  pkg/scaffold/helm/chart.go
Labels: size/M

#1035 .travis.yml: make dep ensure verbose
  .travis.yml
Labels: size/XS, testing

#1020 pkg/scaffold: update to controller-runtime v0.1.10 and k8s 1.13.1
  Gopkg.lock
  Gopkg.toml
  pkg/scaffold/ansible/gopkgtoml.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/controller_kind.go
  pkg/scaffold/controller_kind_test.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/helm/gopkgtoml.go
Labels: do-not-merge/work-in-progress, size/L

#1025 commands/.../scorecard: disable inconsistent test
  commands/operator-sdk/cmd/scorecard/scorecard.go
  doc/test-framework/scorecard.md
  hack/tests/scorecard-subcommand.sh
Labels: scorecard, size/S

#873 pkg/log/zap: adding helpers for zap logger configuration
  Gopkg.lock
  commands/operator-sdk/cmd/run/ansible.go
  commands/operator-sdk/cmd/run/helm.go
  commands/operator-sdk/cmd/up/local.go
  doc/user/logging.md
  images/scorecard-proxy/cmd/proxy/main.go
  pkg/ansible/flags/flag.go
  pkg/helm/flags/flag.go
  pkg/log/zap/flags.go
  pkg/log/zap/logger.go
  pkg/scaffold/ansible/main.go
  pkg/scaffold/cmd.go
  pkg/scaffold/cmd_test.go
  pkg/scaffold/helm/main.go
  test/test-framework/cmd/manager/main.go
Labels: size/L

#869 Create CRD validation specs in CRD manifests and as Go code
  Gopkg.lock
  commands/operator-sdk/cmd/add.go
  commands/operator-sdk/cmd/add/api.go
  commands/operator-sdk/cmd/add/crd.go
  commands/operator-sdk/cmd/generate.go
  commands/operator-sdk/cmd/generate/internal/genutil.go
  commands/operator-sdk/cmd/generate/k8s.go
  commands/operator-sdk/cmd/generate/openapi.go
  commands/operator-sdk/cmd/new.go
  internal/util/projutil/project_util.go
  internal/util/yamlutil/manifest.go
  pkg/scaffold/constants.go
  pkg/scaffold/cr.go
  pkg/scaffold/cr_test.go
  pkg/scaffold/crd.go
  pkg/scaffold/crd_test.go
  pkg/scaffold/gopkgtoml.go
  pkg/scaffold/gopkgtoml_test.go
  pkg/scaffold/olm-catalog/config.go
  pkg/scaffold/olm-catalog/config_test.go
  pkg/scaffold/types.go
  pkg/scaffold/types_test.go
  test/e2e/memcached_test.go
Labels: enhancement, size/XL

#1040 CHANGELOG: update for k8s 1.13.1 and controller-runtime v0.1.10
  CHANGELOG.md
Labels: size/XS
