Repository operator-framework/operator-sdk, pull requests merged in 2019-07, with the labels that each got.

#1617 fix: Fix a link in README
  doc/test-framework/writing-e2e-tests.md
Labels: lgtm, ok-to-test, size/XS

#1612 Upgrade the version of the dependency controller-runtime from `v0.1.10` to `v0.1.12`
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  doc/user/unit-testing.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/codec.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
  vendor/k8s.io/client-go/transport/token_source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: lgtm, ok-to-test, size/L

#1621 CHANGELOG.md,doc/dev/release.md: fix CHANGELOG, clarify release doc
  CHANGELOG.md
  doc/dev/release.md
Labels: lgtm, size/S

#1577 cmd/operator-sdk/alpha/*,internal/olm: added alpha subcommands to manage OLM installation
  Gopkg.lock
  Makefile
  cmd/operator-sdk/alpha/cmd.go
  cmd/operator-sdk/alpha/olm/cmd.go
  cmd/operator-sdk/alpha/olm/install.go
  cmd/operator-sdk/alpha/olm/status.go
  cmd/operator-sdk/alpha/olm/uninstall.go
  cmd/operator-sdk/main.go
  doc/sdk-cli-reference.md
  hack/tests/alpha-olm-subcommands.sh
  internal/olm/client.go
  internal/olm/manager.go
Labels: size/XL

#1626 pkg/metrics: pass rest.Config to avoid flag issue in library
  CHANGELOG.md
  doc/user/metrics/README.md
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
  pkg/ansible/run.go
  pkg/helm/run.go
  pkg/metrics/metrics.go
Labels: lgtm, size/M

#1623 Makefile: remove test/ansible from ci-ansible
  Makefile
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
Labels: ansible-operator, lgtm, size/M, testing

#1636 internal/pkg/scaffold/crd.go: remove CRD cache
  CHANGELOG.md
  internal/pkg/scaffold/crd.go
Labels: kind/bug, lgtm, size/M

#1647 Fix log message so it doesn't cause an error
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
  pkg/helm/run.go
Labels: lgtm, size/S

#1627 cmd/operator-sdk/new/cmd.go: fallback to default helm RBAC role without kubeconfig
  CHANGELOG.md
  cmd/operator-sdk/new/cmd.go
  internal/pkg/scaffold/helm/role.go
  internal/pkg/scaffold/helm/role_test.go
Labels: size/M

#1651 doc/test-framework: use correct manifest structure in docs
  doc/test-framework/writing-e2e-tests.md
Labels: docs, lgtm, size/XS

#1653 hack/check_error_log_msg_format.sh: correctly check "errors." functions
  hack/check_error_log_msg_format.sh
Labels: size/XS, testing

#1652 doc/operator-scope: add scope tag for CRD generation
  doc/operator-scope.md
  doc/user-guide.md
Labels: lgtm, size/S

#1523 ansible: pull watches into own package
  pkg/ansible/operator/operator.go
  pkg/ansible/operator/operator_test.go
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  pkg/ansible/watches/testdata/duplicate_gvk.yaml
  pkg/ansible/watches/testdata/invalid.yaml
  pkg/ansible/watches/testdata/invalid_duration.yaml
  pkg/ansible/watches/testdata/invalid_finalizer_no_vars.yaml
  pkg/ansible/watches/testdata/invalid_finalizer_playbook_path.yaml
  pkg/ansible/watches/testdata/invalid_finalizer_role_path.yaml
  pkg/ansible/watches/testdata/invalid_playbook_path.yaml
  pkg/ansible/watches/testdata/invalid_role_path.yaml
  pkg/ansible/watches/testdata/invalid_status.yaml
  pkg/ansible/watches/testdata/playbook.yml
  pkg/ansible/watches/testdata/roles/role/tasks.yaml
  pkg/ansible/watches/testdata/valid.yaml.tmpl
  pkg/ansible/watches/watches.go
  pkg/ansible/watches/watches_test.go
Labels: size/XXL

#1635 internal/pkg/scaffold: move some utility functions to internal/util/k8sutil
  internal/pkg/scaffold/crd.go
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/pkg/scaffold/olm-catalog/csv_test.go
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/pkg/scaffold/olm-catalog/package_manifest.go
  internal/pkg/scaffold/olm-catalog/package_manifest_test.go
  internal/util/k8sutil/k8sutil.go
  internal/util/k8sutil/k8sutil_test.go
  internal/util/k8sutil/object.go
  internal/util/operator-registry/package_manifest.go
  internal/util/operator-registry/package_manifest_test.go
Labels: olm-catalog, size/L

#1629 doc/dev,hack/tests: update docs and fix go test configuration
  .travis.yml
  doc/dev/testing/running-the-tests.md
  doc/dev/testing/travis-build.md
  hack/tests/e2e-go.sh
  hack/tests/scaffolding/e2e-go-scaffold.sh
Labels: docs, size/M, testing

#1663 doc/user-guide.md: update Go modules support section
  doc/user-guide.md
Labels: kind/documentation, lgtm, size/S

#1665 hack/tests/scaffolding/scaffold-memcached.go: remove go.mod in SDK repo hack
  hack/tests/scaffolding/scaffold-memcached.go
Labels: lgtm, size/S

#1668 remove apply of RBAC definitions
  doc/helm/dev/developer_guide.md
Labels: size/XS

#1661 ansible: Use operator-sdk's dynamic restmapper
  pkg/ansible/run.go
  pkg/ansible/watches/watches_test.go
Labels: size/XS

#1664 hack/: remove existing replace lines in go.mod for the SDK repo first
  hack/lib/test_lib.sh
  hack/tests/scaffolding/scaffold-memcached.go
Labels: size/XS

#1673 *: release v0.9.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: lgtm, size/M

#1674 *: bump to v0.9.0+git
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1508 Helm E2E in Openshift API-CI
  Makefile
  ci/dockerfiles/helm-e2e-hybrid.Dockerfile
  ci/dockerfiles/helm-e2e.Dockerfile
  ci/dockerfiles/helm.Dockerfile
  ci/tests/e2e-helm-scaffold-hybrid.sh
  ci/tests/e2e-helm-scaffold.sh
  ci/tests/e2e-helm.sh
Labels: size/L

#1683 *: document mercurial dependency for v0.9+ operators
  CHANGELOG.md
  README.md
  doc/user-guide.md
Labels: area/dependency, lgtm, size/XS

#1684 v0.9.x: document mercurial dependency for operators (#1683)
  CHANGELOG.md
  README.md
  doc/user-guide.md
Labels: area/dependency, size/S

#1601 Enable ServiceMonitor creation by default
  doc/user/metrics/README.md
  doc/user/metrics/service-monitor.md
  internal/pkg/scaffold/cmd.go
  internal/pkg/scaffold/cmd_test.go
  internal/pkg/scaffold/role.go
  internal/pkg/scaffold/role_test.go
  pkg/metrics/service-monitor.go
Labels: lgtm, size/M

#1640 doc: add OpenAPI validation info to user guide
  doc/user-guide.md
Labels: lgtm, size/S

#1384 Golang E2E in Openshift API-CI
  Makefile
  ci/dockerfiles/builder.Dockerfile
  ci/dockerfiles/go-e2e.Dockerfile
  ci/tests/e2e-go-scaffold.sh
  ci/tests/e2e-go.sh
  cmd/operator-sdk/test/local.go
  cmd/operator-sdk/up/local.go
  hack/tests/scaffolding/e2e-go-scaffold.sh
  pkg/k8sutil/k8sutil.go
  pkg/leader/leader.go
  pkg/metrics/metrics.go
  test/test-framework/build/bin/entrypoint
  test/test-framework/build/bin/user_setup
Labels: size/L, testing

#1691 doc/usre/csv-annotations.md: fix link
  doc/user/csv-annotations.md
Labels: size/XS

#1697 v0.8.x: fix broken links (#1596)
  doc/migration/v0.1.0-migration-guide.md
  doc/proposals/ansible-operator-status.md
  doc/proposals/metering-operator-metrics.md
Labels: size/XS

#1690 v0.8.x: fix boilerplate check (#1544)
  CHANGELOG.md
  internal/pkg/scaffold/boilerplate_go_txt_test.go
  internal/pkg/scaffold/scaffold.go
Labels: size/M

#1692 ci/tests,test/e2e: log up local errors better
  ci/tests/e2e-go.sh
  test/e2e/_incluster-test-code/memcached_test.go
Labels: lgtm, size/XS, testing

#1695 internal/pkg/scaffold: hardcode repo path in setupTestFrameworkConfig
  internal/pkg/scaffold/test_setup.go
Labels: kind/bug, size/XS

#1622 Move to ubi-based base image for Ansible Operator
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/tests/e2e-ansible.sh
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
  internal/pkg/scaffold/ansible/molecule_default_molecule.go
  internal/pkg/scaffold/ansible/molecule_default_prepare.go
  internal/pkg/scaffold/ansible/molecule_test_local_molecule.go
  test/ansible-inventory/molecule/test-local/molecule.yml
  test/ansible-inventory/molecule/test-local/prepare.yml
  test/ansible-memcached/asserts.yml
  test/ansible-memcached/molecule.yml
Labels: lgtm, size/L

#1694 pkg/metrics/service-monitor.go: handle nil error
  pkg/metrics/service-monitor.go
Labels: lgtm, metrics, size/XS, testing

#1709 internal/pkg/scaffold/olm-catalog: use olm.targetNamespaces annotation in WATCH_NAMESPACE (#1396)
  CHANGELOG.md
  internal/pkg/scaffold/olm-catalog/csv_test.go
  internal/pkg/scaffold/olm-catalog/csv_updaters.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
Labels: size/L

#1710 cmd/operator-sdk/build: expand env in go build (#1535)
  CHANGELOG.md
  cmd/operator-sdk/build/cmd.go
  internal/util/projutil/exec.go
Labels: size/XS

#1711 internal/pkg/scorecard: access `CRManifestOpt` correctly with `--olm-deployed` (#1565)
  CHANGELOG.md
  internal/pkg/scorecard/scorecard.go
Labels: size/M

#1712 internal/pkg/scaffold/crd.go: remove CRD cache (#1636)
  CHANGELOG.md
  internal/pkg/scaffold/crd.go
Labels: size/M

#1672 ansible: load watches in run
  pkg/ansible/operator/operator.go
  pkg/ansible/run.go
  pkg/ansible/run_test.go
Labels: lgtm, size/L

#1718 e2e: better method of adding SDK repo replace directive to operator's go.mod (#1574)
  hack/lib/test_lib.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-helm.sh
  test/e2e/memcached_test.go
Labels: size/L

#1719 e2e: remove existing replace lines in go.mod for the SDK repo (#1664)
  hack/lib/test_lib.sh
  test/e2e/memcached_test.go
Labels: size/S

#1716 CHANGELOG.md,doc/sdk-cli-reference.md: add --operator-name addition
  CHANGELOG.md
  doc/sdk-cli-reference.md
Labels: lgtm, size/XS

#1725 CHANGELOG.md,doc/sdk-cli-reference.md: add --operator-name (#1716)
  CHANGELOG.md
  doc/sdk-cli-reference.md
Labels: size/XS

#1717 *: release v0.8.2
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1715 Ensure Ansible is installed in CI images
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
Labels: size/XS

#1704 internal/pkg/scaffold/olm-catalog: allow multiple RBAC files in CSV config, add operator-name field
  CHANGELOG.md
  doc/user/olm-catalog/generating-a-csv.md
  internal/pkg/scaffold/olm-catalog/config.go
  internal/pkg/scaffold/olm-catalog/csv.go
  internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/csv-config.yaml
Labels: olm-catalog, size/M

#1728 *: revert version from v0.8.2 to v0.8.x
  CHANGELOG.md
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/go_mod_test.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/gopkgtoml_test.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  version/version.go
Labels: size/M

#1729 CHANGELOG.md: add v0.8.2 bug fixes
  CHANGELOG.md
Labels: size/XS

#1731 adding /usr/local/bin/operator-sdk path
  doc/user/install-operator-sdk.md
Labels: size/XS

#1743 docs: add links in install doc
  doc/user/install-operator-sdk.md
Labels: lgtm, ok-to-test, size/XS

#1730 Display simple installation first
  doc/user/install-operator-sdk.md
Labels: ok-to-test, size/S

#1713 README.md: Add missing --repo flag in quickstart
  README.md
Labels: lgtm, ok-to-test, size/XS
