Repository operator-framework/operator-sdk, pull requests merged in 2019-09, with the labels that each got.

#1835 small readme improvements
  README.md
Labels: lgtm, needs-ok-to-test, size/XS

#1777 docs(user dev guide) : replace make dep since it no longer exists
  doc/dev/developer_guide.md
Labels: ok-to-test, size/S

#1839 (c-r v0.2.0) *: bump controller-runtime to v0.2.0, update APIs
  CHANGELOG.md
  doc/user/client.md
  example/memcached-operator/memcached_controller.go.tmpl
  go.mod
  go.sum
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/ansible/gopkgtoml.go
  internal/pkg/scaffold/go_mod.go
  internal/pkg/scaffold/gopkgtoml.go
  internal/pkg/scaffold/helm/go_mod.go
  internal/pkg/scaffold/helm/gopkgtoml.go
  internal/util/k8sutil/options.go
  pkg/ansible/proxy/cache_response.go
  pkg/test/client.go
  test/e2e/_incluster-test-code/memcached_test.go
  test/test-framework/pkg/controller/memcached/memcached_controller.go
  test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go
Labels: refactoring, size/L

#1877 doc: Fix missing word in user guide
  doc/user-guide.md
Labels: lgtm, ok-to-test, size/XS

#1879 add camila macedo
  OWNERS
Labels: lgtm, size/XS

#1880 add jmccormick2001 to OWNERS file
  OWNERS
Labels: lgtm, size/XS

#1888 Fix broken links - OLM Documentation was replaced by doc
  CHANGELOG.md
  doc/design/milestone-0.2.0/csv-generation.md
  doc/proposals/cli-ux-phase1.md
  doc/proposals/sdk-code-annotations.md
  doc/test-framework/scorecard.md
Labels: lgtm, size/S

#1890 cmd: added new flag --skip-generation for operator-sdk add api
  CHANGELOG.md
  cmd/operator-sdk/add/api.go
Labels: lgtm, ok-to-test, size/S

#1860 Remove note about installing molecule from source
  doc/ansible/dev/testing_guide.md
Labels: lgtm, size/XS

#1885 Remove usage of J flag
  doc/user/install-operator-sdk.md
Labels: lgtm, ok-to-test, size/S

#1894 CHANGELOG.md,cmd,doc: update docs about --skip-generation flag
  CHANGELOG.md
  cmd/operator-sdk/add/api.go
  doc/sdk-cli-reference.md
Labels: lgtm, size/S

#1861 pkg/metrics: CreateMetricsService should return latest service
  pkg/metrics/metrics.go
Labels: lgtm, ok-to-test, size/XS

#1881 internal/olm: move GetInstalledVersion() to internal/olm/client
  internal/olm/client.go
  internal/olm/client/client.go
Labels: olm-catalog, refactoring, size/L

#1901 test/test-framework: update manifests to pass registry/OLM validation
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
Labels: lgtm, olm-catalog, size/S

#1919 Issue #1905: Add type of guide to user guide documentation.
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  doc/dev/developer_guide.md
  doc/helm/user-guide.md
  doc/user-guide.md
Labels: lgtm, ok-to-test, size/S

#1920 Issue #1910: Add status to Ansible proposal docs with relevant docs links.
  doc/proposals/ansible-operator-status.md
  doc/proposals/ansible-operator-testing.md
  doc/proposals/ansible-operator.md
Labels: lgtm, ok-to-test, size/S

#1917 cleanup code in internal/pkg/scorecard/interfaces.go
  internal/pkg/scorecard/interfaces.go
Labels: lgtm, ok-to-test, size/S

#1921 add logic to have the scorecard created pod wait till all the contain…
  internal/pkg/scorecard/plugins/resource_handler.go
Labels: lgtm, size/M

#1533 ppc64le helm image build
  .travis.yml
  Makefile
  hack/image/build-helm-image.sh
  hack/image/push-image-tags.sh
  hack/image/push-manifest-list.sh
  hack/lib/image_lib.sh
Labels: lgtm, ok-to-test, size/L

#1807 doc/dev/release.md: some cleanup and require samples repo update on a release
  doc/dev/release.md
Labels: lgtm, size/M, versioning

#1961 *: controller-tools bump to v0.2.2+ to include bugfix for crd generation
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  go.mod
  go.sum
  hack/tests/scaffolding/scaffold-memcached.go
  internal/pkg/scaffold/ansible/go_mod.go
  internal/pkg/scaffold/crd_test.go
Labels: kind/bug, kind/failing-test, kind/flake, size/L

#1909 doc(test-features): improvements in the scorecard
  doc/test-framework/scorecard.md
Labels: lgtm, size/L

#1946 Version flag
  cmd/operator-sdk/scorecard/cmd.go
  internal/pkg/scorecard/helpers/versions.go
  internal/pkg/scorecard/helpers/versions_test.go
  internal/pkg/scorecard/plugins/basic_tests.go
  internal/pkg/scorecard/plugins/resource_handler.go
  internal/pkg/scorecard/scorecard.go
Labels: kind/feature, lgtm, scorecard, size/L

#1967 small typo change to solve the issue 1930
  cmd/operator-sdk/build/cmd.go
Labels: size/XS

#1680 doc/user/migrating-existing-apis.md: document API version migra…
  doc/user/migrating-existing-apis.md
Labels: kind/documentation, size/L

#1952 Operator developers gets UBI8 based images (for all less Ansible)
  CHANGELOG.md
  ci/dockerfiles/go-e2e.Dockerfile
  ci/dockerfiles/helm-e2e-hybrid.Dockerfile
  ci/dockerfiles/helm.Dockerfile
  ci/dockerfiles/scorecard-proxy.Dockerfile
  ci/tests/e2e-helm.sh
  hack/tests/e2e-helm.sh
  images/scorecard-proxy/Dockerfile
  internal/pkg/scaffold/build_dockerfile.go
  internal/pkg/scaffold/build_dockerfile_test.go
  internal/pkg/scaffold/helm/dockerfilehybrid.go
Labels: lgtm, size/S

#1982 Fix few typos.
  README.md
Labels: lgtm, ok-to-test, size/XS

#1986 ci,internal: update ubi7 -> ubi8
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/tests/e2e-ansible.sh
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/S

#1987 Revert "ci,internal: update ubi7 -> ubi8 (#1986)"
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/tests/e2e-ansible.sh
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/S

#1947 Upgrade Ansible Images
  .travis.yml
  CHANGELOG.md
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  doc/ansible/dev/developer_guide.md
  hack/tests/e2e-ansible-molecule.sh
  internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
  internal/pkg/scaffold/ansible/dockerfilehybrid.go
  internal/pkg/scaffold/ansible/k8s_status.go
  internal/pkg/scaffold/ansible/molecule_default_prepare.go
  internal/pkg/scaffold/ansible/molecule_test_cluster_playbook.go
  internal/pkg/scaffold/ansible/molecule_test_local_playbook.go
  internal/pkg/scaffold/ansible/travis.go
  pkg/ansible/runner/internal/inputdir/inputdir.go
  test/ansible-inventory/inventory/hosts
  test/ansible-inventory/molecule/test-local/asserts.yml
  test/ansible-inventory/molecule/test-local/playbook.yml
  test/ansible-inventory/molecule/test-local/prepare.yml
  test/ansible-inventory/plugins/filter/test.py
  test/ansible-inventory/roles/inventory/tasks/main.yml
Labels: lgtm, size/L

#1956 Makefile: add help to major targets.
  Makefile
Labels: lgtm, size/M

#1828 Make generated inventory define implicit localhost
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#1891 doc/migration: add sections for v0.8.x and v0.9.x
  CHANGELOG.md
  doc/migration/version-upgrade-guide.md
Labels: kind/documentation, size/L

#1989 fix link in changelog for the entry : Generated inventory for Ansible…
  CHANGELOG.md
Labels: size/XS
