Repository operator-framework/operator-sdk, pull requests merged in 2020-01, with the labels that each got.

#2357 docs: correct the information in the v0.11.0 upgrade guide
  doc/migration/version-upgrade-guide.md
Labels: size/XS

#2325 pkg/helm: add overrideValues to watches.yaml (with env expansion)
  CHANGELOG.md
  doc/helm/user-guide.md
  pkg/helm/controller/controller.go
  pkg/helm/controller/reconcile.go
  pkg/helm/release/manager_factory.go
  pkg/helm/run.go
  pkg/helm/watches/watches.go
  pkg/helm/watches/watches_test.go
Labels: helm-operator, kind/feature, size/L

#2190 fix error to create service metrics when run operator-sdk up local
  CHANGELOG.md
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
Labels: approved, kind/bug, lgtm, metrics, size/M

#2345 gen-csv: non-Go operators are not yet supported
  doc/user/olm-catalog/csv-annotations.md
  doc/user/olm-catalog/generating-a-csv.md
  internal/scaffold/olm-catalog/csv.go
Labels: kind/bug, lgtm, olm-catalog, size/S

#2366 internal/scaffold/helm: added role rule for creating events
  internal/scaffold/helm/role.go
  internal/scaffold/helm/role_test.go
Labels: helm-operator, kind/bug, size/S

#2360 Scorecard refactor run
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/runner_test.go
Labels: size/XL

#2359 Helm: fix misleading "release not found" errors during CR deletion
  CHANGELOG.md
  pkg/helm/controller/reconcile.go
  pkg/helm/release/manager.go
Labels: helm-operator, kind/bug, lgtm, size/M

#2201 internal/generate: align CRD generator with controller-gen
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/add/crd.go
  cmd/operator-sdk/generate/crds.go
  cmd/operator-sdk/internal/genutil/crds.go
  cmd/operator-sdk/new/cmd.go
  doc/user-guide.md
  doc/user/migrating-existing-apis.md
  internal/generate/crd/crd.go
  internal/generate/crd/crd_test.go
  internal/generate/gen/config.go
  internal/generate/gen/config_test.go
  internal/generate/gen/generator.go
  internal/generate/gen/rules.go
  internal/scaffold/crd.go
  internal/scaffold/crd_test.go
  internal/scaffold/test_setup.go
  internal/util/fileutil/file_util.go
  test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
  test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
Labels: do-not-merge/hold, refactoring, size/XXL

#2367 code-of-conduct: update contact info
  code-of-conduct.md
Labels: kind/documentation, lgtm, size/S

#2368 *: bump controller-tools to v0.2.4
  CHANGELOG.md
  go.mod
  go.sum
  test/test-framework/go.sum
Labels: area/dependency, lgtm, size/S

#2313 internal/olm/operator/internal: operator-registry wrappers
  internal/olm/operator/internal/configmap.go
  internal/olm/operator/internal/deployment.go
  internal/olm/operator/internal/registry.go
  internal/olm/operator/internal/service.go
  internal/util/k8sutil/k8sutil.go
Labels: kind/feature, olm-catalog, size/L

#2356 Extend 3rd party resource management documentation
  doc/user-guide.md
Labels: kind/documentation, lgtm, size/M

#2332 Only add explicit -mod=vendor if needed
  internal/util/projutil/exec.go
Labels: lgtm, size/S

#2381 more context on the doc on override values
  doc/helm/user-guide.md
Labels: lgtm, size/M

#2279 doc/proposals/improve-csv-cli.md: 'gen-csv --inputs' proposal
  doc/proposals/improve-csv-cli.md
Labels: approved, kind/design, lgtm, olm-catalog, size/L

#2379 improvements in the make target for lint checks and automatically fixes
  Makefile
  hack/tests/check-lint.sh
Labels: lgtm, size/S

#2320 internal/olm/operator: OLM operator manager
  .travis.yml
  Makefile
  hack/tests/integration.sh
  internal/olm/operator/manager.go
  internal/olm/operator/olm.go
  internal/olm/operator/operator.go
  internal/olm/operator/tenancy.go
  test/integration/operator_olm_test.go
  test/integration/test_suite.go
  test/test-framework/build/Dockerfile
Labels: kind/feature, lgtm, olm-catalog, size/XXL

#2389 *: release v0.14.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2390 *: bump to v0.14.0+git
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2391 *: bump to v0.14.0+git
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2380 update doc: make clear the required permission for metrics regards the finalizers
  doc/faq.md
Labels: lgtm, size/XS

#2403 .travis.yml: goveralls download should not affect SDK go.mod contents
  .travis.yml
Labels: lgtm, size/XS

#2259 doc: Proposal for Samples QA
  doc/proposals/qa_samples_proposal.md
Labels: approved, kind/documentation, lgtm, size/L, test-framework, testing

#2375 fix: (ansible) - Errors in the event have not been re-trigging the reconcile.
  CHANGELOG.md
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
Labels: ansible-operator, approved, kind/bug, lgtm, size/M

#2382 internal/generate/olm-catalog: package manifest generator
  cmd/operator-sdk/olmcatalog/gen-csv.go
  internal/generate/crd/crd_test.go
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/olm-catalog/package_manifest_test.go
  internal/generate/testdata/go/build/Dockerfile
  internal/generate/testdata/go/deploy/crds/cache.example.com_memcachedrs_crd.yaml
  internal/generate/testdata/go/deploy/crds/cache.example.com_memcacheds_crd.yaml
  internal/generate/testdata/go/deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml
  internal/generate/testdata/go/deploy/crds/cache.example.com_v1alpha1_memcachedrs_cr.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  internal/generate/testdata/go/deploy/operator.yaml
  internal/generate/testdata/go/deploy/role.yaml
  internal/generate/testdata/go/deploy/role_binding.yaml
  internal/generate/testdata/go/deploy/service_account.yaml
  internal/generate/testdata/go/pkg/apis/cache/v1alpha1/doc.go
  internal/generate/testdata/go/pkg/apis/cache/v1alpha1/memcached_types.go
  internal/generate/testdata/go/pkg/apis/cache/v1alpha1/memcachedrs_types.go
  internal/scaffold/olm-catalog/package_manifest.go
  internal/scaffold/olm-catalog/package_manifest_test.go
Labels: olm-catalog, refactoring, size/XXL

#2402 cmd/operator-sdk: OLM integration `alpha run/cleanup` CLI
  CHANGELOG.md
  cmd/operator-sdk/alpha/cleanup/cmd.go
  cmd/operator-sdk/alpha/cmd.go
  cmd/operator-sdk/alpha/run/cmd.go
  doc/cli/operator-sdk_alpha.md
  doc/cli/operator-sdk_alpha_cleanup.md
  doc/cli/operator-sdk_alpha_run.md
  internal/olm/operator/manager.go
  internal/olm/operator/operator.go
  test/integration/operator_olm_test.go
Labels: olm-catalog, size/L

#2412 doc/proposals: move proposals from openshift-* directories
  doc/proposals/ansible-operator-devex.md
  doc/proposals/kubebuilder-integration.md
  doc/proposals/kubernetes-1.17.md
  doc/proposals/operator-testing-tool.md
  doc/proposals/qa-samples-proposal.md
  doc/proposals/tech-debt.md
Labels: kind/documentation, lgtm, size/L

#2410 internal/generate/crd: fix flaky unit test
  internal/generate/crd/crd.go
  internal/generate/crd/crd_test.go
Labels: kind/bug, size/S

#2355 *: use fmt.Errorf with %w/%v for Go 1.13 error wrapping
  CHANGELOG.md
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/add/controller.go
  cmd/operator-sdk/add/crd.go
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/olmcatalog/gen-csv.go
  cmd/operator-sdk/test/local.go
  cmd/operator-sdk/up/local.go
  go.mod
  hack/tests/scaffolding/scaffold-memcached.go
  internal/generate/gen/rules.go
  internal/olm/client.go
  internal/olm/client/client.go
  internal/olm/client/status.go
  internal/olm/manager.go
  internal/scaffold/helm/chart.go
  internal/scaffold/helm/role.go
  internal/scaffold/internal/deps/print_go_mod.go
  internal/scaffold/olm-catalog/csv.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scaffold/olm-catalog/descriptor/descriptor.go
  internal/scaffold/olm-catalog/descriptor/parse.go
  internal/scaffold/olm-catalog/descriptor/search.go
  internal/scaffold/scaffold.go
  internal/scorecard/helpers/test_definitions.go
  internal/scorecard/plugins/config.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/resource_handler.go
  internal/scorecard/scorecard.go
  internal/util/k8sutil/crd.go
  internal/util/k8sutil/k8sutil.go
  internal/util/operator-registry/package_manifest.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
  internal/util/yamlutil/manifest.go
  pkg/ansible/watches/watches.go
  pkg/helm/release/manager.go
  pkg/helm/watches/watches.go
  pkg/kube-metrics/metrics.go
  pkg/kube-metrics/uclient.go
  pkg/metrics/metrics.go
  pkg/test/client.go
  pkg/test/framework.go
  pkg/test/resource_creator.go
  pkg/tls/tls.go
  test/e2e/_incluster-test-code/memcached_test.go
Labels: size/L

#2409 Scorecard refactor viper usage
  cmd/operator-sdk/scorecard/cmd.go
  go.mod
  internal/scorecard/config.go
  internal/scorecard/interfaces.go
  internal/scorecard/scorecard.go
  internal/scorecard/scorecard_output.go
Labels: lgtm, size/L

#2404 Update user-guide.md
  doc/helm/user-guide.md
Labels: lgtm, size/XS

#2335 pkg/test/context.go: create an id that is a valid namespace name
  CHANGELOG.md
  pkg/test/context.go
  pkg/test/context_test.go
  test/test-framework/deploy/namespace-init.yaml
  test/test-framework/go.sum
Labels: lgtm, size/M

#2076 cmd/operator-sdk: `bundle build` builds operator bundle images
  CHANGELOG.md
  cmd/operator-sdk/alpha/bundle/build.go
  cmd/operator-sdk/alpha/bundle/cmd.go
  cmd/operator-sdk/alpha/cmd.go
  doc/cli/operator-sdk_alpha.md
  doc/cli/operator-sdk_alpha_bundle.md
  doc/cli/operator-sdk_alpha_bundle_build.md
Labels: kind/feature, olm-catalog, size/L

#2423 Link directly to Helm CLI examples from helm user guide
  doc/helm/user-guide.md
Labels: lgtm, size/XS

#2387 feat: use operator-framework api to validate pkg manifest
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/olm-catalog/package_manifest_test.go
  internal/util/operator-registry/package_manifest.go
  internal/util/operator-registry/package_manifest_test.go
Labels: size/L

#2414 pkg/helm: install resources in same namespace as CR
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  pkg/helm/client/client.go
  pkg/helm/release/manager_factory.go
Labels: kind/bug, size/L

#2424 [v0.14.x] pkg/helm: install resources in same namespace as CR
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  pkg/helm/client/client.go
  pkg/helm/release/manager_factory.go
Labels: size/L

#2277 pkg/test/client: retry cleanup function if cluster is temporarily unavailable
  CHANGELOG.md
  pkg/test/client.go
Labels: ok-to-test, size/S, test-framework

#2436 *: release v0.14.1
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2437 *: post-v0.14.1 bumps
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2440 doc,CHANGELOG.md: update for v0.14.1 release
  CHANGELOG.md
  doc/user/install-operator-sdk.md
Labels: size/XS

#2428 Scorecard remove v1alpha1 part1
  cmd/operator-sdk/scorecard/cmd.go
  doc/cli/operator-sdk_scorecard.md
  doc/test-framework/scorecard.md
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/config.go
  internal/scorecard/helpers/versions.go
  internal/scorecard/helpers/versions_test.go
  internal/scorecard/interfaces.go
  internal/scorecard/plugins/config.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/scorecard.go
  internal/scorecard/scorecard_output.go
  test/test-framework/.osdk-scorecard-ci.yaml
  test/test-framework/.osdk-scorecard.yaml
  test/test-framework/.test-osdk-scorecard-ci.yaml
  test/test-framework/.test-osdk-scorecard-v1alpha1.yaml
  test/test-framework/.test-osdk-scorecard.yaml
  test/test-framework/scorecard/assets/output.json
  test/test-framework/scorecard/assets/test-1.json
  test/test-framework/scorecard/assets/test-2.json
  test/test-framework/scorecard/assets/test-3.json
  test/test-framework/scorecard/assets/test-4.json
  test/test-framework/scorecard/assets/test-5.json
  test/test-framework/scorecard/bin/my-test.sh
  test/test-framework/scorecard/bin/print-json.sh
Labels: lgtm, size/XL

#2439 cmd/operator-sdk: 'olm-catalog gen-csv' -> 'generate csv'
  CHANGELOG.md
  cmd/operator-sdk/alpha/kubebuilder/cmd.go
  cmd/operator-sdk/alpha/kubebuilder/generate/cmd.go
  cmd/operator-sdk/cli/cli.go
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/csv.go
  cmd/operator-sdk/olmcatalog/cmd.go
  doc/cli/operator-sdk.md
  doc/cli/operator-sdk_generate.md
  doc/cli/operator-sdk_generate_crds.md
  doc/cli/operator-sdk_generate_csv.md
  doc/cli/operator-sdk_generate_k8s.md
  doc/cli/operator-sdk_olm-catalog.md
  doc/proposals/cli-ux-phase1.md
  doc/proposals/improve-csv-cli.md
  doc/proposals/kubebuilder-integration.md
  doc/user/olm-catalog/csv-annotations.md
  doc/user/olm-catalog/generating-a-csv.md
Labels: lgtm, olm-catalog, refactoring, size/L

#2438 cmd/operator-sdk: 'alpha bundle build' -> 'bundle create'
  CHANGELOG.md
  cmd/operator-sdk/alpha/cmd.go
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/cli/cli.go
  doc/cli/operator-sdk.md
  doc/cli/operator-sdk_alpha.md
  doc/cli/operator-sdk_bundle.md
  doc/cli/operator-sdk_bundle_create.md
Labels: olm-catalog, refactoring, size/M

#2411 cmd/operator-sdk: add `bundle validate` command
  CHANGELOG.md
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/bundle/validate.go
  doc/cli/operator-sdk_bundle.md
  doc/cli/operator-sdk_bundle_validate.md
  go.mod
  go.sum
  test/test-framework/go.sum
Labels: olm-catalog, size/L

#2447 cmd/operator-sdk: move `olm` out of `alpha`
  CHANGELOG.md
  cmd/operator-sdk/alpha/cmd.go
  cmd/operator-sdk/cli/cli.go
  cmd/operator-sdk/olm/cmd.go
  cmd/operator-sdk/olm/install.go
  cmd/operator-sdk/olm/status.go
  cmd/operator-sdk/olm/uninstall.go
  doc/cli/operator-sdk.md
  doc/cli/operator-sdk_alpha.md
  doc/cli/operator-sdk_alpha_olm.md
  doc/cli/operator-sdk_olm.md
  doc/cli/operator-sdk_olm_install.md
  doc/cli/operator-sdk_olm_status.md
  doc/cli/operator-sdk_olm_uninstall.md
  hack/tests/integration.sh
  hack/tests/subcommand-olm-install.sh
Labels: olm-catalog, refactoring, size/L

#2448 CHANGELOG.md: add 'breaking change' note to several changes
  CHANGELOG.md
Labels: kind/documentation, size/XS

#2455 doc/{ansible,helm}/dev: 'up local' -> 'run --local'
  doc/ansible/dev/developer_guide.md
  doc/helm/dev/developer_guide.md
Labels: kind/documentation, size/S

#2457 Release v0.15.0
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2459 post release v0.15.0 changes
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2460 v0.15.x post release branch setup
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: size/S

#2458 MAINTAINERS,OWNERS: cleanup
  MAINTAINERS
  OWNERS
Labels: lgtm, size/S

#2464 grep -P is not available on osx
  Makefile
Labels: lgtm, size/XS

#2374 Add blacklist option to Ansible watches.yaml
  CHANGELOG.md
  doc/ansible/user-guide.md
  hack/tests/e2e-ansible.sh
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/controllermap/controllermap.go
  pkg/ansible/proxy/inject_owner.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/run.go
  pkg/ansible/watches/watches.go
  test/ansible-memcached/tasks.yml
  test/ansible-memcached/watches-finalizer.yaml
Labels: ansible-operator, lgtm, size/L

#2462 Scorecard remove v1alpha1 part2
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/helpers/helpers.go
  internal/scorecard/helpers/test_definitions.go
  internal/scorecard/interfaces.go
  internal/scorecard/plugins/basic_tests.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/scorecard.go
  internal/scorecard/scorecard_output.go
  pkg/apis/scorecard/formatting.go
  pkg/apis/scorecard/v1alpha1/boilerplate.txt
  pkg/apis/scorecard/v1alpha1/doc.go
  pkg/apis/scorecard/v1alpha1/formatter.go
  pkg/apis/scorecard/v1alpha1/register.go
  pkg/apis/scorecard/v1alpha1/types.go
  pkg/apis/scorecard/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/scorecard/v1v2conversions.go
Labels: size/XL

#2466 internal/scaffold: fix go.mod scaffolds using openshift/api replacement
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  test/test-framework/go.mod
  test/test-framework/go.sum
Labels: lgtm, size/XS

#2471 *: prep for v0.15.1 release
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2472 *: post release updates for v0.15.1
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2474 CHANGELOG.md,doc/user: update for v0.15.1
  CHANGELOG.md
  doc/user/install-operator-sdk.md
Labels: size/XS

#2475 .travis.yml: reduce use of deprecated configs
  .travis.yml
Labels: size/XS

#2478 cmd/operator-sdk: fix run local flags
  CHANGELOG.md
  cmd/operator-sdk/run/local.go
Labels: kind/bug, lgtm, size/XS

#2479 dockerfiles/ansible: bump openshift client to 0.9.2
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  internal/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/XS

#2484 pkg/helm/release/manager_factory.go: lock on kube.New()
  pkg/helm/release/manager_factory.go
Labels: lgtm, size/S

#2483 ci: remove unused directory
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible-e2e.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  ci/dockerfiles/builder.Dockerfile
  ci/dockerfiles/go-e2e.Dockerfile
  ci/dockerfiles/helm-e2e-hybrid.Dockerfile
  ci/dockerfiles/helm-e2e.Dockerfile
  ci/dockerfiles/helm.Dockerfile
  ci/dockerfiles/scorecard-proxy.Dockerfile
  ci/prow.Makefile
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-go.sh
  ci/tests/e2e-helm.sh
  ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-ansible-scaffold.sh
  ci/tests/scaffolding/e2e-go-scaffold.sh
  ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-helm-scaffold.sh
  ci/tests/scaffolding/scorecard-proxy-scaffold.sh
  ci/tests/subcommand-scorecard.sh
  ci/tests/subcommand.sh
Labels: size/XL

#2418 doc: add better info and example over --custom-api-import flag
  cmd/operator-sdk/add/controller.go
  doc/cli/operator-sdk_add_controller.md
Labels: size/M

#2319 log: add option to deactivate zap stack trace generation
  CHANGELOG.md
  doc/user/logging.md
  pkg/log/zap/flags.go
  pkg/log/zap/logger.go
  pkg/log/zap/logger_test.go
Labels: size/L
