Repository operator-framework/operator-sdk, pull requests merged in 2020-06, with the labels that each got.

#3155 docs: fix v1.17 k8s doc links
  website/content/en/docs/ansible/reference/webhooks.md
Labels: kind/documentation, lgtm

#3154 deps: bump api library for CRD validation bugfix
  changelog/fragments/validation-bug-bump-api.yaml
  go.mod
  go.sum
Labels: kind/bug

#3157 cmd/operator-sdk/generate/bundle: validate args before running
  cmd/operator-sdk/generate/bundle/cmd.go
Labels: lgtm

#3125 scorecard new API
  changelog/fragments/scorecard2-newapi-v1alpha3.yaml
  pkg/apis/scorecard/v1alpha3/doc.go
  pkg/apis/scorecard/v1alpha3/formatter.go
  pkg/apis/scorecard/v1alpha3/register.go
  pkg/apis/scorecard/v1alpha3/types.go
  pkg/apis/scorecard/v1alpha3/zz_generated.deepcopy.go
Labels: lgtm

#3177 internal/plugins: remove minor/patch version, add "-alpha"
  go.mod
  go.sum
  internal/generate/testdata/non-standard-layout/PROJECT
  internal/plugins/golang/plugin.go
  website/content/en/docs/kubebuilder/quickstart.md
Labels: lgtm

#3180 Deprecate 'operator-sdk add crd' cmd
  changelog/fragments/deprecate-add-crd.yaml
  cmd/operator-sdk/add/crd.go
  website/content/en/docs/cli/operator-sdk_add.md
  website/content/en/docs/cli/operator-sdk_add_crd.md
Labels: lgtm

#3184 deps: bump operator-registry version
  go.mod
  go.sum
Labels: lgtm

#3188 updates to add message from Paul
  website/assets/scss/_homepage.scss
  website/content/en/build/images/message.png
  website/layouts/index.html
Labels: lgtm

#3189 Build the manager directory package, not the cmdFile directly
  pkg/test/framework.go
Labels: lgtm

#3194 Scorecard2 fix config example
  internal/scorecard/alpha/testdata/bundle.tar.gz
  internal/scorecard/alpha/testdata/bundle/tests/scorecard/config.yaml
Labels: lgtm

#3195 scorecard2 update custom test documentation
  website/content/en/docs/scorecard/custom-tests.md
Labels: lgtm

#3179 *: release v0.18.1
  CHANGELOG.md
  changelog/fragments/3059-fixleader-election-message.yaml
  changelog/fragments/validation-bug-bump-api.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.18.1.md
Labels: lgtm

#2860 plugin: write Makefile recipes for `generate bundle` subcommand
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/cli/legacy.go
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/bundle/bundle_legacy.go
  cmd/operator-sdk/generate/bundle/cmd.go
  internal/generate/clusterserviceversion/bases/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
  internal/generate/olm-catalog/csv.go
  internal/plugins/golang/api.go
  internal/plugins/golang/init.go
  internal/scaffold/kustomize/kustomize.go
  test/e2e-new/e2e_suite.go
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
Labels: kubebuilder-integration, lgtm

#3205 move cmd/operator-sdk/internal/genutil/* -> internal/genutil/*
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/generate/crds.go
  cmd/operator-sdk/generate/k8s.go
  cmd/operator-sdk/new/cmd.go
  internal/genutil/crds.go
  internal/genutil/genutil.go
  internal/genutil/k8s.go
Labels: lgtm

#3207 *: release v0.18.1 (#3179)
  CHANGELOG.md
  changelog/fragments/3059-fixleader-election-message.yaml
  changelog/fragments/validation-bug-bump-api.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.18.1.md
Labels: lgtm

#3202 Versioned doc links
  hack/check-links.sh
  website/config.toml
  website/layouts/partials/navbar-version-selector.html
  website/layouts/partials/navbar.html
Labels: lgtm

#3204 scorecard2 - update travis CI script to build and push the scorecard-test image
  .travis.yml
Labels: lgtm

#3197 *: post-release v0.18.1
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm

#3223 hack/tests/e2e-ansible.sh: remove `-it` flags
  hack/tests/e2e-ansible.sh
Labels: lgtm

#3221 deps: bump operator-registry version
  changelog/fragments/3221-bugfix.yaml
  cmd/operator-sdk/bundle/validate.go
  go.mod
  go.sum
  internal/scorecard/alpha/tests/olm.go
Labels: kind/bug, lgtm

#3220 String error fix
  internal/scorecard/interfaces.go
  pkg/apis/scorecard/v1alpha2/formatter.go
  pkg/apis/scorecard/v1alpha3/formatter.go
Labels: lgtm

#3248 Nest legacy Go docs under new ones
  cmd/operator-sdk/main.go
  internal/util/projutil/project_util.go
  proposals/leader-for-life.md
  website/content/en/build/_index.html
  website/content/en/docs/_index.md
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
  website/content/en/docs/faq.md
  website/content/en/docs/golang/advanced-topics.md
  website/content/en/docs/golang/crds-scope.md
  website/content/en/docs/golang/installation.md
  website/content/en/docs/golang/legacy/_index.md
  website/content/en/docs/golang/legacy/quickstart.md
  website/content/en/docs/golang/new/_index.md
  website/content/en/docs/golang/operator-scope.md
  website/content/en/docs/golang/project_migration_guide.md
  website/content/en/docs/golang/quickstart.md
  website/content/en/docs/golang/references/_index.md
  website/content/en/docs/golang/references/client.md
  website/content/en/docs/golang/references/event-filtering.md
  website/content/en/docs/golang/references/logging.md
  website/content/en/docs/golang/references/markers.md
  website/content/en/docs/golang/webhooks.md
  website/layouts/index.html
Labels: kubebuilder-integration, lgtm

#3239 Helm Plugin - New CMD
  internal/plugins/helm/flags.go
  internal/plugins/helm/init.go
  internal/plugins/helm/plugin.go
Labels: lgtm

#3250 website: Fix misspelled 'PodDsruptionBudget' in the operator capabilities documentation.
  website/content/en/docs/operator-capabilities.md
Labels: lgtm

#3251 cmd/operator-sdk/generate: fix spacing and regenerate CLI docs
  cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  website/content/en/docs/new-cli/operator-sdk_generate.md
  website/content/en/docs/new-cli/operator-sdk_generate_packagemanifests.md
Labels: kind/documentation

#3234 ansible: use correct download URL for tini on aarch64
  changelog/fragments/3234-arm64-tini-url.yaml
  internal/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm

#3241 deprecate git-init flag
  changelog/fragments/gitnit.yaml
  cmd/operator-sdk/new/cmd.go
  website/content/en/docs/cli/operator-sdk_new.md
  website/content/en/docs/new-cli/operator-sdk_new.md
Labels: lgtm

#3249 Remove unused Go operator scaffold code
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
  internal/scaffold/usersetup.go
  internal/scaffold/usersetup_test.go
  internal/scaffold/version.go
  internal/scaffold/version_test.go
Labels: kubebuilder-integration, lgtm

#3224 generate bundle (new CLI): write a `kustomization.yaml`
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/bundle/bundle_legacy.go
  cmd/operator-sdk/generate/bundle/cmd.go
  internal/plugins/golang/init.go
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
Labels: lgtm

#3255 Update CLI reference doc
  website/content/en/docs/new-cli/operator-sdk_generate_bundle.md
Labels: lgtm

#3149 generate: add `packagemanifests` subcommand for legacy project layouts
  changelog/fragments/generate-packagemanifests-legacy.yaml
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/packagemanifests/cmd.go
  cmd/operator-sdk/generate/packagemanifests/packagemanifests_legacy.go
  hack/tests/subcommand-generate-csv.sh
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  website/content/en/docs/cli/operator-sdk_generate.md
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Labels: kind/feature

#3181 internal/plugins: move `go/v2-alpha` to its own package
  cmd/operator-sdk/cli/cli.go
  go.mod
  go.sum
  internal/plugins/golang/v2/api.go
  internal/plugins/golang/v2/config.go
  internal/plugins/golang/v2/init.go
  internal/plugins/golang/v2/plugin.go
  website/content/en/docs/new-cli/operator-sdk_init.md
Labels: lgtm

#3258 generate (new CLI): add `kustomize` subcommand
  changelog/fragments/generate-kustomize.yaml
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/kustomize/cmd.go
  cmd/operator-sdk/generate/kustomize/manifests.go
  website/content/en/docs/new-cli/operator-sdk_generate.md
  website/content/en/docs/new-cli/operator-sdk_generate_kustomize.md
  website/content/en/docs/new-cli/operator-sdk_generate_kustomize_manifests.md
Labels: kind/feature, lgtm

#3254 Add CHANGELOG fragments for new CLI
  changelog/fragments/3190-add-new-cli-for-go-operators.yaml
  changelog/fragments/3190-deprecate-old-cli-for-go-operators.yaml
  changelog/fragments/3190-remove-new-cmd-for-go-operators.yaml
Labels: kubebuilder-integration

#3266 Added missing "other" in quickstart.md
  website/content/en/docs/golang/quickstart.md
Labels: lgtm

#3222 bundle validate: add tool-less image validation
  changelog/fragments/3222-none-tool.yaml
  cmd/operator-sdk/bundle/validate.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: kind/feature, lgtm

#3273 docs: regenerate 'bundle validate' cli docs
  website/content/en/docs/new-cli/operator-sdk_bundle_validate.md
Labels: kind/documentation, lgtm

#3277 Move config options to appropriate section
  website/config.toml
  website/content/en/search.md
Labels: lgtm

#3280 Modify default value of overwrite flag in generate-bundle cmd
  changelog/fragments/modify-overwrite-flag.yaml
  cmd/operator-sdk/generate/bundle/cmd.go
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
  website/content/en/docs/new-cli/operator-sdk_generate_bundle.md
Labels: lgtm

#3282 deps: bump api repo to v0.3.8
  changelog/fragments/validation-bug-bump-api-2.yaml
  go.mod
  go.sum
  internal/scorecard/alpha/tests/olm.go
  internal/scorecard/plugins/olm_tests.go
Labels: kind/bug

#3269 helm: rename status conditional UpdateError to UpgradeError
  changelog/fragments/helm-conditional.yaml
  pkg/helm/controller/reconcile.go
  pkg/helm/internal/types/types.go
Labels: helm-operator, kind/cleanup, lgtm

#3292 *: release v0.17.2
  CHANGELOG.md
  changelog/fragments/3234-arm64-tini-url.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.17.2.md
Labels: lgtm

#3120 [sdk-stamps] add sdk stamps to bundle images
  changelog/fragments/add-sdk-stamps.yaml
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/generate/bundle/bundle.go
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/registry/validate.go
  internal/util/projutil/sdk_stamps_util.go
  internal/util/projutil/sdk_stamps_util_test.go
Labels: lgtm

#3283 initial scorecard2 kuttl user facing doc
  website/content/en/docs/scorecard/kuttl-tests.md
Labels: lgtm

#3312 update test description for scorecard
  website/content/en/docs/scorecard/scorecard-alpha.md
Labels: kind/documentation

#3316 .github/PULL_REQUEST_TEMPLATE.md: add checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm

#3311 doc: add modules step for 0.18.0 migration guide
  website/content/en/docs/migration/v0.18.0.md
Labels: kind/documentation, lgtm

#3313 move helm version from v3.2.0 to v3.2.4
  changelog/fragments/helm-upgrade.yaml
  go.mod
  go.sum
Labels: lgtm
