Repository operator-framework/operator-sdk, pull requests merged in 2020-05, with the labels that each got.

#2932 Uniformly indent log in text output for readability
  pkg/apis/scorecard/v1alpha2/formatter.go
Labels: lgtm

#2929 Add Scorecard2 spec descriptor validation test
  internal/scorecard/alpha/testdata/bundle/manifests/memcached-operator.v0.0.1.clusterserviceversion.yaml
  internal/scorecard/alpha/tests/olm.go
Labels: lgtm

#2957 internal/util/k8sutil: remove old `MatchingFields` helper
  internal/util/k8sutil/options.go
  pkg/ansible/proxy/cache_response.go
Labels: lgtm

#2729 generate csv: support validating and mutating webhooks
  changelog/fragments/2729-addition.yaml
  go.mod
  go.sum
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/manifests/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/webhooks/cache-example-com-v1alpha1-memcached.webhook.yaml
Labels: kind/feature, olm-catalog

#2966 docs/kubebuilder/quickstart: note on changing base runner image
  website/content/en/docs/kubebuilder/quickstart.md
Labels: kind/documentation, kubebuilder-integration

#2964 run --olm: create one ConfigMap per package
  changelog/fragments/2964-bugfix.yaml
  hack/tests/integration.sh
  internal/olm/operator/internal/configmap.go
  internal/olm/operator/internal/deployment.go
  internal/olm/operator/internal/registry.go
  internal/olm/operator/manager.go
  internal/util/k8sutil/k8sutil.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
Labels: kind/bug, lgtm, olm-catalog

#2969 OLM client: correctly get packageserver version
  changelog/fragments/2969-bugfix.yaml
  internal/olm/client/client.go
Labels: kind/bug, olm-catalog

#2971 cleanup:remove test file commited by mistake
  test/mockdata/kb-memcached-operator/go.sum
Labels: lgtm

#2948 feat: allow kb layout works on operator-sdk run local command
  cmd/operator-sdk/run/cmd.go
  cmd/operator-sdk/run/local.go
  internal/util/kubebuilder/constants.go
  internal/util/projutil/project_util.go
Labels: kubebuilder-integration

#2970 fix layout on website
  website/assets/scss/_global.scss
Labels: lgtm

#2975 CONTRIBUTING.md: fix broken hyperlink to the developer docs
  CONTRIBUTING.MD
Labels: lgtm

#2990 deps: bump api and operator-registry to their k8s v1.18 versions
  go.mod
  go.sum
  internal/generate/crd/crd.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/manifests/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/scorecard/alpha/tests/olm.go
  internal/util/k8sutil/api.go
Labels: area/dependency

#2988 Add link checker travis job
  .travis.yml
  Makefile
  cmd/operator-sdk/build/cmd.go
  hack/check-links.sh
  website/content/en/build/_index.html
  website/content/en/docs/ansible/development-tips.md
  website/content/en/docs/ansible/reference/finalizers.md
  website/content/en/docs/ansible/reference/retroactively-owned-resources.md
  website/content/en/docs/cli/operator-sdk_build.md
  website/content/en/docs/contribution-guidelines/local-docs.md
  website/content/en/docs/contribution-guidelines/release.md
  website/content/en/docs/faq.md
  website/content/en/docs/helm/reference/watches.md
  website/content/en/docs/migration/version-upgrade-guide.md
  website/content/en/docs/olm-integration/generating-a-csv.md
  website/content/en/docs/operator-scope.md
Labels: lgtm

#2936 Add healthz liveness probe
  changelog/fragments/1036-ansible-liveness.yaml
  hack/tests/e2e-ansible.sh
  internal/scaffold/ansible/deploy_operator.go
  internal/scaffold/ansible/molecule_templates_operator.go
  pkg/ansible/run.go
  test/ansible/deploy/operator.yaml
  test/ansible/molecule/cluster/tasks/liveness_test.yml
  test/ansible/molecule/templates/operator.yaml.j2
Labels: lgtm

#2992 Fill out some build/ placeholder
  website/content/en/build/_index.html
Labels: lgtm

#2993 remove test cmd in new CLI
  cmd/operator-sdk/cli/cli.go
Labels: lgtm

#2995 docs/olm-integration revert changes from #2989, fix grammar
  website/content/en/docs/olm-integration/generating-a-csv.md
Labels: kind/documentation, lgtm, olm-catalog

#2997 Website: improve spacing and add favicons
  website/assets/scss/_docs.scss
  website/static/favicons/apple-touch-icon-180x180.png
  website/static/favicons/favicon-16x16.png
  website/static/favicons/favicon-32x32.png
  website/static/favicons/favicon.ico
  website/static/favicons/pwa-192x192.png
  website/static/favicons/pwa-512x512.png
  website/static/favicons/tile150x150.png
  website/static/favicons/tile310x150.png
  website/static/favicons/tile310x310.png
  website/static/favicons/tile70x70.png
Labels: lgtm

#3003 Remove old docs check
  hack/check-doc-diffs.sh
  hack/tests/sanity-check.sh
Labels: lgtm

#3008 website/assets/scss/_variables.scss: fix duplicate color
  website/assets/scss/_variables.scss
Labels: lgtm

#3014 generate csv: do not generate a package manifest for bundles
  changelog/fragments/csv-package-manifests-bugfix.yaml
  cmd/operator-sdk/generate/csv.go
Labels: kind/bug

#3007 internal/olm/operator: initial refactoring for `run` changes
  cmd/operator-sdk/cleanup/cmd.go
  cmd/operator-sdk/run/cmd.go
  internal/olm/operator/manager.go
  internal/olm/operator/operator.go
  internal/olm/operator/operator_manager.go
  internal/olm/operator/tenancy.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_run.md
Labels: lgtm, olm-catalog, refactoring

#3015 internal/generate/olm-catalog: read only one manifest at a time
  changelog/fragments/get-csv-manifest-bugfix.yaml
  internal/generate/olm-catalog/csv_util.go
Labels: kind/bug

#3017 olm-integration: fix link to index image docs
  website/content/en/docs/olm-integration/user-guide.md
Labels: kind/documentation

#3018 internal/generate: refactoring for new `generate` commands
  cmd/operator-sdk/test/local.go
  go.mod
  internal/generate/clusterserviceversion/bases/clusterserviceversion.go
  internal/generate/clusterserviceversion/bases/markers.go
  internal/generate/clusterserviceversion/bases/metadata.go
  internal/generate/clusterserviceversion/bases/metadata_test.go
  internal/generate/crd/crd.go
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_go_test.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/olm-catalog/csv_util.go
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.1/memcached-operator.v0.0.1.clusterserviceversion.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.4/memcached-operator.v0.0.4.clusterserviceversion.yaml
  internal/olm/operator/operator_manager.go
  internal/scorecard/plugins/resource_handler.go
  internal/util/k8sutil/api.go
  internal/util/k8sutil/scan.go
  pkg/test/resource_creator.go
Labels: olm-catalog, refactoring

#3021 Add netlify configuration, bump hugo version to 0.70.0
  netlify.toml
Labels: lgtm

#3041 Bump link checker Hugo version
  hack/check-links.sh
Labels: lgtm

#3039 pkg/helm/controller/reconcile.go: finalizer fix
  changelog/fragments/helm-fix-finalizer.yaml
  pkg/helm/controller/controller.go
  pkg/helm/controller/reconcile.go
Labels: lgtm

#3057 cli: remove old scorecard cmd
  cmd/operator-sdk/cli/cli.go
Labels: lgtm

#3009 scorecard (alpha): extract files from a bundle image
  cmd/operator-sdk/alpha/scorecard/cmd.go
  images/scorecard-test/cmd/test/main.go
  internal/scorecard/alpha/bundle_test.go
  internal/scorecard/alpha/registry.go
  internal/scorecard/alpha/scorecard.go
  internal/scorecard/alpha/testdata/bundle.tar.gz
  internal/scorecard/alpha/testdata/bundle/metadata/annotations.yaml
  internal/scorecard/alpha/testpod.go
  internal/scorecard/alpha/tests/bundle_test.go
Labels: kind/feature

#3016 run,cleanup: add `packagemanifests` subcommand, deprecate `--olm`
  cmd/operator-sdk/cleanup/cmd.go
  cmd/operator-sdk/cleanup/packagemanifests.go
  cmd/operator-sdk/cli/cli.go
  cmd/operator-sdk/run/cmd.go
  cmd/operator-sdk/run/packagemanifests.go
  internal/olm/operator/operator_manager.go
  internal/olm/operator/packagemanifests.go
  internal/olm/operator/packagemanifests_manager.go
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_cleanup_packagemanifests.md
  website/content/en/docs/cli/operator-sdk_run.md
  website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
Labels: kind/feature, olm-catalog

#3072 improve pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm

#3067 run: deprecate '--local' flag in favor of 'local' subcommand
  changelog/fragments/run-local.yaml
  cmd/operator-sdk/execentrypoint/ansible.go
  cmd/operator-sdk/execentrypoint/cmd.go
  cmd/operator-sdk/execentrypoint/helm.go
  cmd/operator-sdk/run/cmd.go
  cmd/operator-sdk/run/local/cmd.go
  cmd/operator-sdk/run/local/local.go
  cmd/operator-sdk/run/packagemanifests/packagemanifests.go
  hack/tests/subcommand.sh
  test/e2e/_incluster-test-code/memcached_test.go
  website/content/en/docs/ansible/development-tips.md
  website/content/en/docs/ansible/quickstart.md
  website/content/en/docs/cli/operator-sdk_run.md
  website/content/en/docs/cli/operator-sdk_run_local.md
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
  website/content/en/docs/golang/quickstart.md
  website/content/en/docs/golang/references/logging.md
  website/content/en/docs/helm/quickstart.md
Labels: kind/feature

#3078 README.md: fix a small nit
  README.md
Labels: lgtm

#3063 Scorecard2 user docs
  cmd/operator-sdk/alpha/scorecard/cmd.go
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_alpha.md
  website/content/en/docs/cli/operator-sdk_alpha_scorecard.md
  website/content/en/docs/scorecard/_index.md
  website/content/en/docs/scorecard/scorecard-alpha.md
  website/content/en/docs/scorecard/scorecard.md
Labels: lgtm

#3081 deps: bump api repo version, use bundle types/functions
  go.mod
  go.sum
  hack/tests/subcommand-scorecard.sh
  images/scorecard-test/cmd/test/main.go
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/olm-catalog/package_manifest_test.go
  internal/olm/operator/internal/configmap.go
  internal/olm/operator/internal/registry.go
  internal/olm/operator/olm.go
  internal/olm/operator/packagemanifests_manager.go
  internal/olm/operator/tenancy.go
  internal/scorecard/alpha/tests/basic.go
  internal/scorecard/alpha/tests/bundle_test.go
  internal/scorecard/alpha/tests/crhelper.go
  internal/scorecard/alpha/tests/olm.go
  internal/scorecard/plugins/olm_tests.go
  pkg/scorecard/tests/test_bundle.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
Labels: area/dependency

#3088 generate: add `bundle` subcommand for current project layouts
  changelog/fragments/3088-addition.yaml
  cmd/operator-sdk/generate/bundle/bundle_legacy.go
  cmd/operator-sdk/generate/bundle/cmd.go
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/internal/genutil.go
  hack/tests/subcommand-generate-csv.sh
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  website/content/en/docs/cli/operator-sdk_generate.md
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
Labels: kind/feature

#2982 doc: add operator-scope kb layout
  website/content/en/docs/crds-scope.md
  website/content/en/docs/faq.md
  website/content/en/docs/kubebuilder/crds-scope.md
  website/content/en/docs/kubebuilder/operator-scope.md
  website/content/en/docs/operator-scope.md
  website/content/en/docs/versioning.md
Labels: kind/documentation, kubebuilder-integration

#3107 Scorecard2 test image push
  Makefile
  changelog/fragments/scorecard2-add-image-push.yaml
Labels: lgtm

#3115 *: release v0.17.1 (#3047)
  CHANGELOG.md
  changelog/fragments/2884-fix.yaml
  changelog/fragments/2944-change.yaml
  changelog/fragments/2964-bugfix.yaml
  changelog/fragments/2969-bugfix.yaml
  changelog/fragments/csv-package-manifests-bugfix.yaml
  changelog/fragments/fix-issue-2393.yaml
  changelog/fragments/fix-issue-bug-1701041.yaml
  changelog/fragments/get-csv-manifest-bugfix.yaml
  changelog/fragments/helm-fix-finalizer.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.17.1.md
Labels: lgtm

#3117 *: post release v0.17.1 (#3056)
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm

#3119 bundle validate: update example to force choosing a registry namespace
  cmd/operator-sdk/bundle/validate.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: kind/documentation

#2943 [scorecard] Add Check Spec Tests to SC2 Alpha
  internal/scorecard/alpha/testdata/noSpecBundle/manifests/cache.example.com_memcacheds_crd.yaml
  internal/scorecard/alpha/testdata/noSpecBundle/manifests/memcached-operator.v0.0.1.clusterserviceversion.yaml
  internal/scorecard/alpha/testdata/noSpecBundle/metadata/annotations.yaml
  internal/scorecard/alpha/tests/basic.go
  internal/scorecard/alpha/tests/bundle_test.go
Labels: lgtm

#3118 Makefile: reorganize, update recipes
  Makefile
Labels: lgtm

#3124 bundle create: set default channel if only one channel is set
  changelog/fragments/bundle-default-channel.yaml
  cmd/operator-sdk/bundle/create.go
Labels: lgtm

#3103 Stop attempting to cache all subresources in Ansible Operator proxy
  changelog/fragments/ansible-no-cache-subresources.yaml
  hack/tests/e2e-ansible-molecule.sh
  pkg/ansible/proxy/cache_response.go
  test/ansible/deploy/crds/test.example.com_subresourcestests_crd.yaml
  test/ansible/molecule/cluster/tasks/exec_test.yml
  test/ansible/molecule/cluster/tasks/subresources_test.yml
  test/ansible/molecule/cluster/verify.yml
  test/ansible/playbooks/subresources.yml
  test/ansible/watches.yaml
Labels: lgtm

#3112 Ansible Operator proxy now fails requests when virtual resource can't be determined
  changelog/fragments/ansible-fail-if-cant-determine-vr.yaml
  pkg/ansible/proxy/inject_owner.go
Labels: lgtm

#3113 Add ansible webhook doc to reference section, fix formatting
  website/content/en/docs/ansible/reference/webhooks.md
Labels: lgtm

#3132 deps: bump api to latest version to fix CRD conversion bug
  go.mod
  go.sum
Labels: lgtm

#3129 util: set r/x permissions for bundle dirs
  changelog/fragments/3129.yaml
  cmd/operator-sdk/generate/internal/genutil.go
  internal/generate/internal/genutil.go
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/package_manifest.go
Labels: kind/bug, lgtm

#3121 *: handle both v1 and v1beta1 CRD versions
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/bundle/bundle_legacy.go
  cmd/operator-sdk/generate/internal/genutil.go
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
  internal/generate/collector/collect.go
  internal/generate/collector/filter.go
  internal/generate/crd/crd.go
  internal/generate/crd/crd_test.go
  internal/generate/olm-catalog/csv.go
  internal/scorecard/plugins/olm_tests.go
  internal/util/k8sutil/api.go
  internal/util/k8sutil/manifest.go
  pkg/helm/release/manager.go
Labels: lgtm

#3011 bundle validate: new alpha flag `--output=<text|json-alpha1>` to format results
  changelog/fragments/json-hidden-flag.yaml
  cmd/operator-sdk/bundle/internal/logger.go
  cmd/operator-sdk/bundle/internal/result.go
  cmd/operator-sdk/bundle/internal/result_test.go
  cmd/operator-sdk/bundle/validate.go
Labels: kind/feature, olm-catalog

#3137 docs: update contribution guide formatting and a link
  CONTRIBUTING.MD
  website/content/en/docs/contribution-guidelines/release.md
Labels: kind/documentation

#3140 CHANGELOG.md: add v0.17.1 section and fix PR references
  CHANGELOG.md
Labels: kind/documentation

#3136 docs: move golang API migration doc to golang section
  website/content/en/docs/golang/migrating-existing-apis.md
Labels: kind/documentation

#3097 [scorecard] reformat scorecard olm tests to ginkgo/gomega
  internal/scorecard/alpha/testdata/noSpecBundle/manifests/cache.example.com_memcacheds_crd.yaml
  internal/scorecard/alpha/testdata/noSpecBundle/manifests/memcached-operator.v0.0.1.clusterserviceversion.yaml
  internal/scorecard/alpha/testdata/noSpecBundle/metadata/annotations.yaml
  internal/scorecard/alpha/tests/basic.go
  internal/scorecard/alpha/tests/bundle_test.go
Labels: lgtm

#3145 test/e2e-new: remove utils in favor of upstream utils
  go.mod
  go.sum
  test/e2e-new/e2e_suite.go
  test/e2e-new/utils/kubectl.go
  test/e2e-new/utils/test_context.go
  test/e2e-new/utils/util.go
Labels: lgtm

#3148 bundle generate: ensure default channel exists
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/bundle/bundle_legacy.go
  cmd/operator-sdk/generate/bundle/cmd.go
Labels: kind/bug
