Repository operator-framework/operator-sdk, pull requests merged in 2020-10, with the labels that each got.

#3952 Initial docs for project issue processes
  website/content/en/docs/contribution-guidelines/issue-lifecycle.md
Labels: lgtm

#3972 docs: fix typo in golang/webhooks.md
  website/content/en/docs/building-operators/golang/webhooks.md
Labels: lgtm

#3974 ansible-operator|helm-operator: add the kubernetes auth clients
  changelog/fragments/fix-ansible-helm-auth-providers.yaml
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
Labels: lgtm

#3939 proposals/automating-releases.md: automate the release process
  proposals/automating-releases.md
Labels: lgtm

#3978 cmd/ansible|helm-operator: minor nit improvements
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
Labels: lgtm

#3885 Update advance topics
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: kind/documentation, lgtm

#3977 [v0.19.x] ansible-operator|helm-operator: add the kubernetes auth clients
  changelog/fragments/fix-ansible-helm-auth-providers.yaml
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
Labels: backport, lgtm

#3982 doc: remove very old docs from master
  design/long-term/norms-to-follow.md
  design/long-term/simple-extensions.md
  design/long-term/testing-operators.md
  design/milestone-0.0.2/action-api.md
  design/milestone-0.0.2/query-api.md
  design/milestone-0.2.0/csv-generation.md
Labels: lgtm

#3921 cleanup: scorecard with its own test
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-ansible/e2e_ansible_scorecard_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-go/e2e_go_scorecard_test.go
  test/e2e-go/e2e_go_suite_test.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e-helm/e2e_helm_scorecard_test.go
  test/e2e-helm/e2e_helm_suite_test.go
Labels: kind/cleanup, lgtm, testing

#3993 *: ensure no exported APIs
  hack/generate/changelog/gen-changelog.go
  hack/generate/changelog/internal/util/changelog.go
  hack/generate/changelog/internal/util/changelog_test.go
  hack/generate/changelog/internal/util/fragment.go
  hack/generate/changelog/internal/util/fragment_test.go
  hack/generate/changelog/internal/util/migration_guide.go
  hack/generate/changelog/internal/util/migration_guide_test.go
  hack/generate/changelog/internal/util/testdata/ignore/00-template.yaml
  hack/generate/changelog/internal/util/testdata/ignore/more-fragments/ignored.yaml
  hack/generate/changelog/internal/util/testdata/ignore/non-yaml.txt
  hack/generate/changelog/internal/util/testdata/invalid_entry/fragment1.yaml
  hack/generate/changelog/internal/util/testdata/invalid_yaml/fragment1.yaml
  hack/generate/changelog/internal/util/testdata/valid/fragment1.yaml
  hack/generate/changelog/internal/util/testdata/valid/fragment2.yml
  hack/generate/samples/generate_all.go
  hack/generate/samples/internal/ansible/memcached.go
  hack/generate/samples/internal/helm/memcached.go
  hack/generate/samples/internal/helm/testdata/memcached-0.0.1.tgz
  hack/generate/samples/internal/pkg/context.go
  hack/generate/samples/internal/pkg/utils.go
  hack/tests/sanity-check.sh
  internal/testutils/olm.go
  internal/testutils/scorecard.go
  internal/testutils/utils.go
  test/e2e-ansible/e2e_ansible_cluster_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
  test/e2e-go/e2e_go_suite_test.go
  test/e2e-helm/e2e_helm_cluster_test.go
  test/e2e-helm/e2e_helm_suite_test.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
Labels: lgtm

#3992 update bundle image name in examples to denote this is a bundle image
  website/content/en/docs/olm-integration/quickstart-bundle.md
Labels: lgtm

#3987 Update go version in SDK
  .travis.yml
  go.mod
  release.sh
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/installation/install-operator-sdk.md
Labels: lgtm

#3997 Update docs on Conditions
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: lgtm

#3988 Add fragment for run-bundle.
  changelog/fragments/enable-run-bundle-cmd.yaml
Labels: lgtm

#4005 changelog/fragments/csv-whdescs-defaults.yaml: change to bugfixes, update descriptions
  changelog/fragments/csv-whdescs-defaults.yaml
Labels: lgtm

#3995 doc: update places to direct the users to check the samples in /testdata
  website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/overview/_overview.md
Labels: lgtm

#4014 Ansible: pin community-kubernetes to <1.0.0 in tests to match ansible project scaffold
  hack/tests/e2e-ansible-molecule.sh
  test/ansible/requirements.yml
Labels: area/dependency, kind/bug, kind/failing-test, language/ansible, lgtm

#4017 [v1.0.x]: Change olm version in test script
  hack/tests/subcommand-olm-install.sh
Labels: lgtm

#4022 Add k8s black lives matter statement
  website/assets/scss/_homepage.scss
  website/layouts/index.html
Labels: lgtm

#3908 runbundle: refactor printing deployment/pod errors
  internal/olm/.DS_Store
  internal/olm/client/client.go
  internal/olm/client/client_test.go
Labels: lgtm

#4033 Makefile: run cli-doc generator directly
  Makefile
  hack/generate/cli-doc/gen-cli-doc.sh
  hack/tests/sanity-check.sh
Labels: lgtm

#4031 Release v1.1.0
  CHANGELOG.md
  changelog/fragments/3761.yaml
  changelog/fragments/ansible-gitignore.yaml
  changelog/fragments/ansible-helm-commit-info.yaml
  changelog/fragments/ansible-helm-multigroup.yaml
  changelog/fragments/bump-operator-registry.yaml
  changelog/fragments/bundle-validate-optional-validators.yaml
  changelog/fragments/bundle-validate-verbose.yaml
  changelog/fragments/csv-allnamespaces-default.yaml
  changelog/fragments/csv-whdescs-defaults.yaml
  changelog/fragments/disable_gather_facts.yaml
  changelog/fragments/enable-run-bundle-cmd.yaml
  changelog/fragments/fix-ansible-helm-auth-providers.yaml
  changelog/fragments/fix-run-packagemanifests-e2e.yaml
  changelog/fragments/gen-bundle-namespaced.yaml
  changelog/fragments/helm-gitignore.yaml
  changelog/fragments/helm-install-status-fix.yaml
  changelog/fragments/helm-json-patch-bug.yaml
  changelog/fragments/helm-roles-permissions.yaml
  changelog/fragments/makefile_test.yaml
  changelog/fragments/olm-improve-logs.yaml
  changelog/fragments/operatorgroup-conflict.yaml
  changelog/fragments/relax-csv-name-validation.yaml
  changelog/fragments/rescue-reconciliation.yaml
  changelog/fragments/run-pkgmnfs-writable-dir.yaml
  changelog/fragments/scorecard-kuttl-image-bump-061.yaml
  changelog/fragments/scorecard-kuttl-image-bump.yaml
  changelog/fragments/scorecard-kuttl-version-bump.yaml
  changelog/fragments/scorecard-multiarch-images.yaml
  changelog/fragments/scorecard_scaffolded_version.yaml
  changelog/fragments/sdk-base-image.yaml
  changelog/fragments/socket-cleanup.yaml
  changelog/fragments/store-olm-bindata.yaml
  changelog/fragments/travis-deploy-consolidate.yaml
  website/config.toml
  website/content/en/docs/installation/install-operator-sdk.md
  website/content/en/docs/upgrading-sdk-version/v1.1.0.md
Labels: lgtm

#4051 post-release: update samples tag and fix get sdk version (v1.1.x)
  internal/annotations/metrics/metrics.go
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle.Dockerfile
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/bundle/metadata/annotations.yaml
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/memcached-operator/bundle.Dockerfile
  testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/bundle/metadata/annotations.yaml
  testdata/go/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle.Dockerfile
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/bundle/metadata/annotations.yaml
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
Labels: lgtm

#4055 Revert 1.1.x - Revert metric change. the stamps should have the +git
  internal/annotations/metrics/metrics.go
  testdata/ansible/memcached-operator/bundle.Dockerfile
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/bundle/metadata/annotations.yaml
  testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/bundle.Dockerfile
  testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/bundle/metadata/annotations.yaml
  testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/bundle.Dockerfile
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/bundle/metadata/annotations.yaml
  testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
Labels: lgtm

#4050 post-release: update samples tag
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle.Dockerfile
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/bundle/metadata/annotations.yaml
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/memcached-operator/bundle.Dockerfile
  testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/bundle/metadata/annotations.yaml
  testdata/go/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle.Dockerfile
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/bundle/metadata/annotations.yaml
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
Labels: lgtm

#4049 Post release 1.1
  website/config.toml
Labels: lgtm

#4038 change makefile test target for no longer be required manual steps to…
  changelog/fragments/makefile_test.yaml
  internal/plugins/envtest/init.go
  internal/plugins/golang/v2/init.go
  internal/plugins/manifests/init.go
  website/content/en/docs/building-operators/golang/project_migration_guide.md
  website/content/en/docs/building-operators/golang/quickstart.md
Labels: lgtm

#3996 cleanup e2e: centralize the code to manage the prerequisites
  internal/testutils/utils.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-go/e2e_go_suite_test.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e-helm/e2e_helm_suite_test.go
Labels: kind/cleanup, testing

#4075 fix incorrect build command in installation doc
  website/content/en/docs/installation/install-operator-sdk.md
Labels: lgtm

#4076 docs/advanced-topics/scorecard: pin master links to a commit
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: kind/documentation, lgtm

#4081 Makefile,release/Makefile: remove custom-scorecard-tests from image build/push
  Makefile
  release/Makefile
Labels: lgtm

#4062 upgrade kb and controller-runtime dep version
  changelog/fragments/upgrade-kb.yaml
  go.mod
  go.sum
  testdata/go/memcached-operator/go.mod
  testdata/go/memcached-operator/go.sum
  website/content/en/docs/cli/operator-sdk_init.md
Labels: area/dependency, lgtm

#4086 Auto-generate cncf maintainers file from OWNERS and OWNERS_ALIASES
  .cncf-maintainers
  Makefile
  hack/generate/cncf-maintainers/main.go
Labels: lgtm

#4011 e2e tests: migrate the memcached molecule tests to use the new layout (1.0+) with mock samples stack
  .gitignore
  Makefile
  hack/generate/samples/generate_testdata.go
  hack/generate/samples/internal/ansible/constants.go
  hack/generate/samples/internal/ansible/memcached.go
  hack/generate/samples/internal/ansible/molecule.go
  hack/generate/samples/molecule/generate.go
  hack/tests/e2e-ansible-molecule.sh
  internal/testutils/utils.go
  test/ansible-memcached/OWNERS
  test/ansible-memcached/defaults.yml
  test/ansible-memcached/memcached_test.yml
  test/ansible-memcached/memfin/tasks/main.yml
  test/ansible-memcached/prepare-test-image.yml
  test/ansible-memcached/secret/tasks/main.yml
  test/ansible-memcached/tasks.yml
  test/ansible-memcached/watches-finalizer.yaml
  test/ansible-memcached/watches-foo-kind.yaml
  test/ansible-memcached/watches-v1-kind.yaml
  testdata/ansible/memcached-operator/molecule/default/tasks/memcached_test.yml
  testdata/ansible/memcached-operator/playbooks/memcached.yml
  testdata/ansible/memcached-operator/watches.yaml
Labels: language/ansible, testing

#4089 cleanup: delete catsrc and operatorgroup even if subscription is not found
  changelog/fragments/fix-cleanup.yaml
  internal/cmd/operator-sdk/cleanup/cmd.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/helpers.go
  internal/olm/operator/packagemanifests/install.go
  internal/olm/operator/uninstall.go
Labels: kind/bug, lgtm

#4093 Remove suggestions if status is not present in CR
  internal/scorecard/tests/olm.go
Labels: lgtm

#4107 website: re-point master links to v1.1.x
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/references/client.md
  website/content/en/docs/building-operators/golang/references/logging.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/contribution-guidelines/testing.md
  website/content/en/docs/olm-integration/testing-deployment.md
  website/content/en/docs/overview/_overview.md
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: lgtm

#4105 internal/plugins/helm: scaffold finalizers subresource permission for created APIs
  CHANGELOG.md
  changelog/fragments/fix-helm-finalizers-permissions.yaml
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/rbac/role.yaml
Labels: lgtm

#4118 internal/scorecard/run_test.go: make parallel test more lenient on timing to reduce flakes
  internal/scorecard/run_test.go
Labels: lgtm

#4125 update README link for travis from travis-ci.org to travis-ci.com
  README.md
Labels: lgtm

#4121 Makefile: always build linux binaries when building for an image
  Makefile
Labels: kind/bug, lgtm

#4127 internal/olm: Remove .DS_Store
  internal/olm/.DS_Store
Labels: lgtm

#4126 images/scorecard-test-kuttl: re-add entrypoint script
  .gitignore
  Makefile
  images/ansible-operator/Dockerfile
  images/custom-scorecard-tests/Dockerfile
  images/custom-scorecard-tests/bundle/manifests/cache.example.com_memcacheds_crd.yaml
  images/custom-scorecard-tests/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  images/custom-scorecard-tests/bundle/metadata/annotations.yaml
  images/custom-scorecard-tests/bundle/tests/scorecard/config.yaml
  images/helm-operator/Dockerfile
  images/operator-sdk/Dockerfile
  images/scorecard-test-kuttl/Dockerfile
  images/scorecard-test-kuttl/entrypoint
  images/scorecard-test/Dockerfile
Labels: kind/bug

#4133 ci: use fixed image name when building docker images
  Makefile
  release/Makefile
Labels: lgtm

#4109 Bump operator-framework/api to v0.3.20
  changelog/fragments/upgrade-operator-framework-api.yaml
  go.mod
  go.sum
Labels: lgtm

#4132 Revert doc on operator conditions
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: lgtm

#4138 bump kuttl version to 0.7.1
  images/scorecard-test-kuttl/Dockerfile
Labels: lgtm

#4141 [v1.0.x] fix: modify olm-status-descriptor-test in scorecard
  changelog/fragments/scorecard-status-descriptor-test.yaml
  internal/scorecard/tests/bundle_test.go
  internal/scorecard/tests/olm.go
Labels: lgtm

#4136 go/ansible/helm plugins: use rbac/v1 for metrics reader cluster role
  changelog/fragments/plugins-use-rbac-v1.yaml
  go.mod
  go.sum
  internal/generate/testdata/go/static/basic.operator.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/auth_proxy_client_clusterrole.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/client_cluster_role.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  testdata/ansible/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/go/memcached-operator/bundle/manifests/memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  testdata/go/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  testdata/helm/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
Labels: lgtm

#4137 generate/internal/manifests.go: add all supported kinds to manifests
  changelog/fragments/bundle-pm-supported-kinds.yaml
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/olm/operator/uninstall.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
  testdata/go/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/go/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
  testdata/go/memcached-operator/bundle/manifests/memcached-operator-webhook-service_v1_service.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
  website/content/en/docs/olm-integration/generation.md
Labels: approved, lgtm

#3787 internal/olm/operator: do not suppress the real error
  changelog/fragments/return-olm-install-error.yaml
  internal/olm/client/status.go
  internal/olm/installer/client.go
Labels: approved, lgtm

#4002 [docs] Update doc site to improve navigation
  website/config.toml
  website/layouts/docs/baseof.html
Labels: approved, kind/documentation, lgtm

#4150 Add doc on validation of custom categories
  website/content/en/docs/olm-integration/generation.md
Labels: lgtm
