Repository operator-framework/operator-sdk, pull requests merged in 2020-02, with the labels that each got.

#2417 add unit tests for the Generator
  internal/generate/olm-catalog/package_manifest_test.go
Labels: lgtm, size/M

#2495 internal/generate/olm-catalog/package_manifest_test.go: fix sanity test
  internal/generate/olm-catalog/package_manifest_test.go
Labels: lgtm, size/XS

#1143 Add status conditions helpers
  CHANGELOG.md
  doc/user-guide.md
  pkg/status/conditions.go
  pkg/status/conditions_test.go
Labels: size/L

#2413 enable default lints which were missing
  cmd/operator-sdk/test/local.go
  hack/tests/check-lint.sh
  internal/olm/operator/tenancy.go
  internal/scaffold/entrypoint_test.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scaffold/scaffold.go
  internal/scaffold/usersetup_test.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/scorecard_output.go
  internal/util/k8sutil/k8sutil.go
  pkg/ansible/events/log_events.go
  pkg/ansible/proxy/proxy.go
  pkg/ansible/watches/watches_test.go
  pkg/k8sutil/k8sutil.go
  pkg/kube-metrics/uclient.go
  pkg/tls/tls.go
Labels: lgtm, size/M

#2499 doc/user-guide.md: add godoc link for status conditions
  doc/user-guide.md
Labels: lgtm, size/XS

#2505 scorecard - refactor - remove merging of results, add CR name to output
  hack/tests/subcommand-scorecard.sh
  internal/scorecard/helpers/helpers.go
  internal/scorecard/helpers/test_definitions.go
  internal/scorecard/plugins/basic_tests.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
  pkg/apis/scorecard/v1alpha2/formatter.go
  pkg/apis/scorecard/v1alpha2/types.go
Labels: lgtm, size/L

#2504 doc: add controller runtime faq link to sdk FAQ
  doc/faq.md
Labels: size/XS

#2469 internal/scaffold: don't change /etc/passwd perms
  CHANGELOG.md
  internal/scaffold/ansible/entrypoint.go
  internal/scaffold/ansible/usersetup.go
  internal/scaffold/entrypoint.go
  internal/scaffold/entrypoint_test.go
  internal/scaffold/helm/entrypoint.go
  internal/scaffold/helm/usersetup.go
  internal/scaffold/usersetup.go
  internal/scaffold/usersetup_test.go
Labels: size/M

#2500 doc: ansible.operator-sdk/verbosity become string.
  doc/ansible/dev/advanced_options.md
  doc/ansible/user-guide.md
  test/ansible/deploy/crds/test.example.com_v1alpha1_inventory_cr.yaml
Labels: lgtm, size/XS

#2513 fix broken link regards k8s 1.17 changelog
  doc/proposals/kubernetes-1.17.md
Labels: lgtm, size/XS

#2179 chore(ansible): Create service monitor
  CHANGELOG.md
  hack/lib/common.sh
  hack/tests/e2e-ansible.sh
  pkg/ansible/run.go
  test/ansible/molecule/cluster/prepare.yml
  test/ansible/molecule/cluster/tasks/servicemonitor_test.yml
  test/ansible/molecule/cluster/verify.yml
Labels: ansible-operator, kind/bug, lgtm, ok-to-test, size/L

#2515 fix link k8s 1.17
  doc/proposals/kubernetes-1.17.md
Labels: lgtm, size/XS

#2514 upgrade guide with 0.13 changes
  doc/migration/version-upgrade-guide.md
Labels: size/M

#2523 update test-framework mock data
  test/test-framework/cmd/manager/main.go
  test/test-framework/deploy/crds/cache.example.com_dummys_crd.yaml
  test/test-framework/deploy/crds/cache.example.com_otherdummies_crd.yaml
  test/test-framework/go.sum
Labels: lgtm, size/L

#2524 Updated README.md, so that the quick start guide will require less editing
  README.md
Labels: lgtm, size/S

#2535 fix broken link regards 1.17 changelog
  doc/proposals/kubernetes-1.17.md
Labels: lgtm, size/XS

#2538 internal/scaffold: don't change /etc/passwd perms (#2469)
  CHANGELOG.md
  internal/scaffold/ansible/entrypoint.go
  internal/scaffold/ansible/usersetup.go
  internal/scaffold/entrypoint.go
  internal/scaffold/entrypoint_test.go
  internal/scaffold/helm/entrypoint.go
  internal/scaffold/helm/usersetup.go
  internal/scaffold/usersetup.go
  internal/scaffold/usersetup_test.go
Labels: size/M

#2539 cmd/operator-sdk: fix run local flags (#2478)
  CHANGELOG.md
  cmd/operator-sdk/run/local.go
Labels: size/XS

#2528 remove TestSuite structure
  internal/scorecard/helpers/helpers.go
  internal/scorecard/helpers/test_definitions.go
  internal/scorecard/plugins/basic_tests.go
  internal/scorecard/plugins/labels_test.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
Labels: lgtm, size/L

#2548 rename wachFlags for Flags
  internal/flags/watch/flags.go
  pkg/ansible/flags/flag.go
  pkg/helm/flags/flag.go
Labels: lgtm, size/S

#2521 `generate csv`: add empty `spec.{icon,keywords,maintainers}` for user discovery
  CHANGELOG.md
  internal/scaffold/olm-catalog/csv.go
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
Labels: lgtm, size/S

#2518 fix ci for when just docs were updated
  .travis.yml
Labels: do-not-merge/hold, lgtm, size/S

#2560 revert the PR: #2548
  internal/flags/watch/flags.go
  pkg/ansible/flags/flag.go
  pkg/helm/flags/flag.go
Labels: size/S

#2536 pre-release commit for the patch v0.15.2
  CHANGELOG.md
  doc/user/install-operator-sdk.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2564 Enable all images on ppc64le and s390x
  .travis.yml
  Makefile
  doc/dev/release.md
  hack/image/build-ansible-image.sh
  hack/image/build-scorecard-proxy-image.sh
  internal/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm, size/L

#2516 add migration guide for sdk 0.14
  doc/migration/version-upgrade-guide.md
Labels: size/L

#2563 changelog release 0.15.2
  CHANGELOG.md
  doc/user/install-operator-sdk.md
Labels: lgtm, size/S

#2562 Post release 0.15.2
  CHANGELOG.md
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm, size/S

#2519 doc: add upgrade guide for 0.15+
  doc/migration/version-upgrade-guide.md
Labels: size/M

#2522 Scaffold code in `cmd/manager/main.go` for Go operators and add logic to Ansible/Helm operators to handle [multinamespace caching]
  CHANGELOG.md
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
  pkg/ansible/run.go
  pkg/helm/run.go
  test/test-framework/cmd/manager/main.go
Labels: size/L

#2574 update instructions for building operator-sdk
  doc/dev/developer_guide.md
  doc/user/install-operator-sdk.md
Labels: lgtm, size/XS

#2512 Add skip-cleanup-on-errors option to `test local` command
  CHANGELOG.md
  cmd/operator-sdk/test/local.go
  doc/cli/operator-sdk_test_local.md
  doc/test-framework/writing-e2e-tests.md
  pkg/test/context.go
  pkg/test/framework.go
Labels: lgtm, size/M

#2481 cmd/operator-sdk/run: use Windows binary suffix with '--local'
  CHANGELOG.md
  cmd/operator-sdk/run/local.go
Labels: lgtm, size/XS

#2585 [OWNERS] add varsha prasad narsing
  OWNERS
Labels: lgtm, size/XS

#2580 Add event stats output to the operator logs for Ansible based-operators.
  CHANGELOG.md
  pkg/ansible/controller/reconcile.go
Labels: lgtm, size/S

#2586 Deprecated `inotify-tools` on Ansible based-operator images and remove Ansible sidecar container.
  CHANGELOG.md
  cmd/operator-sdk/migrate/cmd.go
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  doc/migration/version-upgrade-guide.md
  hack/image/ansible/scaffold-ansible-image.go
  hack/tests/e2e-ansible.sh
  internal/scaffold/ansible/ao_logs.go
  internal/scaffold/ansible/deploy_operator.go
  internal/scaffold/ansible/dockerfilehybrid.go
  internal/scaffold/ansible/molecule_templates_operator.go
  test/ansible-memcached/verify.yml
  test/ansible/deploy/operator.yaml
  test/ansible/molecule/templates/operator.yaml.j2
Labels: lgtm, size/L

#2590 add info over how to gen others CR/CRDs for the Ansible operators
  doc/ansible/user-guide.md
Labels: size/XS

#2582 Update instructions for cluster wide resource watching
  doc/operator-scope.md
Labels: size/S

#2589 Improve operator logs by adding the possibility to get the full Ansible logs on it
  CHANGELOG.md
  doc/ansible/dev/developer_guide.md
  doc/ansible/user-guide.md
  pkg/ansible/controller/controller.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/events/log_events.go
  pkg/ansible/run.go
Labels: ansible-operator, kind/feature, lgtm, size/L

#2591 deprecate extensions for scorecard config file
  CHANGELOG.md
  cmd/operator-sdk/scorecard/cmd.go
  doc/cli/operator-sdk_scorecard.md
  doc/test-framework/scorecard.md
Labels: lgtm, size/M

#2541 fix: kclient.Discovery() deprecations
  internal/scaffold/helm/role.go
  internal/scaffold/helm/role_test.go
  pkg/ansible/proxy/proxy.go
  pkg/k8sutil/k8sutil.go
  pkg/kube-metrics/uclient.go
Labels: lgtm, size/M

#2571 doc(release): add osx required notes and a missing step
  doc/dev/release.md
Labels: size/S

#2597 Scorecard finalizer fix
  CHANGELOG.md
  doc/test-framework/scorecard.md
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/resource_handler.go
Labels: kind/bug, lgtm, scorecard, size/M

#2605 typo
  doc/user/client.md
Labels: lgtm, size/XS

#2549 Deprecated test.TestCtx in order to rename test.TestCtx to test.Context
  CHANGELOG.md
  doc/test-framework/writing-e2e-tests.md
  pkg/test/context.go
  pkg/test/context_test.go
  pkg/test/framework.go
  pkg/test/resource_creator.go
  test/e2e/_incluster-test-code/memcached_test.go
  test/e2e/tls_util_test.go
  test/test-framework/test/e2e/memcached_test.go
Labels: lgtm, size/M
