Repository operator-framework/operator-sdk, pull requests merged in 2020-08, with the labels that each got.

#3610 generate: consider service accounts when generating a CSV
  changelog/fragments/fix-csv-role-names.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
  internal/generate/collector/clusterserviceversion.go
  internal/generate/collector/clusterserviceversion_test.go
  internal/generate/collector/collect_test.go
  internal/generate/collector/collector_suite_test.go
  internal/generate/collector/manifests.go
  internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/go/PROJECT
  internal/generate/testdata/go/api/v1alpha1/doc.go
  internal/generate/testdata/go/api/v1alpha1/memcached_types.go
  internal/generate/testdata/go/api/v1alpha2/doc.go
  internal/generate/testdata/go/cmd/manager/main.go
  internal/generate/testdata/go/deploy/crds_v1/cache.example.com_memcachedrs_crd.yaml
  internal/generate/testdata/go/deploy/crds_v1/cache.example.com_memcacheds_crd.yaml
  internal/generate/testdata/go/deploy/crds_v1/cache.example.com_v1alpha1_memcached_cr.yaml
  internal/generate/testdata/go/deploy/crds_v1/cache.example.com_v1alpha1_memcachedrs_cr.yaml
  internal/generate/testdata/go/deploy/crds_v1beta1/cache.example.com_memcachedrs_crd.yaml
  internal/generate/testdata/go/deploy/crds_v1beta1/cache.example.com_memcacheds_crd.yaml
  internal/generate/testdata/go/deploy/crds_v1beta1/cache.example.com_v1alpha1_memcached_cr.yaml
  internal/generate/testdata/go/deploy/crds_v1beta1/cache.example.com_v1alpha1_memcachedrs_cr.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/manifests/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/operator.yaml
  internal/generate/testdata/go/deploy/role.yaml
  internal/generate/testdata/go/deploy/role_binding.yaml
  internal/generate/testdata/go/deploy/service_account.yaml
  internal/generate/testdata/go/deploy/webhooks/cache-example-com-v1alpha1-memcached.webhook.yaml
  internal/generate/testdata/go/emptydir/.keep
  internal/generate/testdata/go/pkg/apis/cache/v1alpha1/dummy_types.go
  internal/generate/testdata/go/pkg/apis/cache/v1alpha1/memcached_types.go
  internal/generate/testdata/go/pkg/apis/cache/v1alpha1/memcachedrs_types.go
  internal/generate/testdata/go/static/basic.operator.yaml
  internal/generate/testdata/non-standard-layout/api/cache/v1alpha1/memcached_types.go
  internal/generate/testdata/non-standard-layout/config/crds-with-core-types/foo.example.com_deployment_crd.yaml
  internal/generate/testdata/non-standard-layout/config/crds-with-core-types/foo.example.com_v1alpha1_deployment_cr.yaml
  internal/generate/testdata/non-standard-layout/config/crds/cache.example.com_memcacheds_crd.yaml
  internal/generate/testdata/non-standard-layout/config/crds/cache.example.com_v1alpha1_memcached_cr.yaml
  internal/generate/testdata/non-standard-layout/config/operator.yaml
  internal/generate/testdata/non-standard-layout/config/role.yaml
  internal/generate/testdata/non-standard-layout/config/role_binding.yaml
  internal/generate/testdata/non-standard-layout/config/service_account.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.1/memcached-operator.v0.0.1.clusterserviceversion.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.4/memcached-operator.v0.0.4.clusterserviceversion.yaml
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/memcached-operator.package.yaml
  internal/generate/testdata/non-standard-layout/main.go
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Labels: kind/bug, lgtm

#3629 *: post-release version reset
  internal/version/version.go
Labels: lgtm

#3634 internal/plugins/manifests: inject operator image using `IMG=<tag>`
  changelog/fragments/inject-operator-image-olm.yaml
  internal/plugins/manifests/init.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e/e2e_suite.go
  test/internal/utils.go
  website/content/en/docs/olm-integration/generation.md
Labels: lgtm

#3643 Bug 1865808: Version informations populating error fix
  Makefile
Labels: bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#3645 internal/plugins: update instead of overwrite samples kustomization
  changelog/fragments/config-samples-kustomize-scaffold.yaml
  internal/plugins/ansible/v1/api.go
  internal/plugins/golang/v2/api.go
  internal/plugins/helm/v1/api.go
  internal/plugins/manifests/api.go
  internal/plugins/manifests/samples.go
Labels: lgtm

#3648 website/content/en/docs/migration/v0.19.0.md: fix migration link
  CHANGELOG.md
  website/content/en/docs/migration/v0.19.0.md
  website/content/en/docs/scorecard/scorecard-alpha.md
Labels: lgtm

#3649 website/content/en/docs/: fix links pointing to master docs site
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/upgrading-sdk-version/v0.19.0.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
Labels: lgtm

#3551 doc: quickstart for Go projects
  website/content/en/docs/building-operators/golang/advanced-topics.md
  website/content/en/docs/building-operators/golang/crds-scope.md
  website/content/en/docs/building-operators/golang/installation.md
  website/content/en/docs/building-operators/golang/operator-scope.md
  website/content/en/docs/building-operators/golang/project_migration_guide.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/references/env-test-setup.md
  website/content/en/docs/building-operators/golang/references/envtest-setup.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/golang/webhooks.md
Labels: go-operator, kind/documentation, lgtm

#3653 go.mod: controller-runtime v0.6.2
  go.mod
  go.sum
Labels: area/dependency, lgtm

#3654 Fix undefined var in scaffolded molecule tests
  internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mdefault/destroy.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mdefault/prepare.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mkind/molecule.go
Labels: lgtm

#3655 internal/plugins/{ansible,helm}: run `CreateAPI` phase 2 plugins in `Init`
  internal/plugins/ansible/v1/init.go
  internal/plugins/helm/v1/init.go
Labels: kind/bug, lgtm

#3657 website: fix old e2e file link
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
Labels: lgtm

#3543 doc: Fix/Update the migration guide for Go projects
  website/content/en/docs/building-operators/golang/project_migration_guide.md
Labels: go-operator, kind/documentation, lgtm

#3651 update go tutorial docs to reflect call to NewManager func
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: lgtm

#3661 Various molecule scaffolding tweaks
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/kustomization.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mdefault/verify.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mkind/destroy.go
Labels: lgtm

#3668 test/integration: use default service account for CSV perms
  test/integration/integration_helpers.go
Labels: lgtm

#3670 [olm] Remove olm-namespace flag from install sub-command
  changelog/fragments/remove-olm-namespace-flag.yaml
  internal/cmd/operator-sdk/olm/install.go
  internal/cmd/operator-sdk/olm/install_test.go
  website/content/en/docs/cli/operator-sdk_olm_install.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
Labels: lgtm

#3697 internal/plugins: scaffold a vanilla `go.kubebuilder.io/v2` project when `--project-version=2`
  changelog/fragments/3-alpha-config.yaml
  internal/plugins/golang/v2/api.go
  internal/plugins/golang/v2/config.go
  internal/plugins/golang/v2/init.go
  internal/plugins/manifests/api.go
  internal/plugins/manifests/init.go
  internal/plugins/scorecard/init.go
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/quickstart-package-manifests.md
Labels: lgtm

#3713 *: release v1.0.0
  CHANGELOG.md
  changelog/fragments/3-alpha-config.yaml
  changelog/fragments/config-samples-kustomize-scaffold.yaml
  changelog/fragments/inject-operator-image-olm.yaml
  changelog/fragments/refactor-cleanup.yaml
  changelog/fragments/remove-olm-namespace-flag.yaml
  changelog/fragments/rm-s390x-builds.yaml
  changelog/fragments/run-pkgman-allnamespaces.yaml
  hack/tests/e2e-ansible-molecule.sh
  internal/version/version.go
  website/config.toml
  website/content/en/docs/contribution-guidelines/release.md
  website/content/en/docs/installation/install-operator-sdk.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
Labels: lgtm

#3717 *: post-release version update
  internal/version/version.go
  website/config.toml
Labels: lgtm

#3718 [v1.0.x]: post-release version bump
  internal/version/version.go
Labels: lgtm

#3652 add kuttl logs into scorecard output when running kuttl tests
  images/scorecard-test-kuttl/cmd/test-kuttl/main.go
Labels: lgtm

#3659 bump kuttl base image version
  changelog/fragments/scorecard-kuttl-image-bump.yaml
  images/scorecard-test-kuttl/Dockerfile
Labels: lgtm

#3685 Narrower Linter to Project NOT Global
  .golangci.yml
  Makefile
  hack/tests/check-lint.sh
Labels: lgtm

#3703 Update `Advanced Topics` conditions with operator-framework/operator-lib
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: lgtm

#3662 Clarify that a role, playbook is necessary for a running operator
  internal/plugins/ansible/v1/api.go
Labels: lgtm

#3650 Adding checks for rescued tasks during reconciliation
  internal/ansible/controller/reconcile.go
  internal/ansible/runner/eventapi/types.go
Labels: lgtm

#3725 fix broken link in ansible quickstart docs
  website/content/en/docs/building-operators/ansible/quickstart.md
Labels: lgtm

#3582 Closes #2502: Specifying a requeue reconciliation period
  internal/ansible/controller/reconcile.go
  test/ansible/deploy/crds/test.example.com_reconciliationtest_crd.yaml
  test/ansible/molecule/cluster/tasks/reconciliation_test.yml
  test/ansible/playbooks/reconciliation.yml
  test/ansible/watches.yaml
Labels: lgtm

#3724 Adding unconvert to Linter
  .golangci.yml
  images/scorecard-test-kuttl/cmd/test-kuttl/main.go
  internal/ansible/proxy/kubeconfig/kubeconfig.go
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/olm/operator/internal/registry_pod.go
  internal/registry/validate.go
Labels: lgtm

#3729 Adding fragment file for PR #3650 (Rescue tasks reconciliation)
  changelog/fragments/rescue-reconciliation.yaml
Labels: lgtm

#3732 fix ansible-operator link to CR sample
  website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
Labels: lgtm

#3721 Removing stale sockets while running Ansible operators
  changelog/fragments/socket-cleanup.yaml
  internal/ansible/runner/eventapi/eventapi.go
Labels: lgtm

#3727 Bug 1856714: Adding checks for rescued tasks during reconciliation
  CHANGELOG.md
  changelog/fragments/rescue-reconciliation.yaml
  cmd/operator-sdk/main.go
  hack/tests/e2e-ansible-molecule.sh
  internal/util/projutil/project_util.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/runner/eventapi/types.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium, lgtm

#3735 fix: (helm) - in some rare helm install cases, status is missing InstallSuccessful
  changelog/fragments/helm-install-status-fix.yaml
  internal/helm/controller/reconcile.go
Labels: lgtm

#3686 Fix main.go path, and desc for zap stacktrace level for logging.md
  website/content/en/docs/building-operators/golang/references/logging.md
Labels: lgtm

#3745 update scorecard custom docs
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: lgtm

#3467 [run bundle] Implement IndexImageCatalogCreator - create grpc catalog source
  internal/operator/internal/index_image.go
  internal/operator/internal/registry_pod.go
  internal/operator/internal/registry_pod_test.go
Labels: lgtm

#3750 docs: fix Go API xDesriptor marker example
  website/content/en/docs/building-operators/golang/references/markers.md
Labels: kind/documentation

#3746 `generate`: support only AllNamespaces by default in CSV bases
  changelog/fragments/csv-allnamespaces-default.yaml
  images/custom-scorecard-tests/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  internal/generate/clusterserviceversion/bases/clusterserviceversion.go
  internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/clusterserviceversions/bases/with-ui-metadata.clusterserviceversion.yaml
  internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
  internal/scorecard/testdata/bundle.tar.gz
  internal/scorecard/testdata/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: lgtm

#3757 doc: fixing minor typos
  website/content/en/docs/building-operators/ansible/tutorial.md
Labels: lgtm

#3751 use kuttl v0.5.2 as the base for scorecard-test-kuttl
  images/scorecard-test-kuttl/Dockerfile
Labels: lgtm

#3734 feat: ansible e2e tests
  hack/tests/e2e-ansible.sh
  test/e2e-ansible/e2e_ansible_cluster_test.go
  test/e2e-ansible/e2e_ansible_local_test.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
Labels: lgtm

#3768 Run scorecard tests in helm e2e tests
  test/e2e-helm/e2e_helm_olm_test.go
Labels: lgtm

#3236 Tweak development tips for Ansible operator
  website/content/en/docs/building-operators/ansible/development-tips.md
Labels: ansible-operator, kind/documentation

#3689 internal/olm/operator: handle conflicting OperatorGroups
  changelog/fragments/operatorgroup-conflict.yaml
  internal/olm/operator/operator_suite_test.go
  internal/olm/operator/packagemanifests_manager.go
  internal/olm/operator/tenancy.go
  internal/olm/operator/tenancy_test.go
Labels: kind/bug, lgtm

#3782 .github/ISSUE_TEMPLATE: update template comments and add language labels
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-question.md
Labels: lgtm

#3764 internal/olm: refactor package `internal/operator` and `run packagemanifests` logic
  internal/cmd/operator-sdk/cleanup/cmd.go
  internal/cmd/operator-sdk/olm/install.go
  internal/cmd/operator-sdk/olm/install_test.go
  internal/cmd/operator-sdk/olm/status.go
  internal/cmd/operator-sdk/olm/status_test.go
  internal/cmd/operator-sdk/olm/uninstall.go
  internal/cmd/operator-sdk/olm/uninstall_test.go
  internal/cmd/operator-sdk/run/bundle/cmd.go
  internal/cmd/operator-sdk/run/cmd.go
  internal/cmd/operator-sdk/run/cmd_test.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_test.go
  internal/olm/client/client.go
  internal/olm/client/status.go
  internal/olm/installer/client.go
  internal/olm/installer/manager.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/config.go
  internal/olm/operator/constants.go
  internal/olm/operator/install_mode.go
  internal/olm/operator/olm.go
  internal/olm/operator/operator_manager.go
  internal/olm/operator/packagemanifests.go
  internal/olm/operator/packagemanifests/install.go
  internal/olm/operator/packagemanifests_manager.go
  internal/olm/operator/registry/catalog.go
  internal/olm/operator/registry/configmap.go
  internal/olm/operator/registry/configmap/configmap.go
  internal/olm/operator/registry/configmap/deployment.go
  internal/olm/operator/registry/configmap/registry.go
  internal/olm/operator/registry/configmap/service.go
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/index_image.go
  internal/olm/operator/registry/olm_resources.go
  internal/olm/operator/registry/operator_installer.go
  internal/olm/operator/registry/operatorgroup_test.go
  internal/olm/operator/registry/registry_suite_test.go
  internal/olm/operator/tenancy.go
  internal/olm/operator/uninstall.go
  internal/operator/internal/operator_installer.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
Labels: lgtm

#3791 fix: use relative path in documentation
  website/content/en/docs/building-operators/ansible/tutorial.md
Labels: lgtm

#3779 Bugfix: Helm operator: add finalizers permission for created APIs
  changelog/fragments/helm-roles-permissions.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
Labels: lgtm

#3802 remove definition of namespace scope from CRD scope section.
  website/content/en/docs/building-operators/golang/crds-scope.md
Labels: lgtm

#3795 Make bundle validate subcommand respect verbosity
  changelog/fragments/bundle-validate-verbose.yaml
  internal/cmd/operator-sdk/bundle/validate.go
  internal/cmd/operator-sdk/bundle/validate_test.go
Labels: lgtm

#3812 v0.19.x: Make bundle validate subcommand respect verbosity (#3795)
  changelog/fragments/bundle-validate-verbose.yaml
  cmd/operator-sdk/bundle/validate.go
  cmd/operator-sdk/bundle/validate_test.go
Labels: lgtm

#3810 cleanup: helm gitignore
  changelog/fragments/helm-gitignore.yaml
  internal/plugins/helm/v1/scaffolds/internal/templates/gitignore.go
Labels: lgtm

#3694 redirect links for webhook to point kubebuilder doc
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/golang/webhooks.md
Labels: lgtm

#3817 release v0.19.3
  CHANGELOG.md
  changelog/fragments/3-alpha-config.yaml
  changelog/fragments/bundle-validate-verbose.yaml
  changelog/fragments/fix-csv-role-names.yaml
  changelog/fragments/fix-cve-2020-14040.yaml
  changelog/fragments/rescue-reconciliation.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.19.3.md
Labels: lgtm

#3806 For Ansible-based Operator, add .gitignore file which was missing.
  changelog/fragments/ansible-gitignore.yaml
  internal/plugins/ansible/v1/scaffolds/init.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/gitignore.go
Labels: kind/feature, language/ansible, lgtm
