Repository operator-framework/operator-sdk, pull requests merged in 2020-07, with the labels that each got.

#3247 add unit tests for cmd/bundle
  cmd/operator-sdk/bundle/bundle_suite_test.go
  cmd/operator-sdk/bundle/cmd_test.go
  cmd/operator-sdk/bundle/create_test.go
  cmd/operator-sdk/bundle/validate.go
  cmd/operator-sdk/bundle/validate_test.go
Labels: lgtm

#3275 Closes #2378: Filtering of watched resources
  changelog/fragments/predicateChanges.yaml
  pkg/ansible/controller/controller.go
  pkg/ansible/run.go
  pkg/ansible/watches/watches.go
  pkg/predicate/predicate.go
  test/ansible/deploy/crds/test.example.com_selectortest_crd.yaml
  test/ansible/molecule/cluster/tasks/selector_test.yml
  test/ansible/playbooks/selector.yml
  test/ansible/watches.yaml
Labels: lgtm

#3319 Migration subcommand deprecation message added
  changelog/fragments/3319-deprecate-migrate-subcommand.yaml
  cmd/operator-sdk/migrate/cmd.go
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_migrate.md
Labels: lgtm

#3012 plug OLM in build guide
  website/content/en/build/_index.html
Labels: lgtm

#3160 doc: Add clarifications to the helm upgrade release force annotation option
  website/content/en/docs/helm/reference/advanced_features.md
Labels: helm-operator, kind/documentation

#3345 feat: condition status conditional UpdateSuccessful was renamed to UpgradeSuccessful
  changelog/fragments/helm-conditional-reason.yaml
  pkg/helm/controller/reconcile.go
  pkg/helm/internal/types/types.go
Labels: helm-operator

#3278 Scorecard2 kuttl image
  .gitignore
  Makefile
  changelog/fragments/3278-add-scorecard-kuttl-image.yaml
  hack/image/build-scorecard-test-kuttl-image.sh
  images/scorecard-test-kuttl/Dockerfile
  images/scorecard-test-kuttl/bin/entrypoint
  images/scorecard-test-kuttl/bin/user_setup
  images/scorecard-test-kuttl/cmd/test-kuttl/main.go
  internal/scorecard/alpha/scorecard.go
  internal/scorecard/alpha/testdata/bundle.tar.gz
  internal/scorecard/alpha/testdata/bundle/tests/scorecard/kuttl/kuttl-test.yaml
  internal/scorecard/alpha/testdata/bundle/tests/scorecard/kuttl/list-pods/00-assert.yaml
  internal/scorecard/alpha/testdata/bundle/tests/scorecard/kuttl/list-pods/00-pod.yaml
  internal/scorecard/alpha/testpod.go
Labels: lgtm

#3270 feat: upgrade lint version and fix gofmt
  hack/tests/check-lint.sh
  internal/plugins/golang/v2/plugin.go
Labels: area/dependency, lgtm

#3091 cmd/operator-sdk/generate/crds.go: check for existence of `pkg/apis`
  changelog/fragments/generate-crds-non-go.yaml
  cmd/operator-sdk/generate/crds.go
Labels: approved, kind/bug, lgtm

#3314 `run packagemanifests`: alias as `run pm`
  changelog/fragments/alias-run-packagemanifests.yaml
  cmd/operator-sdk/run/packagemanifests/packagemanifests.go
Labels: kind/feature, lgtm

#3296 add unit tests for cmd/completion
  cmd/operator-sdk/completion/bash_test.go
  cmd/operator-sdk/completion/cmd_test.go
  cmd/operator-sdk/completion/completion_suite_test.go
  cmd/operator-sdk/completion/zsh_test.go
Labels: lgtm

#3305 feat: add kb scaffold utilities for plugins in internal/kubebuilder
  hack/check-license.sh
  internal/kubebuilder/cmdutil/cmdutil.go
  internal/kubebuilder/filesystem/errors.go
  internal/kubebuilder/filesystem/errors_test.go
  internal/kubebuilder/filesystem/filesystem.go
  internal/kubebuilder/filesystem/filesystem_test.go
  internal/kubebuilder/filesystem/mock.go
  internal/kubebuilder/filesystem/mock_test.go
  internal/kubebuilder/machinery/errors.go
  internal/kubebuilder/machinery/errors_test.go
  internal/kubebuilder/machinery/scaffold.go
  internal/kubebuilder/machinery/scaffold_test.go
Labels: helm-operator, kubebuilder-integration, lgtm

#3342 doc: add migration guide for helm new layout
  website/content/en/docs/helm/migration.md
Labels: helm-operator, kind/documentation, kubebuilder-integration

#3320 docs: OLM integration docs reference new commands (new and legacy CLI)
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/bundle/validate.go
  website/content/en/build/_index.html
  website/content/en/docs/ansible/quickstart.md
  website/content/en/docs/cli/operator-sdk_bundle.md
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/golang/legacy/quickstart.md
  website/content/en/docs/golang/legacy/references/markers.md
  website/content/en/docs/golang/references/markers.md
  website/content/en/docs/helm/quickstart.md
  website/content/en/docs/new-cli/operator-sdk_bundle.md
  website/content/en/docs/new-cli/operator-sdk_bundle_validate.md
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/legacy/_index.md
  website/content/en/docs/olm-integration/legacy/cli-overview.md
  website/content/en/docs/olm-integration/legacy/generating-a-csv.md
  website/content/en/docs/olm-integration/legacy/quickstart-bundle.md
  website/content/en/docs/olm-integration/legacy/quickstart-package-manifests.md
  website/content/en/docs/olm-integration/legacy/testing-deployment.md
  website/content/en/docs/olm-integration/olm-deployment.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/quickstart-package-manifests.md
  website/content/en/docs/olm-integration/testing-deployment.md
  website/content/en/docs/olm-integration/user-guide.md
Labels: kind/documentation

#3359 cmd/operator-sdk/bundle/cmd.go: uncomment previously broken docs link
  cmd/operator-sdk/bundle/cmd.go
  website/content/en/docs/cli/operator-sdk_bundle.md
Labels: kind/documentation

#3062 scorecard (alpha): use bundle labels in pod runner
  cmd/operator-sdk/alpha/scorecard/cmd.go
  cmd/operator-sdk/alpha/scorecard/cmd_test.go
  images/scorecard-test/cmd/test/main.go
  internal/registry/image.go
  internal/registry/labels.go
  internal/registry/validate.go
  internal/scorecard/alpha/bundle.go
  internal/scorecard/alpha/bundle_test.go
  internal/scorecard/alpha/scorecard.go
  internal/scorecard/alpha/tar.go
  internal/scorecard/alpha/testdata/bundle.tar.gz
  internal/scorecard/alpha/testpod.go
  internal/scorecard/alpha/tests/bundle_test.go
  internal/scorecard/alpha/tests/olm.go
Labels: kind/feature

#3363 Makefile,hack/image: build and release targets for helm and ansible binaries
  Makefile
  changelog/fragments/release-helm-ansible-binaries.yaml
  hack/image/build-ansible-image.sh
  hack/image/build-helm-image.sh
  website/content/en/docs/install-operator-sdk.md
Labels: lgtm

#3362 *: remove `lll` linter
  cmd/operator-sdk/add/controller.go
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/csv.go
  cmd/operator-sdk/generate/kustomize/manifests.go
  cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  hack/generate/changelog/util/fragment.go
  hack/tests/check-lint.sh
  hack/tests/scaffolding/scaffold-memcached.go
  internal/generate/collector/collect.go
  internal/generate/crd/crd.go
  internal/generate/crd/crd_test.go
  internal/generate/olm-catalog/descriptor/parse.go
  internal/plugins/golang/v2/init.go
  internal/scaffold/ansible/dockerfilehybrid.go
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/ansible/molecule_cluster_destroy.go
  internal/scaffold/ansible/molecule_cluster_prepare.go
  internal/scaffold/ansible/molecule_cluster_verify.go
  internal/scaffold/ansible/molecule_test_local_converge.go
  internal/scaffold/ansible/molecule_test_local_prepare.go
  internal/scaffold/controller_kind.go
  internal/scaffold/doc.go
  internal/scaffold/entrypoint.go
  internal/scaffold/entrypoint_test.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  internal/scaffold/register.go
  internal/scaffold/role.go
  internal/util/k8sutil/api.go
  pkg/helm/release/manager_test.go
  website/content/en/docs/cli/operator-sdk_add_controller.md
Labels: lgtm

#3352 Scorecard kuttl image
  .travis.yml
Labels: lgtm

#3365 pkg/internal/predicate: refactor DependentPredicate
  pkg/ansible/proxy/proxy.go
  pkg/helm/controller/controller.go
  pkg/internal/predicate/dependent.go
  pkg/internal/predicates/predicates.go
Labels: lgtm

#3369 bump kuttl version, handle a kuttl report file name change with the n…
  changelog/fragments/scorecard2-bump-kuttl.yaml
  images/scorecard-test-kuttl/Dockerfile
  images/scorecard-test-kuttl/cmd/test-kuttl/main.go
  website/content/en/docs/scorecard/kuttl-tests.md
Labels: lgtm

#3380 *: post release v0.19.0
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm

#3381 [v0.19.x] *: post release v0.19.0
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/config.toml
Labels: lgtm

#3302 docs: Added the selector feature to docs
  website/content/en/docs/ansible/reference/watches.md
Labels: lgtm

#3330 feat: allow know the project type by the config file
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/internal/genutil.go
  cmd/operator-sdk/generate/kustomize/manifests.go
  cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/util/projutil/project_util.go
Labels: ansible-operator, helm-operator, kubebuilder-integration

#3395 Fix invalid migration link
  cmd/operator-sdk/main.go
Labels: lgtm

#3392 Indicate that latest release is currently v0.19
  website/config.toml
Labels: lgtm

#3401 Fix typos in migration guide
  website/content/en/docs/golang/project_migration_guide.md
Labels: lgtm

#3403 docs: fix go version
  website/content/en/docs/golang/installation.md
  website/content/en/docs/golang/project_migration_guide.md
Labels: kind/documentation, lgtm

#3405 docs: add link in project migration guide
  website/content/en/docs/golang/project_migration_guide.md
Labels: kind/documentation

#3349 cleanup: keeping sdk scaffolds centralized
  internal/plugins/golang/v2/api.go
  internal/plugins/golang/v2/init.go
  internal/util/plugins/makefile.go
  internal/util/plugins/samples.go
Labels: lgtm

#3404 helm/doc:replace the word update to upgrade in the info log
  website/content/en/docs/helm/reference/advanced_features.md
Labels: lgtm

#3388 helm-operator: use "Upgrade" instead of "Update" in var/fn names
  pkg/helm/controller/reconcile.go
  pkg/helm/release/manager.go
Labels: lgtm

#3408 internal/registry/labels.go: FindMetadataDir fix
  changelog/fragments/fix-find-metadata-dir.yaml
  internal/registry/labels.go
Labels: lgtm

#3412 changelog: add test framework removal fragment
  changelog/fragments/remove-test-framework.yaml
Labels: lgtm

#3416 changelog/fragments: add rm-legacy-go.yaml and rm-legacy-run.yaml
  changelog/fragments/rm-legacy-go.yaml
  changelog/fragments/rm-legacy-run.yaml
Labels: lgtm

#3337 [run bundle]: Create bundle registry server
  internal/olm/operator/internal/registry_pod.go
  internal/olm/operator/internal/registry_pod_test.go
Labels: lgtm

#3425 Removing escape characters in the operator-sdk binary build
  Makefile
Labels: lgtm

#3415 cmd/ansible-operator,cmd/helm-operator: embed code in main.go
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
  internal/flags/watch/flags.go
  pkg/ansible/flags/flag.go
  pkg/ansible/run.go
  pkg/helm/flags/flag.go
  pkg/helm/run.go
Labels: lgtm

#3428 scorecard: fix label permission bug
  changelog/fragments/scorecard-label-perms.yaml
  internal/scorecard/alpha/tar.go
Labels: lgtm

#3430 Trivial - use consts rather than literals for env vars
  pkg/ansible/watches/watches.go
Labels: lgtm

#3383 contrib: update release guide with helm/ansible operator and website info
  website/content/en/docs/contribution-guidelines/backport-policy.md
  website/content/en/docs/contribution-guidelines/release.md
Labels: kind/documentation

#3384 doc: add extra info over ansible watches and reconcile period
  website/content/en/docs/ansible/development-tips.md
  website/content/en/docs/ansible/reference/watches.md
Labels: lgtm

#3432 website,example: remove legacy docs and fixup links
  example/kb-memcached-operator/memcached_controller.go.tmpl
  example/memcached-operator/memcached_controller.go.tmpl
  hack/check-links.sh
  website/content/en/docs/ansible/quickstart.md
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
  website/content/en/docs/faq.md
  website/content/en/docs/golang/legacy/_index.md
  website/content/en/docs/golang/legacy/migrating-existing-apis.md
  website/content/en/docs/golang/legacy/monitoring/_index.md
  website/content/en/docs/golang/legacy/monitoring/prometheus.md
  website/content/en/docs/golang/legacy/monitoring/service-monitor.md
  website/content/en/docs/golang/legacy/quickstart.md
  website/content/en/docs/golang/legacy/references/_index.md
  website/content/en/docs/golang/legacy/references/client.md
  website/content/en/docs/golang/legacy/references/event-filtering.md
  website/content/en/docs/golang/legacy/references/logging.md
  website/content/en/docs/golang/legacy/references/markers.md
  website/content/en/docs/golang/legacy/references/project-layout.md
  website/content/en/docs/golang/legacy/unit-testing.md
  website/content/en/docs/golang/quickstart.md
  website/content/en/docs/helm/quickstart.md
  website/content/en/docs/legacy-common/crds-scope.md
  website/content/en/docs/legacy-common/operator-scope.md
  website/content/en/docs/migration/v0.1.0-migration-guide.md
  website/content/en/docs/migration/version-upgrade-guide.md
  website/content/en/docs/olm-integration/legacy/_index.md
  website/content/en/docs/olm-integration/legacy/cli-overview.md
  website/content/en/docs/olm-integration/legacy/generating-a-csv.md
  website/content/en/docs/olm-integration/legacy/quickstart-bundle.md
  website/content/en/docs/olm-integration/legacy/quickstart-package-manifests.md
  website/content/en/docs/olm-integration/legacy/testing-deployment.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/scorecard/scorecard.md
Labels: kind/documentation, lgtm

#3434 internal/scorecard/alpha: add parallelism support
  changelog/fragments/scorecard-parallel.yaml
  internal/registry/labels.go
  internal/scorecard/alpha/config.go
  internal/scorecard/alpha/examples/custom-scorecard-tests/bundle/tests/scorecard/config.yaml
  internal/scorecard/alpha/formatting.go
  internal/scorecard/alpha/labels_test.go
  internal/scorecard/alpha/run_test.go
  internal/scorecard/alpha/scorecard.go
  internal/scorecard/alpha/testdata/bundle.tar.gz
  internal/scorecard/alpha/testdata/bundle/tests/scorecard/config.yaml
  website/content/en/docs/scorecard/custom-tests.md
  website/content/en/docs/scorecard/kuttl-tests.md
  website/content/en/docs/scorecard/scorecard-alpha.md
Labels: lgtm

#3442 website/content/en/docs/golang/project_migration_guide.md: fix broken link
  website/content/en/docs/golang/project_migration_guide.md
  website/content/en/docs/golang/references/logging.md
Labels: lgtm

#3444 Scorecard move alpha
  changelog/fragments/scorecard-move-alpha.yaml
  cmd/operator-sdk/alpha/alpha_suite_test.go
  cmd/operator-sdk/alpha/cmd.go
  cmd/operator-sdk/alpha/cmd_test.go
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/cli/cli.go
  cmd/operator-sdk/cli/legacy.go
  cmd/operator-sdk/scorecard/cmd.go
  cmd/operator-sdk/scorecard/cmd_test.go
  cmd/operator-sdk/scorecard/scorecard_suite_test.go
  images/scorecard-test/cmd/test/main.go
  internal/scorecard/bundle.go
  internal/scorecard/bundle_test.go
  internal/scorecard/config.go
  internal/scorecard/config_test.go
  internal/scorecard/examples/custom-scorecard-tests/Makefile
  internal/scorecard/examples/custom-scorecard-tests/bundle/manifests/cache.example.com_memcacheds_crd.yaml
  internal/scorecard/examples/custom-scorecard-tests/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  internal/scorecard/examples/custom-scorecard-tests/bundle/metadata/annotations.yaml
  internal/scorecard/examples/custom-scorecard-tests/bundle/tests/scorecard/config.yaml
  internal/scorecard/examples/custom-scorecard-tests/go.mod
  internal/scorecard/examples/custom-scorecard-tests/images/custom-scorecard-tests/Dockerfile
  internal/scorecard/examples/custom-scorecard-tests/images/custom-scorecard-tests/bin/entrypoint
  internal/scorecard/examples/custom-scorecard-tests/images/custom-scorecard-tests/bin/user_setup
  internal/scorecard/examples/custom-scorecard-tests/images/custom-scorecard-tests/cmd/test/main.go
  internal/scorecard/examples/custom-scorecard-tests/internal/tests/tests.go
  internal/scorecard/formatting.go
  internal/scorecard/formatting_test.go
  internal/scorecard/kubeclient.go
  internal/scorecard/labels_test.go
  internal/scorecard/run_test.go
  internal/scorecard/scorecard.go
  internal/scorecard/tar.go
  internal/scorecard/testconfigmap.go
  internal/scorecard/testdata/bundle.tar.gz
  internal/scorecard/testdata/bundle/manifests/cache.example.com_memcacheds_crd.yaml
  internal/scorecard/testdata/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  internal/scorecard/testdata/bundle/metadata/annotations.yaml
  internal/scorecard/testdata/bundle/tests/scorecard/config.yaml
  internal/scorecard/testdata/bundle/tests/scorecard/kuttl/kuttl-test.yaml
  internal/scorecard/testdata/bundle/tests/scorecard/kuttl/list-pods/00-assert.yaml
  internal/scorecard/testdata/bundle/tests/scorecard/kuttl/list-pods/00-pod.yaml
  internal/scorecard/testdata/pod.yaml
  internal/scorecard/testpod.go
  internal/scorecard/tests/basic.go
  internal/scorecard/tests/bundle_test.go
  internal/scorecard/tests/crhelper.go
  internal/scorecard/tests/olm.go
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_alpha.md
  website/content/en/docs/cli/operator-sdk_scorecard.md
  website/content/en/docs/new-cli/operator-sdk.md
  website/content/en/docs/new-cli/operator-sdk_alpha.md
  website/content/en/docs/new-cli/operator-sdk_scorecard.md
  website/content/en/docs/scorecard/custom-tests.md
  website/content/en/docs/scorecard/kuttl-tests.md
  website/content/en/docs/scorecard/scorecard.md
Labels: lgtm

#3449 update scorecard doc links
  website/content/en/docs/scorecard/custom-tests.md
  website/content/en/docs/scorecard/scorecard.md
Labels: lgtm

#3436 Add new handler for metrics
  changelog/fragments/enqueue-object-handler.yml
  pkg/ansible/controller/controller.go
  pkg/handler/instrumented_enqueue_object.go
  pkg/handler/internal/metrics/metrics.go
  pkg/helm/controller/controller.go
Labels: ansible-operator, helm-operator, kind/feature, lgtm

#3414 Remove legacy generate and bundle commands
  changelog/fragments/rm-legacy-bundle-cmds.yaml
  changelog/fragments/rm-legacy-gen-bundle.yaml
  changelog/fragments/rm-legacy-gen-csv.yaml
  changelog/fragments/rm-legacy-gen-packagemanifests.yaml
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/bundle/cmd_test.go
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/bundle/create_test.go
  cmd/operator-sdk/bundle/validate.go
  cmd/operator-sdk/cli/legacy.go
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/csv.go
  cmd/operator-sdk/generate/packagemanifests/cmd.go
  cmd/operator-sdk/generate/packagemanifests/packagemanifests_legacy.go
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_go_test.go
  internal/generate/olm-catalog/csv_util.go
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/olm-catalog/package_manifest_test.go
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_bundle.md
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/cli/operator-sdk_generate.md
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Labels: lgtm

#3446 Helm: add leader election flags, use lease-based election
  changelog/fragments/helm-leader-election.yaml
  cmd/helm-operator/main.go
  hack/tests/e2e-helm.sh
  internal/plugins/helm/v1/scaffolds/init.go
  internal/plugins/helm/v1/scaffolds/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/templates/manager/config.go
  internal/plugins/helm/v1/scaffolds/templates/metricsauth/auth_proxy_patch.go
  pkg/helm/flags/flag.go
Labels: lgtm

#3413 add unit tests for cmd/run
  cmd/operator-sdk/run/cmd_test.go
  cmd/operator-sdk/run/packagemanifests/packagemanifests.go
  cmd/operator-sdk/run/packagemanifests/packagemanifests_suite_test.go
  cmd/operator-sdk/run/packagemanifests/packagemanifests_test.go
  cmd/operator-sdk/run/run_suite_test.go
Labels: lgtm

#3451 Remove metrics logic from cmd/helm-operator/main.go
  changelog/fragments/rm-helm-metrics.yml
  cmd/helm-operator/main.go
  hack/tests/e2e-helm.sh
  internal/plugins/helm/v1/scaffolds/templates/manager/config.go
Labels: lgtm

#3453 .gitignore: ignore scorecard example go.sum
  .gitignore
Labels: lgtm

#3454 Add unit tests for cmd/version
  cmd/operator-sdk/version/cmd.go
  cmd/operator-sdk/version/cmd_test.go
  cmd/operator-sdk/version/version_suite_test.go
Labels: lgtm

#3326 docs: update helm docs for the new layout
  CHANGELOG.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/reference/advanced_features.md
  website/content/en/docs/building-operators/helm/reference/scaffolding.md
  website/content/en/docs/building-operators/helm/reference/watches.md
  website/content/en/docs/upgrading-sdk-version/v0.19.0.md
Labels: helm-operator, kind/documentation, kubebuilder-integration

#3456 fix: remove max-workers flag for ansible
  cmd/ansible-operator/main.go
  pkg/ansible/flags/flag.go
Labels: lgtm

#3452 ansible/helm: Rename max-workers to max-concurrent-reconciles
  changelog/fragments/rename-max-workers.yaml
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
  pkg/ansible/controller/controller.go
  pkg/ansible/watches/testdata/valid.yaml.tmpl
  pkg/ansible/watches/watches.go
  pkg/ansible/watches/watches_test.go
  pkg/helm/controller/controller.go
  pkg/helm/flags/flag.go
  website/content/en/docs/building-operators/helm/reference/advanced_features.md
Labels: lgtm

#3464 internal/plugins/helm/v1/scaffolds/templates/role.go: remove metrics rules
  internal/plugins/helm/v1/scaffolds/templates/role.go
Labels: lgtm

#3465 internal/scaffold/role_test.go: make tests execute properly
  internal/scaffold/role_test.go
Labels: lgtm

#3455 *: remove legacy CLI docs
  hack/generate/cli-doc/gen-cli-doc.go
  proposals/ansible-helm-addapi.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/golang/references/markers.md
  website/content/en/docs/cli/_index.md
  website/content/en/docs/cli/ansible-helm/_index.md
  website/content/en/docs/cli/ansible-helm/operator-sdk.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_add.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_add_api.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_build.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_completion.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_completion_bash.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_completion_zsh.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_new.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_olm.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_olm_install.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_olm_status.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_olm_uninstall.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_scorecard.md
  website/content/en/docs/cli/ansible-helm/operator-sdk_version.md
  website/content/en/docs/cli/golang/_index.md
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_build.md
  website/content/en/docs/cli/operator-sdk_bundle.md
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_cleanup_packagemanifests.md
  website/content/en/docs/cli/operator-sdk_completion.md
  website/content/en/docs/cli/operator-sdk_completion_bash.md
  website/content/en/docs/cli/operator-sdk_completion_zsh.md
  website/content/en/docs/cli/operator-sdk_create.md
  website/content/en/docs/cli/operator-sdk_create_api.md
  website/content/en/docs/cli/operator-sdk_create_webhook.md
  website/content/en/docs/cli/operator-sdk_generate.md
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
  website/content/en/docs/cli/operator-sdk_generate_kustomize.md
  website/content/en/docs/cli/operator-sdk_generate_kustomize_manifests.md
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
  website/content/en/docs/cli/operator-sdk_init.md
  website/content/en/docs/cli/operator-sdk_new.md
  website/content/en/docs/cli/operator-sdk_olm.md
  website/content/en/docs/cli/operator-sdk_olm_install.md
  website/content/en/docs/cli/operator-sdk_olm_status.md
  website/content/en/docs/cli/operator-sdk_olm_uninstall.md
  website/content/en/docs/cli/operator-sdk_run.md
  website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
  website/content/en/docs/cli/operator-sdk_scorecard.md
  website/content/en/docs/cli/operator-sdk_version.md
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/generation.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/quickstart-package-manifests.md
  website/content/en/docs/olm-integration/testing-deployment.md
Labels: kind/documentation, lgtm

#3472 gen-changelog: use yaml extension for fragments
  changelog/fragments/ansible-operator-optional-case.yaml
  changelog/fragments/enqueue-object-handler.yaml
  changelog/fragments/rm-helm-metrics.yaml
Labels: lgtm

#3473 helm: migrate tests for the new layout
  internal/plugins/helm/v1/scaffolds/templates/role.go
  internal/plugins/helm/v1/scaffolds/templates/role_test.go
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/invalid_role/config/rbac/role.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_clusterrole/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role1/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role2/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role3/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role4/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role5/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role6/mergedRole.yaml
Labels: lgtm

#3343 removal: helm legacy scaffold
  changelog/fragments/cmd-legacy-helm.yaml
  changelog/fragments/remove-legacy-helm.yaml
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/new/cmd.go
  go.mod
  internal/flags/apiflags/flags.go
  internal/flags/apiflags/flags_test.go
  internal/scaffold/helm/api.go
  internal/scaffold/helm/chart.go
  internal/scaffold/helm/chart_test.go
  internal/scaffold/helm/dockerfile.go
  internal/scaffold/helm/init.go
  internal/scaffold/helm/operator.go
  internal/scaffold/helm/role.go
  internal/scaffold/helm/role_test.go
  internal/scaffold/helm/testdata/testcharts/test-chart-1.2.0.tgz
  internal/scaffold/helm/testdata/testcharts/test-chart-1.2.3.tgz
  internal/scaffold/helm/testdata/testcharts/test-chart/.helmignore
  internal/scaffold/helm/testdata/testcharts/test-chart/Chart.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/NOTES.txt
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/_helpers.tpl
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/deployment.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/ingress.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/service.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/serviceaccount.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/templates/tests/test-connection.yaml
  internal/scaffold/helm/testdata/testcharts/test-chart/values.yaml
  internal/scaffold/role_test.go
  internal/scaffold/testdata/testroles/invalid_role/deploy/role.yaml
  internal/scaffold/testdata/testroles/valid_clusterrole/mergedRole.yaml
  internal/scaffold/testdata/testroles/valid_role1/mergedRole.yaml
  internal/scaffold/testdata/testroles/valid_role2/mergedRole.yaml
  internal/scaffold/testdata/testroles/valid_role3/mergedRole.yaml
  internal/scaffold/testdata/testroles/valid_role4/mergedRole.yaml
  internal/scaffold/testdata/testroles/valid_role5/mergedRole.yaml
  internal/scaffold/testdata/testroles/valid_role6/mergedRole.yaml
  internal/util/projutil/project_util.go
  pkg/helm/watches/watches.go
  pkg/helm/watches/watches_test.go
  website/content/en/docs/cli/operator-sdk_new.md
Labels: helm-operator, kubebuilder-integration, lgtm

#3476 Remove pkg/ready
  changelog/rm-pkg-ready.yaml
  pkg/ready/ready.go
  pkg/ready/ready_test.go
Labels: lgtm

#3482 internal/plugins/helm/v1/scaffolds/templates/role.go: simplify updates
  go.mod
  go.sum
  internal/plugins/helm/v1/scaffolds/api.go
  internal/plugins/helm/v1/scaffolds/templates/role.go
  internal/plugins/helm/v1/scaffolds/templates/role_test.go
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/invalid_role/config/rbac/role.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_clusterrole/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role1/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role2/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role3/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role4/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role5/mergedRole.yaml
  internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role6/mergedRole.yaml
Labels: lgtm

#3483 cmd/operator-sdk/generate: remove unused legacy code
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/bundle/bundle_legacy.go
  cmd/operator-sdk/generate/bundle/cmd.go
  cmd/operator-sdk/generate/packagemanifests/cmd.go
Labels: lgtm

#3478 scorecard - lookup namespace from kubeconfig
  changelog/fragments/scorecard-default-ns.yaml
  cmd/operator-sdk/scorecard/cmd.go
  cmd/operator-sdk/scorecard/cmd_test.go
  internal/scorecard/kubeclient.go
  internal/scorecard/kubeclient_test.go
  website/content/en/docs/cli/operator-sdk_scorecard.md
Labels: lgtm

#3474 scorecard: add bundle metadata
  changelog/fragments/scorecard-bundle-metadata.yaml
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/bundle/cmd.go
  cmd/operator-sdk/scorecard/cmd.go
  internal/annotations/metrics/metrics.go
  internal/annotations/metrics/metrics_test.go
  internal/annotations/scorecard/scorecard.go
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/registry/labels.go
  internal/scorecard/config.go
  internal/scorecard/examples/custom-scorecard-tests/bundle/metadata/annotations.yaml
  internal/scorecard/testdata/bundle.tar.gz
  internal/scorecard/testdata/bundle/metadata/annotations.yaml
  internal/util/projutil/project_util.go
  internal/util/projutil/projutil_test.go
  internal/util/projutil/sdk_stamps_util.go
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
Labels: kind/feature

#3423 helm:replace test in shell for go
  hack/tests/e2e-helm.sh
  internal/plugins/helm/v1/scaffolds/templates/makefile.go
  test/e2e-helm/e2e_helm_cluster_test.go
  test/e2e-helm/e2e_helm_local_test.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e-helm/e2e_helm_suite_test.go
  test/e2e/e2e_suite.go
  test/internal/utils.go
Labels: helm-operator, kind/cleanup, kubebuilder-integration

#3484 Remove pkg/metrics and pkg/kube-metrics
  changelog/fragments/rm-pkg-kube-metrics.yaml
  changelog/fragments/rm-pkg-metrics.yaml
  go.mod
  go.sum
  pkg/kube-metrics/metrics.go
  pkg/kube-metrics/server.go
  pkg/kube-metrics/store.go
  pkg/kube-metrics/uclient.go
  pkg/metrics/metrics.go
  pkg/metrics/service-monitor.go
Labels: lgtm

#3489 Add Ansible metrics address flag
  changelog/fragments/ansible-metrics-addr.yml
  cmd/ansible-operator/main.go
  pkg/ansible/flags/flag.go
Labels: lgtm

#3493 allow fragments to end in either .yml or .yaml
  hack/generate/changelog/util/fragment.go
  hack/generate/changelog/util/testdata/valid/fragment2.yml
Labels: lgtm

#3496 changelog: move fragment to correct dir
  changelog/fragments/rm-pkg-ready.yaml
Labels: lgtm

#3497 fix: reword changelog fragment for renaming flag
  changelog/fragments/modify-ansible-flags.yaml
Labels: lgtm

#3495 update scorecard docs to be consistent in command examples
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/kuttl-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: lgtm

#3490 scorecard: make config a componentconfig, scaffold config kustomization on `init`
  changelog/fragments/scorecard-config-scaffold.yaml
  cmd/operator-sdk/generate/bundle/bundle.go
  cmd/operator-sdk/generate/kustomize/manifests.go
  internal/generate/collector/collect.go
  internal/plugins/golang/v2/init.go
  internal/plugins/helm/v1/init.go
  internal/plugins/scorecard/init.go
  internal/scorecard/config.go
  internal/scorecard/examples/custom-scorecard-tests/bundle/tests/scorecard/config.yaml
  internal/scorecard/formatting.go
  internal/scorecard/labels_test.go
  internal/scorecard/run_test.go
  internal/scorecard/scorecard.go
  internal/scorecard/testdata/bundle.tar.gz
  internal/scorecard/testdata/bundle/tests/scorecard/config.yaml
  internal/scorecard/testpod.go
  pkg/apis/scorecard/v1alpha3/configuration_types.go
  pkg/apis/scorecard/v1alpha3/test_types.go
  pkg/apis/scorecard/v1alpha3/zz_generated.deepcopy.go
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: kind/feature

#3504 website: fix scorecard links
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: lgtm

#3503 Remove leader and status which have moved to operator-lib.
  changelog/fragments/rm-pkg-leader-and-status.yaml
  pkg/leader/doc.go
  pkg/leader/leader.go
  pkg/status/conditions.go
  pkg/status/conditions_test.go
Labels: lgtm

#3501 website: Fix link to the pull requests that implements support for configuring a liveness probe for an Ansible operator.
  website/content/en/docs/upgrading-sdk-version/v0.18.0.md
Labels: lgtm

#3519 Fix quick start link 0.19
  CHANGELOG.md
  website/content/en/docs/golang/quickstart.md
Labels: lgtm

#3516 doc: apply small fixes perform on master on to the migration guide (0.19)
  website/content/en/docs/golang/project_migration_guide.md
  website/content/en/docs/migration/v0.19.0.md
Labels: kind/documentation, lgtm

#3509 cmd/operator-sdk/generate/packagemanifests: add `--from-version` flag
  changelog/fragments/packagemanifests-from-version.yaml
  cmd/operator-sdk/generate/internal/genutil.go
  cmd/operator-sdk/generate/packagemanifests/cmd.go
  cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
  website/content/en/docs/olm-integration/generation.md
Labels: lgtm

#3520 website: Fix link to the pull requests that implements support for configuring a liveness probe for an Ansible operator.
  website/content/en/docs/migration/v0.18.0.md
Labels: lgtm

#3508 Fix flag name in error message for generate packagemanifests
  cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
Labels: lgtm

#3521 internal/plugins/helm: refactor for organization and isolation
  internal/plugins/helm/v1/scaffolds/api.go
  internal/plugins/helm/v1/scaffolds/init.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/crd/crd.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/crd/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/prometheus/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/prometheus/monitor.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/auth_proxy_role.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/auth_proxy_role_binding.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/auth_proxy_service.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/client_cluster_role.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/crd_editor_rbac.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/crd_viewer_rbac.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/leader_election_role.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/leader_election_role_binding.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role_binding.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role_test.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/samples/crd_sample.go
  internal/plugins/helm/v1/scaffolds/internal/templates/dockerfile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/gitignore.go
  internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/watches.go
Labels: lgtm

#3506 Remove EnqueueRequestForAnnotation handler from SDK
  changelog/fragments/mv-EnqueueRequestForAnnotation.yaml
  go.mod
  go.sum
  internal/generate/crd/crd_test.go
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/inject_owner.go
  pkg/ansible/proxy/proxy.go
  pkg/handler/enqueue_annotation.go
  pkg/helm/client/client.go
  pkg/helm/controller/controller.go
Labels: lgtm

#3438 internal/plugins/helm: add `--project-name` and use `Config.ProjectName` in scaffold
  changelog/fragments/operator-name-config-file.yaml
  go.mod
  go.sum
  internal/plugins/helm/v1/chartutil/chart.go
  internal/plugins/helm/v1/init.go
  internal/plugins/helm/v1/plugin.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go
  internal/util/projutil/project_util.go
Labels: lgtm

#3526 internal/scorecard: fix cleanup skip on timeout bug
  changelog/fragments/no-pod-left-behind.yaml
  internal/scorecard/run_test.go
  internal/scorecard/scorecard.go
  internal/scorecard/testpod.go
Labels: kind/bug, lgtm

#3528 hack/generate/changelog: fixes in preparation for v1.0.0-alpha1 release
  hack/generate/changelog/gen-changelog.go
Labels: lgtm

#3513 cleanup: remove the funcs from k8sutil which are no longer used
  internal/util/k8sutil/k8sutil.go
  internal/util/k8sutil/k8sutil_test.go
Labels: kind/cleanup

#3524 [v0.19.x] cmd/operator-sdk/generate/packagemanifests: add `--from-version` flag (#3509)
  changelog/fragments/packagemanifests-from-version.yaml
  cmd/operator-sdk/generate/internal/genutil.go
  cmd/operator-sdk/generate/packagemanifests/cmd.go
  cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
  website/content/en/docs/new-cli/operator-sdk_generate_packagemanifests.md
  website/content/en/docs/olm-integration/generating-a-csv.md
Labels: lgtm

#3525 move zap flags internally
  changelog/fragments/move-log-internally.yaml
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
  internal/log/zap/flags.go
  internal/log/zap/flags_test.go
  internal/log/zap/logger.go
  internal/log/zap/logger_test.go
  pkg/ansible/flags/flag.go
  pkg/helm/flags/flag.go
Labels: lgtm

#3527 *: consistently use *.sdk.operatorframework.io wherever we use domains
  changelog/fragments/consistent-domain.yaml
  internal/generate/testdata/non-standard-layout/PROJECT
  internal/plugins/plugins.go
  pkg/ansible/controller/reconcile.go
  pkg/ansible/runner/runner.go
  pkg/helm/controller/reconcile.go
  pkg/helm/controller/reconcile_test.go
  test/ansible/deploy/crds/test.example.com_v1_inventorytest_cr.yaml
  test/ansible/deploy/crds/test.example.com_v1alpha1_inventorytest_cr.yaml
  test/e2e-helm/e2e_helm_suite_test.go
  website/content/en/docs/building-operators/ansible/development-tips.md
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/reference/advanced_options.md
  website/content/en/docs/building-operators/ansible/reference/watches.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/reference/advanced_features.md
  website/content/en/docs/building-operators/helm/reference/scaffolding.md
  website/content/en/docs/cli/operator-sdk_init.md
Labels: lgtm

#3334 scorecard,generate-csv: consider api "group" while checking for known types
  changelog/fragments/crds-with-core-types.yaml
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/generate/collector/collect.go
  internal/generate/collector/collect_test.go
  internal/generate/testdata/non-standard-layout/config/crds-with-core-types/foo.example.com_deployment_crd.yaml
  internal/generate/testdata/non-standard-layout/config/crds-with-core-types/foo.example.com_v1alpha1_deployment_cr.yaml
Labels: lgtm

#3510 doc: steps and info to setup envtest
  website/content/en/docs/building-operators/golang/project_migration_guide.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/references/env-test-setup.md
Labels: kind/documentation

#3534 test,website: use --plugins=helm when referencing the plugin name
  test/e2e-helm/e2e_helm_suite_test.go
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/reference/scaffolding.md
Labels: lgtm

#3536 [v0.19.x] website: fix install from source instructions
  website/content/en/docs/install-operator-sdk.md
Labels: lgtm

#3548 internal/plugins: refactor plugins packages, utils
  cmd/operator-sdk/generate/kustomize/manifests.go
  internal/plugins/ansible/v1/api.go
  internal/plugins/ansible/v1/init.go
  internal/plugins/ansible/v1/plugin.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
  internal/plugins/golang/v2/api.go
  internal/plugins/golang/v2/init.go
  internal/plugins/helm/v1/api.go
  internal/plugins/helm/v1/init.go
  internal/plugins/manifests/api.go
  internal/plugins/manifests/init.go
  internal/plugins/scorecard/init.go
  internal/plugins/util/kustomize/kustomize.go
Labels: lgtm

#3547 *: remove the `add crd` subcommand and related utilities
  changelog/fragments/remove-add-crd.yaml
  cmd/operator-sdk/add/cmd.go
  cmd/operator-sdk/add/crd.go
  internal/generate/crd/crd.go
  internal/generate/crd/crd_test.go
  internal/generate/gen/generator.go
  internal/generate/gen/rules.go
  internal/genutil/crds.go
Labels: lgtm

#3535 website: fix install from source instructions
  website/content/en/docs/installation/install-operator-sdk.md
Labels: lgtm

#3537 Move pkg/helm to internal/helm
  changelog/fragments/mv-pkg-helm.yaml
  cmd/helm-operator/main.go
  internal/helm/client/client.go
  internal/helm/client/doc.go
  internal/helm/controller/controller.go
  internal/helm/controller/doc.go
  internal/helm/controller/reconcile.go
  internal/helm/controller/reconcile_test.go
  internal/helm/flags/flag.go
  internal/helm/internal/diff/diff.go
  internal/helm/internal/types/doc.go
  internal/helm/internal/types/types.go
  internal/helm/internal/types/types_test.go
  internal/helm/release/doc.go
  internal/helm/release/manager.go
  internal/helm/release/manager_factory.go
  internal/helm/release/manager_test.go
  internal/helm/watches/watches.go
  internal/helm/watches/watches_test.go
Labels: lgtm

#3560 *: move pkg/ansible to internal/ansible
  .gitignore
  changelog/fragments/mv-ansible-internal.yaml
  cmd/ansible-operator/main.go
  hack/tests/e2e-ansible.sh
  internal/ansible/OWNERS
  internal/ansible/controller/controller.go
  internal/ansible/controller/reconcile.go
  internal/ansible/controller/reconcile_test.go
  internal/ansible/controller/status/types.go
  internal/ansible/controller/status/utils.go
  internal/ansible/controller/status/utils_test.go
  internal/ansible/events/log_events.go
  internal/ansible/flags/flag.go
  internal/ansible/metrics/metrics.go
  internal/ansible/paramconv/paramconv.go
  internal/ansible/paramconv/paramconv_test.go
  internal/ansible/predicate/predicate.go
  internal/ansible/proxy/cache_response.go
  internal/ansible/proxy/controllermap/controllermap.go
  internal/ansible/proxy/inject_owner.go
  internal/ansible/proxy/kubeconfig/kubeconfig.go
  internal/ansible/proxy/kubectl.go
  internal/ansible/proxy/proxy.go
  internal/ansible/proxy/proxy_test.go
  internal/ansible/proxy/requestfactory/requestinfo.go
  internal/ansible/runner/eventapi/eventapi.go
  internal/ansible/runner/eventapi/types.go
  internal/ansible/runner/fake/runner.go
  internal/ansible/runner/internal/inputdir/inputdir.go
  internal/ansible/runner/runner.go
  internal/ansible/runner/runner_test.go
  internal/ansible/runner/testdata/playbook.yml
  internal/ansible/runner/testdata/roles/role/tasks.yaml
  internal/ansible/watches/testdata/ansible_collections/nameSpace/collection/roles/someRole/empty_file
  internal/ansible/watches/testdata/duplicate_gvk.yaml
  internal/ansible/watches/testdata/invalid.yaml
  internal/ansible/watches/testdata/invalid_collection.yaml
  internal/ansible/watches/testdata/invalid_duration.yaml
  internal/ansible/watches/testdata/invalid_finalizer_no_vars.yaml
  internal/ansible/watches/testdata/invalid_finalizer_playbook_path.yaml
  internal/ansible/watches/testdata/invalid_finalizer_role_path.yaml
  internal/ansible/watches/testdata/invalid_finalizer_whithout_name.yaml
  internal/ansible/watches/testdata/invalid_playbook_path.yaml
  internal/ansible/watches/testdata/invalid_role_path.yaml
  internal/ansible/watches/testdata/invalid_status.yaml
  internal/ansible/watches/testdata/invalid_yaml_file.yaml
  internal/ansible/watches/testdata/playbook.yml
  internal/ansible/watches/testdata/roles/role/tasks.yaml
  internal/ansible/watches/testdata/valid.yaml.tmpl
  internal/ansible/watches/watches.go
  internal/ansible/watches/watches_test.go
Labels: lgtm

#3562 Meta ansible operator meta
  changelog/fragments/rename-meta-ansible-operator-meta.yaml
  internal/ansible/runner/runner.go
  test/ansible-memcached/tasks.yml
  test/ansible/watches.yaml
  website/content/en/docs/building-operators/ansible/development-tips.md
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/reference/apb-migration-guide.md
  website/content/en/docs/building-operators/ansible/testing-guide.md
Labels: lgtm

#3549 Add back setting environment variable
  changelog/fragments/ansible-operator-env.yaml
  cmd/ansible-operator/main.go
Labels: ansible-operator, lgtm

#3554 doc: additionals and improvements on helm migration steps
  website/content/en/docs/building-operators/helm/migration.md
Labels: helm-operator, kind/documentation, lgtm

#3517 doc: add envtest setup info (0.19.x)
  website/content/en/docs/golang/project_migration_guide.md
  website/content/en/docs/golang/quickstart.md
  website/content/en/docs/golang/references/env-test-setup.md
Labels: lgtm

#3564 Ansible/Helm: use structured logging for version info
  changelog/fragments/ansible-helm-log-fmt.yaml
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
Labels: lgtm

#3566 cmd/operator-sdk: remove `build` subcommand
  changelog/fragments/remove-build.yaml
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/cli/cli.go
  go.mod
  go.sum
  hack/tests/e2e-ansible-molecule.sh
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_build.md
Labels: lgtm

#3565 pkg/ansible/run.go: add back setting environment variables (v0.19.x)
  changelog/fragments/ansible-operator-env.yaml
  pkg/ansible/run.go
Labels: lgtm

#3555 doc: quickstart for Ansible projects
  website/content/en/docs/building-operators/ansible/development-tips.md
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/testing-guide.md
  website/content/en/docs/building-operators/ansible/tutorial.md
Labels: ansible-operator, kind/documentation, lgtm

#3568 Move cmd APIs to internal/cmd/operator-sdk/
  cmd/operator-sdk/main.go
  hack/generate/cli-doc/gen-cli-doc.go
  internal/cmd/operator-sdk/bundle/bundle_suite_test.go
  internal/cmd/operator-sdk/bundle/cmd.go
  internal/cmd/operator-sdk/bundle/cmd_test.go
  internal/cmd/operator-sdk/bundle/internal/logger.go
  internal/cmd/operator-sdk/bundle/internal/result.go
  internal/cmd/operator-sdk/bundle/internal/result_test.go
  internal/cmd/operator-sdk/bundle/validate.go
  internal/cmd/operator-sdk/bundle/validate_test.go
  internal/cmd/operator-sdk/cleanup/cmd.go
  internal/cmd/operator-sdk/cleanup/packagemanifests/packagemanifests.go
  internal/cmd/operator-sdk/cli/cli.go
  internal/cmd/operator-sdk/completion/bash.go
  internal/cmd/operator-sdk/completion/bash_test.go
  internal/cmd/operator-sdk/completion/cmd.go
  internal/cmd/operator-sdk/completion/cmd_test.go
  internal/cmd/operator-sdk/completion/completion_suite_test.go
  internal/cmd/operator-sdk/completion/zsh.go
  internal/cmd/operator-sdk/completion/zsh_test.go
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/bundle/cmd.go
  internal/cmd/operator-sdk/generate/cmd.go
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/kustomize/cmd.go
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/cmd/operator-sdk/olm/cmd.go
  internal/cmd/operator-sdk/olm/cmd_test.go
  internal/cmd/operator-sdk/olm/install.go
  internal/cmd/operator-sdk/olm/install_test.go
  internal/cmd/operator-sdk/olm/olm_suite_test.go
  internal/cmd/operator-sdk/olm/status.go
  internal/cmd/operator-sdk/olm/status_test.go
  internal/cmd/operator-sdk/olm/uninstall.go
  internal/cmd/operator-sdk/olm/uninstall_test.go
  internal/cmd/operator-sdk/run/cmd.go
  internal/cmd/operator-sdk/run/cmd_test.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_suite_test.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_test.go
  internal/cmd/operator-sdk/run/run_suite_test.go
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/cmd/operator-sdk/scorecard/cmd_test.go
  internal/cmd/operator-sdk/scorecard/scorecard_suite_test.go
  internal/cmd/operator-sdk/version/cmd.go
  internal/cmd/operator-sdk/version/cmd_test.go
  internal/cmd/operator-sdk/version/version_suite_test.go
Labels: lgtm

#3570 internal/plugins/ansible: manager scaffolding updates for --metrics-addr and envvars
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
Labels: lgtm

#3341 Allows OLM subcommands work for Helm/Ansible new layout
  go.mod
  go.sum
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/bundle/cmd.go
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/internal/utils.go
  website/content/en/docs/cli/operator-sdk_init.md
  website/content/en/docs/olm-integration/generation.md
Labels: ansible-operator, helm-operator, kubebuilder-integration

#3574 *: release v1.0.0-alpha.1
  CHANGELOG.md
  changelog/fragments/ansible-helm-log-fmt.yaml
  changelog/fragments/ansible-leader-election.yaml
  changelog/fragments/ansible-metrics-addr.yml
  changelog/fragments/ansible-operator-env.yaml
  changelog/fragments/ansible-operator-optional-case.yaml
  changelog/fragments/cmd-legacy-helm.yaml
  changelog/fragments/consistent-domain.yaml
  changelog/fragments/crds-with-core-types.yaml
  changelog/fragments/enqueue-object-handler.yaml
  changelog/fragments/fix-find-metadata-dir.yaml
  changelog/fragments/helm-leader-election.yaml
  changelog/fragments/helm-metrics-addr.yaml
  changelog/fragments/modify-ansible-flags.yaml
  changelog/fragments/move-log-internally.yaml
  changelog/fragments/mv-EnqueueRequestForAnnotation.yaml
  changelog/fragments/mv-ansible-internal.yaml
  changelog/fragments/mv-pkg-helm.yaml
  changelog/fragments/no-pod-left-behind.yaml
  changelog/fragments/operator-name-config-file.yaml
  changelog/fragments/packagemanifests-from-version.yaml
  changelog/fragments/remove-add-crd.yaml
  changelog/fragments/remove-build.yaml
  changelog/fragments/remove-legacy-helm.yaml
  changelog/fragments/remove-pkg-predicate.yaml
  changelog/fragments/remove-test-framework.yaml
  changelog/fragments/rename-max-workers.yaml
  changelog/fragments/rename-meta-ansible-operator-meta.yaml
  changelog/fragments/rm-ansible-metrics.yml
  changelog/fragments/rm-cmd-legacy-ansible.yaml
  changelog/fragments/rm-helm-metrics.yaml
  changelog/fragments/rm-k8sutils.yaml
  changelog/fragments/rm-legacy-bundle-cmds.yaml
  changelog/fragments/rm-legacy-gen-bundle.yaml
  changelog/fragments/rm-legacy-gen-csv.yaml
  changelog/fragments/rm-legacy-gen-packagemanifests.yaml
  changelog/fragments/rm-legacy-go.yaml
  changelog/fragments/rm-legacy-run.yaml
  changelog/fragments/rm-pkg-kube-metrics.yaml
  changelog/fragments/rm-pkg-leader-and-status.yaml
  changelog/fragments/rm-pkg-metrics.yaml
  changelog/fragments/rm-pkg-ready.yaml
  changelog/fragments/rm-tls-pkg.yaml
  changelog/fragments/scorecard-bundle-metadata.yaml
  changelog/fragments/scorecard-config-scaffold.yaml
  changelog/fragments/scorecard-default-ns.yaml
  changelog/fragments/scorecard-label-perms.yaml
  changelog/fragments/scorecard-metadata-source-of-truth.yaml
  changelog/fragments/scorecard-move-alpha.yaml
  changelog/fragments/scorecard-output-api.yaml
  changelog/fragments/scorecard-parallel.yaml
  changelog/fragments/use-operator-lib-metrics.yaml
  version/version.go
  website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
Labels: lgtm

#3577 *: post-release version reset
  version/version.go
Labels: lgtm

#3538 Add some documentation for Ansible operator scaffolding
  website/content/en/docs/building-operators/ansible/reference/scaffolding.md
Labels: lgtm

#3584 release v0.19.1
  CHANGELOG.md
  changelog/fragments/ansible-operator-env.yaml
  changelog/fragments/packagemanifests-from-version.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.19.1.md
Labels: lgtm

#3583 website/content/en/docs: reorganize helm-based operator docs
  website/content/en/docs/building-operators/helm/installation.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/reference/_index.md
  website/content/en/docs/building-operators/helm/reference/advanced_features/_index.md
  website/content/en/docs/building-operators/helm/reference/advanced_features/annotations.md
  website/content/en/docs/building-operators/helm/reference/advanced_features/max_concurrent_reconciles.md
  website/content/en/docs/building-operators/helm/reference/advanced_features/override_values.md
  website/content/en/docs/building-operators/helm/reference/project_layout.md
  website/content/en/docs/building-operators/helm/reference/scaffolding.md
  website/content/en/docs/building-operators/helm/reference/watches.md
  website/content/en/docs/installation/install-operator-sdk.md
Labels: lgtm

#3587 post release v0.19.1 update master changelog
  CHANGELOG.md
Labels: lgtm

#3550 Cleanup CMD tests
  internal/cmd/operator-sdk/bundle/bundle_suite_test.go
  internal/cmd/operator-sdk/completion/completion_suite_test.go
  internal/cmd/operator-sdk/olm/olm_suite_test.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_suite_test.go
  internal/cmd/operator-sdk/run/run_suite_test.go
  internal/cmd/operator-sdk/scorecard/scorecard_suite_test.go
  internal/cmd/operator-sdk/version/version_suite_test.go
  internal/scorecard/scorecard_suite_test.go
Labels: kind/cleanup, lgtm, testing

#3588 website: fix typo in helm override_values.md
  website/content/en/docs/building-operators/helm/reference/advanced_features/override_values.md
Labels: lgtm

#3586 post-release v0.19.1
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
Labels: lgtm

#3592 Fix variable watchNamespace name in operator-scope
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: lgtm

#3575 website/content/en/docs/building-operators: update legacy references
  website/content/en/docs/building-operators/ansible/development-tips.md
  website/content/en/docs/building-operators/ansible/reference/advanced_options.md
  website/content/en/docs/building-operators/ansible/reference/apb-migration-guide.md
  website/content/en/docs/building-operators/ansible/reference/webhooks.md
  website/content/en/docs/building-operators/ansible/testing-guide.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/quickstart.md
Labels: lgtm

#3591 release.sh, website: update release script and docs
  release.sh
  website/content/en/docs/contribution-guidelines/release.md
  website/content/en/docs/installation/install-operator-sdk.md
Labels: lgtm

#3552 doc: quickstart for Helm projects and more details for the migration guide
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/tutorial.md
Labels: helm-operator, kind/documentation

#3597 doc: fix the duplicated line in the migration guide
  website/content/en/docs/building-operators/helm/migration.md
Labels: lgtm

#3599 <run|cleanup> packagemanifests: remove `--include-paths`, change `--operator-version` to `--version`
  changelog/fragments/run-packagemanifests-flags-1.yaml
  internal/olm/operator/operator_manager.go
  internal/olm/operator/packagemanifests.go
  internal/olm/operator/packagemanifests_manager.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e/e2e_suite.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_cleanup_packagemanifests.md
  website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
  website/content/en/docs/olm-integration/quickstart-package-manifests.md
  website/content/en/docs/olm-integration/testing-deployment.md
Labels: lgtm, olm-catalog

#3530 generate: remove `--operator-name`
  changelog/fragments/operator-name-config.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/bundle/cmd.go
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/generate/packagemanifest/packagemanifest.go
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
  website/content/en/docs/cli/operator-sdk_generate_kustomize_manifests.md
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
  website/content/en/docs/olm-integration/generation.md
  website/content/en/docs/olm-integration/quickstart-package-manifests.md
Labels: lgtm

#3601 <run|cleanup> packagemanifests: remove `--olm-namespace`, change `--operator-namespace` to `--namespace`
  changelog/fragments/run-packagemanifests-flags-2.yaml
  internal/olm/operator/operator_manager.go
  internal/olm/operator/packagemanifests_manager.go
  test/e2e/e2e_suite.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_cleanup_packagemanifests.md
  website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/testing-deployment.md
Labels: olm-catalog

#3603 fix: (ansible) - kustomize target is missing realpath
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
Labels: lgtm

#3602 deps: bump operator-registry to v1.13.4
  changelog/fragments/bundle-validate-default-channel.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/registry/labels.go
  internal/registry/labels_test.go
  internal/registry/validate.go
Labels: area/dependency, lgtm

#3605 [v0.19.x] deps: bump operator-registry to v1.13.4
  changelog/fragments/bundle-validate-default-channel.yaml
  cmd/operator-sdk/generate/bundle/bundle.go
  go.mod
  go.sum
  internal/registry/labels.go
  internal/registry/validate.go
Labels: lgtm

#3607 *: release v0.19.2
  CHANGELOG.md
  changelog/fragments/bundle-validate-default-channel.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.19.2.md
Labels: lgtm

#3609 *: post release v0.19.2
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm

#3595 doc: helm : tiny improvements and fixes
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/reference/_index.md
  website/content/en/docs/building-operators/helm/tutorial.md
Labels: lgtm

#3539 removal: cleanup over legacy support
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/util/projutil/project_util.go
Labels: kind/cleanup, lgtm

#3616 bump operator-lib to v0.1.0
  go.mod
  go.sum
Labels: lgtm

#3507 Scorecard e2e Testing
  test/e2e/e2e_suite.go
Labels: lgtm

#3374 Closes #2262: Allowing users to specify arbitrary CLI arguments for Ansible-based operators
  changelog/fragments/arbitraryArgs.yaml
  internal/ansible/flags/flag.go
  internal/ansible/runner/internal/inputdir/inputdir.go
  internal/ansible/runner/runner.go
  internal/ansible/runner/runner_test.go
  internal/cmd/ansible-operator/run/cmd.go
  test/ansible/build/Dockerfile
  test/ansible/deploy/crds/test.example.com_argstest_crd.yaml
  test/ansible/molecule/cluster/tasks/args_test.yml
  test/ansible/molecule/templates/operator.yaml.j2
  test/ansible/playbooks/args.yml
  test/ansible/watches.yaml
  website/content/en/docs/building-operators/ansible/reference/advanced_options.md
Labels: lgtm

#3621 remove MAINTAINERS: official list maintained in OWNERS file
  MAINTAINERS
Labels: lgtm

#3622 scorecard: use api repo v1alpha3 API, remove existing
  changelog/fragments/move-scorecard-apis.yaml
  go.mod
  go.sum
  images/scorecard-test-kuttl/cmd/test-kuttl/main.go
  images/scorecard-test/cmd/test/main.go
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/generate/collector/collect.go
  internal/plugins/scorecard/init.go
  internal/scorecard/config.go
  internal/scorecard/examples/custom-scorecard-tests/images/custom-scorecard-tests/cmd/test/main.go
  internal/scorecard/examples/custom-scorecard-tests/internal/tests/tests.go
  internal/scorecard/formatting.go
  internal/scorecard/labels_test.go
  internal/scorecard/run_test.go
  internal/scorecard/scorecard.go
  internal/scorecard/testpod.go
  internal/scorecard/tests/basic.go
  internal/scorecard/tests/bundle_test.go
  internal/scorecard/tests/olm.go
  pkg/apis/scorecard/v1alpha2/doc.go
  pkg/apis/scorecard/v1alpha2/formatter.go
  pkg/apis/scorecard/v1alpha2/register.go
  pkg/apis/scorecard/v1alpha2/types.go
  pkg/apis/scorecard/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/scorecard/v1alpha3/configuration_types.go
  pkg/apis/scorecard/v1alpha3/doc.go
  pkg/apis/scorecard/v1alpha3/formatter.go
  pkg/apis/scorecard/v1alpha3/register.go
  pkg/apis/scorecard/v1alpha3/test_types.go
  pkg/apis/scorecard/v1alpha3/zz_generated.deepcopy.go
  test/e2e/e2e_suite.go
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: area/dependency, lgtm

#3627 CHANGELOG.md: update scorecard API links
  CHANGELOG.md
Labels: kind/documentation, lgtm

#3624 Modify rbac role, rather than patch with kustomize
  hack/tests/e2e-ansible-molecule.sh
  internal/plugins/ansible/v1/scaffolds/api.go
  internal/plugins/ansible/v1/scaffolds/init.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/crd_editor_rbac.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/crd_viewer_rbac.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/kustomization.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
Labels: lgtm
