Repository operator-framework/operator-sdk, pull requests merged in 2020-03, with the labels that each got.

#2621 move helm version from v3.0.1 to v3.0.2
  CHANGELOG.md
  go.mod
  go.sum
  test/test-framework/go.sum
Labels: area/dependency, helm-operator, kind/bug, size/S

#2626 doc/proposals/kubebuilder-integration.md: update requirements
  doc/proposals/kubebuilder-integration.md
Labels: kind/documentation, lgtm, size/M

#2598 operator bundle docs
  doc/user/olm-catalog/operator-bundles.md
Labels: kind/documentation, lgtm, olm-catalog, size/S

#2587 Allow Ansible watches to use collection roles
  cmd/operator-sdk/execentrypoint/ansible.go
  doc/ansible/dev/finalizers.md
  doc/ansible/user-guide.md
  hack/tests/e2e-ansible-molecule.sh
  pkg/ansible/flags/flag.go
  pkg/ansible/watches/testdata/ansible_collections/nameSpace/collection/roles/someRole/empty_file
  pkg/ansible/watches/testdata/invalid_collection.yaml
  pkg/ansible/watches/testdata/valid.yaml.tmpl
  pkg/ansible/watches/watches.go
  pkg/ansible/watches/watches_test.go
  test/ansible-memcached/molecule.yml
  test/ansible/build/Dockerfile
  test/ansible/deploy/crds/test.example.com_collections_crd.yaml
  test/ansible/fixture_collection/galaxy.yml
  test/ansible/fixture_collection/roles/dummy/tasks/main.yml
  test/ansible/molecule/cluster/tasks/collections_test.yml
  test/ansible/molecule/cluster/verify.yml
  test/ansible/watches.yaml
Labels: lgtm, size/L

#2607 Adds --max-workers flag to the exec-entrypoint helm command
  CHANGELOG.md
  doc/helm/user-guide.md
  pkg/helm/controller/controller.go
  pkg/helm/flags/flag.go
  pkg/helm/run.go
Labels: lgtm, size/M

#2629 Add docs about not running e2e testing m directly
  doc/test-framework/writing-e2e-tests.md
Labels: lgtm, size/XS

#2606 Update the docs and scaffold to make clear how works the metrics and what is required to do for third party API's.
  doc/user-guide.md
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
  test/test-framework/cmd/manager/main.go
Labels: kind/documentation, metrics, size/M

#2631 add discussion of registry options for the image build
  doc/user-guide.md
Labels: lgtm, size/XS

#2632 Add changelog for collections in Ansible watches
  CHANGELOG.md
Labels: lgtm, size/XS

#2599 Doc(logging.md): add notes for logging using custom zap logger
  doc/user/logging.md
Labels: kind/documentation, size/M

#2601 fix: creation of monitor service when operator is cluster-scoped
  CHANGELOG.md
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
  pkg/ansible/run.go
  test/test-framework/cmd/manager/main.go
Labels: kind/bug, metrics, size/M

#2638 doc: add info over openAPI validations for Ansible based operators
  doc/ansible/dev/advanced_options.md
Labels: ansible-operator, kind/documentation, lgtm, size/M

#2637 doc : update docs regards break changing in the run command
  doc/migration/version-upgrade-guide.md
  doc/sdk-cli-reference.md
Labels: ansible-operator, kind/documentation, lgtm, size/M

#2603 Add helm prometheus metrics support and handle MultiNamespace scenario for metrics
  CHANGELOG.md
  hack/tests/e2e-helm.sh
  internal/scaffold/cmd.go
  internal/scaffold/cmd_test.go
  pkg/ansible/run.go
  pkg/helm/run.go
  pkg/kube-metrics/metrics.go
  test/test-framework/cmd/manager/main.go
Labels: metrics, size/L

#2625 Add to migration doc steps regards changes over metrics to the scaffolded files.
  doc/migration/version-upgrade-guide.md
Labels: lgtm, size/M

#2634 Scorecard - add proxy port configuration setting
  CHANGELOG.md
  doc/test-framework/scorecard.md
  images/scorecard-proxy/cmd/proxy/main.go
  internal/scorecard/interfaces.go
  internal/scorecard/plugins/config.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/resource_handler.go
Labels: lgtm, size/M

#2635 [fix] correct console output in logging.md
  doc/user/logging.md
Labels: lgtm, size/XS

#2643 Text change in the Capability Level diagram(s): change from "Phase" to "Level"
  doc/images/operator-capability-level-transparent-bg.png
  doc/images/operator-capability-level.png
  doc/images/operator-capability-level.svg
Labels: size/M

#2611 [fix]: include filename in the error returned by generate-csv command
  cmd/operator-sdk/generate/csv.go
Labels: size/XS

#2640 Add error context to log messages
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/inject_owner.go
Labels: lgtm, size/XS

#2642 Update client.md incorrect patch examples
  doc/user/client.md
Labels: lgtm, size/XS

#2646 Use the Kubernetes Ansible collection
  CHANGELOG.md
  doc/ansible/dev/apb_migration_guide.md
  doc/ansible/dev/developer_guide.md
  doc/ansible/dev/retroactively-owned-resources.md
  doc/ansible/dev/testing_guide.md
  doc/ansible/user-guide.md
  internal/scaffold/ansible/dockerfilehybrid.go
  internal/scaffold/ansible/molecule_cluster_destroy.go
  internal/scaffold/ansible/molecule_cluster_playbook.go
  internal/scaffold/ansible/molecule_cluster_prepare.go
  internal/scaffold/ansible/molecule_cluster_verify.go
  internal/scaffold/ansible/molecule_test_local_playbook.go
  internal/scaffold/ansible/playbook.go
  internal/scaffold/ansible/roles_meta_main.go
  test/ansible-memcached/memfin/tasks/main.yml
  test/ansible-memcached/secret/tasks/main.yml
  test/ansible-memcached/tasks.yml
  test/ansible-memcached/verify.yml
  test/ansible/build/Dockerfile
  test/ansible/fixture_collection/roles/dummy/tasks/main.yml
  test/ansible/molecule/cluster/playbook.yml
  test/ansible/molecule/cluster/verify.yml
  test/ansible/molecule/test-local/playbook.yml
  test/ansible/roles/inventory/tasks/main.yml
Labels: lgtm, size/L

#2653 docs: fixed a bunch of things in the docs
  doc/ansible/user-guide.md
Labels: lgtm

#2645 operator capability definitions
  doc/operator-capabilities.md
Labels: size/L

#2661 fix: CR has not error faced in the task
  CHANGELOG.md
  pkg/ansible/controller/reconcile.go
  pkg/ansible/controller/reconcile_test.go
Labels: ansible-operator, kind/bug, lgtm

#2641 doc: Ansible/Helm add api command Proposal for Operator SDK
  doc/proposals/ansible-helm-addapi.md
Labels: size/L

#2651 fix: ansible verbosity
  CHANGELOG.md
  pkg/ansible/runner/runner.go
  pkg/ansible/runner/runner_test.go
  test/ansible/deploy/crds/test.example.com_v1_inventorytest_cr.yaml
  test/ansible/deploy/crds/test.example.com_v1alpha1_inventory_cr.yaml
Labels: ansible-operator, kind/bug

#2660 Link to Capability Levels documentation
  README.md
Labels: lgtm

#2650 adding steps over how to test the changes made locally
  doc/dev/developer_guide.md
Labels: lgtm

#2666 Add SECURITY.md for responsible disclosure instructions
  SECURITY.md
Labels: lgtm

#2652 Scaffold a requirements.yml file for collection dependencies
  CHANGELOG.md
  cmd/operator-sdk/migrate/cmd.go
  cmd/operator-sdk/new/cmd.go
  doc/ansible/dev/developer_guide.md
  doc/ansible/dev/testing_guide.md
  doc/ansible/project_layout.md
  doc/migration/version-upgrade-guide.md
  internal/scaffold/ansible/build_dockerfile.go
  internal/scaffold/ansible/dockerfilehybrid.go
  internal/scaffold/ansible/requirements.go
  test/ansible/build/Dockerfile
  test/ansible/requirements.yml
Labels: lgtm

#2675 doc/.../generating-a-csv.md: update notes on CSV annotations
  doc/user/olm-catalog/generating-a-csv.md
Labels: kind/documentation, lgtm, olm-catalog

#2673 Fix typo in bundle validate help text
  cmd/operator-sdk/bundle/validate.go
  doc/cli/operator-sdk_bundle_validate.md
Labels: lgtm

#2682 remove `doc/sdk-cli-reference.md` and update all links
  CHANGELOG.md
  README.md
  cmd/operator-sdk/new/cmd.go
  doc/cli/operator-sdk_new.md
  doc/helm/user-guide.md
  doc/migration/version-upgrade-guide.md
  doc/proposals/ansible-helm-addapi.md
  doc/proposals/cli-ux-phase1.md
  doc/proposals/sdk-code-annotations.md
  doc/sdk-cli-reference.md
  doc/test-framework/scorecard.md
  doc/test-framework/writing-e2e-tests.md
  website/content/en/docs/helm/user-guide.md
  website/content/en/docs/migration/version-upgrade-guide.md
  website/content/en/docs/sdk-cli-reference.md
  website/content/en/docs/test-framework/scorecard.md
  website/content/en/docs/test-framework/writing-e2e-tests.md
Labels: kind/documentation

#2617 Improve behavior of namespace flags in operator-sdk run and operator-sdk test local subcommands
  CHANGELOG.md
  cmd/operator-sdk/cleanup/cmd.go
  cmd/operator-sdk/run/cmd.go
  cmd/operator-sdk/run/local.go
  cmd/operator-sdk/test/local.go
  doc/ansible/dev/testing_guide.md
  doc/cli/operator-sdk_cleanup.md
  doc/cli/operator-sdk_run.md
  doc/cli/operator-sdk_test_local.md
  doc/migration/version-upgrade-guide.md
  doc/test-framework/writing-e2e-tests.md
  doc/user-guide.md
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/subcommand.sh
  internal/olm/operator/operator.go
  internal/scaffold/ansible/molecule_cluster_molecule.go
  internal/scaffold/ansible/molecule_default_molecule.go
  internal/scaffold/ansible/molecule_test_local_molecule.go
  pkg/test/context.go
  pkg/test/e2eutil/wait_util.go
  pkg/test/framework.go
  pkg/test/resource_creator.go
  pkg/test/resource_creator_test.go
  test/ansible-memcached/molecule.yml
  test/ansible/molecule/cluster/molecule.yml
  test/ansible/molecule/test-local/molecule.yml
  test/e2e/_incluster-test-code/memcached_test.go
  test/e2e/tls_util_test.go
  test/test-framework/test/e2e/memcached_test.go
  website/content/en/docs/ansible/dev/testing_guide.md
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_run.md
  website/content/en/docs/cli/operator-sdk_test_local.md
  website/content/en/docs/migration/version-upgrade-guide.md
  website/content/en/docs/test-framework/writing-e2e-tests.md
  website/content/en/docs/user-guide.md
Labels: lgtm, size/XL

#2157 remove the remaining slashes from targets
  Makefile
Labels: do-not-merge/hold, kind/cleanup, size/XS

#2683 add already exists check in object creation
  CHANGELOG.md
  internal/scorecard/plugins/resource_handler.go
Labels: lgtm

#2613 Add `--olm-namespace` flag to OLM related subcommands
  CHANGELOG.md
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/olm/status.go
  doc/cli/operator-sdk_cleanup.md
  doc/cli/operator-sdk_new.md
  doc/cli/operator-sdk_olm_status.md
  doc/cli/operator-sdk_run.md
  internal/olm/client.go
  internal/olm/client/client.go
  internal/olm/manager.go
  internal/olm/operator/manager.go
  internal/olm/operator/operator.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_new.md
  website/content/en/docs/cli/operator-sdk_olm_status.md
  website/content/en/docs/cli/operator-sdk_run.md
Labels: size/M

#2676 Add docs about needed cluster roles for e2e operator tests
  doc/test-framework/writing-e2e-tests.md
  website/content/en/docs/test-framework/writing-e2e-tests.md
Labels: lgtm

#2544 remove dynamicrestmapper which is deprecated
  CHANGELOG.md
  pkg/restmapper/dynamicrestmapper.go
Labels: lgtm, size/L

#2717 website - update test-framework pages
  website/content/en/docs/test-framework/scorecard.md
  website/content/en/docs/test-framework/writing-e2e-tests.md
Labels: lgtm

#2716 Fix exec in proxy
  CHANGELOG.md
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/kubectl.go
  pkg/ansible/proxy/proxy.go
  test/ansible/deploy/crds/test.example.com_collectiontests_crd.yaml
  test/ansible/deploy/crds/test.example.com_exectests_crd.yaml
  test/ansible/deploy/crds/test.example.com_inventorytests_crd.yaml
  test/ansible/deploy/crds/test.example.com_v1alpha1_inventorytest_cr.yaml
  test/ansible/deploy/role.yaml
  test/ansible/molecule/cluster/tasks/collections_test.yml
  test/ansible/molecule/cluster/tasks/exec_test.yml
  test/ansible/molecule/cluster/tasks/inventory_test.yml
  test/ansible/molecule/templates/operator.yaml.j2
  test/ansible/molecule/test-local/playbook.yml
  test/ansible/playbooks/exec.yml
  test/ansible/watches.yaml
Labels: lgtm

#2685 Add guide explaining how to use webhooks with Ansible-based Operators
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/inject_owner.go
  pkg/ansible/proxy/proxy.go
  website/content/en/docs/ansible/dev/webhooks.md
Labels: lgtm

#2446 Add Compatible Kubernetes to Version Printout
  .travis.yml
  CHANGELOG.md
  Makefile
  cmd/operator-sdk/version/cmd.go
  hack/ci/setup-k8s.sh
  version/version.go
Labels: size/S

#2720 run,cleanup: document `--olm` mode
  cmd/operator-sdk/run/cmd.go
  doc/cli/operator-sdk_run.md
  doc/user-guide.md
  doc/user/olm-catalog/bundle-cli.md
  doc/user/olm-catalog/olm-cli.md
  website/content/en/docs/cli/operator-sdk_run.md
  website/content/en/docs/golang/olm-catalog/bundle-cli.md
  website/content/en/docs/golang/olm-catalog/olm-cli.md
  website/content/en/docs/user-guide.md
Labels: kind/documentation, olm-catalog

#2743 fix marker issue by testing just the doc folder
  Makefile
  hack/check-markdown.sh
Labels: lgtm

#2736 doc/user-guide.md: fix typo and remove redundant section
  doc/user-guide.md
  website/content/en/docs/user-guide.md
Labels: kind/documentation

#2740 cmd/operator-sdk/generate: remove deprecated openapi subcommand
  CHANGELOG.md
  cmd/operator-sdk/generate/cmd.go
  cmd/operator-sdk/generate/openapi.go
  doc/migration/version-upgrade-guide.md
  website/content/en/docs/migration/version-upgrade-guide.md
Labels: lgtm

#2746 deps: bump to k8s v1.17
  CHANGELOG.md
  Makefile
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/internal/genutil/k8s.go
  cmd/operator-sdk/internal/genutil/openapi.go
  doc/cli/operator-sdk_bundle_create.md
  doc/migration/version-upgrade-guide.md
  doc/user/olm-catalog/bundle-cli.md
  go.mod
  go.sum
  hack/tests/subcommand-bundle.sh
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  internal/scaffold/olm-catalog/csv_test.go
  internal/scaffold/olm-catalog/csv_updaters.go
  internal/scorecard/plugins/plugin_runner.go
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/requestfactory/requestinfo.go
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/cache.example.com_memcachedrs_crd.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/cache.example.com_memcacheds_crd.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/cache.example.com_memcachedrs_crd.yaml
  test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/cache.example.com_memcacheds_crd.yaml
  test/test-framework/go.mod
  test/test-framework/go.sum
  website/content/en/docs/cli/operator-sdk_bundle_create.md
  website/content/en/docs/golang/olm-catalog/bundle-cli.md
  website/content/en/docs/migration/version-upgrade-guide.md
Labels: area/dependency

#2751 .travis.yml: organize jobs into stages
  .travis.yml
Labels: testing

#2731 test framework: handle double-registered `--kubeconfig` flag
  CHANGELOG.md
  pkg/test/framework.go
  pkg/test/main_entry.go
  test/e2e/_incluster-test-code/main_test.go
Labels: kind/bug, lgtm, test-framework
