Repository operator-framework/operator-sdk, pull requests merged in 2020-04, with the labels that each got.

#2756 CHANGELOG.md: added line for #2754
  CHANGELOG.md
Labels: lgtm

#2755 generate csv: deprecate package manifest generation
  CHANGELOG.md
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/olm-catalog/package_manifest_test.go
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/memcached-operator.package.yaml
  internal/util/projutil/project_util.go
Labels: olm-catalog

#2737 bundle validate: validate a bundle directory
  CHANGELOG.md
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/bundle/validate.go
  doc/cli/operator-sdk_bundle_validate.md
  doc/user/olm-catalog/bundle-cli.md
  hack/lib/test_lib.sh
  hack/tests/subcommand-bundle.sh
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/golang/olm-catalog/bundle-cli.md
Labels: kind/feature, lgtm, olm-catalog

#2742 Added ARM64 Build
  .travis.yml
  Makefile
Labels: lgtm

#2758 util,generate: fix CRD parsers
  CHANGELOG.md
  cmd/operator-sdk/generate/csv.go
  cmd/operator-sdk/test/local.go
  doc/cli/operator-sdk_generate_csv.md
  internal/generate/crd/crd.go
  internal/generate/olm-catalog/csv.go
  internal/olm/operator/manager.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/resource_handler.go
  internal/util/k8sutil/api.go
  internal/util/k8sutil/api_test.go
  internal/util/k8sutil/manifest.go
  internal/util/k8sutil/scan.go
  pkg/test/resource_creator.go
  website/content/en/docs/cli/operator-sdk_generate_csv.md
Labels: kind/bug

#2730 generate csv: refactor CSV updaters to extend to webhooks
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_go_test.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/olm-catalog/csv_updaters_test.go
  internal/generate/testdata/non-standard-layout/main.go
  internal/scaffold/olm-catalog/testdata/deploy/crds/app.example.com_appservices2_crd.yaml
  internal/scaffold/olm-catalog/testdata/deploy/crds/app.example.com_appservices_crd.yaml
  internal/scaffold/olm-catalog/testdata/deploy/crds/app.example.com_v1alpha1_appservice_cr.yaml
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/app-operator.package.yaml
  internal/scaffold/olm-catalog/testdata/deploy/olm-catalog/csv-config.yaml
  internal/scaffold/olm-catalog/testdata/deploy/operator.yaml
  internal/scaffold/olm-catalog/testdata/deploy/role.yaml
  internal/scaffold/olm-catalog/testdata/deploy/role_binding.yaml
  internal/scaffold/olm-catalog/testdata/deploy/service_account.yaml
  internal/util/projutil/project_util.go
Labels: olm-catalog, refactoring

#2762 .travis.yml: organize arm64 travis job under deploy stage
  .travis.yml
Labels: lgtm, testing

#2760 Add Skeleton Command for Scorecard 2
  cmd/operator-sdk/alpha/cmd.go
  cmd/operator-sdk/alpha/scorecard/cmd.go
Labels: lgtm

#2764 Add tests to increase code coverage
  internal/scaffold/go_mod_test.go
  internal/scaffold/group_test.go
  internal/scaffold/tools_test.go
  pkg/ready/ready_test.go
Labels: lgtm

#2765 add changelog for issue 2742
  CHANGELOG.md
Labels: lgtm

#2749 Upgrade Molecule from 2.22 to 3.0.2
  CHANGELOG.md
  cmd/operator-sdk/new/cmd.go
  doc/ansible/dev/testing_guide.md
  doc/migration/version-upgrade-guide.md
  hack/tests/e2e-ansible-molecule.sh
  internal/scaffold/ansible/molecule_cluster_converge.go
  internal/scaffold/ansible/molecule_cluster_molecule.go
  internal/scaffold/ansible/molecule_default_converge.go
  internal/scaffold/ansible/molecule_default_molecule.go
  internal/scaffold/ansible/molecule_test_local_converge.go
  internal/scaffold/ansible/molecule_test_local_molecule.go
  internal/scaffold/ansible/travis.go
  test/ansible-memcached/molecule.yml
  test/ansible/deploy/crds/test.example.com_collectiontests_crd.yaml
  test/ansible/deploy/crds/test.example.com_exectests_crd.yaml
  test/ansible/deploy/crds/test.example.com_inventorytests_crd.yaml
  test/ansible/molecule/cluster/converge.yml
  test/ansible/molecule/cluster/molecule.yml
  test/ansible/molecule/test-local/converge.yml
  test/ansible/molecule/test-local/molecule.yml
  website/content/en/docs/ansible/testing-guide.md
  website/content/en/docs/migration/version-upgrade-guide.md
Labels: lgtm

#2766 Makefile: speed up make tasks that don't require Go deps
  Makefile
Labels: lgtm

#2767 added alpha scorecard config struct
  internal/scorecard/alpha/config.go
Labels: lgtm

#2771 [website-doc] Remove user-guide from website docs
  website/content/en/docs/user-guide.md
Labels: lgtm

#2752 Add migration docs to website
  website/content/en/docs/migration/v0.1.0-migration-guide.md
  website/content/en/docs/migration/version-upgrade-guide.md
Labels: lgtm

#2782 Bundle creation docs are missing code format
  cmd/operator-sdk/bundle/create.go
  doc/cli/operator-sdk_bundle_create.md
  website/content/en/docs/cli/operator-sdk_bundle_create.md
Labels: lgtm

#2783 Add frontmatter to contributor docs
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/contribution-guidelines/developer_guide.md
  website/content/en/docs/contribution-guidelines/local-docs.md
  website/content/en/docs/contribution-guidelines/release.md
  website/content/en/docs/contribution-guidelines/reporting-issues.md
  website/content/en/docs/contribution-guidelines/testing/_index.md
  website/content/en/docs/contribution-guidelines/testing/running-the-tests.md
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
Labels: lgtm

#2778 Scorecard2 label processing
  cmd/operator-sdk/alpha/scorecard/cmd.go
  internal/scorecard/alpha/config.go
  internal/scorecard/alpha/config_test.go
  internal/scorecard/alpha/labels_test.go
  internal/scorecard/alpha/scorecard.go
Labels: lgtm

#2777 [helm-operator] Fix reconciliation of resources with jsonpatch
  CHANGELOG.md
  go.mod
  go.sum
  pkg/helm/release/manager.go
  pkg/helm/release/manager_test.go
  test/test-framework/go.sum
Labels: lgtm

#2789 Fix broken internal links
  website/content/en/docs/ansible/development-tips.md
  website/content/en/docs/ansible/quickstart.md
  website/content/en/docs/ansible/reference/advanced_options.md
  website/content/en/docs/ansible/reference/retroactively-owned-resources.md
  website/content/en/docs/golang/olm-integration/csv-annotations.md
  website/content/en/docs/golang/olm-integration/generating-a-csv.md
  website/content/en/docs/migration/v0.1.0-migration-guide.md
  website/content/en/docs/migration/version-upgrade-guide.md
  website/content/en/docs/test-framework/writing-e2e-tests.md
Labels: lgtm

#2787 Look for more than just roles when detecting project type for Ansible-based Operators
  internal/util/projutil/project_util.go
Labels: lgtm

#2813 .travis.yml: use before_script as to not override test.before_install
  .travis.yml
Labels: lgtm, testing

#2816 remove unused bill-of-materials files
  bill-of-materials.json
  bill-of-materials.override.json
Labels: lgtm

#2824 user_setup scripts: add double quotes
  images/scorecard-proxy/bin/user_setup
  internal/scaffold/ansible/usersetup.go
  internal/scaffold/helm/usersetup.go
  internal/scaffold/usersetup.go
  internal/scaffold/usersetup_test.go
  test/test-framework/build/bin/user_setup
Labels: lgtm

#2776 generate csv: support manifests/ format with --make-manifests
  CHANGELOG.md
  Makefile
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/generate/csv.go
  doc/user/olm-catalog/generating-a-csv.md
  go.mod
  go.sum
  hack/tests/subcommand-generate-csv.sh
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_go_test.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/olm-catalog/csv_util.go
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/testdata/go/cmd/manager/main.go
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/manifests/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
  website/content/en/docs/cli/operator-sdk_generate_csv.md
  website/content/en/docs/golang/olm-integration/generating-a-csv.md
Labels: kind/feature, olm-catalog

#2818 [Website] - ansible docs - fix layout of testing with Molecule
  doc/ansible/dev/testing_guide.md
  website/content/en/docs/ansible/reference/information-flow-ansible-operator.md
  website/content/en/docs/ansible/testing-guide.md
Labels: lgtm

#2823 docs: organize local change testing info
  doc/dev/developer_guide.md
  doc/dev/local-changes.md
  doc/dev/local-docs.md
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/contribution-guidelines/local-changes.md
Labels: lgtm

#2830 Resources without generation will not skip events
  pkg/predicate/predicate.go
  test/ansible/molecule/cluster/tasks/secrets_test.yml
  test/ansible/playbooks/secret.yml
  test/ansible/watches.yaml
Labels: lgtm

#2833 website: reorganize testing docs
  doc/migration/version-upgrade-guide.md
  website/content/en/docs/golang/e2e-tests.md
  website/content/en/docs/migration/version-upgrade-guide.md
  website/content/en/docs/scorecard/_index.md
  website/content/en/docs/test-framework/_index.md
  website/content/en/docs/test-framework/scorecard.md
  website/content/en/docs/test-framework/writing-e2e-tests.md
Labels: kind/documentation, lgtm

#2846 changelog: update links
  CHANGELOG.md
Labels: lgtm

#2840 run --olm: support `metadata/annotations.yaml`
  CHANGELOG.md
  go.mod
  hack/tests/integration.sh
  internal/olm/operator/internal/configmap.go
  internal/olm/operator/internal/registry.go
  internal/olm/operator/manager.go
  internal/olm/operator/operator.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_run.md
Labels: kind/feature, olm-catalog

#2829 Scorecard2 stub test binary
  images/scorecard-test/cmd/test/main.go
  internal/scorecard/alpha/testdata/bundle/manifests/cache.example.com_memcacheds_crd.yaml
  internal/scorecard/alpha/testdata/bundle/manifests/memcached-operator.v0.0.1.clusterserviceversion.yaml
  internal/scorecard/alpha/testdata/bundle/metadata/annotations.yaml
  internal/scorecard/alpha/tests/basic_tests.go
  internal/scorecard/alpha/tests/bundle_test.go
  internal/scorecard/alpha/tests/olm_tests.go
  internal/scorecard/alpha/tests/test_bundle.go
Labels: lgtm

#2850 Makefile: fix script paths for 'gen-*' make targets
  Makefile
Labels: lgtm

#2859 internal/scaffold/helm/chart.go: change default API version
  changelog/fragments/helm-rm-default-api-version.yaml
  internal/scaffold/helm/chart.go
Labels: lgtm

#2842 Fix snake conversion
  changelog/fragments/fix-issue-2393.yaml
  pkg/ansible/paramconv/paramconv.go
  pkg/ansible/paramconv/paramconv_test.go
Labels: ansible-operator, kind/bug

#2858 plugins: wrap kubebuilder Go v2 plugin
  cmd/operator-sdk/cli/cli.go
  internal/plugins/golang/api.go
  internal/plugins/golang/config.go
  internal/plugins/golang/init.go
  internal/plugins/golang/plugin.go
  internal/plugins/plugins.go
Labels: kubebuilder-integration

#2856 go.mod,internal,test: remove OLM dependency
  go.mod
  go.sum
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/olm-catalog/csv_util.go
  internal/generate/olm-catalog/descriptor/descriptor.go
  internal/generate/olm-catalog/descriptor/descriptor_test.go
  internal/generate/olm-catalog/descriptor/parse.go
  internal/generate/olm-catalog/descriptor/parse_test.go
  internal/olm/client.go
  internal/olm/client/client.go
  internal/olm/operator/manager.go
  internal/olm/operator/olm.go
  internal/olm/operator/tenancy.go
  internal/scorecard/plugins/olm_tests.go
  internal/scorecard/plugins/plugin_runner.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
Labels: lgtm

#2852 remove inotify-tools dep and AoLogs scaffolded for ansible based-operator
  changelog/fragments/2852-pr.yaml
  cmd/operator-sdk/migrate/cmd.go
  hack/image/ansible/scaffold-ansible-image.go
  internal/scaffold/ansible/ao_logs.go
  internal/scaffold/ansible/dockerfilehybrid.go
Labels: ansible-operator, kind/cleanup

#2786 fix tech debt: remove the unmaintained github.com/ghodss/yaml dep
  cmd/operator-sdk/new/cmd.go
  cmd/operator-sdk/test/local.go
  go.mod
  go.sum
  internal/generate/crd/crd.go
  internal/generate/olm-catalog/csv.go
  internal/generate/olm-catalog/csv_go_test.go
  internal/generate/olm-catalog/csv_updaters.go
  internal/generate/olm-catalog/csv_updaters_test.go
  internal/generate/olm-catalog/csv_util.go
  internal/generate/olm-catalog/descriptor/descriptor_test.go
  internal/generate/olm-catalog/package_manifest.go
  internal/olm/operator/internal/configmap.go
  internal/scaffold/helm/role.go
  internal/scaffold/role.go
  internal/scorecard/config.go
  internal/scorecard/plugins/plugin_runner.go
  internal/scorecard/plugins/resource_handler.go
  internal/util/k8sutil/api.go
  internal/util/k8sutil/manifest.go
  pkg/ansible/watches/watches.go
  pkg/helm/controller/controller.go
  pkg/helm/watches/watches.go
  pkg/test/resource_creator.go
  test/integration/integration_helpers.go
  test/mockdata/kb-memcached-operator/go.sum
Labels: area/dependency, kind/cleanup, lgtm

#2865 remove index in order to keep all docs following the same standard
  doc/user/unit-testing.md
  website/content/en/docs/golang/unit-testing.md
  website/content/en/docs/scorecard/_index.md
Labels: lgtm

#2612 Add reconcile details
  doc/user-guide.md
  website/content/en/docs/golang/quickstart.md
Labels: lgtm, size/M

#2264 Adding context timeout for Ansible proxy
  changelog/fragments/fix-issue-bug-1701041.yaml
  pkg/ansible/proxy/cache_response.go
  pkg/ansible/proxy/proxy.go
Labels: ansible-operator, kind/bug, size/M

#2896 update to css
  website/assets/scss/_docs.scss
  website/assets/scss/_styles_project.scss
  website/content/en/build/_index.html
  website/content/en/build/_index.md
  website/content/en/docs/_index.md
  website/layouts/build/baseof.html
  website/layouts/docs/baseof.html
Labels: lgtm

#2894 bugfix: pass annotation value to strconv.ParseBool
  changelog/fragments/2884-fix.yaml
  pkg/helm/controller/reconcile.go
  pkg/helm/controller/reconcile_test.go
Labels: lgtm

#2874 internal/generate/crd: change default CRD to v1
  changelog/fragments/crd-default-v1.yaml
  internal/generate/crd/crd.go
  test/test-framework/deploy/crds/cache.example.com_memcachedrs_crd.yaml
  test/test-framework/deploy/crds/cache.example.com_memcacheds_crd.yaml
  website/content/en/docs/cli/operator-sdk_add_api.md
  website/content/en/docs/cli/operator-sdk_add_crd.md
  website/content/en/docs/cli/operator-sdk_generate_crds.md
  website/content/en/docs/cli/operator-sdk_new.md
Labels: lgtm

#2897 kubebuilder/quickstart: add instruction for enabling status subresource
  website/content/en/docs/kubebuilder/quickstart.md
Labels: kind/documentation

#2902 hack/generate/changelog: use sigs.k8s.io/yaml
  hack/generate/changelog/util/fragment.go
  hack/generate/changelog/util/fragment_test.go
Labels: lgtm

#2910 Remove under construction warning from docs
  website/content/en/docs/_index.md
  website/content/en/docs/ansible/_index.md
  website/content/en/docs/ansible/reference/_index.md
  website/content/en/docs/contribution-guidelines/_index.md
  website/content/en/docs/faq.md
  website/content/en/docs/helm/_index.md
  website/content/en/docs/helm/reference/_index.md
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/_index.md
  website/content/en/docs/versioning.md
Labels: lgtm

#2908 Fix last mod on docs
  website/config.toml
Labels: lgtm

#2911 website: update OLM integration docs
  cmd/operator-sdk/run/cmd.go
  doc/design/milestone-0.2.0/csv-generation.md
  doc/user-guide.md
  doc/user/olm-catalog/bundle-cli.md
  doc/user/olm-catalog/olm-cli.md
  website/content/en/docs/ansible/quickstart.md
  website/content/en/docs/cli/_index.md
  website/content/en/docs/cli/operator-sdk_run.md
  website/content/en/docs/golang/olm-integration/_index.md
  website/content/en/docs/golang/olm-integration/bundle-cli.md
  website/content/en/docs/golang/olm-integration/csv-annotations.md
  website/content/en/docs/golang/olm-integration/generating-a-csv.md
  website/content/en/docs/golang/olm-integration/olm-cli.md
  website/content/en/docs/golang/quickstart.md
  website/content/en/docs/golang/references/markers.md
  website/content/en/docs/helm/quickstart.md
  website/content/en/docs/kubebuilder/quickstart.md
  website/content/en/docs/olm-integration/_index.md
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/generating-a-csv.md
  website/content/en/docs/olm-integration/olm-deployment.md
  website/content/en/docs/olm-integration/user-guide.md
  website/content/en/docs/scorecard/_index.md
  website/layouts/shortcodes/table.html
Labels: kind/documentation

#2893 doc: add backport policy
  website/content/en/docs/contribution-guidelines/backport-policy.md
Labels: lgtm

#2921 website: ignore kubebuilder docs
  website/config.toml
Labels: lgtm

#2920 Updated Cyan colour palette - Merge only if colours are approved.
  website/assets/scss/_global.scss
  website/assets/scss/_header.scss
  website/assets/scss/_homepage.scss
  website/assets/scss/_variables.scss
  website/content/en/build/images/bg-masthead-SDK.svg
  website/content/en/build/images/bg-masthead-purple.svg
Labels: lgtm

#2919 internal/olm/operator: create a global OperatorGroup correctly
  internal/olm/operator/manager.go
  internal/olm/operator/olm.go
  internal/olm/operator/operator.go
  internal/olm/operator/tenancy.go
  test/integration/integration_helpers.go
  test/integration/operator_olm_test.go
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_run.md
Labels: kind/bug, olm-catalog

#2935 clean code: small nits in kbutils
  cmd/operator-sdk/main.go
  internal/util/kubebuilder/project.go
Labels: kind/cleanup

#2917 feat: add operator-sdk build to kb layout
  cmd/operator-sdk/build/cmd.go
  cmd/operator-sdk/cli/cli.go
  internal/util/projutil/project_util.go
Labels: kubebuilder-integration

#2941 go.mod: bump kubebuilder to a master commit for plugins
  go.mod
  go.sum
  internal/plugins/golang/config.go
  internal/plugins/golang/init.go
Labels: area/dependency, kubebuilder-integration, lgtm

#2944 generate csv: de-deprecate package manifests format
  changelog/fragments/2944-change.yaml
  cmd/operator-sdk/bundle/cmd.go
  cmd/operator-sdk/bundle/create.go
  cmd/operator-sdk/bundle/validate.go
  cmd/operator-sdk/generate/csv.go
  hack/lib/test_lib.sh
  hack/tests/subcommand-bundle.sh
  internal/generate/olm-catalog/package_manifest.go
  internal/generate/olm-catalog/package_manifest_test.go
  internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/memcached-operator.package.yaml
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_bundle.md
  website/content/en/docs/cli/operator-sdk_bundle_create.md
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/cli/operator-sdk_generate_csv.md
  website/content/en/docs/olm-integration/generating-a-csv.md
  website/content/en/docs/olm-integration/user-guide.md
Labels: olm-catalog

#2901 *: consolidate helm watch file management
  cmd/operator-sdk/add/api.go
  cmd/operator-sdk/new/cmd.go
  internal/scaffold/helm/testdata/testwatches/invalid/emptywatchfile/watches.yaml
  internal/scaffold/helm/testdata/testwatches/invalid/invalid_watch/watches.yaml
  internal/scaffold/helm/testdata/testwatches/valid-1/validWatches.yaml
  internal/scaffold/helm/testdata/testwatches/valid-2/validWatches.yaml
  internal/scaffold/helm/watches.go
  internal/scaffold/helm/watches_test.go
  pkg/helm/controller/controller.go
  pkg/helm/run.go
  pkg/helm/watches/watches.go
  pkg/helm/watches/watches_test.go
Labels: lgtm
