Repository operator-framework/operator-sdk, pull requests merged in 2020-09, with the labels that each got.

#3814 cleanup: remove unused code
  internal/util/k8sutil/k8sutil.go
  internal/util/projutil/exec.go
  internal/util/projutil/project_util.go
Labels: kind/cleanup, lgtm

#3813 manifest generation: remove `metadata.namespace` from manifests
  changelog/fragments/gen-bundle-namespaced.yaml
  internal/cmd/operator-sdk/generate/internal/genutil_suite_test.go
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/cmd/operator-sdk/generate/internal/manifests_test.go
Labels: lgtm

#3827 Use rpm installed setuptools
  hack/image/ansible/Dockerfile
Labels: lgtm

#3828 Revert "release v0.19.3 (#3817)"
  CHANGELOG.md
  changelog/fragments/3-alpha-config.yaml
  changelog/fragments/bundle-validate-verbose.yaml
  changelog/fragments/fix-csv-role-names.yaml
  changelog/fragments/fix-cve-2020-14040.yaml
  changelog/fragments/rescue-reconciliation.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.19.3.md
Labels: lgtm

#3830 Use rpm installed python-setuptools
  internal/scaffold/ansible/dockerfilehybrid.go
Labels: lgtm

#3836 release v0.19.3
  CHANGELOG.md
  changelog/fragments/3-alpha-config.yaml
  changelog/fragments/bundle-validate-verbose.yaml
  changelog/fragments/fix-csv-role-names.yaml
  changelog/fragments/fix-cve-2020-14040.yaml
  changelog/fragments/fix-find-metadata-dir.yaml
  changelog/fragments/rescue-reconciliation.yaml
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
  website/content/en/docs/install-operator-sdk.md
  website/content/en/docs/migration/v0.19.3.md
Labels: lgtm

#3788 MD5 out... in with SHA256
  .golangci.yml
  internal/olm/operator/registry/configmap/configmap.go
Labels: lgtm

#3837 post 0.19.3 version bump
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  version/version.go
Labels: lgtm

#3841 Include 0.19.x stream in the changelog
  CHANGELOG.md
Labels: lgtm

#3838 [run bundle] Install plan generation and approval for subscription
  internal/cmd/operator-sdk/run/cmd.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/registry/catalog.go
  internal/olm/operator/registry/olm_resources.go
  internal/olm/operator/registry/operator_installer.go
Labels: lgtm

#3852 Ignore some untracked files
  release.sh
Labels: lgtm

#3834 Fixes annotations on Ansible development tips
  website/content/en/docs/building-operators/ansible/development-tips.md
Labels: lgtm

#3856 internal/olm/operator: fix operator-registry image for run packagemanifests
  changelog/fragments/fix-run-packagemanifests-e2e.yaml
  hack/tests/integration.sh
  internal/olm/client/client.go
  internal/olm/operator/registry/configmap/deployment.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/bug, olm-catalog

#3866 :book: fix broken links
  website/content/en/docs/building-operators/golang/project_migration_guide.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
Labels: lgtm

#3853 docs/upgrade-sdk-version: fix v0.17.x version reference, condense v1.0.0 guides
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/upgrading-sdk-version/_index.md
  website/content/en/docs/upgrading-sdk-version/v0.19.0.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.2.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: kind/documentation

#3864 Fix a typo in the header
  website/content/en/docs/overview/_overview.md
Labels: lgtm

#3819 run bundle: Add deployment status check when verifying installed operator.
  internal/olm/client/client.go
  internal/olm/client/client_suite_test.go
  internal/olm/client/client_test.go
Labels: lgtm

#3845 bugfix: use the tags in the scorecard scaffolded manifests
  changelog/fragments/scorecard_scaffolded_version.yaml
  internal/plugins/scorecard/init.go
Labels: scorecard

#3854 Makefile,internal/version: inject version based on git tree
  .travis.yml
  Makefile
  internal/cmd/operator-sdk/version/cmd.go
  internal/version/version.go
  website/content/en/docs/contribution-guidelines/release.md
Labels: lgtm

#3855 .travis.yml: re-enable s390x, consolidate builds
  .travis.yml
  Makefile
  changelog/fragments/travis-deploy-consolidate.yaml
Labels: lgtm

#3869 Drop the use of memecached in Go migration docs
  website/content/en/docs/building-operators/golang/migration.md
Labels: lgtm

#3822 for helm/ansible fix msg for multigroup support
  changelog/fragments/ansible-helm-multigroup.yaml
  internal/plugins/ansible/v1/scaffolds/api.go
  internal/plugins/helm/v1/scaffolds/api.go
Labels: kind/bug, lgtm

#3883 restrict autoprefixer version
  netlify.toml
Labels: lgtm

#3886 [v0.19.x] Relax csv name validation
  changelog/fragments/relax-csv-name-validation-v0.19.x.yaml
  go.mod
  go.sum
  netlify.toml
Labels: lgtm

#3891 Fix broken Go e2e link
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
Labels: lgtm

#3887 Relax csv name validation
  changelog/fragments/relax-csv-name-validation.yaml
  go.mod
  go.sum
Labels: lgtm

#3893 [1.0.x] Fix broken links
  netlify.toml
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
  website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
  website/content/en/docs/building-operators/golang/project_migration_guide.md
  website/content/en/docs/building-operators/golang/references/envtest-setup.md
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
Labels: lgtm

#3895 [v1.0.x] *: fix run packagemanifests
  changelog/fragments/fix-run-packagemanifests-e2e.yaml
  changelog/fragments/run-pkgmnfs-writable-dir.yaml
  hack/tests/integration.sh
  internal/olm/client/client.go
  internal/olm/operator/internal/deployment.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e/e2e_suite_test.go
Labels: lgtm

#3894 [v0.19.x] *: fix run packagemanifests
  changelog/fragments/fix-run-packagemanifests-e2e.yaml
  changelog/fragments/run-pkgmnfs-writable-dir.yaml
  hack/tests/integration.sh
  internal/olm/client/client.go
  internal/olm/operator/internal/deployment.go
  test/e2e-new/e2e_suite.go
Labels: lgtm

#3898 Replace method 'Should(Succeed())' with 'NotTo(HaveOccurred())'
  test/e2e-ansible/e2e_ansible_cluster_test.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
  test/e2e-go/e2e_go_cluster_test.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-go/e2e_go_suite_test.go
  test/e2e-helm/e2e_helm_cluster_test.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e-helm/e2e_helm_suite_test.go
Labels: lgtm

#3899 [v1.0.x] Backports
  changelog/fragments/bundle-validate-verbose.yaml
  changelog/fragments/csv-allnamespaces-default.yaml
  changelog/fragments/gen-bundle-namespaced.yaml
  changelog/fragments/helm-install-status-fix.yaml
  changelog/fragments/helm-roles-permissions.yaml
  changelog/fragments/operatorgroup-conflict.yaml
  changelog/fragments/rescue-reconciliation.yaml
  changelog/fragments/scorecard_scaffolded_version.yaml
  internal/ansible/controller/reconcile.go
  internal/ansible/runner/eventapi/types.go
  internal/cmd/operator-sdk/bundle/validate.go
  internal/cmd/operator-sdk/bundle/validate_test.go
  internal/cmd/operator-sdk/generate/internal/genutil_suite_test.go
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/cmd/operator-sdk/generate/internal/manifests_test.go
  internal/generate/clusterserviceversion/bases/clusterserviceversion.go
  internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/clusterserviceversions/bases/with-ui-metadata.clusterserviceversion.yaml
  internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
  internal/helm/controller/reconcile.go
  internal/olm/operator/operator_suite_test.go
  internal/olm/operator/packagemanifests_manager.go
  internal/olm/operator/tenancy.go
  internal/olm/operator/tenancy_test.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
  internal/plugins/scorecard/init.go
  internal/scorecard/examples/custom-scorecard-tests/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  internal/scorecard/testdata/bundle.tar.gz
  internal/scorecard/testdata/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: lgtm

#3876 Fix Migration Guide link
  changelog/fragments/fix-migration-guide-link.yaml
  cmd/operator-sdk/main.go
Labels: lgtm

#3890 remove references to --manifests command in generate packagemanifest docs
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Labels: lgtm

#3915 [v1.0.x] *: use CI-built scorecard images during e2e tests
  Makefile
  hack/image/build-ansible-image.sh
  hack/image/build-helm-image.sh
  hack/image/build-scorecard-test-image.sh
  hack/image/build-scorecard-test-kuttl-image.sh
  hack/tests/e2e-ansible.sh
  hack/tests/e2e-go.sh
  test/e2e-helm/e2e_helm_suite_test.go
  test/e2e/e2e_suite_test.go
  test/internal/utils.go
Labels: lgtm

#3901 *: release v1.0.1
  CHANGELOG.md
  changelog/fragments/3761.yaml
  changelog/fragments/bundle-validate-verbose.yaml
  changelog/fragments/csv-allnamespaces-default.yaml
  changelog/fragments/fix-run-packagemanifests-e2e.yaml
  changelog/fragments/gen-bundle-namespaced.yaml
  changelog/fragments/helm-install-status-fix.yaml
  changelog/fragments/helm-roles-permissions.yaml
  changelog/fragments/operatorgroup-conflict.yaml
  changelog/fragments/relax-csv-name-validation-v1.0.x.yaml
  changelog/fragments/rescue-reconciliation.yaml
  changelog/fragments/run-pkgmnfs-writable-dir.yaml
  changelog/fragments/scorecard_scaffolded_version.yaml
  internal/version/version.go
  website/content/en/docs/installation/install-operator-sdk.md
  website/content/en/docs/upgrading-sdk-version/v1.0.1.md
Labels: lgtm

#3903 `generate`: default CSV `admissionReviewVersions` and `sideEffects`
  changelog/fragments/csv-whdescs-defaults.yaml
  internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
  internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
Labels: kind/feature, lgtm

#3917 CHANGELOG.md: add v0.19.4 and v1.0.1
  CHANGELOG.md
Labels: lgtm

#3914 [e2e-test] Added the ginkgo style checks for e2e tests
  test/e2e-ansible/e2e_ansible_cluster_test.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-go/e2e_go_cluster_test.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-helm/e2e_helm_cluster_test.go
  test/e2e-helm/e2e_helm_olm_test.go
Labels: lgtm

#3920 Centralize the logic for scorecard dev image replacement
  test/e2e-ansible/e2e_ansible_suite_test.go
  test/e2e-go/e2e_go_suite_test.go
  test/e2e-helm/e2e_helm_suite_test.go
  test/internal/scorecard.go
Labels: lgtm

#3926 fix upgrade version menu
  website/content/en/docs/upgrading-sdk-version/v0.1.0-migration-guide.md
  website/content/en/docs/upgrading-sdk-version/v0.18.0.md
  website/content/en/docs/upgrading-sdk-version/v0.19.0.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: lgtm

#3932 Revert "updates to add message from Paul"
  website/assets/scss/_homepage.scss
  website/content/en/build/images/message.png
  website/layouts/index.html
Labels: lgtm

#3861 run bundle: OperatorGroup Install modes
  internal/olm/operator/bundle/install.go
  internal/olm/operator/install_mode.go
  internal/olm/operator/install_mode_test.go
  internal/olm/operator/operator_suite_test.go
  internal/olm/operator/packagemanifests/install.go
  internal/olm/operator/registry/operator_installer.go
  internal/olm/operator/registry/operator_installer_test.go
  internal/olm/operator/registry/operatorgroup_test.go
Labels: lgtm

#3719 `bundle validate`: enable optional validators
  changelog/fragments/bundle-validate-optional-validators.yaml
  internal/cmd/operator-sdk/bundle/cmd.go
  internal/cmd/operator-sdk/bundle/validate/cmd.go
  internal/cmd/operator-sdk/bundle/validate/cmd_suite_test.go
  internal/cmd/operator-sdk/bundle/validate/internal/logger.go
  internal/cmd/operator-sdk/bundle/validate/internal/result.go
  internal/cmd/operator-sdk/bundle/validate/internal/result_test.go
  internal/cmd/operator-sdk/bundle/validate/optional.go
  internal/cmd/operator-sdk/bundle/validate/optional_test.go
  internal/cmd/operator-sdk/bundle/validate/validate.go
  internal/cmd/operator-sdk/bundle/validate/validate_test.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/olm-integration/generation.md
Labels: do-not-merge/hold, kind/feature

#3935 Pin to ansible 2.9
  .travis.yml
Labels: lgtm

#3929 remove versioning doc
  website/content/en/docs/upgrading-sdk-version/operator-sdk-versioning.md
Labels: lgtm

#3879 docs/contribution-guidelines: improve formatting, remove specifics of tests
  website/content/en/docs/contribution-guidelines/_index.md
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/contribution-guidelines/documentation.md
  website/content/en/docs/contribution-guidelines/local-changes.md
  website/content/en/docs/contribution-guidelines/local-docs.md
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/contribution-guidelines/reporting-issues.md
  website/content/en/docs/contribution-guidelines/testing.md
  website/content/en/docs/contribution-guidelines/testing/_index.md
  website/content/en/docs/contribution-guidelines/testing/running-the-tests.md
  website/content/en/docs/contribution-guidelines/testing/travis-build.md
Labels: kind/documentation, lgtm

#3907 [olm] Improve error message in olm install cmd
  changelog/fragments/olm-improve-logs.yaml
  internal/olm/installer/client.go
Labels: lgtm

#3936 deps: fix upstream JSON patch issues
  go.mod
  go.sum
Labels: lgtm

#3942 changelog/fragments: add bugfix 3936 fragment
  changelog/fragments/helm-json-patch-bug.yaml
Labels: lgtm

#3705 doc: operator-scope update examples with the new layout and clarifies steps.
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: kind/documentation

#3940 [v0.19.x] deps: fix upstream JSON patch issues (#3936)
  changelog/fragments/helm-json-patch-bug.yaml
  go.mod
  go.sum
  internal/scaffold/ansible/go_mod.go
  internal/scaffold/go_mod.go
  internal/scaffold/helm/go_mod.go
  test/test-framework/go.mod
Labels: lgtm

#3956 docs/building-operators/ansible/testing-guide.md: pin links to v2.9
  website/content/en/docs/building-operators/ansible/testing-guide.md
Labels: lgtm

#3954 OWNERS: add jberkhahn as reviewer
  OWNERS
Labels: lgtm

#3953 go.mod: bump operator-registry to v1.14.3 for bundle validation improvements
  changelog/fragments/bump-operator-registry.yaml
  go.mod
  go.sum
Labels: lgtm

#3957 bump kuttl version to 0.6.1 in scorecard-test-kuttl
  changelog/fragments/scorecard-kuttl-image-bump-061.yaml
  images/scorecard-test-kuttl/Dockerfile
Labels: lgtm

#3961 change kutt-test.yaml to specify suppressLog setting
  internal/scorecard/testdata/bundle.tar.gz
  internal/scorecard/testdata/bundle/tests/scorecard/kuttl/kuttl-test.yaml
  website/content/en/docs/advanced-topics/scorecard/kuttl-tests.md
Labels: lgtm

#3960 [v0.19.x] *: bump operator-registry to v1.14.3
  changelog/fragments/bump-operator-registry.yaml
  go.mod
  go.sum
Labels: lgtm
