Repository operator-framework/operator-sdk, pull requests merged in 2020-12, with the labels that each got.

#4266 .github/workflows: skip e2e/integration tests when PR is docs-only
  .github/workflows/integration.yml
  .github/workflows/markdown-link-check-config.json
  .github/workflows/markdown.yml
  .github/workflows/test-ansible.yml
  .github/workflows/test-go.yml
  .github/workflows/test-helm.yml
  .github/workflows/test-sanity.yml
  .travis.yml
  hack/ci/check-doc-only-update.sh
Labels: lgtm

#4264 Add an import statement to the Go building operators tutorial
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: lgtm

#4236 Fix missing url for operator_install
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: lgtm

#4254 generate: add `order=<int>` CSV marker fields
  changelog/fragments/csv-order.yaml
  internal/generate/clusterserviceversion/bases/definitions/crd.go
  internal/generate/clusterserviceversion/bases/definitions/crd_test.go
  internal/generate/clusterserviceversion/bases/definitions/definitions.go
  internal/generate/clusterserviceversion/bases/definitions/definitions_suite_test.go
  internal/generate/clusterserviceversion/bases/definitions/definitions_test.go
  internal/generate/clusterserviceversion/bases/definitions/markers.go
  internal/generate/clusterserviceversion/bases/definitions/zz_generated.markerhelp.go
  website/content/en/docs/building-operators/golang/references/markers.md
Labels: kind/feature, lgtm

#4276 generate: fix "invalid CSV name" bug
  changelog/fragments/csv-base-name-bugfix.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/bundle/cmd.go
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/generate/clusterserviceversion/bases/clusterserviceversion.go
  internal/generate/clusterserviceversion/bases/metadata_test.go
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/clusterserviceversions/bases/with-ui-metadata.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  website/content/en/docs/olm-integration/generation.md
Labels: kind/bug, lgtm

#4242 Add bindata for OLM release 0.17.0
  Makefile
  changelog/fragments/add-0.17.0-olm-bindata.yaml
  hack/generate/olm_bindata.sh
  hack/tests/integration.sh
  hack/tests/subcommand-olm-install.sh
  internal/bindata/olm/manifests.go
  internal/bindata/olm/versions.go
  internal/olm/installer/client.go
  internal/testutils/olm.go
Labels: lgtm

#4283 e2e-intgration-tests: keep using OLM version 0.15.1
  hack/tests/integration.sh
Labels: lgtm

#4288 fix: (helm) - prevent a possible nil pointer in the helm uninstall
  internal/helm/controller/reconcile.go
  internal/helm/release/manager.go
Labels: lgtm

#4056 test-e2e/go : using samples
  hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  test/e2e-go/e2e_go_cluster_test.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-go/e2e_go_scorecard_test.go
  test/e2e-go/e2e_go_suite_test.go
  testdata/go/v2/memcached-operator/api/v1alpha1/memcached_webhook.go
  testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v2/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
Labels: area/testing

#4300 test/e2e-go: fix reconcile check
  test/e2e-go/e2e_go_cluster_test.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-go/e2e_go_scorecard_test.go
  test/e2e-go/e2e_go_suite_test.go
Labels: area/testing, lgtm

#4298 OLM client: Wait till the deployment appear
  internal/olm/client/client.go
Labels: lgtm

#4303 test/integration: rewrite in BDD style, fixup `cleanup` command
  Makefile
  changelog/fragments/cleanup-all-resources.yaml
  hack/tests/integration.sh
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/olm/operator/uninstall.go
  internal/testutils/olm.go
  test/e2e-go/e2e_go_olm_test.go
  test/integration/integration_helpers.go
  test/integration/integration_suite_test.go
  test/integration/operator_olm_test.go
  test/integration/packagemanifests_test.go
  website/content/en/docs/olm-integration/generation.md
Labels: area/testing, do-not-merge/hold

#4313 netlify.toml: pin postcss dependency to ^8.0.0, recursive submodule update
  hack/ci/check-doc-only-update.sh
  netlify.toml
  website/assets/scss/_styles_project.scss
  website/package-lock.json
Labels: lgtm

#4315 test/: clean up some e2e setup code
  internal/testutils/utils.go
  test/e2e-ansible/e2e_ansible_cluster_test.go
  test/e2e-go/e2e_go_cluster_test.go
  test/e2e-helm/e2e_helm_cluster_test.go
Labels: lgtm

#4309 olm/operator: fix issue in wrapping error
  internal/olm/operator/registry/operator_installer.go
Labels: lgtm

#4144 test-e2e/samples/cleanup: centralize code to integrate the project with OLM
  hack/generate/samples/internal/ansible/memcached.go
  hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  hack/generate/samples/internal/helm/memcached.go
  hack/generate/samples/internal/pkg/utils.go
  internal/testutils/olm.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
  test/e2e-go/e2e_go_suite_test.go
  test/e2e-helm/e2e_helm_olm_test.go
  test/e2e-helm/e2e_helm_suite_test.go
Labels: lgtm

#4333 docs: update old links, FAQ, and Reconcile() code references
  website/content/en/docs/building-operators/golang/advanced-topics.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/references/client.md
  website/content/en/docs/building-operators/golang/references/logging.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/faqs/_index.md
Labels: kind/documentation, lgtm

#4332 Makefile: bump IMAGE_VERSION to v1.3.0
  Makefile
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: lgtm

#4336 docs/building-operators: update and align tutorials
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/tutorial.md
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
Labels: do-not-merge/hold, kind/documentation

#4340 helm/samples: customize config/sample to allow it runs in OCP with default config
  hack/generate/samples/internal/helm/memcached.go
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
Labels: lgtm
