Repository operator-framework/operator-sdk, pull requests merged in 2020-11, with the labels that each got.

#4134 test/e2e-helm: use generated helm sample
  internal/testutils/utils.go
  test/e2e-helm/e2e_helm_cluster_test.go
  test/e2e-helm/e2e_helm_suite_test.go
Labels: approved, lgtm

#4159 docs/building-operators/helm/tutorial: remove unsupported 'operator-sdk run local'
  website/content/en/docs/building-operators/helm/tutorial.md
Labels: lgtm

#4161 docs/building-operators/helm/tutorial: Remove unsupported 'operator-sdk run local' (Cherry pick for v1.1.x )
  website/content/en/docs/building-operators/helm/tutorial.md
Labels: lgtm

#4160 docs/building-operators/helm/tutorial: Remove unsupported 'operator-sdk run local' (Cherry pick for v1.0.x )
  website/content/en/docs/building-operators/helm/tutorial.md
Labels: lgtm

#4164 website: Fix the watches.yaml backticks in the Ansible migration guide
  website/content/en/docs/building-operators/ansible/migration.md
Labels: lgtm

#4167 Docs: Re-enable compact left-side bar
  website/config.toml
Labels: lgtm

#4155 testutils/cleanup: remove InstallOLM method that is no lonnger used
  internal/testutils/utils.go
Labels: lgtm

#4181 internal/olm/installer: prepend 'v' to semvers >= 0.17.0
  changelog/fragments/olm-version-v.yaml
  internal/olm/installer/client.go
  internal/olm/installer/client_test.go
  internal/olm/installer/installer_suite_test.go
Labels: lgtm

#4162 add finalizer rbac permission to the go/sample and doc steps
  hack/generate/samples/internal/go/memcached_with_webhooks.go
  testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/config/rbac/role.yaml
  testdata/go/memcached-operator/controllers/memcached_controller.go
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/faqs/faqs.md
Labels: lgtm

#4185 docs/olm-integration/quickstart-package-manifests.md: fix Makefile target link
  website/content/en/docs/olm-integration/quickstart-package-manifests.md
Labels: kind/documentation, lgtm

#4142 test-e2e/ansible : using samples
  hack/generate/samples/internal/ansible/constants.go
  hack/generate/samples/internal/ansible/molecule.go
  test/e2e-ansible/e2e_ansible_cluster_test.go
  test/e2e-ansible/e2e_ansible_olm_test.go
  test/e2e-ansible/e2e_ansible_suite_test.go
  testdata/ansible/memcached-operator/roles/memcached/tasks/main.yml
Labels: lgtm

#4165 Add unit tests for operator_installer.go
  internal/olm/operator/registry/olm_resources_test.go
  internal/olm/operator/registry/operator_installer.go
  internal/olm/operator/registry/operator_installer_test.go
Labels: lgtm

#4186 Makefile: add submodule checkout to 'test-links'
  Makefile
Labels: lgtm

#4197 Makfile,testdata: bump IMAGE_VERSION to v1.2.0, regenerate samples
  Makefile
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
Labels: lgtm

#4187 ansible-operator,helm-operator: improve executable help text
  changelog/fragments/ansible-helm-help-text.yaml
  cmd/ansible-operator/main.go
  cmd/helm-operator/main.go
Labels: lgtm

#4199 deps: exclude github.com/spf13/viper@v1.3.2 to fix CVE-2018-1098
  changelog/fragments/CVE-2018-1098.yaml
  go.mod
  go.sum
Labels: area/dependency

#4205 hack/check-links.sh: add 'ignore' check options
  hack/check-error-log-msg-format.sh
  hack/check-license.sh
  hack/check-links.sh
  hack/lib/common.sh
  hack/lib/test_lib.sh
  hack/tests/e2e-ansible-molecule.sh
  hack/tests/integration.sh
Labels: lgtm

#4213 hack/generate/samples: strip operator-sdk metrics annotations
  hack/generate/samples/internal/ansible/memcached.go
  hack/generate/samples/internal/go/memcached_with_webhooks.go
  hack/generate/samples/internal/helm/memcached.go
  hack/generate/samples/internal/pkg/utils.go
  internal/testutils/olm.go
  test/e2e-go/e2e_go_olm_test.go
  test/e2e-go/e2e_go_suite_test.go
  testdata/ansible/memcached-operator/bundle.Dockerfile
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/bundle/metadata/annotations.yaml
  testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/bundle.Dockerfile
  testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/memcached-operator/bundle/metadata/annotations.yaml
  testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/bundle.Dockerfile
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/bundle/metadata/annotations.yaml
  testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
Labels: lgtm

#4208 doc: fix typo in scorecard content of website
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
Labels: lgtm

#4188 Add tests for registry/configmap.go
  internal/olm/operator/registry/configmap_test.go
Labels: lgtm

#4219 release/Makefile: honor GOOS and GOARCH when building release binaries
  release/Makefile
Labels: lgtm

#4218 feat: doc standard for changelog
  changelog/fragments/00-template.yaml
Labels: lgtm

#4222 increase timeout for the scorecard tests
  test/e2e-ansible/e2e_ansible_scorecard_test.go
  test/e2e-go/e2e_go_scorecard_test.go
  test/e2e-helm/e2e_helm_scorecard_test.go
Labels: lgtm

#4004 [docs] Improve Website Styling
  website/assets/scss/_breadcrumb.scss
  website/assets/scss/_docs.scss
  website/assets/scss/_global.scss
  website/assets/scss/_sidebar-tree.scss
  website/assets/scss/_styles_project.scss
  website/assets/scss/_variables.scss
  website/content/en/build/_index.html
  website/content/en/docs/building-operators/_index.md
  website/content/en/docs/building-operators/ansible/installation.md
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/installation.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/tutorial.md
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/faqs/_index.md
  website/content/en/docs/installation/_index.md
  website/content/en/docs/overview/_index.md
  website/layouts/partials/section-index.html
  website/package-lock.json
Labels: lgtm

#4227 website: remove confusing/unnecessary install helm/ansible instructions
  website/content/en/docs/installation/_index.md
Labels: lgtm

#4220 internal/cmd: add build info metric in helm/ansible operators
  changelog/fragments/helm-ansible-version-metric.yaml
  internal/ansible/metrics/metrics.go
  internal/cmd/ansible-operator/run/cmd.go
  internal/cmd/helm-operator/run/cmd.go
  internal/helm/metrics/metrics.go
Labels: lgtm

#4247 sample generation fixes
  hack/generate/samples/internal/helm/memcached.go
  hack/generate/samples/internal/pkg/utils.go
Labels: lgtm

#4250 doc: fix log statement in multi namespace example
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: lgtm

#4034 *: automate releases with goreleaser
  .ci/gpg/create-keyring.sh
  .ci/gpg/pubring.auto
  .ci/gpg/secring.auto.gpg
  .gitignore
  .goreleaser.yml
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  hack/image/push-image-tags.sh
  hack/image/push-manifest-list.sh
  netlify.toml
  release.sh
  release/Makefile
  tools/scripts/fetch
  website/config.toml
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/contribution-guidelines/testing.md
  website/content/en/docs/installation/_index.md
  website/scripts/set_menu_version.sh
  website/scripts/update_branch_mappings.sh
Labels: lgtm
