Repository operator-framework/operator-sdk, pull requests merged in 2021-03, with the labels that each got.

#4554 ci: replace travis completely with github actions
  .ci/gpg/create-keyring.sh
  .github/workflows/deploy.yml
  .travis.yml
  Makefile
  README.md
  hack/ci/check-doc-only-update.sh
  hack/image/push-image-tags.sh
  hack/image/push-manifest-list.sh
  hack/lib/image_lib.sh
  hack/tests/e2e-ansible-molecule.sh
  images/ansible-operator/Dockerfile
  images/custom-scorecard-tests/Dockerfile
  images/helm-operator/Dockerfile
  images/operator-sdk/Dockerfile
  images/scorecard-test-kuttl/Dockerfile
  images/scorecard-test/Dockerfile
  release/Makefile
  test/e2e/ansible/cluster_test.go
  test/e2e/helm/cluster_test.go
  website/content/en/docs/contribution-guidelines/developer-guide.md
Labels: area/testing, lgtm

#4584 (helm/v1) run `create api` plugin only after `init` plugin finishes execution
  changelog/fragments/bugfix-4575.yaml
  hack/generate/samples/internal/helm/memcached.go
  internal/plugins/helm/v1/api.go
  internal/plugins/helm/v1/chartutil/chart.go
  internal/plugins/helm/v1/chartutil/chart_test.go
  internal/plugins/helm/v1/init.go
  internal/plugins/helm/v1/scaffolds/api.go
  internal/plugins/helm/v1/scaffolds/init.go
Labels: kind/bug, lgtm

#4552 test/: refactor scorecard e2e test, clean up existing test poll funcs
  test/common/scorecard.go
  test/e2e/ansible/cluster_test.go
  test/e2e/ansible/scorecard_test.go
  test/e2e/ansible/suite_test.go
  test/e2e/go/cluster_test.go
  test/e2e/go/scorecard_test.go
  test/e2e/go/suite_test.go
  test/e2e/helm/cluster_test.go
  test/e2e/helm/scorecard_test.go
  test/e2e/helm/suite_test.go
Labels: area/testing, lgtm

#4555 ci: add ansible-operator-base image and manual build workflow
  .github/workflows/deploy-manual.yml
  images/ansible-operator/Dockerfile
  images/ansible-operator/base.Dockerfile
Labels: area/dependency

#4598 Document olm version support
  website/content/en/docs/overview/_index.md
Labels: lgtm

#4603 actions/deploy-manual: checkout before tag creation for git data
  .github/workflows/deploy-manual.yml
Labels: lgtm

#4068 internal/generate/clusterserviceversion: add tests for apply{Cluster}Roles()
  internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
Labels: lifecycle/rotten

#4608 images/ansible-operator/base.Dockerfile: move some setup out of base image
  images/ansible-operator/base.Dockerfile
Labels: lgtm

#4604 actions/deploy: check if docs-only before running
  .github/workflows/deploy.yml
Labels: lgtm

#4612 deps: bump controller-runtime to v0.8.2 and controller-tools to v0.5.0
  go.mod
  go.sum
Labels: area/dependency, lgtm

#4622 testdata: remove unnecessary newlines
  internal/testutils/utils.go
  testdata/ansible/memcached-operator/config/default/kustomization.yaml
  testdata/go/v2/memcached-operator/config/default/kustomization.yaml
  testdata/go/v3/memcached-operator/config/default/kustomization.yaml
  testdata/helm/memcached-operator/config/default/kustomization.yaml
Labels: lgtm

#4626 deps: bump kubebuilder to dd3942c
  changelog/fragments/kubebuilder-dd3942c.yaml
  go.mod
  go.sum
  internal/plugins/ansible/v1/api.go
  internal/plugins/helm/v1/api.go
  test/e2e/go/cluster_test.go
  test/e2e/go/suite_test.go
  testdata/go/v2/memcached-operator/go.mod
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/manager/manager.yaml
  testdata/go/v3/memcached-operator/config/rbac/auth_proxy_role_binding.yaml
  testdata/go/v3/memcached-operator/config/rbac/kustomization.yaml
  testdata/go/v3/memcached-operator/config/rbac/leader_election_role_binding.yaml
  testdata/go/v3/memcached-operator/config/rbac/role_binding.yaml
  testdata/go/v3/memcached-operator/config/rbac/service_account.yaml
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/go.mod
  testdata/go/v3/memcached-operator/go.sum
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
  website/content/en/docs/advanced-topics/scorecard/kuttl-tests.md
  website/content/en/docs/building-operators/golang/migration.md
Labels: area/dependency

#4630 website/content: update non-existent coreos.com blogpost link to openshift.com
  website/content/en/_index.html
  website/content/en/docs/overview/_index.md
Labels: kind/documentation, lgtm

#4632 .github/workflows: use 'github.repository_owner' in image tags
  .github/workflows/deploy-manual.yml
  .github/workflows/deploy.yml
Labels: area/testing

#4631 [v1.4.x] hack/tests/e2e-ansible-molecule.sh: pin openshift and cryptography (#4588)
  hack/tests/e2e-ansible-molecule.sh
Labels: area/testing

#4613 config3alphato3: convert config version 3-alpha to 3
  changelog/fragments/confg-3-alpha-removed.yaml
  go.mod
  internal/cmd/operator-sdk/alpha/cmd.go
  internal/cmd/operator-sdk/alpha/config3alphato3/cmd.go
  internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3.go
  internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3_test.go
  internal/cmd/operator-sdk/alpha/config3alphato3/suite_test.go
  internal/cmd/operator-sdk/cli/cli.go
  website/content/en/docs/cli/operator-sdk.md
  website/content/en/docs/cli/operator-sdk_alpha.md
  website/content/en/docs/cli/operator-sdk_alpha_config-3alpha-to-3.md
Labels: kind/feature, release-blocker

#4637 docs: remove redundancy in Go migration, discuss service account in scope doc
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: kind/documentation, lgtm

#4639 release: update samples tag 1.5.0
  Makefile
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
Labels: do-not-merge/hold, lgtm

#4646 Release v1.5.0
  changelog/fragments/align-kb.yaml
  changelog/fragments/ansible-graceful-shutdown-timeout.yaml
  changelog/fragments/bugfix-3744.yaml
  changelog/fragments/bugfix-4575.yaml
  changelog/fragments/bugfix-nonexistent-apis-dir-generate-bundle.yaml
  changelog/fragments/bump-cryptography-dep.yaml
  changelog/fragments/confg-3-alpha-removed.yaml
  changelog/fragments/fix-generate-bundle-flags.yaml
  changelog/fragments/kube-rbac-proxy.yaml
  changelog/fragments/kubebuilder-dd3942c.yaml
  changelog/fragments/make-ansible-logs-debug.yaml
  changelog/fragments/swap-readiness-liveness-paths-4541.yaml
  changelog/generated/v1.5.0.md
  website/config.toml
  website/content/en/docs/upgrading-sdk-version/v1.5.0.md
Labels: lgtm

#4406 (manifests/v2) add catalog targets to Makefile
  changelog/fragments/make-catalog-build.yaml
  internal/plugins/manifests/api.go
  internal/plugins/manifests/init.go
  testdata/ansible/memcached-operator/Makefile
  testdata/go/v2/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
  website/content/en/docs/olm-integration/quickstart-bundle.md
Labels: lgtm

#4633 release: push scorecard-test-kuttl images on `scorecard-kuttl/v*` tags
  .github/workflows/deploy.yml
  .github/workflows/get_image_tags.sh
  .github/workflows/integration.yml
  .github/workflows/test-ansible.yml
  .github/workflows/test-go.yml
  .github/workflows/test-helm.yml
  .github/workflows/test-sanity.yml
  images/scorecard-test-kuttl/main.go
  release/Makefile
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: priority/important-soon, scorecard

#4557 Upgrade kuttl testing image to 0.9.0 version
  images/scorecard-test-kuttl/Dockerfile
Labels: lgtm, ok-to-test

#4543 Use pipenv for python dependency management
  changelog/fragments/use-pipenv-for-python-package-installation.yaml
  images/ansible-operator/Pipfile
  images/ansible-operator/Pipfile.lock
  images/ansible-operator/base.Dockerfile
Labels: lgtm, ok-to-test

#4566 [ansible]: mark variables from custom resources as unsafe
  changelog/fragments/mark-variables-unsafe.yaml
  internal/ansible/runner/runner.go
  internal/ansible/runner/runner_test.go
  internal/ansible/watches/testdata/valid.yaml.tmpl
  internal/ansible/watches/watches.go
  internal/ansible/watches/watches_test.go
Labels: lgtm

#4655 ansible/helm: add ssc to not allow root previleges
  changelog/fragments/ansible-helm-ssc.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/manager/manager.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/manager/manager.yaml
Labels: lgtm

#4666 ci: fix docs only check patterns and workflow output names
  .github/workflows/check-docs-only.sh
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .github/workflows/test-ansible.yml
  .github/workflows/test-go.yml
  .github/workflows/test-helm.yml
  .github/workflows/test-sanity.yml
Labels: kind/bug, lgtm

#4638 add doc on updating bindata in release guide
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/overview/_index.md
Labels: lgtm

#4660 ansible/helm: add makefile helper
  changelog/fragments/ansible-helm-makefile-help.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
  testdata/ansible/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: lgtm

#4668 (manifests/v2) use docker in 'catalog-build' target to align with others
  changelog/fragments/make-catalog-build.yaml
  internal/plugins/manifests/init.go
  testdata/ansible/memcached-operator/Makefile
  testdata/go/v2/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: lgtm, olm-integration

#4659 Fix typo in the event filtering docs
  website/content/en/docs/building-operators/golang/references/event-filtering.md
Labels: lgtm

#4657 doc: add sdk cheat-sheet
  website/content/en/docs/overview/cheat-sheet.md
Labels: lgtm

#4677 doc: only point out for the project-layout
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#4665 docs/building-operators: update `make` usage in quickstarts and tutorials, general alignment
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/tutorial.md
  website/content/en/docs/faqs/_index.md
Labels: kind/documentation

#4680 deps: bump kubebuilder to 646f742
  changelog/fragments/kubebuilder-646f742.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/plugins/ansible/v1/init.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/prometheus/monitor.go
  internal/plugins/helm/v1/init.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/prometheus/monitor.go
  internal/plugins/manifests/init.go
  internal/testutils/olm.go
  internal/util/projutil/project_util.go
  testdata/ansible/memcached-operator/PROJECT
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/ansible/memcached-operator/config/prometheus/monitor.yaml
  testdata/go/v2/memcached-operator/PROJECT
  testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/go/v2/memcached-operator/config/prometheus/monitor.yaml
  testdata/go/v3/memcached-operator/PROJECT
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/go/v3/memcached-operator/config/prometheus/monitor.yaml
  testdata/helm/memcached-operator/PROJECT
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  testdata/helm/memcached-operator/config/prometheus/monitor.yaml
Labels: area/dependency, lgtm

#4682 fix(Helm.controller.watch): Process watch for List kind
  changelog/fragments/helm-handle-list-kind.yaml
  internal/helm/controller/controller.go
Labels: kind/bug, lgtm

#4654 ansible/helm : align flags and deprecate the old ones
  changelog/fragments/ansible-helm-flags.yaml
  hack/generate/samples/internal/ansible/advanced_molecule.go
  internal/ansible/flags/flag.go
  internal/cmd/ansible-operator/run/cmd.go
  internal/cmd/helm-operator/run/cmd.go
  internal/helm/flags/flag.go
  internal/plugins/ansible/v1/scaffolds/init.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/config.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/kustomization.go
  internal/plugins/helm/v1/scaffolds/init.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/config.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/kustomization.go
  test/e2e/ansible/suite_test.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/default/kustomization.yaml
  testdata/ansible/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/ansible/memcached-operator/config/manager/manager.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/default/kustomization.yaml
  testdata/helm/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/helm/memcached-operator/config/manager/manager.yaml
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/operator-scope.md
  website/content/en/docs/building-operators/golang/references/logging.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
Labels: lgtm

#4670 enable 'alpha config-gen' command
  changelog/fragments/alpha-config-gen.yaml
  internal/cmd/operator-sdk/cli/cli.go
  website/content/en/docs/cli/operator-sdk_alpha.md
  website/content/en/docs/cli/operator-sdk_alpha_config-gen.md
  website/content/en/docs/cli/operator-sdk_alpha_config-gen_install-as-plugin.md
Labels: kind/feature

#4683 docs/migration: add prereqs, align guides for all languages
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/helm/migration.md
Labels: kind/documentation

#4623 (manifests/v2) add support for webhooks by default and docs
  changelog/fragments/bugfix-csv-webhooks.yaml
  hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/plugins/ansible/v1/init.go
  internal/plugins/golang/v2/init.go
  internal/plugins/golang/v3/init.go
  internal/plugins/helm/v1/init.go
  internal/plugins/manifests/v2/init.go
  internal/plugins/manifests/v2/kustomization.go
  internal/plugins/manifests/v2/plugin.go
  testdata/ansible/memcached-operator/config/manifests/kustomization.yaml
  testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v2/memcached-operator/config/manifests/kustomization.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/manifests/kustomization.yaml
  testdata/helm/memcached-operator/config/manifests/kustomization.yaml
  website/content/en/docs/olm-integration/generation.md
Labels: kind/bug

#4672 docs/installation: use version in download URL
  release/Makefile
  website/content/en/docs/installation/_index.md
  website/scripts/update_download_url.sh
Labels: kind/documentation, lgtm

#4686 *.md: uncomment links, remove TODO's
  README.md
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/olm-integration/generation.md
Labels: kind/documentation, lgtm

#4662 Properly document that reconcilePeriod is a time.Duration
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/ansible/reference/watches.md
Labels: lgtm

#4676 doc: add faq question about kb docs usage + clarifications
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#4582 allow we see the alpha option output the bundle validation in another format
  internal/cmd/operator-sdk/bundle/validate/validate.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: lgtm

#4529 Pin ansible galaxy installs
  changelog/fragments/pin-ansible-galaxy-collections.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
  testdata/ansible/memcached-operator/requirements.yml
Labels: lgtm

#4687 doc: small nits fixes
  website/content/en/docs/building-operators/golang/references/envtest-setup.md
  website/content/en/docs/faqs/_index.md
  website/content/en/docs/overview/cheat-sheet.md
Labels: lgtm

#4594 Update Ansible Collections
  changelog/fragments/update-ansible-collections.yaml
  hack/tests/e2e-ansible-molecule.sh
  internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
  testdata/ansible/memcached-operator/requirements.yml
Labels: lgtm

#4651 ansible-operator: pin to `ansible-operator-base:c6796de9b29ace4f4c737325c9037f6f715ce6d1`
  images/ansible-operator/Dockerfile
Labels: lgtm

#4698 docs: use memcached in ansible dev tips, clean up code blocks, add prerequisites
  website/content/en/docs/building-operators/ansible/development-tips.md
Labels: kind/documentation, lgtm

#4697 *: pin internally used images to specific versions, add TODO's for others
  hack/check-links.sh
  internal/olm/operator/bundle/install.go
  internal/olm/operator/bundleupgrade/upgrade.go
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/index_image.go
  internal/scorecard/testpod.go
Labels: area/dependency, lgtm

#4696 Repair merge conflicts from #4594
  internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
  testdata/ansible/memcached-operator/requirements.yml
Labels: lgtm

#4700 Fix typo in helm reconciliation loop
  internal/helm/controller/reconcile.go
Labels: lgtm

#4694 `run bundle(-upgrade)`: configure service account and secret
  changelog/fragments/run-bundle-with-secret.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/cleanup/cmd.go
  internal/cmd/operator-sdk/run/bundle/cmd.go
  internal/cmd/operator-sdk/run/bundleupgrade/cmd.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/bundleupgrade/upgrade.go
  internal/olm/operator/config.go
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/index_image.go
  internal/olm/operator/registry/olm_resources.go
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/tutorial.md
  website/content/en/docs/cli/operator-sdk_cleanup.md
  website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
  website/content/en/docs/cli/operator-sdk_run_bundle.md
  website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/testing-deployment.md
  website/content/en/docs/overview/cheat-sheet.md
Labels: kind/feature, olm-integration

#4702 internal/olm/operator/registry/index: do not add secret if name is empty
  internal/olm/operator/registry/index/registry_pod.go
Labels: lgtm

#4705 Changed arch with uname for finding the architecture in macOS
  website/content/en/docs/installation/_index.md
Labels: lgtm
