Repository operator-framework/operator-sdk, pull requests merged in 2021-02, with the labels that each got.

#3431 Bug fix: helm operator uninstall is not properly checking for existing release
  changelog/fragments/helm-uninstall-fix.yaml
  internal/helm/release/manager.go
Labels: kind/bug, language/helm, lgtm

#4417 Pin docker base images
  changelog/fragments/pin-docker-base-images.yaml
  images/ansible-operator/Dockerfile
  images/custom-scorecard-tests/Dockerfile
  images/helm-operator/Dockerfile
  images/operator-sdk/Dockerfile
  images/scorecard-test/Dockerfile
Labels: lgtm

#4462 `run bundle{-upgrade}`: validate `--mode` before running a bundle
  changelog/fragments/bugfix-validate-add-mode.yaml
  internal/olm/operator/bundle/install.go
  internal/olm/operator/bundleupgrade/upgrade.go
  internal/olm/operator/registry/index/bundle_add_mode.go
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
Labels: kind/bug, lgtm

#4256 fixed typo anisible->ansible
  website/content/en/docs/building-operators/ansible/migration.md
Labels: lgtm

#4445 generate: make CSV generator for Go GVKs package-aware
  changelog/fragments/csv-gen-package-aware.yaml
  internal/generate/clusterserviceversion/bases/definitions/ast.go
  internal/generate/clusterserviceversion/bases/definitions/crd.go
  internal/generate/clusterserviceversion/bases/definitions/definitions.go
  internal/generate/clusterserviceversion/bases/definitions/definitions_test.go
  internal/generate/clusterserviceversion/bases/definitions/markers.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
  internal/generate/testdata/go/api/shared/doc.go
  internal/generate/testdata/go/api/shared/memcached_types.go
  internal/generate/testdata/go/api/v1alpha1/memcached_types.go
  internal/generate/testdata/go/api/v1alpha2/dummy_types.go
  internal/generate/testdata/go/api/v1alpha2/memcached_types.go
Labels: kind/bug, lgtm

#4424 docs: add `run bundle` documentation
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/testing-deployment.md
Labels: lgtm

#4465 Align tutorial imports with test samples
  website/content/en/docs/building-operators/golang/advanced-topics.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/references/client.md
  website/content/en/docs/building-operators/golang/references/event-filtering.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/upgrading-sdk-version/v0.1.0-migration-guide.md
Labels: lgtm

#4473 docs: fix incorrect file path
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: kind/documentation

#4475 docs/building-operators/golang: fix context.Context usage, imports, general formatting
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/references/client.md
  website/content/en/docs/building-operators/golang/references/event-filtering.md
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: kind/documentation, lgtm

#4413 upgrade Python to v 3.8
  changelog/fragments/upgrade-python-on-ansible-operator.yaml
  images/ansible-operator/Dockerfile
  website/content/en/docs/building-operators/ansible/installation.md
Labels: lgtm

#4471 Fixed invalid object names generated for long package names
  changelog/fragments/fix-trim-format-dns1123-functions.yaml
  internal/olm/operator/registry/configmap/deployment_test.go
  internal/util/k8sutil/k8sutil.go
  internal/util/k8sutil/k8sutil_test.go
Labels: lgtm

#4466 *: Replace 'docker build . -t ${IMG}' with '-t ${IMG} .'
  changelog/fragments/reorder-docker-args.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
  testdata/ansible/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: lgtm

#4486 Release v1.4.0
  changelog/fragments/bugfix-generate-no-project-name.yaml
  changelog/fragments/bugfix-run-bundle-upgrade.yaml
  changelog/fragments/bugfix-validate-add-mode.yaml
  changelog/fragments/change-finalizer-format.yaml
  changelog/fragments/csv-gen-package-aware.yaml
  changelog/fragments/fix-bundle-validate-failure-on-warnings.yaml
  changelog/fragments/fix-bundle-validate-panic.yaml
  changelog/fragments/fix-mac-m1.yaml
  changelog/fragments/fix-trim-format-dns1123-functions.yaml
  changelog/fragments/helm-ansible-download-makefile.yaml
  changelog/fragments/helm-uninstall-fix.yaml
  changelog/fragments/helm_operator_fix_helm_keep_annotated_delete.yaml
  changelog/fragments/kuttl-v0.8.0.yaml
  changelog/fragments/liveness_readiness_probe_for_operator.yaml
  changelog/fragments/phase-2-plugin-keys.yaml
  changelog/fragments/pin-docker-base-images.yaml
  changelog/fragments/reorder-docker-args.yaml
  changelog/fragments/upgrade-python-on-ansible-operator.yaml
  changelog/generated/v1.4.0.md
  website/config.toml
  website/content/en/docs/upgrading-sdk-version/v1.4.0.md
Labels: lgtm

#4491 Fix misspeling
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: lgtm

#4493 test: remove redundant parts of directory and file names
  Makefile
  test/e2e/ansible/cluster_test.go
  test/e2e/ansible/local_test.go
  test/e2e/ansible/olm_test.go
  test/e2e/ansible/scorecard_test.go
  test/e2e/ansible/suite_test.go
  test/e2e/go/cluster_test.go
  test/e2e/go/local_test.go
  test/e2e/go/scorecard_test.go
  test/e2e/go/suite_test.go
  test/e2e/helm/cluster_test.go
  test/e2e/helm/local_test.go
  test/e2e/helm/olm_test.go
  test/e2e/helm/scorecard_test.go
  test/e2e/helm/suite_test.go
  test/integration/suite_test.go
Labels: area/testing

#4482 ansible output should log with GVK info, namespace as the CR name
  internal/ansible/controller/reconcile.go
  internal/ansible/events/log_events.go
Labels: lgtm, ok-to-test

#4504 Red Hat is two words.
  code-of-conduct.md
Labels: lgtm

#4506 [doc] Add doc for run bundle upgrade
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
Labels: lgtm

#4498 Fix kube rbac proxy
  changelog/fragments/kube-rbac-proxy.yaml
  internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
  internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
  internal/generate/testdata/go/static/basic.operator.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/default/manager_auth_proxy_patch.yaml
Labels: lgtm

#4507 generate: fix multiple Go file type parsing bug
  changelog/fragments/bugfix-3744.yaml
  internal/generate/clusterserviceversion/bases/definitions/ast.go
  internal/generate/clusterserviceversion/bases/definitions/crd.go
  internal/generate/clusterserviceversion/bases/definitions/crd_test.go
  internal/generate/testdata/go/api/v1alpha2/dummy_types.go
  internal/generate/testdata/go/api/v1alpha2/motorcycle_types.go
Labels: kind/bug, lgtm

#4510 [v1.3.x] images/ansible-operator/Dockerfile: pin cryptography python package
  images/ansible-operator/Dockerfile
Labels: lgtm

#4515 docs/upgrade-sdk-version/v1.3.0.md: correct link to migration guide
  website/content/en/docs/upgrading-sdk-version/v1.3.0.md
Labels: kind/documentation, lgtm

#4518 Makefile: `test-docs` target tests docs only
  .github/workflows/test-sanity.yml
  .travis.yml
  Makefile
  website/content/en/docs/contribution-guidelines/documentation.md
Labels: lgtm

#4511 Change the log message "Skipping cache lookup" from Ansible operator to debug level
  changelog/fragments/make-ansible-logs-debug.yaml
  internal/ansible/proxy/cache_response.go
  test/e2e/ansible/cluster_test.go
  test/e2e/ansible/suite_test.go
Labels: ok-to-test

#4520 Release v1.3.2
  Makefile
  changelog/fragments/bugfix-3744.yaml
  changelog/generated/v1.3.2.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/upgrading-sdk-version/v1.3.2.md
Labels: lgtm

#4521 Release v1.4.1
  Makefile
  changelog/fragments/bugfix-3744.yaml
  changelog/generated/v1.4.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/upgrading-sdk-version/v1.4.1.md
Labels: lgtm

#4513 fix bundle run install mode MultiNamespace
  internal/olm/operator/registry/operator_installer.go
  internal/olm/operator/registry/operator_installer_test.go
Labels: lgtm

#4494 Pipenv
  changelog/fragments/use-pipenv-for-python-package-installation.yaml
  images/ansible-operator/Dockerfile
  images/ansible-operator/Pipfile
  images/ansible-operator/Pipfile.lock
Labels: lgtm

#4531 [v1.4.1] bump cryptography dep
  changelog/fragments/bump-cryptography-dep.yaml
  images/ansible-operator/Dockerfile
Labels: lgtm

#4533 Release v1.4.2
  Makefile
  changelog/fragments/bugfix-3744.yaml
  changelog/fragments/bump-cryptography-dep.yaml
  changelog/generated/v1.4.2.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/upgrading-sdk-version/v1.4.2.md
Labels: lgtm

#4538 Revert "Pipenv (#4494)"
  changelog/fragments/use-pipenv-for-python-package-installation.yaml
  images/ansible-operator/Dockerfile
  images/ansible-operator/Pipfile
  images/ansible-operator/Pipfile.lock
Labels: lgtm

#4536 Improve/Upgrade the migration guide to address the need of the users to move from pre-1.0.0 to latest
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#4540 Make getInstalledCSV testable
  internal/olm/operator/registry/configmap.go
  internal/olm/operator/registry/operator_installer.go
  internal/olm/operator/registry/operator_installer_test.go
Labels: lgtm

#4545 docs: fix wrong paths in 1.4.2 upgrade guide. (#4541)
  website/content/en/docs/upgrading-sdk-version/v1.4.0.md
Labels: lgtm

#4489 Remove `shell` specification in Makefile for Ansible and Helm
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
  testdata/ansible/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: lgtm

#4546 fix swapped liveness/readiness http paths. (#4541)
  changelog/fragments/swap-readiness-liveness-paths-4541.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/manager/manager.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/manager/manager.yaml
Labels: lgtm

#4565 Expand `run bundle-upgrade` documentation
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/testing-deployment.md
Labels: lgtm

#4570 run packagemanifests: pin upstream-registry-builder to v1.16.0
  internal/olm/operator/registry/configmap/deployment.go
Labels: area/dependency, lgtm

#4567 docs: Remove mercurial from current install guide.
  website/content/en/docs/building-operators/golang/installation.md
  website/content/en/docs/installation/_index.md
Labels: lgtm

#4572 docs/: specify go 1.15 must be used
  website/content/en/docs/building-operators/golang/installation.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/contribution-guidelines/developer-guide.md
  website/content/en/docs/installation/_index.md
Labels: kind/documentation, lgtm

#4573 samples(go/v3): add watch verb to RBAC marker
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/rbac/role.yaml
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
Labels: lgtm

#4574 docs: document k8s version compatibility and platform support
  website/content/en/docs/building-operators/ansible/installation.md
  website/content/en/docs/building-operators/golang/installation.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/installation.md
  website/content/en/docs/contribution-guidelines/testing.md
  website/content/en/docs/overview/_index.md
Labels: kind/documentation, lgtm

#4576 fix link in readme
  README.md
Labels: lgtm

#4583 README.md: update support info with links to SDK docs website
  README.md
Labels: kind/documentation, lgtm

#4571 Graceful shutdown timeout
  changelog/fragments/ansible-graceful-shutdown-timeout.yaml
  internal/ansible/flags/flag.go
  internal/cmd/ansible-operator/run/cmd.go
Labels: lgtm

#4514 generate: improve out-of-project usage, resolve ambiguous bundle flags
  changelog/fragments/fix-generate-bundle-flags.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/bundle/cmd.go
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests_test.go
  internal/generate/collector/manifests.go
  internal/registry/labels.go
  testdata/ansible/memcached-operator/bundle.Dockerfile
  testdata/ansible/memcached-operator/bundle/metadata/annotations.yaml
  testdata/go/v2/memcached-operator/bundle.Dockerfile
  testdata/go/v2/memcached-operator/bundle/metadata/annotations.yaml
  testdata/go/v3/memcached-operator/bundle.Dockerfile
  testdata/go/v3/memcached-operator/bundle/metadata/annotations.yaml
  testdata/helm/memcached-operator/bundle.Dockerfile
  testdata/helm/memcached-operator/bundle/metadata/annotations.yaml
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
  website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Labels: kind/bug, kind/documentation, lgtm

#4580 improve bundle output
  internal/cmd/operator-sdk/bundle/validate/cmd.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: lgtm

#4558 fix/sample/go: use recon after x time to ensure that the pod names were created
  hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  testdata/go/v2/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
Labels: lgtm

#4588 tests: fix ansible-molecule tests, install deps in venv, pin versions
  hack/tests/e2e-ansible-molecule.sh
Labels: area/testing, lgtm
