Repository operator-framework/operator-sdk, pull requests merged in 2021-07, with the labels that each got.

#5020 Bump java-operator-plugins.
  changelog/fragments/java-operator-bump.yaml
  go.mod
  go.sum
Labels: lgtm

#5042 fix: issue-5041
  changelog/fragments/helm-deepequals.yaml
  internal/helm/release/manager.go
  internal/helm/release/manager_test.go
Labels: lgtm

#5047 Release v1.8.1
  Makefile
  changelog/fragments/empty-patch-requests.yaml
  changelog/fragments/generate-bundle-fix.yaml
  changelog/fragments/helm-deepequals.yaml
  changelog/generated/v1.8.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.8.1.md
Labels: lgtm

#5016 docs/olm-integration: Add image registry config reference link
  website/content/en/docs/olm-integration/testing-deployment.md
Labels: lgtm

#5015 config3alphato3: Default domain to empty string
  internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3.go
  internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3_test.go
Labels: lgtm

#5039 Add the missing test suite for the metrics
  internal/annotations/metrics/metrics_suite_test.go
  internal/annotations/metrics/metrics_test.go
Labels: lgtm

#5034 Modified release instructions for MacOS users
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: lgtm

#5019 modified and added admission Webhook
  website/content/en/docs/building-operators/golang/webhook.md
Labels: kind/documentation, lgtm

#5057 Bump k8s dependencies to 1.21+
  Makefile
  changelog/fragments/bump-kustomize.yaml
  go.mod
  go.sum
  internal/ansible/controller/reconcile_test.go
  internal/ansible/handler/logging_enqueue_object_test.go
  internal/clientbuilder/clientbuilder.go
  internal/cmd/ansible-operator/run/cmd.go
  internal/cmd/helm-operator/run/cmd.go
  internal/plugins/ansible/v1/scaffolds/init.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mdefault/prepare.go
  internal/plugins/helm/v1/scaffolds/init.go
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-manager-config_v1_configmap.yaml
  testdata/ansible/memcached-operator/molecule/default/prepare.yml
  testdata/go/v2/memcached-operator/config/crd/kustomization.yaml
  testdata/go/v3/memcached-operator/.dockerignore
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/bundle/manifests/cache.example.com_memcacheds.yaml
  testdata/go/v3/memcached-operator/config/crd/bases/cache.example.com_memcacheds.yaml
  testdata/go/v3/memcached-operator/config/crd/kustomization.yaml
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/go.mod
  testdata/go/v3/memcached-operator/go.sum
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-manager-config_v1_configmap.yaml
  tools/scripts/fetch
  website/content/en/docs/cli/operator-sdk_alpha_config-gen.md
Labels: lgtm

#5048 Add XUnit Formatting Output to Scorecard
  changelog/fragments/xunit-xml-output.yaml
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/cmd/operator-sdk/scorecard/xunit/xunit.go
  internal/scorecard/scorecard.go
  website/content/en/docs/cli/operator-sdk_scorecard.md
Labels: lgtm

#5062 Modify channels for previous versions of manifests
  changelog/fragments/modify-default-channel.yaml
  internal/cmd/operator-sdk/pkgmantobundle/cmd.go
  internal/cmd/operator-sdk/pkgmantobundle/pkgmantobundle_test.go
Labels: lgtm

#5071 [1.8.x] modify default channels for previous versions of manifests
  changelog/fragments/modify-default-channel.yaml
  internal/cmd/operator-sdk/pkgmantobundle/cmd.go
  internal/cmd/operator-sdk/pkgmantobundle/pkgmantobundle_test.go
Labels: lgtm

#5079 docs/olm-integration: Fix misspelling
  website/content/en/docs/olm-integration/cli-overview.md
Labels: lgtm

#4998 Update generation.md
  website/content/en/docs/olm-integration/generation.md
Labels: lgtm

#5078 docs: improve old changelog entry
  website/content/en/docs/upgrading-sdk-version/v1.6.0.md
  website/content/en/docs/upgrading-sdk-version/v1.6.1.md
Labels: lgtm

#5074 docs: fix comment for "what did you see instead"
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: lgtm

#5069 docs: flesh out how to handle resources on deletion.
  website/content/en/docs/best-practices/best-practices.md
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: lgtm

#4945 docs/olm-integration: fix example Go code for OLM < 0.17
  website/content/en/docs/olm-integration/generation.md
Labels: kind/documentation, lgtm, olm-integration

#5084 Release PR for Patch release v1.9.1
  Makefile
  changelog/fragments/generate-bundle-fix.yaml
  changelog/fragments/helm-deepequals.yaml
  changelog/fragments/modify-default-channel.yaml
  changelog/generated/v1.9.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.9.1.md
Labels: lgtm

#5023 Makes run command version details in sync with the version command
  internal/cmd/ansible-operator/run/cmd.go
  internal/cmd/helm-operator/run/cmd.go
Labels: lgtm

#5085 Release v1.10.0
  Makefile
  changelog/fragments/bump-kustomize.yaml
  changelog/fragments/generate-bundle-fix.yaml
  changelog/fragments/helm-deepequals.yaml
  changelog/fragments/java-operator-bump.yaml
  changelog/fragments/modify-default-channel.yaml
  changelog/fragments/xunit-xml-output.yaml
  changelog/generated/v1.10.0.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.10.0.md
Labels: lgtm

#5028 Add ability to configure storage to scorecard
  go.mod
  go.sum
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/scorecard/kubeclient.go
  internal/scorecard/scorecard.go
  internal/scorecard/storage.go
  internal/scorecard/testpod.go
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  website/content/en/docs/cli/operator-sdk_scorecard.md
Labels: lgtm

#5093 Add changelog info to docs and contribution guide
  CONTRIBUTING.MD
  website/content/en/docs/contribution-guidelines/changelog.md
Labels: lgtm
