Repository operator-framework/operator-sdk, pull requests merged in 2021-05, with the labels that each got.

#4850 Fix bug in cluster scoped ansible operators
  changelog/fragments/ansible-fix-cluster-annotations.yaml
  hack/generate/samples/internal/ansible/advanced_molecule.go
  hack/generate/samples/internal/ansible/testdata/tasks/clusterannotationtest_test.yml
  hack/generate/samples/internal/ansible/testdata/watches.yaml
  internal/ansible/proxy/inject_owner.go
Labels: lgtm

#4861 docs: link to kubebuilder's envtest setup instructions
  website/content/en/docs/building-operators/golang/references/envtest-setup.md
  website/content/en/docs/building-operators/golang/testing.md
  website/content/en/docs/contribution-guidelines/testing.md
Labels: kind/documentation

#4865 fix: link to rbac markers in doc
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: lgtm

#4863 bump kb to latest commit and projects to k8s 1.20
  changelog/fragments/bump-kb.yaml
  go.mod
  go.sum
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/go.mod
  testdata/go/v3/memcached-operator/go.sum
Labels: lgtm

#4860 Release v1.7.1
  Makefile
  changelog/fragments/ansible-fix-cluster-annotations.yaml
  changelog/fragments/bump-kb.yaml
  changelog/generated/v1.7.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.7.1.md
Labels: lgtm

#4816 operator-sdk: run bundle{-upgrade} support insecure registry server
  changelog/fragments/run-bundle-from-insecure-registry.yaml
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/bundleupgrade/upgrade.go
  internal/olm/operator/helpers.go
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/index_image.go
  internal/registry/image.go
  website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
  website/content/en/docs/cli/operator-sdk_run_bundle.md
Labels: lgtm

#4866 Fix spelling
  website/content/en/docs/advanced-topics/operator-capabilities/operator-capabilities.md
Labels: lgtm

#4873 images: bump ubi to 8.3-297.1618432833 and ubi-minimal to 8.3-298.1618432845
  changelog/fragments/ubi-security.yaml
  images/ansible-operator/base.Dockerfile
  images/custom-scorecard-tests/Dockerfile
  images/helm-operator/Dockerfile
  images/operator-sdk/Dockerfile
  images/scorecard-test/Dockerfile
Labels: lgtm

#4874 internal/olm/operator/registry/index: fix lint errors
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
Labels: lgtm

#4877 images/ansible-operator/base.Dockerfile: pin `pip3~=21.1`
  changelog/fragments/pip3-21.1.yaml
  images/ansible-operator/base.Dockerfile
Labels: area/dependency, lgtm

#4883 workflows/deploy-manual: add commit signoff to automatically created PRs
  .github/workflows/deploy-manual.yml
Labels: lgtm

#4752 Fix markup
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#4888 deps: bump operator-lib to v0.4.1
  changelog/fragments/operator-lib-v0.4.1.yaml
  go.mod
  go.sum
Labels: area/dependency, lgtm

#4889 [v1.7.x] deps: bump operator-lib to v0.4.1 (#4888)
  changelog/fragments/operator-lib-v0.4.1.yaml
  go.mod
  go.sum
Labels: lgtm

#4898 Release v1.6.3
  Makefile
  changelog/fragments/ansible-fix-cluster-annotations.yaml
  changelog/fragments/fmt-info-logs.yaml
  changelog/fragments/pip3-21.1.yaml
  changelog/fragments/ubi-security.yaml
  changelog/generated/v1.6.3.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.6.3.md
Labels: lgtm

#4900 Release v1.6.4
  Makefile
  changelog/generated/v1.6.4.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.6.4.md
Labels: lgtm

#4903 deps: bump operator-framework/api to v0.8.1
  changelog/fragments/api-v0.8.1.yaml
  go.mod
  go.sum
Labels: area/dependency, lgtm

#4871 Added quarkus/v1-alpha plugin
  changelog/fragments/java-plugin-enable-changes.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/cli/cli.go
  testdata/ansible/memcached-operator/bundle/manifests/cache.example.com_memcacheds.yaml
  testdata/go/v2/memcached-operator/bundle/manifests/cache.example.com_memcacheds.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/cache.example.com_memcacheds.yaml
  testdata/helm/memcached-operator/bundle/manifests/cache.example.com_memcacheds.yaml
  testdata/helm/memcached-operator/helm-charts/memcached/Chart.yaml
  website/content/en/docs/cli/operator-sdk.md
Labels: lgtm

#4910 Return actual olm client error
  internal/olm/installer/manager.go
Labels: lgtm

#4916 docs: s/godoc.org/pkg.go.dev/g
  proposals/upstream-osdk-features-into-controller-runtime.md
  website/content/en/docs/advanced-topics/scorecard/scorecard.md
  website/content/en/docs/best-practices/common-recommendation.md
  website/content/en/docs/building-operators/golang/advanced-topics.md
  website/content/en/docs/building-operators/golang/crds-scope.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/operator-scope.md
  website/content/en/docs/building-operators/golang/references/client.md
  website/content/en/docs/building-operators/golang/references/event-filtering.md
  website/content/en/docs/building-operators/golang/references/logging.md
  website/content/en/docs/building-operators/golang/testing.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/faqs/_index.md
  website/content/en/docs/upgrading-sdk-version/v0.1.0-migration-guide.md
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: kind/documentation, lgtm

#4915 docs: fix scorecard patches path.
  website/content/en/docs/advanced-topics/scorecard/custom-tests.md
Labels: lgtm

#4918 generate: correct error message when package name is missing
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests_test.go
Labels: lgtm

#4932 *: update old k8s and OLM versions to latest supported
  Makefile
  go.mod
  go.sum
  internal/bindata/olm/manifests.go
  internal/bindata/olm/versions.go
  internal/testutils/olm.go
  website/content/en/docs/overview/_index.md
Labels: area/dependency

#4941 fix: link to k8s version
  website/content/en/docs/building-operators/helm/installation.md
Labels: lgtm

#4940 bump java plugins
  go.mod
  go.sum
Labels: lgtm

#4946 Add changelog fragment for PR #4944
  changelog/fragments/bugfix-ansible-runner.yaml
Labels: lgtm

#4897 Polish patch release documentation
  website/content/en/docs/contribution-guidelines/releasing.md
  website/scripts/update_download_url.sh
Labels: lgtm

#4939 add: new community validator to check bundles
  changelog/fragments/community-validator.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/bundle/validate/cmd.go
  internal/cmd/operator-sdk/bundle/validate/optional.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/olm-integration/generation.md
Labels: lgtm

#4826 generate bundle: add --extra-service-accounts flag to consider extra-Deployment SAs
  changelog/fragments/extra-service-accounts.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/bundle/cmd.go
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/cmd/operator-sdk/generate/internal/manifests_test.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
  internal/generate/clusterserviceversion/clusterserviceversion.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
  internal/generate/collector/clusterserviceversion.go
  internal/generate/collector/clusterserviceversion_test.go
  website/content/en/docs/cli/operator-sdk_generate_bundle.md
Labels: kind/feature

#4948 internal/cmd/operator-sdk/bundle/validate: remove incorrect wording, grammatical fixup
  changelog/fragments/community-validator.yaml
  internal/cmd/operator-sdk/bundle/validate/cmd.go
  internal/cmd/operator-sdk/bundle/validate/optional.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: lgtm, release-blocker

#4950 docs(release): add branch information so the correct commit is tagged
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: kind/documentation
