Repository operator-framework/operator-sdk, pull requests merged in 2021-01, with the labels that each got.

#4360 testdata: bump samples to year 2021
  testdata/go/v2/memcached-operator/api/v1alpha1/groupversion_info.go
  testdata/go/v2/memcached-operator/api/v1alpha1/memcached_types.go
  testdata/go/v2/memcached-operator/api/v1alpha1/memcached_webhook.go
  testdata/go/v2/memcached-operator/api/v1alpha1/zz_generated.deepcopy.go
  testdata/go/v2/memcached-operator/controllers/memcached_controller.go
  testdata/go/v2/memcached-operator/controllers/suite_test.go
  testdata/go/v2/memcached-operator/hack/boilerplate.go.txt
  testdata/go/v2/memcached-operator/main.go
  testdata/go/v3/memcached-operator/api/v1alpha1/groupversion_info.go
  testdata/go/v3/memcached-operator/api/v1alpha1/memcached_types.go
  testdata/go/v3/memcached-operator/api/v1alpha1/memcached_webhook.go
  testdata/go/v3/memcached-operator/api/v1alpha1/webhook_suite_test.go
  testdata/go/v3/memcached-operator/api/v1alpha1/zz_generated.deepcopy.go
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/controllers/suite_test.go
  testdata/go/v3/memcached-operator/hack/boilerplate.go.txt
  testdata/go/v3/memcached-operator/main.go
Labels: lgtm

#4359 go.mod: Bump containerd dependency to correctly detect Apple Silicon ARM variant
  changelog/fragments/fix-mac-m1.yaml
  go.mod
  go.sum
Labels: area/dependency, lgtm

#4379 Bundle validation desc
  internal/cmd/operator-sdk/bundle/validate/cmd.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: lgtm

#4373 Fix panic with "operator-sdk bundle validate" and OCI
  changelog/fragments/fix-bundle-validate-panic.yaml
  internal/cmd/operator-sdk/bundle/validate/validate.go
Labels: lgtm

#4337 *: replace defunct coreos.com/operators/ with kubernetes.io link
  README.md
  website/content/en/_index.html
  website/content/en/docs/overview/_index.md
Labels: kind/documentation

#4387 docs: fix broken link
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: kind/documentation, lgtm

#4390 Makefile: bump envtest version to v0.7.0
  Makefile
Labels: area/testing

#4391 images/scorecard-test-kuttl: upgrade kuttl to v0.8.0
  changelog/fragments/kuttl-v0.8.0.yaml
  images/scorecard-test-kuttl/Dockerfile
Labels: area/dependency, lgtm

#4393 Align tutorial imports with test samples
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/golang/advanced-topics.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/references/client.md
  website/content/en/docs/building-operators/golang/references/event-filtering.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/upgrading-sdk-version/v0.1.0-migration-guide.md
Labels: lgtm

#4389 fix: (helm) - do not add owner references to resources that contain the Helm keep resource-policy annotation
  changelog/fragments/helm_operator_fix_helm_keep_annotated_delete.yaml
  internal/helm/client/client.go
  internal/helm/client/client_test.go
Labels: lgtm

#4343 hack/ci: remove workflows dir from docs-only check
  hack/ci/check-doc-only-update.sh
Labels: lgtm

#4399 Handle operator bundle upgrade from traditional operator installation
  internal/olm/operator/registry/index_image.go
  internal/olm/operator/registry/operator_installer.go
Labels: lgtm

#4400 internal/testutils: fix bad err check
  internal/testutils/utils.go
Labels: lgtm

#4404 Fix a tiny typo in Ansible tutorial.
  website/content/en/docs/building-operators/ansible/tutorial.md
Labels: lgtm

#4408 docs/upgrading-sdk-version: note v0.19.0 migration guide as well as latest
  website/content/en/docs/upgrading-sdk-version/v0.19.0.md
Labels: kind/documentation

#4395 Updates to the tutorial docs
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: do-not-merge/hold, lgtm

#4398 add a better doc/description over bundle options in the makefile
  internal/plugins/manifests/init.go
  testdata/ansible/memcached-operator/Makefile
  testdata/go/v2/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: lgtm, olm-integration

#4410 Update doc with upstream conditions
  website/content/en/docs/building-operators/golang/advanced-topics.md
Labels: lgtm

#4407 (helm/v1,ansible/v1) fix download URLs and order of binary checks
  changelog/fragments/helm-ansible-download-makefile.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
  testdata/ansible/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: kind/bug, lgtm

#4416 docs: Add useful links to the README
  README.md
Labels: lgtm

#4420 internal/plugins/scorecard: refactor init plugin code for easier reading
  internal/plugins/scorecard/init.go
Labels: lgtm

#4429 Removed trailing double-asterisks on a several headers
  website/content/en/docs/advanced-topics/operator-capabilities/operator-capabilities.md
Labels: lgtm

#4437 docs: add ubuntu keyserver to installation instructions, remove gpg requirement from release guide
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/installation/_index.md
Labels: kind/documentation, lgtm

#4431 generate: respect project version when getting package name
  changelog/fragments/bugfix-generate-no-project-name.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
Labels: kind/bug, lgtm

#4443 generate: respect project version when getting package name (#4431)
  changelog/fragments/bugfix-generate-no-project-name.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/internal/genutil.go
  internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
Labels: lgtm

#4411 add kubebuilder/operator-sdk FAQ
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#4441 docs: Update memcached example implementation in Go tutorial
  website/content/en/docs/building-operators/golang/tutorial.md
Labels: lgtm

#4021 doc: improve/fix memcached go tutorial
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/references/openapi-validation.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/tutorial.md
Labels: kind/documentation, lgtm

#4448 Bug 1921458: `run bundle-upgrade` should handle error gracefully when a previous operator version doesn't exist
  changelog/fragments/bugfix-run-bundle-upgrade.yaml
  internal/olm/operator/registry/operator_installer.go
Labels: lgtm

#4449 Bug 1921727: Bundle validate should not fail because of warnings.
  changelog/fragments/fix-bundle-validate-failure-on-warnings.yaml
  go.mod
  go.sum
Labels: lgtm

#4452 bugfix for `run bundle-upgrade`: handle subscription that matches package name not being found
  internal/olm/operator/registry/operator_installer.go
Labels: lgtm

#4444 Add issues template for documentation
  .github/ISSUE_TEMPLATE/doc-report.md
Labels: lgtm
