Repository operator-framework/operator-sdk, pull requests merged in 2021-08, with the labels that each got.

#4997 Closes #4949: Label-based filtering for Helm via predicates
  changelog/fragments/helm-labelselector.yaml
  internal/cmd/helm-operator/run/cmd.go
  internal/helm/controller/controller.go
  internal/helm/controller/controller_test.go
  internal/helm/watches/watches.go
  website/content/en/docs/building-operators/helm/reference/watches.md
Labels: lgtm

#5100 docs: Fix link to the envtest documentation in the v1.0.0 migration guide
  website/content/en/docs/faqs/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.0.0.md
Labels: lgtm

#5097 [helm] revert changes made to release equality comparison
  changelog/fragments/revert-helm-equality-comparison.yaml
  internal/helm/release/manager.go
  internal/helm/release/manager_test.go
  internal/helm/release/testdata/simple/.helmignore
  internal/helm/release/testdata/simple/Chart.yaml
  internal/helm/release/testdata/simple/templates/NOTES.txt
  internal/helm/release/testdata/simple/templates/_helpers.tpl
  internal/helm/release/testdata/simple/templates/secrets.yaml
  internal/helm/release/testdata/simple/values.yaml
  internal/helm/release/testdata/simpledf/.helmignore
  internal/helm/release/testdata/simpledf/Chart.yaml
  internal/helm/release/testdata/simpledf/templates/NOTES.txt
  internal/helm/release/testdata/simpledf/templates/_helpers.tpl
  internal/helm/release/testdata/simpledf/templates/secrets.yaml
  internal/helm/release/testdata/simpledf/values.yaml
Labels: lgtm

#5105 helm-operator: support go text/template evaluation in override values
  changelog/fragments/helm-overrides-template.yaml
  go.mod
  go.sum
  internal/helm/watches/watches.go
  internal/helm/watches/watches_test.go
  website/content/en/docs/building-operators/helm/reference/advanced_features/override_values.md
Labels: kind/feature, language/helm

#5118 prepend local roles path to ANSIBLE_ROLES_PATH
  changelog/fragments/ansible-set-local-rolespath.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
  testdata/ansible/memcached-operator/Makefile
Labels: lgtm

#5117 bump kubebuilder commit in Operator SDK
  changelog/fragments/bump-kb.yaml
  go.mod
  go.sum
  internal/plugins/ansible/v1/init.go
  internal/plugins/helm/v1/init.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/ansible/memcached-operator/config/rbac/auth_proxy_service.yaml
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-webhook-service_v1_service.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/go/v3/memcached-operator/config/manager/manager.yaml
  testdata/go/v3/memcached-operator/config/rbac/auth_proxy_service.yaml
  testdata/go/v3/memcached-operator/config/webhook/service.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/helm/memcached-operator/config/manager/manager.yaml
  testdata/helm/memcached-operator/config/rbac/auth_proxy_service.yaml
Labels: lgtm

#5126 [v1.8.x] fix(generate): exclude ServiceAccounts in the CSV from generated bundle
  changelog/fragments/fix-bundle-service-accounts.yaml
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
  internal/generate/collector/clusterserviceversion.go
  internal/generate/collector/clusterserviceversion_test.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
Labels: lgtm

#5127 [v1.9.x] fix(generate): exclude ServiceAccounts in the CSV from generated bundle
  changelog/fragments/fix-bundle-service-accounts.yaml
  internal/cmd/operator-sdk/generate/internal/manifests.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
  internal/generate/collector/clusterserviceversion.go
  internal/generate/collector/clusterserviceversion_test.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
Labels: lgtm

#5125 release v1.9.2
  Makefile
  changelog/fragments/fix-bundle-service-accounts.yaml
  changelog/fragments/revert-helm-equality-comparison.yaml
  changelog/generated/v1.9.2.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.9.2.md
Labels: lgtm

#5129 Release v1.10.1
  Makefile
  changelog/fragments/bump-kb.yaml
  changelog/fragments/fix-bundle-service-accounts.yaml
  changelog/fragments/revert-helm-equality-comparison.yaml
  changelog/generated/v1.10.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.10.1.md
Labels: do-not-merge/hold

#5119 Bump operator-framework api to 0.10.5
  changelog/fragments/bump-of-api-0.10.5.yaml
  go.mod
  go.sum
Labels: lgtm

#5096 Add Testing for Scorecard Storage Output Feature
  test/common/scorecard.go
Labels: lgtm

#5137 docs: Add version range for `ansible-runner` in installation.md
  website/content/en/docs/building-operators/ansible/installation.md
Labels: lgtm

#5135 Add bundle quickstart
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/operator-scope.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/tutorial.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/testing-deployment.md
  website/content/en/docs/olm-integration/tutorial-bundle.md
  website/content/en/docs/olm-integration/tutorial-package-manifests.md
  website/content/en/docs/overview/cheat-sheet.md
Labels: lgtm

#5086 Refactoring code for label-based filtering for Ansible Operators
  internal/ansible/controller/controller.go
  internal/ansible/controller/controller_test.go
  internal/ansible/predicate/predicate.go
  internal/ansible/watches/watches.go
Labels: lgtm

#5142 Kickoff the v1.11.x docs build
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: lgtm

#5162 bump operator-lib to v0.6.0
  go.mod
  go.sum
Labels: lgtm

#5154 Add additional variable to print k8s version
  Makefile
Labels: lgtm

#5174 Update webhook.md spelling error
  website/content/en/docs/building-operators/golang/webhook.md
Labels: lgtm
