Repository operator-framework/operator-sdk, pull requests merged in 2021-04, with the labels that each got.

#4649 actions(deploy-manual): use commit as ansible-operator-base tag
  .github/workflows/deploy-manual.yml
Labels: lgtm

#4370 olm/operator: do not tamper error type returned by the apiserver
  internal/olm/operator/registry/operator_installer.go
Labels: lgtm

#4723 ansible-operator: bump base image to `ansible-operator-base:b187f86157fbdc115da60d275628b3dd633e55c2`
  changelog/fragments/urllib3-1.26.4.yaml
  images/ansible-operator/Dockerfile
Labels: area/dependency, lgtm

#4724 [v1.5.x] images/ansible-operator: pin urllib3 to 1.26.4
  changelog/fragments/urllib3-1.26.4.yaml
  images/ansible-operator/base.Dockerfile
Labels: lgtm

#4730 feat: add kustomize plugin
  changelog/fragments/add-plugins.yaml
  internal/cmd/operator-sdk/cli/cli.go
  website/content/en/docs/cli/operator-sdk.md
Labels: lgtm

#4734 Ansible bump deps
  changelog/fragments/ansible-dep-bump.yaml
  images/ansible-operator/Pipfile
  images/ansible-operator/Pipfile.lock
  internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
  testdata/ansible/memcached-operator/requirements.yml
Labels: lgtm

#4703 `run bundle(-upgrade)`: configure registry pod with root certificate secret
  changelog/fragments/ca-secret-name-run-bundle.yaml
  changelog/fragments/run-bundle-with-secret.yaml
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/index_image.go
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/ansible/quickstart.md
  website/content/en/docs/building-operators/ansible/tutorial.md
  website/content/en/docs/building-operators/golang/migration.md
  website/content/en/docs/building-operators/golang/quickstart.md
  website/content/en/docs/building-operators/golang/tutorial.md
  website/content/en/docs/building-operators/helm/migration.md
  website/content/en/docs/building-operators/helm/quickstart.md
  website/content/en/docs/building-operators/helm/tutorial.md
  website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
  website/content/en/docs/cli/operator-sdk_run_bundle.md
  website/content/en/docs/olm-integration/cli-overview.md
  website/content/en/docs/olm-integration/quickstart-bundle.md
  website/content/en/docs/olm-integration/testing-deployment.md
  website/content/en/docs/overview/cheat-sheet.md
Labels: kind/feature, lgtm

#4742 fix: only print controller comment for Go projects
  go.mod
  go.sum
  internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3.go
  internal/cmd/operator-sdk/cli/cli.go.orig
Labels: lgtm

#4748 deps: bump kubebuilder to c7525d74815300c4d5b8c6e6fa6cf4cd80a9dbd2
  go.mod
  go.sum
Labels: lgtm, release-blocker

#4487 enh: (helm) - add annotation to wait for all resources to be deleted before removing CR finalizer
  changelog/fragments/helm-uninstall-wait-anno.yml
  internal/helm/controller/reconcile.go
  internal/helm/controller/reconcile_test.go
  internal/helm/manifestutil/resource_policy.go
  internal/helm/release/manager.go
  test/e2e/helm/cluster_test.go
  website/content/en/docs/building-operators/helm/reference/advanced_features/annotations.md
Labels: lgtm

#4750 bump github.com/operator-framework/api from 0.5.3 to 0.8.0
  go.mod
  go.sum
  internal/cmd/operator-sdk/generate/kustomize/manifests.go
  internal/generate/internal/genutil.go
Labels: lgtm

#4741 workflows/deploy-manual: automate ansible-operator base image bump PR creation
  .github/workflows/deploy-manual.yml
Labels: lgtm

#4760 Release v1.5.1
  Makefile
  changelog/fragments/urllib3-1.26.4.yaml
  changelog/generated/v1.5.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.5.1.md
Labels: lgtm

#4756 Release v1.6.0
  Makefile
  changelog/fragments/add-declarative.yaml
  changelog/fragments/add-plugins.yaml
  changelog/fragments/add_common_kb.yaml
  changelog/fragments/alpha-config-gen.yaml
  changelog/fragments/ansible-2.10.7.yaml
  changelog/fragments/ansible-dep-bump.yaml
  changelog/fragments/ansible-helm-flags.yaml
  changelog/fragments/ansible-helm-makefile-help.yaml
  changelog/fragments/ansible-helm-ssc.yaml
  changelog/fragments/bugfix-csv-webhooks.yaml
  changelog/fragments/ca-secret-name-run-bundle.yaml
  changelog/fragments/helm-handle-list-kind.yaml
  changelog/fragments/helm-uninstall-wait-anno.yml
  changelog/fragments/kubebuilder-646f742.yaml
  changelog/fragments/make-catalog-build.yaml
  changelog/fragments/mark-variables-unsafe.yaml
  changelog/fragments/optional-flags-cleanup.yaml
  changelog/fragments/pin-ansible-galaxy-collections.yaml
  changelog/fragments/run-bundle-with-secret.yaml
  changelog/fragments/service_account.yaml
  changelog/fragments/update-ansible-collections.yaml
  changelog/fragments/urllib3-1.26.4.yaml
  changelog/fragments/use-pipenv-for-python-package-installation.yaml
  changelog/generated/v1.6.0.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.6.0.md
Labels: lgtm

#4732 doc: add plugins contribution doc
  website/content/en/docs/contribution-guidelines/plugins.md
  website/content/en/docs/contribution-guidelines/releasing.md
  website/content/en/docs/contribution-guidelines/reporting-issues.md
  website/content/en/docs/contribution-guidelines/testing.md
Labels: lgtm

#4770 Update _index.md
  website/content/en/docs/installation/_index.md
Labels: lgtm

#4775 website/content: Add trailing code bracket to the sdk v0.13.x migration guide
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: lgtm

#4768 deps: bump kubebuilder, align ansible/helm plugins with `kustomize/v1` updates
  go.mod
  go.sum
  internal/cmd/operator-sdk/cli/cli.go
  internal/plugins/ansible/v1/api.go
  internal/plugins/ansible/v1/init.go
  internal/plugins/ansible/v1/scaffolds/api.go
  internal/plugins/ansible/v1/scaffolds/init.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/crd/kustomization.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/crd_editor_rbac.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/crd_viewer_rbac.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
  internal/plugins/ansible/v1/scaffolds/internal/templates/config/samples/cr_sample.go
  internal/plugins/helm/v1/api.go
  internal/plugins/helm/v1/init.go
  internal/plugins/helm/v1/scaffolds/api.go
  internal/plugins/helm/v1/scaffolds/init.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/crd/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/crd_editor_rbac.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/crd_viewer_rbac.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/samples/custom_resource.go
  internal/plugins/util/cleanup.go
  testdata/ansible/memcached-operator/config/default/kustomization.yaml
  testdata/ansible/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
  testdata/helm/memcached-operator/config/default/kustomization.yaml
Labels: area/dependency, lgtm

#4776 `{ansible,helm}-operator run`: add component config flag `--config`
  changelog/fragments/add-componentconfig-flag.yaml
  internal/ansible/flags/flag.go
  internal/ansible/flags/flag_test.go
  internal/ansible/flags/suite_test.go
  internal/cmd/ansible-operator/run/cmd.go
  internal/cmd/helm-operator/run/cmd.go
  internal/helm/flags/flag.go
  internal/helm/flags/flag_test.go
  internal/helm/flags/suite_test.go
  internal/plugins/ansible/v1/init.go
  internal/plugins/helm/v1/init.go
Labels: kind/bug

#4766 deps: enable Dependabot to upgrade base images
  .github/dependabot.yml
Labels: lgtm

#4758 website/content: Update migration guide to allow copy-pasting Gopkg.toml updates
  website/content/en/docs/contribution-guidelines/documentation.md
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: lgtm

#4772 fix: ensure labels are ordered in generated bundle
  internal/cmd/operator-sdk/generate/bundle/bundle.go
Labels: lgtm

#4807 [v1.5.x] hack/check-links.sh: pin klakegg/html-proofer image to 3.18.8 to fix dep issue
  hack/check-links.sh
Labels: lgtm

#4808 release: bump goreleaser to 0.156.0
  release/Makefile
Labels: area/dependency

#4811 [v1.6.x] images/ansible-operator: bumped base to ansible-operator-base:v1.6.x-ce34186d53201446db17dc8c3498f035130498d8
  images/ansible-operator/Dockerfile
Labels: lgtm

#4809 [v1.5.x] images/ansible-operator: bumped base to ansible-operator-base:v1.5.x-61a9e03de149f6b9d3c7f192e1f303ce97a42420
  images/ansible-operator/Dockerfile
Labels: lgtm

#4810 workflows/deploy-manual: set branch name in auto-PR title and body
  .github/workflows/deploy-manual.yml
Labels: lgtm

#4794 fix the explanation
  website/content/en/docs/contribution-guidelines/plugins.md
Labels: lgtm

#4693 add new optional for bundle validate
  changelog/fragments/new-option-validate.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/bundle/validate/optional.go
  internal/cmd/operator-sdk/bundle/validate/optional_test.go
  internal/cmd/operator-sdk/bundle/validate/validate.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
  website/content/en/docs/olm-integration/generation.md
Labels: do-not-merge/hold, lgtm

#4817 workflows/deploy-manual: set branch suffix to valid enum
  .github/workflows/deploy-manual.yml
Labels: lgtm

#4821 Release v1.5.2
  Makefile
  changelog/generated/v1.5.2.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.5.2.md
Labels: lgtm

#4822 Release v1.6.2
  Makefile
  changelog/fragments/add-componentconfig-flag.yaml
  changelog/generated/v1.6.2.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.6.2.md
Labels: lgtm

#4832 Add olm bindata for 0.18.0
  Makefile
  go.mod
  go.sum
  internal/bindata/olm/manifests.go
  internal/bindata/olm/versions.go
  internal/testutils/olm.go
  website/content/en/docs/overview/_index.md
Labels: lgtm

#4839 Add changelog for pkgman-to-bundle cmd
  changelog/fragments/add-pkgman-to-bundle-cmd.yaml
Labels: lgtm

#4812 update golang docs on CRD scoping
  website/content/en/docs/building-operators/golang/crds-scope.md
Labels: lgtm

#4843 test/integration: bump tested OLM version to 0.18.0, remove old test code
  internal/testutils/utils.go
  test/e2e/ansible/suite_test.go
  test/e2e/go/suite_test.go
  test/e2e/helm/suite_test.go
  test/integration/packagemanifests_test.go
  test/integration/suite_test.go
Labels: area/testing, lgtm

#4844 internal/cmd: format log.Info messages correctly
  changelog/fragments/fmt-info-logs.yaml
  internal/cmd/ansible-operator/run/cmd.go
  internal/cmd/helm-operator/run/cmd.go
Labels: kind/bug

#4835 deps: bump kubebuilder to v3.0.0
  changelog/fragments/kubebuilder-v3.0.0.yaml
  go.mod
  go.sum
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/ansible/memcached-operator/config/rbac/auth_proxy_role.yaml
  testdata/ansible/memcached-operator/config/rbac/leader_election_role.yaml
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/go/v3/memcached-operator/config/rbac/auth_proxy_role.yaml
  testdata/go/v3/memcached-operator/config/rbac/leader_election_role.yaml
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  testdata/helm/memcached-operator/config/rbac/auth_proxy_role.yaml
  testdata/helm/memcached-operator/config/rbac/leader_election_role.yaml
Labels: area/dependency

#4842 fix: skip adding unserved CRDs to CSV
  changelog/fragments/skip-adding-deprecard-crds.yaml
  internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
  internal/util/k8sutil/api.go
Labels: lgtm

#4849 test/integration: fix flaky test
  test/integration/packagemanifests_test.go
  test/integration/suite_test.go
Labels: area/testing

#4852 Updating release version to v.1.7.0
  Makefile
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
Labels: lgtm

#4854 Updating Release v1.7.0
  changelog/fragments/add-componentconfig-flag.yaml
  changelog/fragments/add-pkgman-to-bundle-cmd.yaml
  changelog/fragments/ansible_log_events.yaml
  changelog/fragments/deprecate-packagemanifests.yaml
  changelog/fragments/fmt-info-logs.yaml
  changelog/fragments/kubebuilder-v3.0.0.yaml
  changelog/fragments/new-option-validate.yaml
  changelog/fragments/skip-adding-deprecard-crds.yaml
  changelog/generated/v1.7.0.md
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.7.0.md
Labels: lgtm
