Repository operator-framework/operator-sdk, pull requests merged in 2022-08, with the labels that each got.

#5976 Remove metering from deep insights capability
  website/content/en/docs/overview/operator-capabilities.md
Labels: lgtm

#5960 :bug: fix operator-sdk generate kustomize manifests to respect changes made by users in the config/manifests
  changelog/fragments/fix.yaml
  internal/plugins/manifests/v2/templates/config/manifests/kustomization.go
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#5941 doc/samples: better clarification about runAsNonRoot and RunAsUser regards pod standards
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5973 fix: run and upgrade bundle subcommands to they work well with vendors
  changelog/fragments/fix-run-upgrade-bundle.yaml
  internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
  internal/olm/operator/registry/index/registry_pod.go
Labels: lgtm

#5985 doc: add recommendation to the best practices
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5977 doc: improve capability doc by providing a better explanation over the deep insight level
  website/content/en/docs/overview/operator-capabilities.md
Labels: lgtm

#5997 fix: deploy-image for sdk to generate the bundle with the apis created by it
  changelog/fragments/fix-plugin.yaml
  internal/cmd/operator-sdk/cli/cli.go
Labels: release-blocker

#6000 update olm bindata to 0.22.0
  Makefile
  changelog/fragments/bump-olm-v0220.yaml
  hack/generate/olm_bindata.sh
  internal/bindata/olm/manifests.go
Labels: release-blocker, lgtm

#6001 Release v1.23.0
  Makefile
  changelog/fragments/add-muiltiarch.yaml
  changelog/fragments/annotations-watch.yaml
  changelog/fragments/bump-helm-operator-plugins.yaml
  changelog/fragments/bump-kb-3-5-0.yaml
  changelog/fragments/bump-kubebuilder-add-kustomize.yaml
  changelog/fragments/bump-olm-v0220.yaml
  changelog/fragments/export-scorecard-storage.yaml
  changelog/fragments/fix-plugin.yaml
  changelog/fragments/fix-run-upgrade-bundle.yaml
  changelog/fragments/fix-scorecard-mountpath.yaml
  changelog/fragments/fix.yaml
  changelog/fragments/rbu-ip-approval-bugfix.yaml
  changelog/fragments/run-bundle-upgrade-bugfix.yaml
  changelog/fragments/skiptls-usehttp-fbc.yaml
  changelog/generated/v1.23.0.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v4-alpha/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v4-alpha/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v4-alpha/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.23.0.md
Labels: lgtm

#5978 docs-link: increase timeout for the check
  hack/check-links.sh
Labels: lgtm

#5480 Bug 2037208: handle arm64
  changelog/fragments/support-arm64.yaml
  internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
  internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
  testdata/ansible/memcached-operator/Makefile
  testdata/helm/memcached-operator/Makefile
Labels: lifecycle/rotten

#5972 Add a metric to the sample memcached-operator
  hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go
  testdata/go/v3/memcached-operator/Dockerfile
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/go.mod
  testdata/go/v3/memcached-operator/main.go
  testdata/go/v3/memcached-operator/monitoring/metrics.go
  testdata/go/v4-alpha/memcached-operator/Dockerfile
  testdata/go/v4-alpha/memcached-operator/controllers/memcached_controller.go
  testdata/go/v4-alpha/memcached-operator/go.mod
  testdata/go/v4-alpha/memcached-operator/main.go
  testdata/go/v4-alpha/memcached-operator/monitoring/metrics.go
Labels: lgtm

#6007 Bump java-operator-plugins to v0.6.0
  changelog/fragments/bump-java-operator-plugins.yaml
  go.mod
  go.sum
Labels: lgtm

#6003 Remove duplicated step for upgrading to 1.23.0
  website/content/en/docs/upgrading-sdk-version/v1.23.0.md
Labels: lgtm

#5886 docs: fix Ansible metrics reference
  website/content/en/docs/building-operators/ansible/reference/internal_metrics.md
Labels: lgtm
