Repository operator-framework/operator-sdk, pull requests merged in 2022-07, with the labels that each got.

#5912 doc/sample: nit clarifies the vendor caveats
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5907 dx: add option to run only the lint checks as fix small issues automatically i.e. unused imports
  Makefile
Labels: lgtm

#5921 enable --skip-tls-verify and --use-http for FBC run bundle and upgrade
  changelog/fragments/skiptls-usehttp-fbc.yaml
  internal/olm/fbcutil/util.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/registry/index_image.go
Labels: release-blocker

#5931 Add securityContext config to Registry pod spec for run bundle(-upgrade)
  go.mod
  internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
  internal/olm/operator/registry/index/registry_pod.go
Labels: do-not-merge/hold, lgtm

#5943 Release v1.22.1
  Makefile
  changelog/fragments/bump-helm-operator-plugins.yaml
  changelog/fragments/rbu-ip-approval-bugfix.yaml
  changelog/fragments/run-bundle-upgrade-bugfix.yaml
  changelog/generated/v1.22.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.22.1.md
Labels: lgtm

#5829 OSDK-2345: Export scorecard storage as an env variable in a test pod
  changelog/fragments/export-scorecard-storage.yaml
  internal/scorecard/storage.go
Labels: lgtm

#5714 OSDK-2303: Scorecard testOutput is tightly coupled with storage mountPath
  changelog/fragments/fix-scorecard-mountpath.yaml
  internal/scorecard/storage.go
Labels: lgtm

#5954 Release v1.22.2
  Makefile
  changelog/fragments/skiptls-usehttp-fbc.yaml
  changelog/generated/v1.22.2.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.22.2.md
Labels: lgtm
