Repository operator-framework/operator-sdk, pull requests merged in 2022-06, with the labels that each got.

#5830 deprecated skip-tls flag marked as hidden
  changelog/fragments/hide-skip-tls.yaml
  internal/olm/operator/registry/index_image.go
Labels: lgtm

#5816 clean up: remove internal/util/utils.go since it should no longer be used
  hack/generate/samples/internal/ansible/advanced_molecule.go
  hack/generate/samples/internal/ansible/memcached_molecule.go
  internal/util/utils.go
  test/e2e/ansible/suite_test.go
  test/e2e/helm/suite_test.go
Labels: lgtm

#5834 Add a missing space
  website/content/en/docs/building-operators/golang/operator-scope.md
Labels: lgtm

#5814 Upgrade Kubebuilder dep from 3.4.1 to the commit 800fdeec6e5c
  changelog/fragments/kb-800fdeec6e5c.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/plugins/ansible/v1/init.go
  testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/ansible/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/ansible/memcached-operator/config/manager/manager.yaml
  testdata/go/v2/memcached-operator/Dockerfile
  testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/go/v3/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/go/v3/memcached-operator/config/manager/manager.yaml
  testdata/go/v3/memcached-operator/main.go
  testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
  testdata/helm/memcached-operator/config/default/manager_auth_proxy_patch.yaml
  testdata/helm/memcached-operator/config/manager/manager.yaml
Labels: lgtm

#5795 Document how to use the `--extra-service-accounts` flag
  website/content/en/docs/advanced-topics/multi-sa.md
Labels: lgtm

#5815 (ansible/v1, helm/v1): deprecate the flag since APIs is not longer offered from k8s 1.22 and this flag is deprecated for Golang
  changelog/fragments/deprecate-crdversionflag.yaml
  internal/plugins/ansible/v1/api.go
  internal/plugins/helm/v1/api.go
  internal/plugins/util/message.go
Labels: lgtm

#5809 Merge feature/run-bundle into master: Add FBC support to `run bundle` and `run bundle-upgrade` commands
  changelog/fragments/sdk-fbc-run-bundle(-upgrade).yaml
  go.mod
  internal/cmd/operator-sdk/run/bundle/cmd.go
  internal/olm/fbcutil/util.go
  internal/olm/operator/bundle/install.go
  internal/olm/operator/bundleupgrade/upgrade.go
  internal/olm/operator/registry/catalog.go
  internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
  internal/olm/operator/registry/index/registry_pod.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/index_image.go
  internal/olm/operator/registry/operator_installer.go
  website/content/en/docs/cli/operator-sdk_run_bundle.md
Labels: release-blocker, lgtm

#5848 Close #5837: Document reconcile period for Ansible in advanced options
  website/content/en/docs/building-operators/ansible/reference/advanced_options.md
Labels: lgtm

#5849 ci: update python version from 3.6 to 3.8 and ubuntu image from ubuntu-18.04 to ubuntu-20.04
  .github/workflows/deploy-manual.yml
  .github/workflows/deploy.yml
  .github/workflows/freshen-images.yml
  .github/workflows/integration.yml
  .github/workflows/rerun.yml
  .github/workflows/test-ansible.yml
  .github/workflows/test-go.yml
  .github/workflows/test-helm.yml
  .github/workflows/test-sanity.yml
Labels: lgtm

#5843 Bump versions for k8s 1.24
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .github/workflows/test-ansible.yml
  .github/workflows/test-go.yml
  .github/workflows/test-helm.yml
  .github/workflows/test-sanity.yml
  Makefile
  changelog/fragments/k8s-1.24-bump.yaml
  go.mod
  go.sum
  images/ansible-operator-2.11-preview/Dockerfile
  images/ansible-operator/Dockerfile
  images/custom-scorecard-tests/Dockerfile
  images/helm-operator/Dockerfile
  images/operator-sdk/Dockerfile
  images/scorecard-test-kuttl/Dockerfile
  images/scorecard-test/Dockerfile
  internal/ansible/flags/flag.go
  internal/ansible/paramconv/paramconv.go
  internal/ansible/paramconv/paramconv_test.go
  internal/generate/clusterserviceversion/bases/definitions/crd_test.go
  internal/helm/client/client.go
  internal/helm/flags/flag.go
  internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go
  internal/plugins/manifests/v2/init.go
  internal/scorecard/tar.go
  internal/util/k8sutil/k8sutil.go
  testdata/ansible/memcached-operator/Makefile
  testdata/go/v2/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/Dockerfile
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/bundle/manifests/cache.example.com_memcacheds.yaml
  testdata/go/v3/memcached-operator/config/crd/bases/cache.example.com_memcacheds.yaml
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  testdata/go/v3/memcached-operator/go.mod
  testdata/go/v3/memcached-operator/go.sum
  testdata/helm/memcached-operator/Makefile
  website/content/en/docs/building-operators/golang/installation.md
  website/content/en/docs/installation/_index.md
Labels: release-blocker, lgtm

#5851 Update Helm sample to comply with Pod Security Standards and changes in k8s api
  hack/generate/samples/internal/helm/memcached.go
  hack/generate/samples/internal/helm/testdata/memcached-0.0.1.tgz
  hack/generate/samples/internal/helm/testdata/memcached-0.0.2.tgz
  testdata/helm/memcached-operator/helm-charts/memcached/Chart.yaml
  testdata/helm/memcached-operator/helm-charts/memcached/templates/pdb.yaml
  testdata/helm/memcached-operator/helm-charts/memcached/templates/statefulset.yaml
Labels: lgtm

#5857 doc: (Pod Security Standards) fix nit format
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5835 Bumping envtest to 1.24
  Makefile
  test/common/sa_secret.go
  test/e2e/ansible/cluster_test.go
  test/e2e/go/cluster_test.go
  test/e2e/helm/cluster_test.go
Labels: release-blocker, lgtm

#5867 doc/samples: update pod security standards to clarifies usage
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5853 Update Ansible sample to comply with Pod Security Standards
  hack/generate/samples/internal/ansible/constants.go
  testdata/ansible/memcached-operator/roles/memcached/tasks/main.yml
Labels: lgtm

#5863 update ubi images registry.access.redhat.com/ubi8/ubi-minimal from 8.5 to 8.6
  images/custom-scorecard-tests/Dockerfile
  images/helm-operator/Dockerfile
  images/operator-sdk/Dockerfile
  images/scorecard-test/Dockerfile
Labels: lgtm

#5862 ci: update docker/build-push-action@v2 to docker/build-push-action@v3
  .github/workflows/deploy-manual.yml
  .github/workflows/deploy.yml
Labels: lgtm

#5876 Release v1.22.0
  Makefile
  changelog/fragments/anible-requierments.yaml
  changelog/fragments/bugfix-run-bundle.yaml
  changelog/fragments/bundle-scorecard.yaml
  changelog/fragments/deprecate-crdversionflag.yaml
  changelog/fragments/hide-skip-tls.yaml
  changelog/fragments/k8s-1.24-bump.yaml
  changelog/fragments/kb-800fdeec6e5c.yaml
  changelog/fragments/sdk-fbc-run-bundle(-upgrade).yaml
  changelog/generated/v1.22.0.md
  go.mod
  go.sum
  internal/bindata/olm/manifests.go
  internal/bindata/olm/versions.go
  internal/testutils/olm.go
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/overview/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.22.0.md
Labels: lgtm

#5892 doc: best practices: pod security standards : improvements
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5895 doc: fix statment
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5893 Bug 2090135: Propagate correct error message for an invalid index
  internal/olm/operator/bundle/install.go
  internal/olm/operator/registry/index_image.go
Labels: lgtm

#5894 (bugfix): `run bundle` and `run bundle-upgrade` - update registry pod index directory
  internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
  internal/olm/operator/registry/index_image.go
Labels: lgtm

#5901 (bugfix): approve `InstallPlan` only if it is a new `InstallPlan`
  changelog/fragments/rbu-ip-approval-bugfix.yaml
  internal/olm/operator/registry/operator_installer.go
  internal/olm/operator/registry/operator_installer_test.go
Labels: lgtm

#5904 (bugfix): fix SecurityContext in Go memcached sample
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  test/e2e/go/cluster_test.go
  testdata/go/v3/memcached-operator/controllers/memcached_controller.go
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: do-not-merge/hold, lgtm

#5905 doc: Improve Pod Standards doc
  website/content/en/docs/best-practices/pod-security-standards.md
Labels: lgtm

#5911 Correct cloud.common version to match the requirements.yaml
  website/content/en/docs/upgrading-sdk-version/v1.22.0.md
Labels: lgtm

#5908 add multiarch optional validator
  changelog/fragments/add-muiltiarch.yaml
  go.mod
  go.sum
  internal/cmd/operator-sdk/bundle/validate/cmd.go
  internal/cmd/operator-sdk/bundle/validate/optional.go
  website/content/en/docs/cli/operator-sdk_bundle_validate.md
Labels: lgtm

#5906 Add e2e tests to the Memcached Go sample providing an example and improved docs
  .github/workflows/test-sample-go.yml
  Makefile
  hack/generate/samples/internal/go/v3/e2e_test_code.go
  hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
  testdata/go/v3/memcached-operator/Makefile
  testdata/go/v3/memcached-operator/test/e2e/e2e_suite_test.go
  testdata/go/v3/memcached-operator/test/e2e/e2e_test.go
  testdata/go/v3/memcached-operator/test/utils/utils.go
  website/content/en/docs/best-practices/common-recommendation.md
  website/content/en/docs/best-practices/pod-security-standards.md
  website/content/en/docs/building-operators/golang/testing.md
Labels: lgtm
