Repository operator-framework/operator-sdk, pull requests merged in 2022-04, with the labels that each got.

#5614 fix java bump changelog in v1.18.0 docs
  website/content/en/docs/upgrading-sdk-version/v1.18.0.md
Labels: lgtm

#5622 Restrict secrets to watch with label selector
  hack/generate/samples/internal/ansible/testdata/watches.yaml
Labels: lgtm

#5630 Fixed Docsy Link
  website/content/en/docs/contribution-guidelines/documentation.md
Labels: lgtm

#5626 Notify users of rbac marker parsing error
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#5638 Docsy Link Fix (again)
  website/content/en/docs/contribution-guidelines/documentation.md
Labels: lgtm

#5633 revert back --skip-tls flag changes with deprecation notice
  changelog/fragments/revert-skiptls-changes-deprc-notice.yaml
  internal/olm/operator/bundle/install.go
  internal/olm/operator/registry/index_image.go
  website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
  website/content/en/docs/cli/operator-sdk_run_bundle.md
Labels: release-blocker, lgtm

#5632 Restore image digest pinning
  go.mod
  go.sum
  internal/cmd/operator-sdk/generate/bundle/bundle.go
Labels: lgtm

#5628 fix: printout errors even if we have a timeout
  changelog/fragments/scorecard-deadline.yaml
  internal/cmd/operator-sdk/scorecard/cmd.go
Labels: lgtm

#5640 bump: update prometheus to fix medium vulnerability
  go.mod
  go.sum
Labels: lgtm

#5643 Document how to update your own OSDK images
  website/content/en/docs/faqs/_index.md
Labels: lgtm

#5644 Release v1.19.0
  Makefile
  changelog/fragments/01-bump-java-operator-plugins.yaml
  changelog/fragments/darwin-arm64.yaml
  changelog/fragments/enable-skiptlsverify-usehttp-flags.yaml
  changelog/fragments/helm-annotations-reconcile-period.yaml
  changelog/fragments/log-error-url-verification.yaml
  changelog/fragments/respect-deployment-labels.yaml
  changelog/fragments/revert-skiptls-changes-deprc-notice.yaml
  changelog/fragments/scorecard-deadline.yaml
  changelog/generated/v1.19.0.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.19.0.md
Labels: lgtm

#5589 (docs) Remove Red Hat links
  website/layouts/partials/footer.html
  website/layouts/partials/head.html
Labels: lgtm

#5578 all: fix some typos
  changelog/generated/v1.8.0.md
  proposals/ansible-helm-addapi.md
  proposals/kubebuilder-integration.md
  proposals/kubernetes-1.17.md
  proposals/operator-testing-tool.md
  proposals/scorecard-custom-tests-2.md
  proposals/scorecard-plugin-system.md
  proposals/tech-debt.md
  website/content/en/docs/advanced-topics/multi-arch.md
  website/content/en/docs/building-operators/ansible/reference/advanced_options.md
  website/content/en/docs/building-operators/ansible/reference/internal_metrics.md
  website/content/en/docs/building-operators/golang/advanced-topics.md
  website/content/en/docs/building-operators/helm/reference/watches.md
  website/content/en/docs/faqs/_index.md
  website/content/en/docs/olm-integration/tutorial-bundle.md
  website/content/en/docs/testing-operators/scorecard/_index.md
Labels: lgtm

#5573 Removed Repetitive word
  website/content/en/docs/building-operators/golang/quickstart.md
Labels: lgtm

#5636 update Go operator quickstart docs
  website/content/en/docs/building-operators/golang/quickstart.md
Labels: lgtm, kind/documentation

#5651 (actions): update link-checker for https://docs.github.com
  .github/workflows/markdown-link-check-config.json
  .github/workflows/test-sanity.yml
  hack/check-links.sh
  website/content/en/docs/contribution-guidelines/developer-guide.md
Labels: lgtm

#5652 Fix scorecard XUnit output
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/cmd/operator-sdk/scorecard/xunit/xunit.go
Labels: lgtm

#5639 Fix related image environment variable discovery
  changelog/fragments/fix-make-bundle.yaml
  internal/cmd/operator-sdk/generate/bundle/bundle.go
  internal/cmd/operator-sdk/generate/internal/relatedimages.go
  internal/cmd/operator-sdk/generate/internal/relatedimages_test.go
  internal/generate/clusterserviceversion/clusterserviceversion.go
Labels: lgtm

#5657 Release v1.19.1
  Makefile
  changelog/fragments/fix-make-bundle.yaml
  changelog/generated/v1.19.1.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.19.1.md
Labels: lgtm

#5659 add note to merge base-update PRs before release
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: lgtm

#5653 Make it so tests share one kind cluster
  Makefile
  hack/tests/e2e-ansible-molecule.sh
Labels: lgtm

#5668 :sparkles: bump operator-framework api
  changelog/fragments/bump-api.yaml
  go.mod
  go.sum
Labels: lgtm

#5672 Fix marker for kubebuilder
  website/content/en/docs/building-operators/golang/crds-scope.md
Labels: lgtm

#5677 Update URL for Docs
  proposals/ansible-operator-status.md
Labels: lgtm

#5691 Archive outdated docs on release
  website/config.toml
  website/content/en/docs/contribution-guidelines/releasing.md
Labels: lgtm

#5684 update olm bindata
  Makefile
  changelog/fragments/bump-supported-olm.yaml
  go.mod
  go.sum
  internal/bindata/olm/manifests.go
  internal/bindata/olm/versions.go
  internal/testutils/olm.go
  website/content/en/docs/overview/_index.md
  website/layouts/partials/footer.html
Labels: lgtm

#5678 Fix ansible-operator finalizer concurrency issue
  Makefile
  changelog/fragments/finalizerconcurrency.yaml
  hack/generate/samples/internal/ansible/advanced_molecule.go
  hack/generate/samples/internal/ansible/constants.go
  hack/generate/samples/internal/ansible/testdata/playbooks/finalizerconcurrencyfinalizer.yml
  hack/generate/samples/internal/ansible/testdata/tasks/finalizerconcurrencytest_test.yml
  hack/generate/samples/internal/ansible/testdata/tasks/subresourcestest_test.yml
  hack/generate/samples/internal/ansible/testdata/watches.yaml
  internal/ansible/controller/reconcile.go
Labels: lgtm

#5712 Release PR v1.20.0
  Makefile
  changelog/fragments/bump-api.yaml
  changelog/fragments/bump-supported-olm.yaml
  changelog/fragments/finalizerconcurrency.yaml
  changelog/fragments/fix-make-bundle.yaml
  changelog/fragments/proxy-port-flag.yaml
  changelog/fragments/remove-error-thrown-for-proxy-path.yaml
  changelog/generated/v1.20.0.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.20.0.md
Labels: lgtm

#5718 add newline, apparently empty commit doesn't trigger netlify
  website/content/en/_index.html
Labels: lgtm

#5687 Docs: Clarification about the use of index image in run bundle(-upgrade)
  website/content/en/docs/olm-integration/tutorial-bundle.md
Labels: lgtm

#5715 ci: add check for up-to-date olm versions
  .github/workflows/olm-check.yml
  hack/check-olm.sh
Labels: lgtm
