Repository operator-framework/operator-sdk, pull requests merged in 2023-05, with the labels that each got.

#6422 stop building "scorecard-storage", "scorecard-untar" images
  .github/workflows/deploy.yml
  Makefile
Labels: lgtm

#6425 Replace non-existing manifests and prevent them from changing in the future
  internal/cmd/operator-sdk/scorecard/cmd.go
  internal/cmd/operator-sdk/scorecard/cmd_test.go
  website/content/en/docs/cli/operator-sdk_scorecard.md
Labels: lgtm

#6414 updating molecule links #6413
  website/content/en/docs/best-practices/common-recommendation.md
  website/content/en/docs/building-operators/ansible/migration.md
  website/content/en/docs/building-operators/ansible/testing-guide.md
  website/content/en/docs/building-operators/golang/testing.md
  website/content/en/docs/overview/project-layout.md
  website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Labels: lgtm

#6421 enable ginkgolinter and fix findings
  .golangci.yml
  internal/ansible/handler/logging_enqueue_annotation_test.go
  internal/ansible/handler/logging_enqueue_object_test.go
  internal/ansible/proxy/inject_owner_test.go
  internal/cmd/ansible-operator/version/cmd_test.go
  internal/cmd/helm-operator/version/cmd_test.go
  internal/cmd/operator-sdk/bundle/cmd_test.go
  internal/cmd/operator-sdk/bundle/validate/optional_test.go
  internal/cmd/operator-sdk/olm/cmd_test.go
  internal/cmd/operator-sdk/run/cmd_test.go
  internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_test.go
  internal/generate/clusterserviceversion/bases/definitions/crd_test.go
  internal/generate/clusterserviceversion/clusterserviceversion_test.go
  internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
  internal/generate/collector/clusterserviceversion_test.go
  internal/generate/packagemanifest/packagemanifest_test.go
  internal/olm/operator/registry/configmap/configmap_test.go
  internal/olm/operator/registry/configmap/registry_test.go
  internal/olm/operator/registry/configmap_test.go
  internal/olm/operator/registry/fbcindex/fbc_registry_pod_test.go
  internal/olm/operator/registry/index/registry_pod_test.go
  internal/olm/operator/registry/operator_installer_test.go
  internal/registry/labels_test.go
  internal/scorecard/bundle_test.go
  internal/scorecard/tests/bundle_test.go
  internal/validate/external_test.go
  test/e2e/ansible/cluster_test.go
  test/e2e/go/cluster_test.go
  test/e2e/helm/cluster_test.go
Labels: ok-to-test

#6408 Fix 6323: compress the bundle configMap
  changelog/fragments/support_configmap_compression.yaml
  internal/olm/operator/registry/fbcindex/configMapWriter.go
  internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
  internal/olm/operator/registry/fbcindex/fbc_registry_pod_test.go
Labels: lgtm, ok-to-test

#6442 ignore github access URI in htmlproofer
  hack/check-links.sh
Labels: lgtm

#6401 Update kuttl to v0.15.0 in the scorecard-test-kuttl image
  changelog/fragments/01-update-kuttl.yaml
  images/scorecard-test-kuttl/Dockerfile
  images/scorecard-test-kuttl/main.go
Labels: lgtm

#6423 OCPBUGS-11569: Update ubi to ubi-micro:8.7
  go.mod
  go.sum
Labels: lgtm

#6449 state default reconcilePeriod value in ansible docs
  website/content/en/docs/building-operators/ansible/reference/advanced_options.md
  website/content/en/docs/building-operators/ansible/reference/watches.md
Labels: lgtm

#6398 Bump Golang version in ansible-operator images to 1.19
  changelog/fragments/image-ansible-operator-go-version.yaml
  images/ansible-operator-2.11-preview/Dockerfile
  images/ansible-operator/Dockerfile
Labels: lgtm

#6454 Release v1.29.0
  Makefile
  changelog/fragments/01-update-kuttl.yaml
  changelog/fragments/docs-bump-go-version.yaml
  changelog/fragments/image-ansible-operator-go-version.yaml
  changelog/fragments/support_configmap_compression.yaml
  changelog/generated/v1.29.0.md
  testdata/ansible/memcached-operator/Dockerfile
  testdata/ansible/memcached-operator/Makefile
  testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v3/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v3/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v3/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v4-alpha/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v4-alpha/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v4-alpha/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/go/v4-alpha/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/go/v4-alpha/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/go/v4-alpha/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
  testdata/helm/memcached-operator/Dockerfile
  testdata/helm/memcached-operator/Makefile
  testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
  testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
  website/config.toml
  website/content/en/docs/installation/_index.md
  website/content/en/docs/upgrading-sdk-version/v1.29.0.md
Labels: lgtm
